### ISSUE TITLE
Meeting Notes - 2016-07-01 17:30Z

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-cluster#1]
# ipfs cluster meeting on 2016-07-01 17:30Z

Participants:
- @whyrusleeping
- @jbenet (leading)
- @hermanjunge
- @JLilic
## Agenda
- rough requirements
- rough design
- list out interfaces/components
- figure out next steps

We itemized all the pieces we need to build, and figured out next steps.
## Interfaces / Components

These are all the components that we need to define or build. We need to: 
- translate these lines into issues describing them
- do the design for all the interfaces
- expand out what building them entails
- figure out dependencies between them
- figure out priorities 
- figure out time estimates

Links:
- ipfs-cluster design notes: https://github.com/ipfs/notes/issues/58
### Tools
- ipfs-clusterd tool
  - exposes IPFS API
  - API?
  - what does the CLI look like?
- ipfs-clusterctl tool
  - what does the CLI look like?
  - look at analogs in kubernetes, docker, and other systems
  - figure out authentication (look at how others do it)
### APIs
- ipfs api state changes (figure out what api commands change state, consensus)
  - read/write
- state replication configuration (UI)
  - RAID
  - (look for other analogs)
  - network/erasure coding
- state replication data structures (implementation)
  - what does the distributed pinset look like
- clusterd-to-clusterd protocol
  - what needs to be defined? (beyond consensus)
  - what do we put on consensus? (is it just replicating an op-log?)
### libp2p pieces
- libp2p consensus modules interface
  - raft
  - pbft
  - ethereum
- libp2p transports
  - p0: clusterd can talk to other clurterd's directly
  - p1: mountable transports / pipes
  - p2: exo transport
### Dev/Sys Ops
- containerization
  - containers? pods?
  - load balancing
- test harnesses
  - scenario driven tests
  - large network tests
  - CI to test clusters
    - team city?
    - snap-ci?
### Use Cases

We need to create use case scenarios
- deployment scenarios
  - write out 6 different scenarios that we want to cover
    (along with the tech to use)
    (translate into modes of operation)
- business use case scenarios
  get feedback with how people would use this tooling
- Look at other tools for inspiration
  - Cluster managers (hashicorp, coreos, docker stuff)
  - FileSystems (GlusterFS, Ceph)
  - Replication (RAID)
  - d/ctl tool UX (coreos, hashicorp)
### PMing

We need to do the following
- task breakdown
  - knowledge requirements explicit
- task dependencies
- Roadmap / timeline
- allocations
### Next Steps
- translate pieces into own spec issues
- do the PM work (tasks, dependencies, allocations)
- figure out roadmap for pieces
- figure out other people interested
- meet again next week `2016-07-06 17:00Z`

**Comment by hermanjunge** [comment]
@jbenet John's github is https://github.com/JLilic

**Comment by JLilic** [comment]
> business use case scenarios
> get feedback with how people would use this tooling

@jbenet we've got a bunch of enterprise engagements with Fortune 500's that are interested in IPFS however most or all will require an MNDA in order to engage in deeper dialogue and discussion around their pain points and potential use cases. I don't want to impose NDA's or suggest them if that's something you guys don't do - are NDA's OK for you guys? If not, I'll try to figure out other ways we can have conversations.
