### ISSUE TITLE
add file with hash blake2b-256 does not work

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1006]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: 0.12.1
 - Installation method: dist.ipfs.io

**Describe the bug:**

I'm running the command on the cluster:

`ipfs-cluster-ctl add --hash blake2b-256 --raw-leaves --quieter --name file --local --replication-min=1 --replication-max=10 /path/to/file`

I like to create a local directory entry with this file afterwards, so I use the CID (bafk2bzacecwvphs5yu7lpay66oksr7tx4ts6q6znldma5cbm53umuq76o6m3i) on the same machine to run an ipfs command:

`ipfs files cp /ipfs/bafk2bzacecwvphs5yu7lpay66oksr7tx4ts6q6znldma5cbm53umuq76o6m3i /cool/path/for/file`

This command does not return within 2-3 minutes since ipfs cannot find the hash locally...

`ipfs-cluster-ctl pin ls bafk2bzacecwvphs5yu7lpay66oksr7tx4ts6q6znldma5cbm53umuq76o6m3i`

Returns with a normal listing of the CID in the cluster.

`ipfs pin ls bafk2bzacecwvphs5yu7lpay66oksr7tx4ts6q6znldma5cbm53umuq76o6m3i`

Returns with an error:

`Error: path 'bafk2bzacecwvphs5yu7lpay66oksr7tx4ts6q6znldma5cbm53umuq76o6m3i' is not pinned`

---

The same file, commands, and cluster work fine, without specifying the "--hash" in the command line.

**Comment by hsanjuan** [comment]
Does it work with sha256 instead of blake?

**Comment by RubenKelevra** [comment]
> Does it work with sha256 instead of blake?

@hsanjuan 
Yes - I think you overlooked the last line:

> The same file, commands, and cluster work fine, without specifying the "--hash" in the command line.

So CIDv0 and sha256 work fine.

If you're interested in the code I run... (it's pretty complex) it's published here:

https://github.com/RubenKelevra/pacman.store/blob/master/toolset/repo2cluster.sh

**Comment by hsanjuan** [comment]
ah, sorry, it was late :(

**Comment by RubenKelevra** [comment]
> ah, sorry, it was late :(

Nevermind! :)

Thanks for putting a priority on this issue. I think I broke my cluster setup with running in this bug.

The cluster-follower tries to get hold of some CIDv1/blake2b-256 CIDs, while it's on the newest state of the cluster. And there are definitely no pin's left in the dataset with blake2b-256 CIDv1.

So they are just historical pins and the cluster-follower seems to have issues discarding/subtracting them from the cluster status.

**Comment by hsanjuan** [comment]
The problem is that cluster is not telling IPFS what type hash it is supposed to use when writing a block, and it uses the default and not the blake2b hash, and then it cannot find them again :(.

Sending a fix shortly.

**Comment by hsanjuan** [comment]
@RubenKelevra if you want you can test the fix from master.

**Comment by RubenKelevra** [comment]
@hsanjuan I'm currently running just a production environment, so no easy way to test this fix. I'm sorry!
