### ISSUE TITLE
Interrupted CRDT syncing is not resumable

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#1007]
Cross posting from https://github.com/ipfs/go-ds-crdt/issues/23

If syncing fails it may not be resumable for old items that were not synced in the same attempt.

Workaround: Cleaning up the cluster state and resync from scratch.

This is mostly problematic for CRDT-based cluster with very long DAGs (where syncing takes very long).

The effect is that the state may be missing items from the part of the DAG that was not synced.

**Comment by RubenKelevra** [comment]
Can't we just write the current DAG on each successful operation to a file, until this is properly solved?
This way we can continue by skipping ahead until the DAG from the file is reached and then start processing all updates.

**Comment by hsanjuan** [comment]
The dag is written in the datastore, the problem is with the skipping. Currently there is no way to reprocess all things.
