### ISSUE TITLE
a non-recursive option for the pin-command

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1009]
**Describe the feature you are proposing**

I like to be able to pin objects non-recursively to the cluster, like `ipfs pin add --recursive=0 ...` does.

**Additional context**

I like release files in a directory listing earlier than the directory itself. So if no client in the cluster or the network holds a file anymore, the file won't be accessible, but my directory listing (which is non-recursively pinned) still works, to list other files, which are still accessible.

**Comment by hsanjuan** [comment]
The good news is that most of the wiring to do this is in place..

**Comment by gargdeepak** [comment]
@hsanjuan I can pick this up if no one else is working on it

**Comment by RubenKelevra** [comment]
@gargdeepak since it's going to be included in the next point release, that would be great! :)

**Comment by hsanjuan** [comment]
@gargdeepak please hold on on this one, as this touches a number of things that may not be obvious for a beginner in the code base and I'd like to get a chance to review your other submissions first.

**Comment by gargdeepak** [comment]
@hsanjuan thanks for letting me know. Also, 
1. if you have any recommendations on issues for me, please feel free to share. 
2. which forum is best to ask/discuss tool/framrwork choices ?

**Comment by RubenKelevra** [comment]
@gargdeepak cool to see someone new join the project, welcome! :)

2) I'm too new to recommend anything, but I'm curious for the answers!

**Comment by hsanjuan** [comment]
> @hsanjuan thanks for letting me know. Also,
> 
>     1. if you have any recommendations on issues for me, please feel free to share.
> 

This https://github.com/ipfs/ipfs-cluster/issues/987

>     2. which forum is best to ask/discuss tool/framework choices ?

https://discuss.ipfs.io
