### ISSUE TITLE
ipfs-cluster-follow list results in too-many-open-files on the unix socket for large pinsets

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#1013]
It makes too many requests (I think it requests status per pin).

```
or/.ipfs-cluster-follow/pacman.store/api-socket: accept4: too many open files; retrying in 1s
2020/03/06 10:31:53 http: Accept error: accept unix //home/hector/.ipfs-cluster-follow/pacman.store/api-socket: accept4: too many open files; retrying in 1s
2020/03/06 10:31:54 http: Accept error: accept unix //home/hector/.ipfs-cluster-follow/pacman.store/api-socket: accept4: too many open files; retrying in 1s
2020/03/06 10:31:55 http: Accept error: accept unix //home/hector/.ipfs-cluster-follow/pacman.store/api-socket: accept4: too many open files; retrying in 1s
2020/03/06 10:31:56 http: Accept error: accep
```

**Comment by gargdeepak** [comment]
I can work on it if you can give me more info and context or repro steps.

**Comment by RubenKelevra** [comment]
@hsanjuan does this also occur on the current 0.5.0-dev branch? Or is this a regression, while it worked before?

**Comment by hsanjuan** [comment]
This still happens. In ipfs-cluster-follow, the List command makes one local `status` request per pin, after doing `pin/ls` (or Allocations). It should really request a full status request for all pins and then do the matching.

@gargdeepak you can give it a try
