### ISSUE TITLE
Add a snapshot of the distributed WP mirror as a collaborative cluster

### ISSUE THREAD

**Issue by metasj** [ipfs/ipfs-cluster#1017]
Create a collaborative cluster from the distributed wikipedia mirror.
https://github.com/ipfs/distributed-wikipedia-mirror/blob/master/snapshot-hashes.yml

Extensions:
a) Recompile a new one each year (followers could switch to following newer iterations as they wish)
b) Do this for each of the core UN languages

I suspect many would be keen to follow the subset in their own languages.

**Comment by RubenKelevra** [comment]
It's actually much easier to just create an IPNS for each language and update those when a new version comes out.

You can run a simple script which resolves the IPNS daily and runs an ipfs pin update, if there's a new CID available.

**Comment by hsanjuan** [comment]
Hi @metasj , I am following current work on that repo. Recompiling of versions is not simple and got broken but there is very significant progress to get Wikipedia ipfs-ified again. After that, we plan to store it in a collaborative cluster.

I will close this issue and refer you to https://github.com/ipfs/distributed-wikipedia-mirror/issues/68# which is a better place for the discussion.
