### ISSUE TITLE
[BOUNTY] Create Collaborative Cluster for all CORD-19 datasets

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-cluster#1021]
## This issue has a bounty!
Successfully closing this issue by producing a production-ready, mergeable PR can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
In response to the COVID-19 pandemic, the Allen Institute for AI has partnered with leading research groups to prepare and distribute the COVID-19 Open Research Dataset (CORD-19), a free resource of over 29,000 scholarly articles, including over 13,000 with full text, about COVID-19 and the coronavirus family of viruses for use by the global research community.

To help with this, we'd like to create a collaborative cluster for the CORD-19 datasets (https://pages.semanticscholar.org/coronavirus-research) in order to enable all IPFS users to help back up this dataset and make it available to scientists.

Instructions for setting up a new collaborative cluster are here: cluster.ipfs.io/documentation/collaborative/setup/

## Deliverable
1+ collaborative cluster(s) for the COVID-19 datasets added to https://collab.ipfscluster.io/

## Guidelines
- Please use the [IPFS Go Contributing Guidelines](https://github.com/ipfs/community/blob/master/CONTRIBUTING_GO.md) as your north star — **adherence to these guidelines are crucial when it comes to awarding a potential bounty**!
- Please DO NOT bundle a general code refactor with the completion of this bounty!

**Comment by rklaehn** [comment]
Great initiative. I don't quite get the remark about the Go Contributing Guidelines though. Ipfs cluster follow is existing functionality, so this would not require writing any code but just spinning up and configuring an ipfs cluster, correct?

**Comment by hsanjuan** [comment]
> this would not require writing any code but just spinning up and configuring an ipfs cluster, correct?

Mostly correct, it would be great to get the code/scripts that produces and updates the archive though.

**Comment by bonedaddy** [comment]
is tihs still available? would be happy to do it unless rklaehn has done it already. cna include scripts and docker-compose files to easily join the cluster, and update the archive.

**Comment by momack2** [comment]
That’d be great! Thanks for pitching in! I’ll move this to the “in
progress” section so others know you’re working on it. Feel free to reach
out to Hector with any questions or helpful bug reports!

**Comment by bonedaddy** [comment]
sounds good, ill be working out of here https://github.com/RTradeLtd/cord19-collaborative-cluster. Where should I open the PR once its done?

**Comment by hsanjuan** [comment]
@bonedaddy need to make a PR against https://collab.ipfscluster.io/ (and the follower config be distributed over ipfs if possible, like the others. We can provide dns if you want).

https://github.com/ipfs-cluster/collab.ipfscluster.io

**Comment by hsanjuan** [comment]
ok, I'm clearly late on processing notifications, you did that already

**Comment by momack2** [comment]
Looking amazing! Ping here when things are complete so we can triage & share this out! (@bonedaddy - I'll ping you on IRC re payment details when ready)

**Comment by bonedaddy** [comment]
As far as I know its complete, just need https://github.com/ipfs-cluster/collab.ipfscluster.io/pull/6 to be merged

**Comment by hsanjuan** [comment]
I'll try it out next week and give the final ok.

**Comment by RubenKelevra** [comment]
I've added a permanent replication :)

**Comment by beatrupp** [comment]
I've tried this and it works.

**Comment by hsanjuan** [comment]
@momack2 all good here. Thanks @bonedaddy !

**Comment by bonedaddy** [comment]
@hsanjuan no problem.
@momack2 would matrix work? im not on IRC often, not sure i even remember my password lol, but I have matrix.
