### ISSUE TITLE
Faster fail on pinning non-available content

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1026]
Currently we have a hard pin timeout to abort pinning actions which take to long.

This is fine in most situations:

- If a pin is large (in download size), it might be just fetched partly before the timeout kills the request. But since the data is probably still in the cache on retry, the second attempt will complete faster, this repeats until it's completed.

- If a pin is large (in structure) the calculation time might be exceeded on the first try, but since it's mainly IO bound, it's probably faster on the second try because of caching.

When this approach is not working:

- If there's no provider of a pin it won't stop early, but the pin command will stall until the timeout is reached.

** How to improve on that **

Run a ipfs findprovs before starting the pin operation, if it doesn't return any peers, abort the pin operation with an error 'no_provider_found'.

This way the pinning slots are not blocked for unavailable content, while the operation can be easily recovered later on with a retry.

**Comment by hsanjuan** [comment]
The timeout resets on every received block. So it can be set pretty short (i.e. cancel the pinning operation if I don't receive anything in 10 seconds).

Running findprovs (in a more general way, not just using the DHT, but also bitswap) is happening internally in IPFS, and it needs to happen per block anyways.

Setting the timeout to 30 seconds is equivalent (but better) to running findprovs for 30 seconds and both will abort when no one to provide the content appears in that time.

**Comment by RubenKelevra** [comment]
@hsanjuan well, alright. I obviously haven't checked the code on this. I'm sorry!

Scrap this idea :)
