### ISSUE TITLE
package context: unrecognized import path "context" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by levansuper** [ipfs/ipfs-cluster#104]
Hello

when i try to install ipfs with:
go get -u -d github.com/ipfs/ipfs-cluster
i get this:
package context: unrecognized import path "context" (import path does not begin with hostname)

and then nothing happens....

**Comment by hsanjuan** [comment]
Hi @levansuper , what go version are you using? Should be a recent one (>=1.7 I think).

**Comment by Kubuxu** [comment]
@hsanjuan is right, you need Go 1.7 or higher as it is when `context` was introduced to stdlib.

**Comment by hsanjuan** [comment]
reopen if needed
