### ISSUE TITLE
Panic during status RPC call 

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#105]
I ran into this while running the test that pins, blocks a minority, unpins in the majority, unblocks the minority and then ensures all data is unpinned everywhere.  Every cluster service node segfaults during this test.  The immediate problem is that the Status RPC call gets a pinInfo with a nil CID from the Status call forwarded to the RPC cluster object, and then the call to pinInfo.ToSerial() segfaults trying to get the string representation of nil.  

The CID is nil because of an error in `mbase.Decode(v)` on line 153 of cid.go.  This error is not checked on line 114 of rpc_api before calling `pinInfo.toSerial()`

The cause of the badly formatted arguments to the Status RPC is still unclear, however it was noted that during the test the cluster appears to lose its leader before this happens.  The message "error broadcasting metric: leader unknown or not existing yet" appears in all the logs at least once before the segfault.

Here is an example stack trace:

```
goroutine 6806 [running]:
gx/ipfs/QmcTcsTvfaeEBRFo1TkFgT8sRmgi1n1LTZpecfVP8fzpGD/go-cid.(*Cid).String(0x0, 0x100, 0xc420475540)
	/go/src/gx/ipfs/QmcTcsTvfaeEBRFo1TkFgT8sRmgi1n1LTZpecfVP8fzpGD/go-cid/cid.go:155 +0x28
github.com/ipfs/ipfs-cluster/api.PinInfo.ToSerial(0x0, 0xc4204aa000, 0x22, 0x1, 0xed0d5f09f, 0x3362d231, 0x563e90968f00, 0xc420233ab0, 0x62, 0x0, ...)
	/go/src/github.com/ipfs/ipfs-cluster/api/types.go:170 +0x64
github.com/ipfs/ipfs-cluster/api.GlobalPinInfo.ToSerial(0xc420267e00, 0xc420267e30, 0xc420267e00, 0xc420267e30, 0x0)
	/go/src/github.com/ipfs/ipfs-cluster/api/types.go:127 +0x1ce
github.com/ipfs/ipfs-cluster.(*RPCAPI).Status(0xc42000e2b8, 0xc42010dd6a, 0x2e, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42032a620, 0x0, ...)
	/go/src/github.com/ipfs/ipfs-cluster/rpc_api.go:115 +0xdc
reflect.Value.call(0xc4201b7aa0, 0xc42000e4e8, 0x13, 0x563e9011b39f, 0x4, 0xc420285ec8, 0x3, 0x3, 0xc42032a620, 0xc42047f5c0, ...)
	/usr/lib/go/src/reflect/value.go:434 +0x921
reflect.Value.Call(0xc4201b7aa0, 0xc42000e4e8, 0x13, 0xc42050c6c8, 0x3, 0x3, 0xc420232d90, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:302 +0xa6
gx/ipfs/QmYqnvVzUjjVddWPLGMAErUjNBqnyjoeeCgZUZFsAJeGHr/go-libp2p-gorpc.(*Server).Call(0xc4201e8600, 0xc42014c770, 0x11, 0xc42032a600)
	/go/src/gx/ipfs/QmYqnvVzUjjVddWPLGMAErUjNBqnyjoeeCgZUZFsAJeGHr/go-libp2p-gorpc/server.go:252 +0x3b5
gx/ipfs/QmYqnvVzUjjVddWPLGMAErUjNBqnyjoeeCgZUZFsAJeGHr/go-libp2p-gorpc.(*Client).makeCall(0xc42022ef00, 0xc42014c770)
	/go/src/gx/ipfs/QmYqnvVzUjjVddWPLGMAErUjNBqnyjoeeCgZUZFsAJeGHr/go-libp2p-gorpc/client.go:122 +0x251
created by gx/ipfs/QmYqnvVzUjjVddWPLGMAErUjNBqnyjoeeCgZUZFsAJeGHr/go-libp2p-gorpc.(*Client).Go
	/go/src/gx/ipfs/QmYqnvVzUjjVddWPLGMAErUjNBqnyjoeeCgZUZFsAJeGHr/go-libp2p-gorpc/client.go:99 +0x181
```

**Comment by Kubuxu** [comment]
@hsanjuan looks like `*Cid` is nil in this case casted (or otherwise created).

**Comment by hsanjuan** [comment]
yeah i know
