### ISSUE TITLE
cluster-follower 0.12.1 crashes with "out of memory" with dev branch ipfs

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1061]
#### Version information:
go-ipfs version: 0.5.0-rc1-6cb3ca41d
Repo version: 9
System version: amd64/linux
Golang version: go1.14.2

```
$ ipfs-cluster-follow --version
ipfs-cluster-follow version 0.12.1
```

#### Description:
I've updated from https://github.com/ipfs/go-ipfs/commit/6c45f9ed9ae1c6c4059fdac0312fca1f5883b9a3 to https://github.com/ipfs/go-ipfs/commit/6cb3ca41da701ca71603dec3d886611397ba141e while changing the go-pie version from 1.13.8 to 1.14.2 in the process.

After the reboot (since there was some kernel updated pending) I cannot start the cluster follower on the ipfs websites:

[error_log_cluster_follower.txt](https://github.com/ipfs/go-ipfs/files/4459211/error_log_cluster_follower.txt)

While the system got still 10 Gigabytes of memory free.

**Comment by hsanjuan** [comment]
I can only add that if you touched nothing, badger in this cluster is configured to FileIO so it should not allocate much on boot (as it seems). I don't see how the issue may be triggered by updating go-ipfs. I would assume that downgrading go-ipfs has no effect?

**Comment by RubenKelevra** [comment]
> * The stack trace says you're using the go 1.13 runtime.

The runtime version is different because ipfs-cluster-follow is a prebuilt binary.

Ipfs itself is built with Go 1.14.2.

> May be something funky with your toolchain? Or linux version?

I'm not sure? I haven't really "touched" anything on purpose.

* The kernel is 5.4.28.
* IPFS is built with the AUR package (and yay as helper): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=go-ipfs-git
* ipfs-cluster-follow is from dist.ipfs.io


> I would assume that downgrading go-ipfs has no effect?

I restarted ipfs and started the cluster follower again and it's working flawlessly - while nothing else changed.

> I don't see how the issue may be triggered by updating go-ipfs.

Me neither - but since it was crashing exactly at the moment when it tries to fetch a file from the web gateway. Why would it reserve 80MiB at this time?

If there's no reason why it should, just a guess in the blue: Maybe it got a very large file size reported by the web gateway, tried to allocate and failed (for some undetermined reason)?

That's the only reason I can think of, how the update could be related - while the trace doesn't look that way, but more like it was reserving memory for badgers.

But the database for ipfs-websites is extremely small:

```
$ du -hc /home/ruben/.ipfs-cluster-follow/ipfs-websites
160K    /home/ruben/.ipfs-cluster-follow/ipfs-websites/badger
176K    /home/ruben/.ipfs-cluster-follow/ipfs-websites
```

**Comment by hsanjuan** [comment]
I think I pulled some improvements for badger memory allocations that will be in the next release, so hopefully they make this issue harder to appear at least.
