### ISSUE TITLE
no re-pin triggered for files pinned on follower

### ISSUE THREAD

**Issue by davidB** [ipfs/ipfs-cluster#1064]
**Additional information:**
 - OS: alpine
 - IPFS Cluster version: 0.12.1
 - Installation method: dist.ipfs.io, peers run inside docker-compose stack

**Describe the bug:**

## short:

If a file is pinned, with a follower at the head of the allocation list, then the file is not re-pinned and break the replication-factor.
Maybe because follower doesn't check metrics alert ?

see https://github.com/ipfs/ipfs-cluster/blob/01d16cdebf93e34b5a0e2e3631399b83568cd68c/cluster.go#L435

## long

I'm playing with ipfs-cluster, so I setup a cluster (inside a docker-compose stack, not based on provided one) with:
* 5 trusted peer
* 4 followers
* replication factor 2-4

I add a file 

```sh
❯ docker-compose exec trusted_0 ipfs-cluster-ctl pin ls
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA |  | PIN | Repl. Factor: 2--4 | Allocations: [12D3KooWEmGnEHhzE2griAu8FtmUJabKZcwLShwMntwEKeox4TKC 12D3KooWEyiDvsaDvqPinKjbuhXDcxorBzWg9afxAjJbpQPa98rt 12D3KooWM6h81TUvpd4YFM7JcYa7AqYxumuYHCmSt6jA27WYH5M3 12D3KooWSa4msCZnh4HKpQQsKeZi8m72jvKPURyV2Wvivccu6HeE] | Recursive | Metadata: no

❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA :
    > peer_trusted_1       : REMOTE | 2020-04-09T21:19:29.0422344Z
    > peer_follower_0      : PINNED | 2020-04-09T21:19:29.0460973Z
    > peer_follower_2      : PINNED | 2020-04-09T21:19:29.0440167Z
    > peer_trusted_2       : REMOTE | 2020-04-09T21:19:29.0433494Z
    > peer_trusted_5       : REMOTE | 2020-04-09T21:19:29.0427891Z
    > peer_trusted_4       : REMOTE | 2020-04-09T21:19:29.0444842Z
    > peer_follower_1      : PINNED | 2020-04-09T21:19:29.041566Z
    > peer_trusted_0       : REMOTE | 2020-04-09T21:19:29.0445994Z
    > peer_trusted_3       : REMOTE | 2020-04-09T21:19:29.0423063Z
    > peer_follower_3      : PINNED | 2020-04-09T21:19:29.0441315Z
```

Then I stop `follower_1`, `follower_2`, `follower_3`  (11s between each)

```sh
❯ docker-compose stop follower_1
Stopping follower_1 ... done
...

❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA :
    > peer_trusted_1       : REMOTE | 2020-04-09T21:23:48.1631185Z
    > peer_follower_0      : PINNED | 2020-04-09T21:23:48.1611455Z
    > peer_trusted_2       : REMOTE | 2020-04-09T21:23:48.1648973Z
    > peer_trusted_5       : REMOTE | 2020-04-09T21:23:48.1625334Z
    > peer_trusted_4       : REMOTE | 2020-04-09T21:23:48.1609017Z
    > peer_trusted_0       : REMOTE | 2020-04-09T21:23:48.1605251Z
    > peer_trusted_3       : REMOTE | 2020-04-09T21:23:48.1613818Z
```

I wait few secondes, minutes, hours idem, then I start reading the code and the logs.

I noticed:

1. Only trusted peer raise alarm when a follower is down

    ```
    trusted_5      | 09:50:09.675 WARNI    cluster: metric alert for ping: Peer: 12D3KooWHLZ3xstxFfJc9fJDrwW29V215gX9EQisRbodzuYwB8VJ. cluster.go:404
    trusted_3      | 09:50:09.827 WARNI    cluster: metric alert for ping: Peer: 12D3KooWHLZ3xstxFfJc9fJDrwW29V215gX9EQisRbodzuYwB8VJ. cluster.go:404
    trusted_0      | 09:50:09.894 WARNI    cluster: metric alert for ping: Peer: 12D3KooWHLZ3xstxFfJc9fJDrwW29V215gX9EQisRbodzuYwB8VJ. cluster.go:404
    trusted_4      | 09:50:09.931 WARNI    cluster: metric alert for ping: Peer: 12D3KooWHLZ3xstxFfJc9fJDrwW29V215gX9EQisRbodzuYwB8VJ. cluster.go:404
    trusted_1      | 09:50:09.998 WARNI    cluster: metric alert for ping: Peer: 12D3KooWHLZ3xstxFfJc9fJDrwW29V215gX9EQisRbodzuYwB8VJ. cluster.go:404
    ```

2. metric alert should trigger check to know if re-pin is requested (from https://github.com/ipfs/ipfs-cluster/blob/01d16cdebf93e34b5a0e2e3631399b83568cd68c/cluster.go)

3. re-pin is trigger by the first peer in the allocation list (from https://github.com/ipfs/ipfs-cluster/blob/01d16cdebf93e34b5a0e2e3631399b83568cd68c/cluster.go#L435)

In my case the first (like all the members) of the allocation list is a follower that didn't log "metric alert for ping" => no check => no trigger.

**Comment by davidB** [comment]
adentum after restart, the file is no longer pinned (`REMOTE` everywhere):

```
❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA :
    > peer_follower_3      : REMOTE | 2020-04-10T13:18:32.6798722Z
    > peer_trusted_1       : REMOTE | 2020-04-10T13:18:32.681236Z
    > peer_trusted_2       : REMOTE | 2020-04-10T13:18:32.6795867Z
    > peer_trusted_5       : REMOTE | 2020-04-10T13:18:32.682663Z
    > peer_trusted_4       : REMOTE | 2020-04-10T13:18:32.681236Z
    > peer_follower_2      : REMOTE | 2020-04-10T13:18:32.682374Z
    > peer_trusted_0       : REMOTE | 2020-04-10T13:18:32.6807715Z
    > peer_trusted_3       : REMOTE | 2020-04-10T13:18:32.6846778Z
    > peer_follower_1      : REMOTE | 2020-04-10T13:18:32.6841268Z
    > peer_follower_0      : REMOTE | 2020-04-10T13:18:32.6837095Z
```

**Comment by hsanjuan** [comment]
Hmm, ok that's stupid. This is a bug affecting crdt mode.

What I don't fully understand is why the file appears as remote for all peers after restart? What is `ipfs-cluster-ctl pin ls Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA` showing?

**Comment by davidB** [comment]
From my log (I resetted the content of folder, for other test), after the restart:
```
docker-compose exec trusted_5 ipfs-cluster-ctl pin ls
...
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA |  | PIN | Repl. Factor: 2--4 | Allocations: [12D3KooWEmGnEHhzE2griAu8FtmUJabKZcwLShwMntwEKeox4TKC 12D3KooWEyiDvsaDvqPinKjbuhXDcxorBzWg9afxAjJbpQPa98rt 12D3KooWM6h81TUvpd4YFM7JcYa7AqYxumuYHCmSt6jA27WYH5M3 12D3KooWSa4msCZnh4HKpQQsKeZi8m72jvKPURyV2Wvivccu6HeE] | Recursive | Metadata: n
```

**Comment by hsanjuan** [comment]
Any changes your peers identities are reset after the restart? A peer would only report "REMOTE" if its peer ID is not in the allocations. I don't see a way a peer could start reporting REMOTE otherwise, but the allocations did not change (I guess).

**Comment by davidB** [comment]
It's possible for followers I didn't mount volume, else I got issue with the binding of the unix socket.

FYI, but maybe unrelated, during an other test, where file was pinned on trusted, I saw in log the request to re-pin and the "add pin" in log, but the allocation list stay the same and the `status`command doesn't report change.

**Comment by davidB** [comment]
I confirm after restart I did a `peers ls` and the peer id of followers were changed, so the peed i listed into the allocation list no longer exist. That explain the issue after restart.

Thanks,

Stay the original issue ;-)

**Comment by RubenKelevra** [comment]
Thanks for your testing!

**Comment by hsanjuan** [comment]
Summary:

* Currently repinning approach uses the current allocations and assumes the first one will pin, which might be a follower.
* Followers don't even handle alerts
* Even if they did they could not repin.

We need to change this to the same process that handles expiration:

* Make a list of potential trusted peers
* If we are the closest to the CID, handle the repinning
* Otherwise assume one of the other peers will do it
* Avoid acting altogether if in follower mode.

**Comment by hsanjuan** [comment]
@davidB any chance you can test with the fix in #1127  ?

**Comment by davidB** [comment]
I'll give a try next week (need to setup the build, and my dev stack to use a custom build,...)

Thanks.

**Comment by hsanjuan** [comment]
@davidB is it easier if I cut an RC release?

**Comment by davidB** [comment]
for me yes, having a pre built beta,rc will be easier (in this case I
should be able to test tomorrow)

**Comment by hsanjuan** [comment]
I will publish an rc1 on dist.ipfs.io soon.

**Comment by hsanjuan** [comment]
https://dist.ipfs.io has a v0.13.0-rc1 release now for cluster things (click on "all versions").

**Comment by davidB** [comment]
After first test, the fix seems to work 👍 

I copy paste the session, I added 1 file (replication factor 2-4), then stop all (2) the trusted with `PINNED` => replication-factor always ok, then I removed a followers => the replication factor no longer statisfy and replication retriggered.

```
❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA:
    > peer_follower_1      : PINNED | 2020-05-16T13:03:10.2039863Z
    > peer_trusted_0       : REMOTE | 2020-05-16T13:03:10.2045521Z
    > peer_follower_0      : PINNED | 2020-05-16T13:03:10.2035954Z
    > peer_trusted_2       : PINNED | 2020-05-16T13:03:10.2040161Z
    > peer_trusted_4       : PINNED | 2020-05-16T13:03:10.2071573Z
    > peer_trusted_3       : REMOTE | 2020-05-16T13:03:10.2038131Z
    > peer_trusted_1       : REMOTE | 2020-05-16T13:03:10.2052014Z
❯ docker-compose stop trusted_2
Stopping trusted_2 ... done
❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA:
    > peer_follower_1      : PINNED | 2020-05-16T13:04:20.6647618Z
    > peer_trusted_0       : REMOTE | 2020-05-16T13:04:20.66623Z
    > peer_follower_0      : PINNED | 2020-05-16T13:04:20.6648836Z
    > peer_trusted_4       : PINNED | 2020-05-16T13:04:20.6646182Z
    > peer_trusted_3       : REMOTE | 2020-05-16T13:04:20.6659036Z
    > peer_trusted_1       : REMOTE | 2020-05-16T13:04:20.6649061Z
❯ docker-compose stop trusted_4
Stopping trusted_4 ... done
❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA:
    > peer_follower_1      : PINNED | 2020-05-16T13:04:59.9640369Z
    > peer_trusted_0       : REMOTE | 2020-05-16T13:04:59.9633791Z
    > peer_follower_0      : PINNED | 2020-05-16T13:04:59.9631633Z
    > peer_trusted_3       : REMOTE | 2020-05-16T13:04:59.9642375Z
    > peer_trusted_1       : REMOTE | 2020-05-16T13:04:59.9651094Z
❯ docker-compose stop follower_0
Stopping follower_0 ... done
❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA:
    > peer_follower_1      : PINNED | 2020-05-16T13:05:29.4741908Z
    > peer_trusted_0       : PINNED | 2020-05-16T13:05:29.4745505Z
    > peer_trusted_3       : PINNED | 2020-05-16T13:05:29.473549Z
    > peer_trusted_1       : PINNED | 2020-05-16T13:05:29.4735243Z
```

Thanks for your work.

**Comment by davidB** [comment]
To complete the test, I restarted the stopped nodes, so nb PINNED (6) go over replication factor max (4) and after time it becomes again (4) as expected.

```
❯ docker-compose exec trusted_0 ipfs-cluster-ctl status
Qmc7tKhvaFDFKuqkfX2UEF81AwyPybUH3YR9GQk89h3UeA:
    > peer_follower_1      : PINNED | 2020-05-16T13:16:51.910817Z
    > peer_trusted_0       : PINNED | 2020-05-16T13:16:51.913689Z
    > peer_trusted_2       : REMOTE | 2020-05-16T13:16:51.9135806Z
    > peer_trusted_4       : REMOTE | 2020-05-16T13:16:51.9112129Z
    > peer_trusted_3       : PINNED | 2020-05-16T13:16:51.911502Z
    > peer_trusted_1       : PINNED | 2020-05-16T13:16:51.9111025Z
```

GG

**Comment by RubenKelevra** [comment]
@davidB thanks for your tests!

**Comment by hsanjuan** [comment]
> To complete the test, I restarted the stopped nodes, so nb PINNED (6) go over replication factor max (4) and after time it becomes again (4) as expected.

Great that it works!
