### ISSUE TITLE
ipfs-cluster docker container is not reachable

### ISSUE THREAD

**Issue by pontiyaraja** [ipfs/ipfs-cluster#1094]
**Additional information:**
 - OS: Ubuntu 18.04
 - IPFS Cluster version: docker pull ipfs/ipfs-cluster:latest
 - Installation method: [docker hub](https://hub.docker.com/r/ipfs/ipfs-cluster)

**Describe the bug:**

**> The API configuration in service.json file is not updating the REST API Listner to 0.0.0.0/tcp/9094
> its updating to 127.0.0.1/tcp/9094**

@hsanjuan

**Comment by hsanjuan** [comment]
Hello,

you need to set environment variable: `CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS=/ip4/0.0.0.0/tcp/9094` . Did you read somewhere that the rest api listener would be updated to 0.0.0.0?

It did this in the past, but since everything is controllable with env vars, we don't do it anymore.

**Comment by pontiyaraja** [comment]
Thank you @hsanjuan but, better to handle it from a script like ipfs

**Comment by pontiyaraja** [comment]
what about proxy and swarm endpoints ?

**Comment by hsanjuan** [comment]
> Thank you @hsanjuan but, better to handle it from a script like ipfs

IPFS does it in a script because it cannot understand env vars. It is much better to do env vars, particularly for any kind of cloud deployment. You can nevertheless replace the entrypoint with whatever script you like. The proxy and swarm endpoints work the same way with env vars: https://cluster.ipfs.io/documentation/reference/configuration/#using-environment-variables-to-overwrite-configuration-values

**Comment by pontiyaraja** [comment]
@hsanjuan I tried it by setting ENV variables 

`
ENV IPFS_CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS /ip4/0.0.0.0/tcp/9094
ENV IPFS_CLUSTER_IPFSPROXY_LISTENMULTIADDRESS   /ip4/0.0.0.0/tcp/9095
`

still its failing to connect

**Comment by pontiyaraja** [comment]
I'm suing Kubernetes node port service type

**Comment by pontiyaraja** [comment]
@hsanjuan why that environment variable not set in docker https://github.com/ipfs/ipfs-cluster/blob/master/Dockerfile

**Comment by hsanjuan** [comment]
Please ask in discuss.ipfs.io. This is not an issue with the codebase and I tried myself and things work as expected with Docker `-e 'envname=value` and `-p 9094:9094`. I don't know much about Kubernetes myself so I can't help there.

**Comment by pontiyaraja** [comment]
its not a discussion @hsanjuan
