### ISSUE TITLE
health metrics freespace shows wrong freespace if no space is left

### ISSUE THREAD

**Issue by i5heu** [ipfs/ipfs-cluster#1120]
```
ipfs@ipfs-cluster-master ~/ipfs-cluster-ctl> ./ipfs-cluster-ctl health metrics freespace
NODE1 | freespace: 18 EB | Expires in: 28 seconds from now
NODE2 | freespace: 1.9 GB | Expires in: 20 seconds from now
```

**Additional information:**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

ipfs-cluster-ctl version 0.12.1

**Describe the bug:**
Node 1 has no space left, but the free space value shows 18EB (that would be a dream).

**Comment by hsanjuan** [comment]
You're right. Sorry, that was a stupid thing to allow when the repo size is larger than the declared StorageMax.
