### ISSUE TITLE
0.12.1 and 0.13 compability

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1145]
I just updated the trusted node on my cluster and on a follower which still runs 0.12.1 I got this errors like 5 times a second:

`07:41:13.603 ERROR       crdt: expected 1 as the cid version number, got: 10 crdt.go:308`

Looks to me like a parsing error - 10 is the max-replication value of my pins.

**Additional information:**
 - OS: Linux
 - IPFS Cluster version: 0.12.1 and 0.13
 - Installation method: dist.ipfs.io

**Comment by hsanjuan** [comment]
Explained in https://github.com/ipfs/ipfs-cluster/blob/master/CHANGELOG.md. Can't do much about it. It was not possible to change the broadcast mechanism in a forward compatible way without keeping the same thing that I wanted to change.

**Comment by RubenKelevra** [comment]
I think a breaking change like this should also just break compatibility between those peers, avoiding that such a break floods the system-log of a system by repeated error messages :/

**Comment by hsanjuan** [comment]
A "breaking change" would have fixed the log with error messages, just different ones. It's breaking enough like this. Don't need to break Raft clusters if not needed.
