### ISSUE TITLE
ipfs-cluster-follow database gets inconsistent when running 0.12.x on a 0.13 cluster

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1157]
**Additional information:**
 - OS: CentOS 7 (cluster-follow)
-  OS: ArchLinux (cluster-service)
 - IPFS cluster-follow version: 0.13
 - IPFS cluster-service version: 0.13
 - Installation method: both from dist.ipfs.io

**Describe the bug:**

This is not meant to be a bugreport, but just a heads up for people who might run into the same issue.

I update the writing node on the cluster first to 0.13, and this resulted in inconsistent databases.

The followers will try to reinitialize the complete cluster pinset generations on each start, after updating to 0.13 and will stall after some minutes of processing the diffs. While they still show many generations remaining to process (merging data message with a priority) and some pin messages will be the last output.

To fix this the badger-db has to be removed and the cluster follower need to reinitialize the cluster-set.

**Comment by RubenKelevra** [comment]
@hsanjuan make sure to check your collab-clusters for any malfunctioning cluster-follower :)

**Comment by hsanjuan** [comment]
I am not sure why something like this would happen. Is it something you can reproduce with a test cluster?
