### ISSUE TITLE
Go Client Import and Test Fails

### ISSUE THREAD

**Issue by omkarprabhu-98** [ipfs/ipfs-cluster#1191]
**Additional information:**
 - OS: Windows 10
 - IPFS Cluster version: 0.13.0
 - Installation method: Import in Go
- Go Version: go1.14.3 windows/amd64

**Describe the bug:**

Running main.go after importing "github.com/ipfs/ipfs-cluster/api/rest/client" results in the following message:
```
➜  upload-service git:(master) ✗ go run .\main.go       
# github.com/libp2p/go-sockaddr
exec: "gcc": executable file not found in %PATH% 
```
Running test on "github.com\ipfs\ipfs-cluster@v0.13.0\api\rest\client" fails as shown: 
```
➜  ipfs-cluster@v0.13.0 cd .\api\rest\client\  
➜  client go test -v
# runtime/cgo
exec: "gcc": executable file not found in %PATH%
FAIL    github.com/ipfs/ipfs-cluster/api/rest/client [build failed]
➜  client pwd

Path
----
F:\go\pkg\mod\github.com\ipfs\ipfs-cluster@v0.13.0\api\rest\client
```

Please let me know if I missed something or any other information is required

**Comment by hsanjuan** [comment]
Hello,

this is not an ipfs-cluster issue. The error clearly states the problem. I suggest you install `gcc`. Unfortunately, there's little other help I can offer for a windows environment, you may want to ask in the forums or google the error if you keep having problems.

**Comment by omkarprabhu-98** [comment]
Sorry for the trouble!

I was under the impression that it should work directly by importing the package as specified in the [README](https://github.com/ipfs/ipfs-cluster/blob/master/api/rest/client/README.md) for the client. Since it was a go package, didn't seem like the GCC program would be an installation requirement, thus I opened the issue to inform people that this occurs.

However, after doing some digging, this issue has been noticed before:
- https://github.com/golang/go/issues/26988
- https://github.com/golang/go/issues/27303

The fix mentioned is to set CGO_ENABLED to 0
```
go env -w CGO_ENABLED=0
```

So installing GCC or it being windows platform is not the problem, so please **do not consider this issue as invalid** as it may help others facing a similar problem.
