### ISSUE TITLE
ipfs-cluster daemon fails to start when mdns discovery fails

### ISSUE THREAD

**Issue by vdebergue** [ipfs/ipfs-cluster#1193]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: 0.13.0
 - Installation method: dist.ipfs.io

**Describe the bug:**

When starting the ipfs-cluster daemon with `ipfs-cluster-service daemon`, the process can fail because the mdns discovery can't start (it can happen in a docker container with a `none` network). 

To reproduce:

```
docker run -it --rm --net=none ipfs/ipfs-cluster
```

output:
```
Changing user to ipfs
ipfs-cluster-service version 0.13.0-next+gitd2a83e45f1ad5f84a3eae70b46fb9b521b90ab03
This container only runs ipfs-cluster-service. ipfs needs to be run separately!
Initializing default configuration...
2020-07-17T10:32:58.111Z	INFO	config	config/config.go:481	Saving configuration
configuration written to /data/ipfs-cluster/service.json.
2020-07-17T10:32:58.115Z	INFO	config	config/identity.go:73	Saving identity
new identity written to /data/ipfs-cluster/identity.json
new empty peerstore written to /data/ipfs-cluster/peerstore.
2020-07-17T10:32:59.161Z	INFO	service	ipfs-cluster-service/daemon.go:46	Initializing. For verbose output run with "-l debug". Please wait...
2020-07-17T10:32:59.192Z	INFO	cluster	ipfs-cluster/cluster.go:132	IPFS Cluster v0.13.0-next+gitd2a83e45f1ad5f84a3eae70b46fb9b521b90ab03 listening on:
        /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWJeiBAhfNgGNZwWDAyXa4cVmVpzDZ7vGRY8YG9uh4TPdm


error starting cluster: No multicast listeners could be started
```

I would expect the daemon to continue to start but without the mdns listeners. This behavior is what ipfs daemon is doing in the same context.

**Comment by hsanjuan** [comment]
Hi,

can you clarify why net=none is an acceptable use case for ipfs cluster?

Btw, setting `mdns_interval`  to 0 should disable mdns.

**Comment by vdebergue** [comment]
I encountered the issue while trying to run ipfs-cluster inside [testground](https://github.com/testground/testground) with `local:docker` runner and managed to reproduce the behavior with `network=none`. 
So I guess it may also happen to docker containers when playing with custom networking (for [instance](https://medium.com/@joatmon08/making-it-easier-docker-containers-on-open-vswitch-4ed757619af9)). 

And yes `mdns_interval = 0s` works in this case 👍

**Comment by hsanjuan** [comment]
Thanks, ok I guess we can make this a non fatal error.

**Comment by sergeiudris** [comment]
- did reproduce the error by setting [`network_mode=none`](https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode) in docker-compose (same as or docker run network=none)
- PRed the change that makes MDNS error non-fatal, `needs review`
- [output after change inside container without network](https://github.com/sergeiudris/ipfs-lab/issues/4#issuecomment-778136651)
