### ISSUE TITLE
Status information for in-flight pins does not set the name field

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#1212]
The status objects include the pin names now, however this is not the case for pins that are currently being tracked (pinning, queued).

This is an issue in the `pintracker` module. The `optracker` module returns `PinInfo` objects that do not have the name set. This should probably be added as soon as they are tracked by checking the state (or when they are returned from the optracker).

**Comment by omkarprabhu-98** [comment]
we can get the pin name through the operation, add it in the PinInfo returned it here? please correct me if I missed something
https://github.com/ipfs/ipfs-cluster/blob/78b3111ed688bb88a16dfcd6f955bdceb91c89c0/pintracker/optracker/operationtracker.go#L155

**Comment by hsanjuan** [comment]
Probably, not 100% sure that there are no more subtleties involved. It would need a PinName() method with a read lock like Cid().
