### ISSUE TITLE
Support the Pinning Services API

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#1213]
**Describe the feature you are proposing**

A unified API for pinning services has been proposed:

https://github.com/ipfs/pinning-services-api-spec

IPFS Cluster can support this by adding a new API module. It seems most functionality in the spec can be supported fairly easily. This is mostly a subset of the REST API with JWT token authentication and some additional transformations on the data (specific pin objects).

**Comment by lidel** [comment]
It would be fantastic if people could spawn own ipfs-cluster and use it as self-hosted pinning service:
- https://docs.ipfs.io/how-to/work-with-pinning-services/

**Comment by lidel** [comment]
@hsanjuan given that cluster already has `/pins` endpoint with bit different semantics, and we [may to add "DAG import" endpoint to the spec](https://github.com/ipfs/pinning-services-api-spec/issues/73#issuecomment-837546271)  that would most likely work bit differently than `/add`, would it make sense to add all this "pinning service business" under `/service/pins` to make them coexist while having a very clear service part? Or would a separate HTTP port with pinning service endpoints easier to implement (given that we want to guard that with `Authorization: Bearer <access-token>`)?
