### ISSUE TITLE
Integrate the failover client in ipfs-cluster-ctl

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#1222]
**Describe the feature you are proposing**

ipfs-cluster-ctl should use the restapi LBClient with a Failover strategy.

Particularly, it should also be possible to create a Failover and a RoundRobin client strategy from a /dnsaddr. If the record resolves to multiple multiaddresses, each client should be initialized to one of them.

This needs a method to turn a single Config into multiple ones that can be used for `NewLBClient`, each of them with one multiaddress as resolved from the `/dnsaddr`. i.e. `config.AsTemplateFor([]multiaddresses) []Config` and `config.AsTemplateForResolvedAddresses(multiaddress) []Config`.

This should in the end enable `ipfs-cluster-ctl` to  perform auto-failover to other resolved addresses in a multiaddress.

**Comment by omkarprabhu-98** [comment]
So the input through the command line would be a list of client config attributes that would be converted to a list of configs and then be passed to create the LBClient?

**Comment by hsanjuan** [comment]
The input form the command line would be `ipfs-cluster-ctl --host /dnsaddr/my.host ...`.

Initializing the LB/Failover clients requires passing each 1 configuration for each endpoint in it. Thus, we need helper methods to, given a template configuration, produce multiple configs only changing the client multiaddress. As mentioned above, an additional method can actually perform resolving:

AsTemplateForResolvedAddresses(address) -> resolves -> calls AsTemplateFor(resolved_addresses).

Once you have these two helper methods, it should be easy to update ipfs-cluster-ctl to use the Failover client.
