### ISSUE TITLE
include cluter-follow to windows ipfs desktop

### ISSUE THREAD

**Issue by strelok899** [ipfs/ipfs-cluster#1245]
it much more user friendly and conviniet to have the ability to join cluster and help to redistribute IPFS from windows PC's 
and it can be easily implemented by community.

**Comment by hsanjuan** [comment]
Hi, I think this is an issue that belongs in https://github.com/ipfs-shipyard/ipfs-desktop/. I'm going to transfer it.

**Comment by hsanjuan** [comment]
I can't transfer it across orgs, so you'll need to open it there. Sorry!
