### ISSUE TITLE
Error when executing `ipfs-cluster-ctl add`

### ISSUE THREAD

**Issue by sohee227** [ipfs/ipfs-cluster#1265]
**Additional information:**
 - OS: Ubuntu 16.04.6 LTS
 - IPFS Cluster docker image version: v0.10.1
 - Cluster configuration: Five clouds, with Docker containers.

**Describe the bug:**
`ipfs-cluster-ctl add` command does not work. The error is as follows:
![image](https://user-images.githubusercontent.com/30330779/96698447-13b5ca80-13c8-11eb-9ad1-3d9d7d294235.png)

**Comment by hsanjuan** [comment]
I tried and it works for me. You are not using the latest cluster version, so maybe try that. If that also fails, include more information about how you are calling the add command.
