### ISSUE TITLE
Latest release broken on go 1.14

### ISSUE THREAD

**Issue by c00w** [ipfs/ipfs-cluster#1284]
quic-go, which is within the ipfs dependencies is broken on go1.14 with ipfs-cluster v0.13.0 (the current release). It appears this has been fixed with a dependency upgrade, however since a release has not been made since may (?!), that build dependency upgrade is not available in a stable release. Can a new release please be cut so that this can support go 1.15? go1.14 will fall out of support when go1.16 releases in February.

**Comment by hsanjuan** [comment]
Master is in 1.15. Can you build from master?

**Comment by c00w** [comment]
We are building from master to mitigate - but it's generally a good idea to have your go code for your last stable release work with the latest version of go - Right now anyone who uses an operating system which keeps go up to date can't build your code from a stable release :)

**Comment by hsanjuan** [comment]
Since I had to make a release, the latest version 0.13.1 uses go1.15 and all the deps are aligned to that.
