### ISSUE TITLE
Support --wait in ipfs-cluster-ctl add

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#1285]
**Describe the feature you are proposing**

Support the `--wait` flag just like in `pin add`. This makes mostly sense when adding with `--local`, since that is when the process of adding might be finished and the process of pinning may take a while longer (otherwise it should be pretty quick).

**Comment by RubenKelevra** [comment]
I think this would fix also https://github.com/ipfs/ipfs-cluster/issues/1067 right?

**Comment by hsanjuan** [comment]
No, not really.

**Comment by RubenKelevra** [comment]
Ah okay, I was getting excited too early ;D

**Comment by olizilla** [comment]
@hsanjuan when you get a moment could you cut a release of ipfs-cluster-ctl with --wait flag in from #1301

**Comment by hsanjuan** [comment]
Hey @olizilla , I'd like to release after https://github.com/ipfs/ipfs-cluster/issues/1319 gets addressed. The release dance is not a cheap one, but perhaps I can cut corners if you can live with an RC1.

**Comment by olizilla** [comment]
I can live with an rc1, but don't feel you need to cut a relase early for this, just wanted to check in.

**Comment by hsanjuan** [comment]
@olizilla this has now shipped in 0.13.2.
