### ISSUE TITLE
Add `wait` query param to `POST /pin` http api 

### ISSUE THREAD

**Issue by dholms** [ipfs/ipfs-cluster#1311]
**Describe the feature you are proposing**

`ipfs-cluster-ctl pin add` has an optional `--wait` flag that waits to return until the CID is pinned across the cluster. We pin to the our cluster via the HTTP API, and it's helpful to know when content is finished pinning so that we can notify the user that their content is replicated.

I am currently working to add this functionality, but wanted to add an issue to ensure that work wasn't currently being done on it/collaborate if it is.

**Comment by hsanjuan** [comment]
It's true the --wait part is not a server side feature, it is a client side feature (`ipfs-cluster-ctl` queries regularly the `status` endpoint for this).

There is helper logic in the `api/rest/client` for this.

Rationale here is that the `POST pin/{hash}` endpoint performs an operation on the shared state and returns a `Pin` type. This type does not have Status information, which corresponds to the Status endpoint (`GET pin/{hash}`).

Therefore, if --wait was to be a server-side feature, it should belong to the `GET pin/{hash}` endpoint (around here https://github.com/ipfs/ipfs-cluster/blob/78b3111ed688bb88a16dfcd6f955bdceb91c89c0/api/rest/restapi.go#L967) and you should query that endpoint after a successful POST /pin/{hash}.

If you are wrapping cluster with anything that then notifies the user, I'd suggest keeping things client-side and poll until you get what you want (things got pinned).

I'm not fully against reviewing implemention for this server-side, but i don't see too many reasons for the complexity increase and it would just also be polling anyways (cluster is architecturally designed to pin in an async way).

**Comment by dholms** [comment]
After diving into the code, this is what I found as well. We ended up doing what you suggested and polling `GET pin/{hash}` until we find that at least one node in the cluster has the requested content. Thanks!
