### ISSUE TITLE
stop using secio

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/ipfs-cluster#1315]
Not really familiar with the code base here, but I see that secio is still used in https://github.com/ipfs/ipfs-cluster/blob/fab2ed814934a19b690bc402a7b499c99f661cfd/api/rest/client/transports.go#L60-L67

#1227 already removed secio from the main package.

Should we disable it here as well? And should we add Noise instead?

**Comment by hsanjuan** [comment]
Thanks for noticing @marten-seemann . Yeah we should have removed secio in these places too, just forgot about them.
