### ISSUE TITLE
Inconsistent hash when using v1 CID

### ISSUE THREAD

**Issue by alanshaw** [ipfs/ipfs-cluster#1358]
When adding content with CID v1 `ipfs add file --cid-version=1` I get a different CID to when I add content with the IPFS Cluster HTTP API, passing `?cid-version=1`.

In IPFS, if you set `--cid-version=1` it implicitly sets `--raw-leaves=true` unless you explicitly pass `--raw-leaves=false`.

I believe that Cluster explicitly passes `?raw-leaves=false` on to IPFS even if you do not explicitly call the cluster API with this parameter and this is the reason for this discrepancy.

The workaround is to explicitly pass `?cid-version=1&raw-leaves=true`, but the current behaviour may be a surprise for people expecting to get the same CID from cluster as they get on the command line when using v1 CIDs.

**Comment by hsanjuan** [comment]
> I believe that Cluster explicitly passes `?raw-leaves=false` on to IPFS even if you do not explicitly call the cluster API with this parameter and this is the reason for this discrepancy.

Cluster does not add via ipfs. It chunks itself and does block-puts.

I will have to sleep on whether having magic defaults is good, but I guess worth fixing.

**Comment by hsanjuan** [comment]
So we do handle this client side at least:

https://github.com/ipfs/ipfs-cluster/blob/bfe179e94343321484f423d882b8770a6ecd4354/cmd/ipfs-cluster-ctl/main.go#L477
