### ISSUE TITLE
Empty CLUSTER_SECRET does not result in empty cluster_secret when initializing configuration

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#136]
it's ignored when the variable is defined but with an empty value...

**Comment by hsanjuan** [comment]
@dgrisham gonna give this one to you

**Comment by dgrisham** [comment]
`urfave/cli` doesn't seem to have support for distinguishing between unset and empty environment variables. I'll use [os.LookupEnv](https://golang.org/pkg/os/#LookupEnv) for this.
