### ISSUE TITLE
Invalid JSON on (possible?) failure when adding to the cluster

### ISSUE THREAD

**Issue by vasco-santos** [ipfs/ipfs-cluster#1365]
**Additional information:**
 - OS: [e.g. Linux] 
 - IPFS Cluster version: [e.g. 0.10.1, master] 0.13.3 (ipfs-cluster deployed for nft.storage)
 - Installation method: [e.g. built from source, dist.ipfs.io, docker] N/A

**Describe the bug:**

When attempting to do a cluster add with a complex/strange dag in a CAR file, the `ipfs-cluster` fails to add it (I could not figure out the concrete issue/type of dag).

Trying to add returns a `OK` response, but it does not return a JSON body. It seems that an error occurred and it should return not OK. This means the [cluster-client](https://github.com/nftstorage/ipfs-cluster/blob/main/index.js#L79) fails with:

```
Error: Unexpected end of JSON input
    at Function.storeBlob (file:///Users/vsantos/work/pl/gh/protocol/nft.storage/packages/client/src/lib.js:106:13)
```

I have a reproduction test case in https://github.com/nftstorage/ipfs-cluster/blob/main/index.js#L79 . Just need to clone the repo and run the `cluster-upload` script

**Comment by hsanjuan** [comment]
What is cluster actually returning, if not a json?

**Comment by vasco-santos** [comment]
The response looks 

```
response Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: ReadableStream {
      _state: 'readable',
      _reader: undefined,
      _storedError: undefined,
      _disturbed: false,
      _readableStreamController: [ReadableStreamDefaultController]
    },
    type: null,
    size: null,
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://cluster.io/api/add?cid-version=1&raw-leaves=true&format=car',
    status: 200,
    statusText: 'OK',
    headers: {
      'access-control-allow-headers': 'X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output',
      'access-control-allow-methods': 'GET, POST, OPTIONS',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Content-Range, X-Chunked-Output, X-Stream-Output',
      'cache-control': 'no-cache',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json',
      date: 'Mon, 21 Jun 2021 14:14:30 GMT',
      server: 'openresty',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      trailer: 'X-Stream-Error',
      'transfer-encoding': 'chunked',
      vary: [Array],
      'www-authenticate': 'Basic realm="Restricted"',
      'x-chunked-output': '1',
      'x-ipfs-pop': 'nft-storage-dc13'
    },
    counter: 0,
    highWaterMark: 16384
  }
}
```

If I read the text of the response it comes empty, if I read json I get:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>
```

**Comment by hsanjuan** [comment]
This was debugged and narrowed down to not using stream-channels plus timeout errors due to using big files without local=true when adding (the proxy closed the connection on lack of response).
