### ISSUE TITLE
Send content origin multiaddr with pin request

### ISSUE THREAD

**Issue by alanshaw** [ipfs/ipfs-cluster#1374]
Sometimes when pinning you do not have the content you want to pin, but you know of an IPFS node that does.

Sending the multiaddr of the origin node(s) would allow Cluster to short circuit content discovery and connect directly to the node that has the content to get it transferred faster.

Note this feature is part of the Pinning Services API https://github.com/ipfs/ipfs-cluster/issues/1213

**Comment by hsanjuan** [comment]
Implementation proposal here is to add "Providers" as a pin parameter (extending the options or the user-options). The ipfs connectors can take advantage of the hints during pin requests, issuing background swarm-connect calls to the providers.

**Comment by alanshaw** [comment]
Yep, the pinning service api calls it origins (https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post) but providers is probably a better name.
