### ISSUE TITLE
ERROR	diskinfo	disk/disk.go:96	Post "http://172.18.0.3:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.3:5001: connect: connection refused

### ISSUE THREAD

**Issue by zichun-xg** [ipfs/ipfs-cluster#1396]
cluster0    | 2021-07-07T11:08:55.867Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:587	error posting to IPFS:Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster0    | 2021-07-07T11:08:55.867Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:749	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster0    | 2021-07-07T11:08:55.867Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster0    | 2021-07-07T11:08:55.867Z	ERROR	diskinfo	disk/disk.go:96	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster0    | 2021-07-07T11:08:55.867Z	WARN	monitor	pubsubmon/pubsubmon.go:200	discarding invalid metric: &{Name:freespace Peer:12D3KooWRaT25zhmEnwsaDVnzDWVzPLnQEUodh7iamdZuE1ZXxuY Value:0 Expire:1625656165867197425 Valid:false ReceivedAt:0}
![2021-07-07 19-10-33屏幕截图](https://user-images.githubusercontent.com/52365871/124749637-11e06700-df57-11eb-8a7c-9b0753d23d26.png)
![2021-07-07 19-11-44屏幕截图](https://user-images.githubusercontent.com/52365871/124749737-31778f80-df57-11eb-939a-b0e98ebee703.png)

**Comment by hsanjuan** [comment]
Errors show the ipfs daemon is not running. It may start a bit later because it takes longer than cluster, and if that is the case, they can be safely ignored.
