### ISSUE TITLE
ERROR	ipfshttp	ipfshttp/ipfshttp.go:587	error posting to IPFS:Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused

### ISSUE THREAD

**Issue by zichun-xg** [ipfs/ipfs-cluster#1397]
It's been running for a whole day, and it's still Error

**Comment by hsanjuan** [comment]
Please do not open new issues to add comments to old issues. Check the ipfs container logs to see why it is not running.

**Comment by zichun-xg** [comment]
Dockerhub ipfs/go-ipfs after the update, it's okay.
