### ISSUE TITLE
Notes from trying out ipfs-cluster for the first time

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-cluster#14]
This is a quick rundown of a first-ever-user trying the `ipfscluster` tooling. Take it with a pile of salt: i noted down everything i ran into, including a bunch of problems that are obviously just polish not meant to be there yet, and other stuff which is probably meant to be experimental or a shortcut for now. I noted everything i ran into to give feedback on what was intuitive and what wasn't, first reactions, etc. My proper review is just beginning-- this is just a first stab at playing with it.

### Connectivity: the good feedback so far.

Already, I think some work can be done on the connectivity side of things. Here's the basic points. maybe these can be extracted to separate issues later, but keeping these here to retain the context.

- check connection to child ipfs node, and see what's going on there. (it wasn't clear to me that the communication was working. it was, i just didn't know how or what feedback to expect for correct or incorrect behavior)
- ideally `ipfs members ls` or something like it would show connectivity status, particularly both:
  - list cluster nodes ids (this is done) #15
  - list cluster nodes' child ipfs nodes' ids #15
  - whether the cluster nodes are currently connected (or disconnected) #15
  - whether the child ipfs node of this cluster is connected to the child ipfs node of the other cluster
  - should have an option to view multiaddrs of the connected entities. (this could just be done by supporting the `ipfs swarm` command. in reality, that should be a libp2p thing, so maybe we can lift that command out of go-ipfs and into go-libp2p, so that `ipfscluster` may take advantage of it). #15
- help ensure connectivity:
  - should discover other cluster nodes from each other-- i.e. if i connect: A -> C, and B -> C, A and B should find out about each other and connect to each other. #16
  - given A is connected to B and C (cluster nodes), A should tell its child node (Achild) to try to connect to Bchild and Cchild. this can be done with `ipfs swarm connect <multiaddr>`. #16
  - in practice, this should bust through nats. as long as one cluster node behind a nat manages to connect to a cluster node outside, it should be able to find other cluster nodes, and their child ipfs nodes and connect to everyone.
- we need some command to output the connectivity graph of all the components, to see who is connected to whom and what's _not_ connected. that way we can determine why something may not be working. Basically, figure out all libp2p nodes involved, and who they're connected to. Can use that to check connectivity in the graph of nodes (cluster nodes, child ipfs nodes, etc). #17

Also, some docs on what log levels or log modules i should listen to to figure things out would be good. Eg if i want to debug connectivity, or the consensus stuff, or the interactions with the ipfs connector, what level should i `--loglevel`. may be good to support per-module support (i think go-ipfs has this with an ENV var or something, i dont recall. it's useful to isolate a module and hear its debug output only). #18 #19

### Trace of trying out `ipfscluster`

- good looking readme.
  - could be more extensive. dont see how to setup a proper cluster #19
  - maybe could have a video or something #19
- good architecture doc. (will review properly later)
- naming 
  - ipfscluster-server = awkward
    - ipfs-cluster-server or ipfsclusterserver?
    - ipfs-cluster-service? ipfs-cluster-daemon?
- install
  - git co devel -- but that's fine. PR to master.
  - make install failed: 
    - go get -u gx. use $(shell which gx)? or download to a local installation. #20
    - go get -u the pkg deps. i had older versions of some packages which did not build.
      - if it _had_ built but been an older, buggy, wrong version and failed silently, it could have been potentially much worse and time waste for me. lucky it did not compile. #20 
    - also, don't use a global `go get -u` -- why should i mess up my system for you? #20 
      - i know this is idiomatic to Go, but it's not idiomatic to IPFS.[0] #20 
      - we are the people that use hash-linking to make sure we have what we intended to have. we should use that to our advantage here.
    - go get's on other packages do not use gx. we should version lock. ideally with gx.
    - gx install failed:
      - go-ipfs got stuck... i think it's a bitswap bug.
      - failed 3 times, wow... :c -- but hey, reproducible go-ipfs failures! yay! \o/
- ipfscluster-server -h
  - well written, clear, helpful
  - yay for config path
    - mayb euse `--config PATH` or `--config FILE`. it's not any string. #21
  - ideally would fit our other tooling help style. (USAGE, COMMANDS, OPTIONS, etc). maybe see the cli help tool gx uses (i dont recommend the one go-ipfs) #21
- i think we probably should default the config path to `$(pwd)/.ipfs-cluster` instead of `$(whoami)/.ipfs-cluster`, because in server side installations (more typical for clusters), users are not the typical place stuff is installed/stored. This is departing from the convention of go-ipfs and IPFS_PATH, but i think that's fine. #22
- ipfscluster-server init
  -  failed because it's lacking a dir, i think:
      ```
      > ipfscluster-server init
      error loading configuration: open /Users/earth/.ipfs-cluster/server.json: no such file or directory
      ```
  - `ipfscluster-server init --config .ipfs-cluster/server.json` did not work, took me a bit to realize the global flag had to be before the subcommand name.
  - `ipfscluster-server --config .ipfs-cluster/server.json init` worked as before (back to failing same way as above).
  - `mkdir .ipfs-cluster` is not enough. still same error.
  - `touch .ipfs-cluster/server.json` gets further, but crashes the process:
      ```
      panic: multihash too short. must be > 3 bytes #22

      goroutine 1 [running]:
      panic(0x682b60, 0xc420074b20)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
      github.com/ipfs/ipfs-cluster.NewMapPinTracker(0xc4201ef130, 0xc42016baa0)
        /Users/earth/go/src/github.com/ipfs/ipfs-cluster/map_pin_tracker.go:45 +0x370
      main.main()
        /Users/earth/go/src/github.com/ipfs/ipfs-cluster/ipfscluster-server/main.go:134 +0x221
      ```
  - maybe it's because it's not json? but `echo '{}' >.ipfs-cluster/server.json` did not work. same error.
  - Ohhh `init` is an option, not a command! (`ipfscluster-server -init`, not `ipfscluster-server init`). that took a while. 
    - not sure why i didn't notice this before. i'm biased to init being a subcommand. (`git init`, `ipfs init`, etc.), and to "commands" being in subcommand notation, not options. (i know golang flags isn't good about this.)
    - it probably should be a subcommand. #21
    - not a big deal anyway, this is a minor detail. but probably important to figure out for other subcommands too (look slike just version). 
  - "try deleting it first." maybe ask user to use `-f` to overwrite. having to `rm` manually is annoying. and it's less automation friendly. #21
  - ok yay it worked!
  - maybe the config file keys should be Go-style (CamlCased), as our other config files do it.
    - this is a stylistic choice. i dont care much about it. others may. #22
    - i do prefer consistency though in style #22
  - ok on to setup a cluster.
- ipfscluster-server init & run on 3x machines.
  - looks like i have to edit the configs manually to add members?
  - wait let's look at `ipfscluster`
- `ipfscluster` has a short command listing, nice. 
  - but the help is not too long. and it should have it too.
  - maybe this belongs under `COMMANDS` section in -h.
- adding a member
  - looks like `ipfscluster member` lacks `ipfscluster member add`. #23
  - hmm i guess it's just a multiaddr? but to what, go-ipfs?
  - it's not clear to me whether i should point to the go-ipfs node or directly to the other ipfscluster-server instances. yeah probably the latter, the config file shows a "api_port" which is different from "ipfs_api_port".
  - Ok, so it looks like ipfscluster-server is going ot use whatever available ipfs node it finds. 
    - maybe it should manage its own? (i originally thought it would work this way).
    - it should be configurable either way. i probably should be able to just use the `ipfscluster` tool to do everything. (launch the `ipfscluster-server`, launch `ipfs daemon`, a local one or a global one.).
- these names are confusing, see comments: #21
      ```js
      {
        // ...
        "ipfs_api_addr": "127.0.0.1", 
        "ipfs_api_port": 9095,
        "ipfs_addr": "127.0.0.1",
        "ipfs_port": 5001    // this is an ipfs_api, so hard to distinguish from ipfs_api_port.
                             // maybe it should be "ipfs_node_port". #22
        // ...
      }
      ```
    - Also, don't use separate addrs and ports, use a multiaddr. The IPFS API is _not at all guaranteed_ to be served over HTTP or TCP. it could be over gRPC over a unix domain socket, or utp, or whatever. maybe use: 
      ```
      "ipfs_cluster_api": "/ip4/127.0.0.1/tcp/9095/http",
      "ipfs_node_api":    "/ip4/127.0.0.1/tcp/5001/http",
      ```
    - this isn't good yet-- something is missing. a distinguishing word instead of `"node"`. (becauser the cluster one is a node, and the cluster one is really the cluster api).
    - `"underlying_ipfs_node_api"` is more clear, but long. and `"underlying"` is not that good of a word. maybe we should clarify the relationship between the cluster (and the ipfs-node it represents) and the sub ipfs-node. maybe "parent/child" works for this, because it works with the tree recursive structure?
      ```
      "cluster_node_api": "/ip4/127.0.0.1/tcp/9095/http",
      "child_node_api":    "/ip4/127.0.0.1/tcp/5001/http", 
      // or
      "parent_cluster_api": "/ip4/127.0.0.1/tcp/9095/http",
      "child_node_api":    "/ip4/127.0.0.1/tcp/5001/http", 
      ```
    - We should consider having an ascii diagram (like the illustration we have from keynote) to convey the components and tree structure in the help text, so that users know what's going on. (@diasdavid is pretty good at ascii diagrams.) #19
  - ok back to adding a member
    - I think I have to link to it manually from the config, in `cluster_peers`. but now i'm not sure how. 
      - If the config doesnt take multiaddrs for the api addresses, what does it take for the `cluster_peers` array? #24 #19
      - oh, code says multiaddrs. yay.
    - Ok, but what format of multiaddr? `/ip4/127.0.0.1/tcp/9095/http`? or `/ip4/127.0.0.1/tcp/9095`? or what?
      - Code looks to be parsing an IPFS multiaddr. (so like `/ip4/127.0.0.1/tcp/9095/ipfs/Qmfoobarbazpk...`).
      - But is this supposed to point to an ipfs node, or to the peer's cluster node? Oh, is it already using libp2p to mount itself as a libp2p protocol? (dont think so as the corenet stuff isnt merged yet...).
      - Oh got it, cluster creates its own libp2p Node, and connects between the peers using libp2p.
  - reading code to get a better understanding. 
    - go-libp2p-rpc is pretty cool
    - ok so it seems we have a libp2p network stack, and a go-libp2p-rpc protocol mounted on top, and _that's_ how cluster nodes talk to each other.
    - hm there's some abstraction/byzantine questions there (eg why does the node call a func on the leader instead of sending a message, etc). #25
    - maybe this is an rpc for clients, and not between cluster nodes? -- No, the docs say "enables components and members of the cluster to communicate and request actions from each other"
    - _[got distracted; went to sleep]_
    - _[return next morning]_
    - we must make sure the cluster node to cluster node RPC model fits in a byzantine environment. right now it seems that directly calling a function on the leader is setup to fail in the byzantine case. Also what about leaderless consensus protocols? Many consensus protocols do not use leaders. It seems there's a conflation here between what is the role of the consensus protocol and what is the role of the ipfs-cluster protocol (which right now includes both consensus protocol updates AND direct node-to-node RPC calls). I think we should be able to abstract out all inter-cluster-node communication to ONLY operating on the consensus log. I may be wrong about this, i need to dig into understanding the need for the RPCs better.
    - why does the consensus interface export a Leader() function? that should be a subclass of "Leader-based Consensus Protocols" if anything. #25
    - Is this intended as a shortcut for now (fine)? or is this meant for the long run? (not fine, we need ipfs-cluster to operate on top of leaderless consensus protocols) #25
 - ok, back to adding a member (third time's a charm!)
    - I think i need to construct a multiaddr by combining server.json's `"/ip4/%s/tcp/%s/ipfs/%s", config.api_addr, config.api_port, config.id`.
    - would be nice if there was a command like `ipfscluster id` similar to `ipfs id`. #21
    - i wonder what the ipfs peer id of the entire cluster is, or where that is defined. 
      - the id listed in the config seems to be the id of the libp2p ipfs cluster node, which is neither the id of the child ipfs node, NOR the simulated cluster ipfs node, it's a third libp2p node (which is fine), just clarifying for myself/readers).
      - reminder: switch libp2p over to use `/p2p` protocol prefix, not `/ipfs`, would be less confusing here.
    - ok, so wrote this tool: https://gist.github.com/jbenet/7007202501fc1c4eb623327e5328cb9d
      - i think it's actually `config.cluster_addr, config.cluster_port` that we want for this.
      - works: /ip4/0.0.0.0/tcp/9096/ipfs/QmbGvizLZHVWto8ZWU2tbkNcV6W92G6AggKdPfx5gFbLZz
      - oops, 0.0.0.0. need the actual ip addr. nvm, should've added this to `ipfscluster`. let's do it manually for now. #21
    - yay! got them to connect. sweet.
    - --debug logs are sweet, shows tons of activity.
    - btw i dont think disconnections and reconnections are graceful. killing one node and starting it again shows some errors. not sure if just notices, or actually problematic. we'll see. #26
    - also ^c on one node, then ^c on the other hangs, looks like it's trapping the exit signal and waiting for the other members to respond, so it's stuck. cant kill it, only kill -9.
    - `ipfscluster member ls` sweet.
      - yeah, killing one node and then doing member ls still shows both, but should only show one now. (or signal who is online and who is not) #15
  - connected, ok now let's pin.
    - ipfs pin add <cid> fails:
        ```
        // ipfscluster
        Error 500: leader unknown or not existing yet
        ---
        // ipfscluster-server logs
        15:14:24.627  INFO    cluster: pinning:QmcskskhwkUFh1vvZbGFhBJhVMvzg6Hx44niysaoiiQGVt cluster.go:275
        15:14:24.627 ERROR libp2p-rpc: leader unknown or not existing yet client.go:125
        15:14:24.627 ERROR    cluster: sending error response: 500: leader unknown or not existing yet rest_api.go:396
        ```
    - ok then, maybe i need a third node for there to be a raft leader. let's add a third.
    - can we just add a third to one node and that will propagate info about the cluster? ie, will the other two nodes find each other? #24
    - nope. adding a third only adds the third to that one node who knows about the other. `ipfscluster members ls` shows (2, 2, 3), instead of (3, 3, 3). 
      - this makes startup tricky, particularly because of reconnection correctness uncertainty.
      - ok link like this:. 1->[], 2->[1], 3->[1,2].
      - looks like they all have each other. `ipfscluster members ls` shows (3, 3, 3)
      - looks like we'll need a "inspect connectivity" command that figures out the cluster connectivity and prints it (possibly graphs it in d3), to make sure our clusters are finding each other and well connected (n^2). #17 
      - and we'll have to figure out how node discovery should work. could plug a node discovery protocol directly into the cluster's libp2p node. OR do it at a higher level (probably safer...). #24
  - ok let's try pinning again.
    - seems to have worked:
        ```
        > ipfscluster pin add <cid>
        Request accepted
        ---
        // ipfscluster-server logs
        15:21:08.581 ERROR libp2p-raf: QmbGvizLZHVWto8ZWU2tbkNcV6W92G6AggKdPfx5gFbLZz: Pipeline error: EOF transport.go:716
        // is this bad? o/
        15:24:19.916  INFO    cluster: pinning:QmcskskhwkUFh1vvZbGFhBJhVMvzg6Hx44niysaoiiQGVt cluster.go:275
        15:24:19.963  INFO    cluster: pin commited to global state: QmcskskhwkUFh1vvZbGFhBJhVMvzg6Hx44niysaoiiQGVt consensus.go:267
        15:24:20.348  INFO    cluster: IPFS object is already pinned: QmcskskhwkUFh1vvZbGFhBJhVMvzg6Hx44niysaoiiQGVt ipfs_http_connector.go:205
        ```
    - now, let's verify. 
    - `ipfscluster pin ls`. #2 and #3 have it, #1 does not. probably that pipeline error, got disconnected... but `ipfscluster members ls` still shows 3 for everyone, but i think #1 disconnected.
    - killed and restarted #1. `#1> ipfscluster members ls` shows just 1. ok need to reconnect #2 and #3.
    - killed #3 (connected to #1 and #2) and restarted it, oops panic: https://gist.github.com/jbenet/55697b749e9f99d2ebf59ae51083bf51
    - killed #2. `2016/12/30 18:30:23 [INFO] snapshot: Creating new snapshot at /home/jbenet/.ipfs-cluster/data/snapshots/421-8-1483140623423.tmp` took a while.
    - started #2 (#1 and #2 on, #3 off). `ipfscluster members ls` shows (3, 2). probably from #3 before it paniced. ok restart everything.
      - start #1. `#1> members ls -> (1)`
      - start #2. `{#1, #2}> members ls -> (1, 2)`, `#2> members ls -> (1, 2)`.
      - start #3. `{#1, #2, #3}> members ls -> (1, 2, 3)`, ok all set. (3, 3, 3).
    - ok, i THINK #1 should automatically catch up with the others, and get the pin, no?
      - Woooh! yeah! \o/ it does!. let's inspect the ipfs nodes manually, and verify the pins.
        - `ipfs pin ls <cid>` ... stuck in 2 machines. looks like it's iterating over the entire damn pinset, hanging the machine...
        - `ipfs refs local | grep <cid>` shows it in #3 (where it was added), but not on #2 nor on #1. looks like the cluster server knows about the pin, but it did not translate to the child ipfs node i had running in those machines... so it did not pin it.
        - hmm the `ipfscluster-server` logs should maybe show whether it found + can connect to the child ipfs node.
            ```
            > ipfscluster status
              cid: QmcskskhwkUFh1vvZbGFhBJhVMvzg6Hx44niysaoiiQGVt
              status:
                  QmTHEzZHGTSiVFFM2h3TgFCSsp2Ecq82U6heAxK7jJRijF: (#2)
                      ipfs: pinning
                  QmUmQ2DRe2keGN8meXXLWjUgGbyiBLPWJFXGi4c2kfDGJb: (#1)
                      ipfs: pin_error
                  QmbGvizLZHVWto8ZWU2tbkNcV6W92G6AggKdPfx5gFbLZz: (#3)
                      ipfs: pinned
            ```
        - ok i have verified that the child ipfs #3 is directly connected to the child of #1, but not #2.
        - ok manually connected #3 to #2 (using `ipfs ping`).
        - something happend in #2's logs. `ipfscluster status` now shows `pinning -> pin_error` on #2.
        - okay, i wonder if it's stuck on `pin_error` forever, or whether the cluster will try to get the node to repin.
        - right now the cluster is in a failed state: the consensus log advanced to track the cid, but 2/3 of the nodes have not pinned. not sure if they will retry, or just get stuck in the failure.
        - let's try issuing it again...
        - same thing. #2 says: `18:46:41.588 WARNI    cluster: IPFS unsuccessful: 500: Path 'QmcskskhwkUFh1vvZbGFhBJhVMvzg6Hx44ed' not pinned`
        - ok reboot #2. 
        - woah, `ipfscluster status` paniced. then #2 paniced: https://gist.github.com/jbenet/e04c59731ce33a3522603efa7a22f3d3
        - very flaky.
        - now ipfscluster-server wont start. what? https://gist.github.com/jbenet/e04c59731ce33a3522603efa7a22f3d3
        - no idea why. maybe a dir is locked. or something.
        - http://grokbase.com/t/gg/golang-nuts/15315a1hhs/go-nuts-getting-runtime-cgo-pthread-create-failed-resource-temporarily-unavailable-crashes
        - no, maybe the os thread is hosed? or some other resource? may need reboot?
        - ok waited 2min and the os recovered.
      - killed everything, started everything. 
      - still nothing, pins wont cross. maybe there's a bitswap bug here. let me reboot the ipfs nodes.
      - stopped all 3 ipfs nodes. stopped all 3 ipfscluster-server nodes.
      - started ipfs nodes. started ipfscluster-server nodes. `ipfscluster members ls` shows (3, 3, 3). 
      - ok, check the pins. still say pinning...
      - ok manually connect #3 to #2 and #1, because #3 is behind a nat ...
      - woah great, now everything says "pinned"!
      - `ipfs pin ls <cid>` shows the pin on all 3! \o/ Yay.
      - that's awesome, it:
        - kept trying to pin the thing.
        - kept once it got it, the cluster figured it out, and finished getting the pin. \o/
        - i wont try messing with it (`ipfs pin rm <cid>` in the child manually, hoping the cluster will notice the pin fail).
    - ok let's try a whole directory.
      - yay! it worked just fine! 
       - looks like ipfs connectivity problems caused the initial isses, which made ipfscluster-server connectivity problems worse.
      - and `ipfs refs local | grep <cid>` shows the pin. yay!
    - ok that's sweet. that's great to see.
    - how can i inspect the raft log manually? i guess `ipfscluster pin ls` 
    - wait, `ipfscluster pin ls` shows the second pin, but no longer the first... the 2nd contains the 1st, but these should not be coalesced.
      - why? i may `pin A, pin B, unpin B`, and I expect `pin A` to remain, whether or not `B` contains `A` is irrelevant.
    - ok i pinned unrelated file `C` and now `pin ls` shows both `B` and `C`.
- ok i'm going to stop for now. 

### Summary

- total time playing with ipfs-cluster: around 4-5 hours.
- i managed to pin things to the cluster. \o/ yay.
- found some panics :0
- ipfscluster recovered pinsets after rebooting. sweet!!
- some feedback on some of the abstractions and tooling construction
- lots of feedback on connectivity, seems to be the main source of problems i ran into.
- lots remains to be reviewed + studied
- i am already very excited about using it to track my personal content!! 😄 
  - a bunch of tooling comes to mind that i want (get size of pinset, etc), but all that comes later.
- intense correctness testing comes to mind. we need tests that do all sorts of things, particularly:
  - particularly messing with the underlying child ipfs nodes (i.e. making them drop pins, or removing content without removing the pin (simulate data loss in the child) to make sure the cluster can self heal.
  - we need tests with harsh connectivity settings: certain connections being impossible, certain connections being flakey, bandwidth limitations, etc. another thing to add to the testing lab queue.

Me when the pins succeeded:

![](https://media.giphy.com/media/rl0FOxdz7CcxO/giphy.gif)

---

[0] Notes on go packaging. (TL;DR: use gx-go. this is the expanded _why_ use gx-go). Warning: this is a **contrarian view** in respect to the Go language. And this is a standard, sane view from package management, version control, and secure open source. Go packaging is designed for monolithic codebases (well tended sequoia) not open source (haphazard expansive brush forest). Go was designed at Google, baking into the language many of the software engineering practices of Google. In general this is a great thing. In the cases where open source != how google develops, it is not. Google has a single, huge tree of code, with atomic safe updates. You  cannot merge something into the tree if ANYTHING across all (most) of google fails to compile/errors. Open Source is fundamentally different. There is no such atomic-safe-update gating. We cannot assume other people's systems are setup like ours, or that they want to update their tree to the version we require (running `go get -u` for the user may be harmful to them). Or that we know who is depending on our code (lots of private code may depend on our package). Or that whoever is running a package we depend on wont screw everything up by moving something or breaking an API. Go uses location addressing for package identification... not just inside a single dilligent org (which works really well) but in the broader internet (which can fail catastrophically). Despite years of heated arguments on this, the Go team has not yet understood this is a real problem (they washed their hands off of it by having an external committe handle it). But that's ok because we are the people who use hash-linking to securely address everything. Let's use it to our advantage!

**Comment by hsanjuan** [comment]
wow THANKS! This is really valuable feedback. I'm going to turn it into issues so I can keep a good track of how far I am addressing everything you point out.

Two comments:

* On the leader/consensus questions:
> I think we should be able to abstract out all inter-cluster-node communication to ONLY operating on the consensus log

> why does the consensus interface export a Leader() function? that should be a subclass of "Leader-based Consensus Protocols" if anything.

> Is this intended as a shortcut for now (fine)? or is this meant for the long run? (not fine, we need ipfs-cluster to operate on top of leaderless consensus protocols)

  * You are right about calling the leader from a place that should be completely abstract to how consensus works below. Super easy to delegate this to the consensus component though. Note that the consensus interface `go-libp2p-consensus` does not export `Leader()`. `go-libp2p-raft` does. The consensus component (maybe you mean that) should probably not export `Leader()`. The consensus component is not 100% abstract to the protocol below, but it tries to be on the most part so it should be very easy to replace with a different implementation.

* Panics: one is definitely from cluster (good catch!). The others I'm inclined to think they are unrelated.

* Of all, this is unexpected:

> wait, ipfscluster pin ls shows the second pin, but no longer the first... the 2nd contains the 1st, but these should not be coalesced. why? i may pin A, pin B, unpin B, and I expect pin A to remain, whether or not B contains A is irrelevant. ok i pinned unrelated file C and now pin ls shows both B and C.

  * Did you just have 3 pins in total? A pin can only go away from the list show by `pin ls` with `pin rm`. I don't see an execution path which makes it disappear and reappear, unless some weird consensus state catch-up problem.

**Comment by hsanjuan** [comment]
I have created a [Milestone](https://github.com/ipfs/ipfs-cluster/issues?q=is%3Aopen+is%3Aissue+milestone%3ABeta) with a bunch of tickets related to the feedback above. I have edited the first post items with links to related tickets.

**Comment by hsanjuan** [comment]
There are only 2 tickets left in the milestone that I created to address much of this feedback. I am closing the ticket for the moment.

**Comment by hsanjuan** [comment]
Cleaning up, all the things in the milestone were fixed a while ago
