### ISSUE TITLE
ipfs-cluster release 0.14.0 is missing on cluster.ipfs.io

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1408]
@hsanjuan I think you're maintaining the [news on cluster.ipfs.io](https://cluster.ipfs.io/news/), right?

The [0.14.0 release](https://blog.ipfs.io/2021-07-12-ipfs-cluster-0-14-0/) is missing there.

**Comment by hsanjuan** [comment]
I don't add news for every release.

**Comment by RubenKelevra** [comment]
Ah okay :)
