### ISSUE TITLE
pubsubmon: msgpack decode error [pos 1]: only encoded map or array can decode into struct

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#1409]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: 0.14.0
 - Installation method: dist.ipfs.io

**Situation after the update:**

I just updated my main cluster node to 0.14.0 and get these error messages in the log:

```
ERROR        monitor        pubsubmon/pubsubmon.go:136        msgpack decode error [pos 1]: only encoded map or array can decode into struct
```

The update describes this, as the following:

> This release is not fully compatible with previous ones. Nodes on different versions will be unable to parse metrics from each other (thus peers ls will not report peers on different versions) and the StatusAll RPC method (a.k.a ipfs-cluster-ctl status or /pins API endpoint) will not work. Hence the minor version bump. Please upgrade all of your cluster peers.

**The issue:**

I prefer not having cryptic error messages in my log if a node with a not fully compatible version is joining my collab cluster.

Can we bump the compatibility version if an update is not compatible and this way just deny these connections?

We could just print an error message on the cluster follow binary, that all cluster members which it tried to reach have a not compatible version, and shut down.

And on normal cluster nodes just a single warning message, that the protocol version of a connecting node wasn't compatible.

**Comment by hsanjuan** [comment]
I sent a patch to mitigate what can be mitigated. You are right, this could have been handled more elegantly.

I think I should have ported the deprecated multicodec things and kept compatibility. I moved too fast.

There is a gray area between fully breaking compat (by directly breaking all connections) and keeping full compat (by accumulating hacks and special cases) and I'm usually avoiding the extremes here, but in this case we should have probably kept compatibility.
