### ISSUE TITLE
basic auth not working as expected

### ISSUE THREAD

**Issue by rvalle** [ipfs/ipfs-cluster#1416]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: 0.14.0+gitf7e6f4a26c01c4e06afade6007c08b50bf534661 (latest docker)
 - Installation method: docker

**Describe the bug:**

basic authentication is not working as described in documentation or as discussed in other issues here:

adding to service.json
```
    "restapi": {
      "http_listen_multiaddress": "/ip4/0.0.0.0/tcp/9094",
      ...
      "basic_auth_credentials": {
        "theuser": "thepass"
       },
       ...
```

and also running:

```
/data/ipfs-cluster # ipfs-cluster-ctl --basic-auth "theuser:thepass" --force-http pin ls
An error occurred:
  Code: 401
  Message: Unauthorized
```

Is behaving as if the username password validation was implemented in a different way.

Any idea of what could be going on?

**Comment by rvalle** [comment]
I think the issue is related to CLUSTER_RESTAPI_BASICAUTHCREDENTIALS

I think the format of this variable is not clear, according to the documentation that would be a json object

```
CLUSTER_RESTAPI_BASICAUTHCREDENTIALS="{'user':'pass'}"
```
But I dont think this is working. 

Also I misunderstood that environment functionality looks like it is used to generate the service.json file AND will also override the service.json, thus, all my testing modifying the service.json didn't work, I guess.

**Comment by rvalle** [comment]
just in case something falls into the same issue: 

```
CLUSTER_RESTAPI_BASICAUTHCREDENTIALS="user:pass" 
```

does works. 
the environment variable will be used to gernerate the service.json file, but while the environment variable is present it will take precedence, thus, editing the service.json will not make any difference.

**Comment by hsanjuan** [comment]
Yes, I was just writing that. Afaik, this is not documented. Did you find any place where this was written?

```
CLUSTER_RESTAPI_BASICAUTHCREDENTIALS="{'user':'pass'}"
```

**Comment by rvalle** [comment]
thanks @hsanjuan 

No, I guessed it from the Documentation, it mentions that the content is a JSON object. In my case I did set it from ansible with  ```{{credentials  | to_json}}`` 

Now I wonder if I can pass several username/passwords, as it seems to be allowed in the service.json file

**Comment by hsanjuan** [comment]
Yes, comma-separated as `user1:pass1,user2:pass2`.

**Comment by rvalle** [comment]
@hsanjuan thanks
