### ISSUE TITLE
[Question] is there a way to set the proxy node multiaddress value thru env or CLI ?

### ISSUE THREAD

**Issue by shazz** [ipfs/ipfs-cluster#1417]
Hi,

Using docker-compose and environment variable, it is possible to set the IPFSPROXY listening address (`CLUSTER_IPFSPROXY_LISTENMULTIADDRESS`) but not the node multiaddress (else the proxy returns `502 bad gateway`).

I tried with `CLUSTER_IPFSPROXY_NODEMULTIADDRESS` but no success.

Without patching manually the `service.json`, is there a way thru env or cli to set the good node value (an not localhost where no ipfs node is listening) ?

Thanks !

**Comment by hsanjuan** [comment]
You would need to set `CLUSTER_IPFSHTTP_NODEMULTIADDRESS`.
