### ISSUE TITLE
Adding directory recursively: Missing files

### ISSUE THREAD

**Issue by rvalle** [ipfs/ipfs-cluster#1420]
I think adding a directory recursively with ```ipfs-cluster-ctl pin add --recurse```

Is it possible that it is leaving out directories and files that start by ```.``` ?

I noticed that the ```.well-known``` directory is missing after adding it with ipfs-cluster-ctl.

I also noticed no option referring perhaps to hidden files or similar.

**Comment by hsanjuan** [comment]
`ipfs-cluster-ctl add --help` documents a `--hidden` flag.

**Comment by rvalle** [comment]
@hsanjuan sorry I missed it. thanks!
