### ISSUE TITLE
API design discussion

### ISSUE THREAD

**Issue by dgrisham** [ipfs/ipfs-cluster#144]
This discussion is meant to decide the best way to write our APIs in a clean way that allows us to add features in the future without 1. specifying them in the present, and 2. making breaking changes when they are introduced. Satisfying all of these points (cleanliness and future-proof) is not that simple in Go as it currently stands.

### Approach 1: Adding API functions

This approach, which is fairly future-proof but isn't clean, is to write a new function when a new feature is added, e.g.:

```go
func NewAPI() API {...}
// added later
func NewTLSAPI() API {...}
```

While this ensures that nothing breaks for users when they get a new version (the older functions remain intact), it also scales horribly: 2^x functions for x features...

```go
func NewAPI() API {...}
func NewAPIFeat0() API {...}
func NewAPIFeat1() API {...}
func NewAPIFeat1Feat0 API{...}
...
```

### Approach 2: Configuration type

We could also implement a `Config` type, something like:

```go
type Config struct {
    Feat1 Type1
    Feat2 Type2
}

func NewAPI(conf Config) API {...}
```

If a user calls our API function and leaves out any `Config` fields, those will automatically default to the zero value for the types of those fields. For example, if we add TLS support to our API and the user isn't aware or simply doesn't want to use it

```go
// API code

type Config struct {
    tls TLS
}

func NewAPI(tls TLSConfig) API {
    if tls == nil {
        // don't use TLS
    }
}

// user code
api := API.NewAPI(API.Config{})
```

Removing a `Config` field would be a breaking change for any users using that feature, but that's also true of the first approach (e.g. removing the `NewTLSAPI()` function).

There is another, kind of subtle, possible issue with this. If the user tries to embed our `Config` type in another type of their own without naming it, then there could be an ambiguity:

```go
// user code
type MyConfig struct {
    API.Config
    tls TLSConfig
}

var conf MyConfig
// conf.tls is ambiguous
```

However, this is something that we can easily document and make sure user's are aware of this case.

### Thoughts

There may be possibilities I'm missing here, but as far as I understand Go there aren't many beyond these. That being said, I think Approach 2 is our best bet. The one issue with it doesn't seem to outweigh the benefit and is something that we could document for users to handle on their end (by simply renaming their fields), and may be rare enough that no one actually runs into it.

@hsanjuan

**Comment by hsanjuan** [comment]
@dgrisham I agree with your analysis, let's update the NewRESTAPI function to receive a configuration object.
