### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ipfs/ipfs-cluster#1442]
**Additional information:**
 - OS:  linux Fedora 35 64bits
 - IPFS Cluster version:  last master
 - Installation method: built from source
logs:
# github.com/minio/blake2b-simd
/home/go/pkg/mod/github.com/minio/blake2b-simd@v0.0.0-20160723061019-3f5f724cb5b1/compress_amd64.go:21:12: error: reference to undefined name ‘avx2’
   21 |         if avx2 {
      |            ^
/home/go/pkg/mod/github.com/minio/blake2b-simd@v0.0.0-20160723061019-3f5f724cb5b1/compress_amd64.go:23:19: error: reference to undefined name ‘avx’
   23 |         } else if avx {
      |                   ^
/home/go/pkg/mod/github.com/minio/blake2b-simd@v0.0.0-20160723061019-3f5f724cb5b1/compress_amd64.go:25:19: error: reference to undefined name ‘ssse3’
   25 |         } else if ssse3 {
      |                   ^
# gonum.org/v1/gonum/internal/asm/f64
/home/go/pkg/mod/gonum.org/v1/gonum@v0.0.0-20190926113837-94b2bbd8ac13/internal/asm/f64/abssum_amd64.s:7:10: fatal error: textflag.h: No such file or directory
    7 | #include "textflag.h"
      |          ^~~~~~~~~~~~
compilation terminated.
# github.com/lucas-clemente/quic-go/internal/qtls
/tmp/ccvVFYyH.s: Assembler messages:
/tmp/ccvVFYyH.s:5575: Error: junk `.cipherSuiteTLS13ByID' after expression
/tmp/ccvVFYyH.s:5575: Error: invalid operands (*UND* and *UND* sections) for `/'
/tmp/ccvVFYyH.s:5575: Error: invalid operands (*UND* and *UND* sections) for `/'
/tmp/ccvVFYyH.s:5575: Error: can't resolve `L0^A' {*ABS* section} - `go1' {*UND* section}
# github.com/minio/sha256-simd
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s: Assembler messages:
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:3: Error: no such instruction: `text ·sha256X16Avx512(SB),7,$0'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:4: Error: junk `(FP)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:4: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:5: Error: junk `(FP)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:5: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:6: Error: junk `(FP)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:6: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:7: Error: junk `(FP)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:7: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:8: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:9: Error: no such instruction: `long $0x92fbc1c4'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:9: Error: no such instruction: `byte $0xce'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:10: Error: junk `(FP)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:10: Error: too many memory references for `lea'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `quad $0xf162076f487ef162'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `quad $0x7ef162014f6f487e'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `quad $0x487ef16202576f48'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `quad $0x6f487ef162035f6f'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `quad $0x6f6f487ef1620467'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `quad $0x06776f487ef16205'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `long $0x487ef162'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: invalid character '$' in mnemonic
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:11: Error: no such instruction: `byte $0x07'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:12: Error: junk `(FP)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:12: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:13: Error: invalid character '$' in mnemonic
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:13: Error: no such instruction: `byte $0xc9'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:16: Error: junk `(AX)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:16: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:17: Error: no such instruction: `long $0x487cc162'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:17: Error: invalid character '$' in mnemonic
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:17: Error: no such instruction: `byte $0x09'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:22: Error: junk `(AX)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:22: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:23: Error: no such instruction: `long $0x487cc162'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:23: Error: invalid character '$' in mnemonic
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:23: Error: no such instruction: `byte $0x09'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:28: Error: junk `(AX)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:28: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:29: Error: no such instruction: `long $0x487cc162'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:29: Error: invalid character '$' in mnemonic
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:29: Error: no such instruction: `byte $0x09'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:34: Error: junk `(AX)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:34: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:35: Error: no such instruction: `long $0x487cc162'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:35: Error: invalid character '$' in mnemonic
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:35: Error: no such instruction: `byte $0x09'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:40: Error: junk `(AX)' after expression
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:40: Error: too many memory references for `movq'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:41: Error: no such instruction: `long $0x487cc162'
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:41: Error: invalid character '$' in mnemonic
/home/go/pkg/mod/github.com/minio/sha256-simd@v1.0.0/sha256blockAvx512_amd64.s:41: Error: no such instruction: `byte $0x09'

no idea why it does not compile

**Comment by hsanjuan** [comment]
What go version are you using?

**Comment by ROBERT-MCDOWELL** [comment]
go version go1.16.5 gccgo (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1) linux/amd64

**Comment by hsanjuan** [comment]
I'm afraid this has to be something specific to your system. Can you post `go env`?

It works for me both with CGO enabled or disabled, but you can always try with `export CGO_ENABLED=0` or by installing go manually per the official docs, rather than using Fedora's build.

**Comment by ROBERT-MCDOWELL** [comment]
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/libexec/gcc/x86_64-redhat-linux/11"
GOVCS=""
GOVERSION="go1.16.5 gccgo (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4210201                                                                                                                                                    215=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

**Comment by ROBERT-MCDOWELL** [comment]
same issue with export CGO_ENABLED=0
should I remove all golang traces from packages before to install from sources?

**Comment by hsanjuan** [comment]
> I remove all golang traces from packages before to install from sources?

Yes, try removing the fedora-provided packages and install the binaries per the golang website.

**Comment by ROBERT-MCDOWELL** [comment]
I tried to compile from source following the docs, git clone cd src ./all.bash
but failed too log attached
[log.txt](https://github.com/ipfs/ipfs-cluster/files/6982534/log.txt)

**Comment by hsanjuan** [comment]
download and install from here https://golang.org/dl/

**Comment by ROBERT-MCDOWELL** [comment]
install from binaries at https://golang.org/dl/ successful but tests failed

--- FAIL: TestInstallationImporter (2.13s)
    importer_test.go:40: Ints: got "func Ints(x []int)"; want "func Ints(a []int)"
FAIL
FAIL    go/internal/gccgoimporter       3.107s

--- FAIL: TestGroupCleanupUserNamespace (0.03s)
    exec_linux_test.go:327: id command output: "uid=0(root) gid=0(root) groups=0(root),655                                                                                                                                                    34(nfsnobody)", expected one of ["uid=0(root) gid=0(root) groups=0(root)" "uid=0(root) gid                                                                                                                                                    =0(root) groups=0(root),65534(nobody)" "uid=0(root) gid=0(root) groups=0(root),65534(nogro                                                                                                                                                    up)" "uid=0(root) gid=0(root) groups=0(root),65534" "uid=0(root) gid=0(root) groups=0(root                                                                                                                                                    ),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),65534(nobody),6553                                                                                                                                                    4(nobody),65534(nobody),65534(nobody),65534(nobody)" "uid=0(root) gid=0(root) groups=0(roo                                                                                                                                                    t) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023" "uid=0(root) gid=0(root)                                                                                                                                                     groups=0(root),65534(nobody) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c102                                                                                                                                                    3"]
FAIL
FAIL    syscall 4.356s

**Comment by hsanjuan** [comment]
This is unrelated to cluster.

**Comment by ROBERT-MCDOWELL** [comment]
FYI, Fedora (and certainly other OS) install by default in /etc/alternatives/ go.gcc, even if golan is not installed.
making big troubles for any go compilation. the trick is to remove any symlinks and go.gcc from this folder
and install golang package. hope it can help others.
