### ISSUE TITLE
'ipfs-cluster-ctl peers add [PeerID]' issue

### ISSUE THREAD

**Issue by gengshuo** [ipfs/ipfs-cluster#145]
Hi, 
I used Vagrant and VirtualBox to run two IPFS and IPFS cluster node.
The 'ipfs daemon' & 'ipfs-cluster-service' is running on them.
But I got "Code: 500
  Message: dial attempt failed: context deadline exceeded" ERROR while I use 'ipfs-cluster-ctl peers add [PeerID]'.
Did I connect the two nodes in the right way?
Or other problem may them have?

Thank you for your reply.

**Comment by hsanjuan** [comment]
hope you found a solution for your problem :)
