### ISSUE TITLE
Private ipfs-cluster with public ipfs gateway bridge?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ipfs/ipfs-cluster#1453]
I read the docs about this subject but didn' find any examples.
I wonder if it's possible to run a private ipfs-cluster in CRDT where all nodes trust each others for add/modify/delete pins
and a bridge allow the whole cluster to transmit all updated pins to the public ipfs?

**Comment by hsanjuan** [comment]
Hello, please use [discourse for support](https://discuss.ipfs.io/).

To answer your question, the IPFS-Cluster "swarm" is different from the IPFS swarm. You can configure the IPFS daemons on the public network and on a private networks, and this is independent from the cluster-peers and how they trust each others.

**Comment by ROBERT-MCDOWELL** [comment]
thanks hsanjuan!
