### ISSUE TITLE
TestAdder_ContextCancelled seems to be flaky

### ISSUE THREAD

**Issue by Luflosi** [ipfs/ipfs-cluster#1461]
**Additional information:**
 - OS: Linux (NixOS)
 - IPFS Cluster version: 0.14.1
 - Installation method: built from source

**Describe the bug:**

I tried updating the version of ipfs-cluster in Nixpkgs from 0.14.0 to 0.14.1: https://github.com/NixOS/nixpkgs/pull/134342. A bot built the new version and ran the test suite but the test TestAdder_ContextCancelled failed. The logs are in https://gist.github.com/r-rmcgibbo/4120129668b85b2bc51dc6f70c64b651. The bot built ipfs-cluster twice, for two different architectures and it failed once. I also can't reproduce the failure on any of my machines, so the failure seems to be non-deterministic. I noticed, that it failed before in https://github.com/ipfs/ipfs-cluster/pull/613#issue-235170657.

**Comment by hsanjuan** [comment]
Hi @Luflosi , can you try with #1462 ?

**Comment by Luflosi** [comment]
Given, that I have never been able to reproduce the failure, I don't see how I could really test this. When I apply the PR as a patch and run the test suite, it works on my Mac and Linux machines.
