### ISSUE TITLE
[cluster init] cannot enable metrics exposure through env vars

### ISSUE THREAD

**Issue by fredleger** [ipfs/ipfs-cluster#1477]
**Additional information:**
 - OS: macos
 - IPFS Cluster version: latest
 - Installation method: docker

**Describe the bug:**

According to these docs https://cluster.ipfs.io/documentation/reference/configuration/ and the following part:

> In general the environment variable takes the form CLUSTER_<COMPONENTNAME>_KEYWITHOUTUNDERSCORES=value. Environment variables will be applied to the resultant configuration file when generating it with ipfs-cluster-service init.

I would expect that setting CLUSTER_OBSERVATIONS_METRICS_ENABLESTATS will generate the following in `service.json`:

```json
"observations": {
    "metrics": {
      "enable_stats": true
  }
}
```

But this is not the case (see screenshot bellow)

<img width="830" alt="image" src="https://user-images.githubusercontent.com/2778741/136009152-daa25819-e518-43b4-a230-e5681d4b9d85.png">

From my understanding such an automatic configuration is only available for "cluster" part of the json config is it right ?
If yes is there a way to configure that dynamically ?

**Comment by hsanjuan** [comment]
The docs you found are what there is:

> In general the environment variable takes the form CLUSTER_\<COMPONENTNAME\>_KEYWITHOUTUNDERSCORES=value. Environment variables will be applied to the resultant configuration file when generating it with ipfs-cluster-service init.

The component name is "metrics" (the component family is "observations"). Would you like to send a PR to the docs (github.com/ipfs/ipfs-cluster-website) with improvements?
