### ISSUE TITLE
Add option for ipfs-cluster to peer IPFS together

### ISSUE THREAD

**Issue by Jorropo** [ipfs/ipfs-cluster#1480]
I have a cluster where I peer all IPFS nodes together as this greatly increase propagation speed.

However managing the peering field in my configs gets old fast as for each node I add I need to also update all other nodes.

I would like ipfs-cluster to have an option where it would automatically manage the peering and join all my nodes together.

**Comment by hsanjuan** [comment]
When a cluster peer starts, after `connect_swarms_delay` it will trigger `swarm connect` from its IPFS node to the rest of IPFS nodes in the cluster that it can see. These connections are protected by default I think.
