### ISSUE TITLE
Ways of working

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#152]
This issue is to discuss what's the best way of working and coordinating work around ipfs-cluster.

Starting-proposal:

* We use the IRC #ipfs-cluster channel for chit-chat and async random-communication.
* We hold a standup meeting on Zoom by default once a week. It should aim to last 15 minutes. Day and time to be decided. Everyone's welcome to join and ask questions. We keep notes https://cryptpad.fr/code/#/1/edit/5AvAVUQ3cNKI-4nHbi8pRA/z25D-PGnShT+plojfIUDslQ7/ and from time to time move them to the repo.
* We make it explicit to publish cluster versions at least once a month (including release to dist.ipfs.io).

@ZenGround0 @dgrisham would be great to have your input. I think we don't need sync-time 3 days a week anymore.

**Comment by ZenGround0** [comment]
Cool!  I agree that we can scale back sync ups a little bit.  As I am starting with a clean calendar anytime works for me apart from noon (EDT) on Thursdays, so I'll let the more constrained @hsanjuan and @dgrisham decide on the final time.  Does the current 1:30 EDT time slot still work for everyone?  I can definitely do 4 hours earlier or later too.

Let's decide our current release date target for September/October ASAP.  From dist.ipfs.io the latest release was July 29th, so perhaps we could release before team-week with what we have right now and then use that as our monthly benchmark?

Note to self, the docker cluster image as well as the docker testing image should also be published to dockerhub alongside releases to dist.ipfs.io (if this isn't already automated).

**Comment by hsanjuan** [comment]
Let's wait a bit until mid-october for the next release, as there are a couple of things in-flight.

**Comment by dgrisham** [comment]
Agreed with your points in general. I like the idea of moving primarily to IRC, and once-a-week sync is good since no one is brand new atm.

As far as sync time, I'm happy with the current time but can move if you guys want. Since I'm moving off of Cluster fairly soon I think your guys' preferences should take priority.

**Comment by ZenGround0** [comment]
It has been decided that the ipfs-cluster weekly community call will occur Mondays 5 PM. UTC following ipfs community calls.  Video conference link to follow.

**Comment by hsanjuan** [comment]
I have created milestones for the main priorities (key results) in the next months (see #163).

I would like that:
  * All work in cluster has an issue
  * Every issue belongs to a milestone (there are sort of catch-all milestones for bugs, feedback and low hanging fruit)
  * All actionable issues have priorities assigned and prio:high gets worked on first

There is a lot of issue-writing left to fill-in many of the milestones. This is something we'll have to work on in the next few days/weeks.

Given a milestone, we should be able to quickly see:

* What work are related to it (by issues belonging to it)
* How much work was done (by closed issues)
* Have an idea of completion of the milestone (for some cases)

We can use the waffle board to get an overview of what's being worked on and what things are "ready" to pick next.

The system is a compromise between strictness and easyness. Should be relatively easy to maintain and produce little managing overhead at the expense of not being able to express much complexity (things spawning multiple KRs, sorted priority etc.).

**Comment by hsanjuan** [comment]
Ok we're on track and doing well. Closing this...
