### ISSUE TITLE
Study how glibc ipfs docker image affects cluster docker images

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#154]
See: https://github.com/ipfs/go-ipfs/pull/4219

**Comment by lgierth** [comment]
Is ipfs-cluster something we should have in mind when making changes to go-ipfs's dockerfile? We try to keep it stable of course.

**Comment by lgierth** [comment]
Okay I see, you build the ipfs-cluster image from the ipfs/go-ipfs:release image -- after ipfs/go-ipfs#4219 you just get a bare busybox image containing the go-ipfs binary, no package manager whatsoever.

**Comment by lgierth** [comment]
Maybe you can do a multistage dockerfile too -- first stage builds the ipfs-cluster binaries, second stage is built FROM ipfs/go-ipfs:release and COPYs the ipfs-cluster binaries from the first stage.

**Comment by hsanjuan** [comment]
> We try to keep it stable of course.

yes yes, it has only broken for us in like every PR touching the dockerfile :)

> Maybe you can do a multistage dockerfile too -- first stage builds the ipfs-cluster binaries, second stage is built FROM ipfs/go-ipfs:release and COPYs the ipfs-cluster binaries from the first stage.

There are permissions and ipfs-setup in the container which seems important and that's why we re-used . However I'm in the mind of simply not including ipfs in the ipfs-cluster container. Probably keep one that includes everything just for testing. But I'm not sure, I have to think a bit more about it.
