### ISSUE TITLE
Expose PeerId of IPFS node pinning a given CID

### ISSUE THREAD

**Issue by vasco-santos** [ipfs/ipfs-cluster#1554]
**Describe the feature you are proposing**

Calling `HTTP GET /pins/{cid}` will give us a Map keyed by PeerId of the cluster and its metadata as value. However, if someone wants to parse this response and establish a direct connection with the Peer pinning content it is not possible unless we do a follow up request to the Cluster ( `HTTP GET /peers` ) and get the PeerId from there.

I think it would be important information to be provided in the `/pins/{cid}` route. Probably a property within the response object as `ipfsPeerId`. This would easily unblock issues like this: https://github.com/web3-storage/web3.storage/issues/414

The alternative solution for us is to perform a follow up request per upload, which is not great.

**Additional context**

N/A

cc @hsanjuan

**Comment by hsanjuan** [comment]
Hm, ok.
