### ISSUE TITLE
`ipfs-cluster-ctl` should not return error code 0 in case of incorrect usage

### ISSUE THREAD

**Issue by gdethier** [ipfs/ipfs-cluster#1633]
**Additional information:**
 - OS: Ubuntu 21.10
 - IPFS Cluster version: 0.14.5
 - Installation method: dist.ipfs.io

**Describe the bug:**
When calling `ipfs-cluster-ctl` with invalid arguments (e.g. ipfs-cluster-ctl add some-file.txt -rmin NaN), an error message is shown (e.g. `Incorrect Usage: invalid value "NaN" for flag -rmin: parse error`) followed by the program's usage string. In that case, the error code is `0` and everything is output to stdout.

I would expect a return code different from `0`, which is particularly important if you use that command in a script.

I see that error codes `1` and `2` are already in use but for another purpose (https://github.com/ipfs/ipfs-cluster/issues/178), maybe add an error code `3` for input related issues?

**Comment by hsanjuan** [comment]
Thank you, indeed per the docs it should return with 1 (argument error).
