### ISSUE TITLE
Protocol Not Supported when accessing GKE-based Cluster Instance

### ISSUE THREAD

**Issue by piboistudios** [ipfs/ipfs-cluster#1638]
**Additional information:**
 - OS:  local: Pop!_OS 21.10   gke: amd64 Docker image
 
 - IPFS Cluster version: [e.g. 0.10.1, master] v1.0.0-rc4 (and v1.0.0; tried both with the same result; and yes the client and cluster versions were aligned)
 - Installation method: [e.g. built from source, dist.ipfs.io, docker] I installed `ipfs-cluster-ctl` locally from the IPFS cluster official distro listing (dist.ipfs.io) and the GKE cluster is running v1.0.0-rc4 pulled from Docker Hub

**Describe the bug:**

I've encountered the exact same problems described in #902 

Namely, I get this error when trying to get the version or id of my cluster as a test:
```
$ ipfs-cluster-ctl --debug --host "/ip4/{{pub_ip}}/tcp/9096/ipfs/{{peer_id}}" --secret "{{hex_cluster_secret}}" version
```
I've also tried this using `p2p` (both locally dialing in and remotely listening; I know they're both equal but I just figured its worth pointing out)

Output:
```
2022-04-24T08:53:24.344-0500    DEBUG   cluster-ctl     ipfs-cluster-ctl/main.go:153    debug level enabled
2022-04-24T08:53:24.445-0500    DEBUG   apiclient       client/lbclient.go:81   retrying 1 times
2022-04-24T08:53:24.445-0500    DEBUG   apiclient       client/request.go:64    GET: libp2p://16Uiu2HAmDEjKjxxDiv8ETmJmF5Q31hz7YH63qY4RgwCFUxq4zNk1/version
2022-04-24T08:53:24.661-0500    ERROR   apiclient       client/lbclient.go:104  reached maximum number of retries without success, retries: 1
An error occurred:
  Code: 0
  Message: Get "libp2p://16Uiu2HAmDEjKjxxDiv8ETmJmF5Q31hz7YH63qY4RgwCFUxq4zNk1/version": protocol not supported
  ```

**Comment by hsanjuan** [comment]
See (https://cluster.ipfs.io/documentation/guides/security/):

```
Note that when no additional libp2p host is configured and running in Raft mode, the Cluster’s peer libp2p host (which listens on 0.0.0.0) is re-used to provide the libp2p API endpoint. As explained, this endpoint is only protected by the cluster secret. When running in CRDT mode, the libp2p endpoint is disabled, as the cluster secret may be shared and would otherwise expose an open endpoint to the world. In order to run a lib2p API endpoint when using CRDT mode, configure an additional, separate libp2p host in the restapi configuration.
```

If you are not using Raft, then you don't have access to http API over the 9096 host, and need to setup a separate one.

**Comment by piboistudios** [comment]
@hsanjuan Ahhh, thank you! I remember seeing that a while back and forgot about that.

I'll give this a shot ASAP and close this when I can confirm this was the issue

**Comment by hsanjuan** [comment]
@piboistudios any news?

**Comment by piboistudios** [comment]
I honestly probably will not get around to this for some time since I can
just get a terminal into my Kubernetes Pod.

Sorry, this can be closed though as what you've mentioned is likely the
issue
