### ISSUE TITLE
Connecting peers without a secret times out and confuses

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#167]
Currently RPCs among peers that do not share a cluster secret time out and do not throw an error that is easy to trace back to the root cause.

**Comment by hsanjuan** [comment]
It might be needed to go down deep in libp2p to fix this correctly.

@Kubuxu do you have any pointers as what's the easiest way to detect mismatch of PNet keys or where this should happen?

**Comment by VictorBjelkholm** [comment]
A quick fix could be that when a timeout error happen, print a short help with possible faults.

```
Could not connect to host /ip4/192.168.1.2/tcp/9096/ipfs/QmPSoSaPXpyunaBwHs1rZBKYSqRV4bLRk32VGYLuvdrypL

Make sure: 
A) You can actually reach the host, try `ping 192.168.1.2 `
B) You share the same secret key, as otherwise nodes won't be able to connect
```

Once we have a proper way of detecting mismatch, you can still have the old error but add a new one when keys mismatch.

**Comment by Kubuxu** [comment]
@hsanjuan there is no way to detect it nicely. go-ipfs prints a warning if it has no peers for X seconds and is using private networks.
