### ISSUE TITLE
combine ipfs-cluster-service and ipfs-cluster-ctl into one binary

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/ipfs-cluster#172]
Currently, the two CLIs are separated, but I'm unsure of why. Would be a much better experience if the `ipfs-cluster-service` was simply a sub-command of a `ipfs-cluster` binary, similar to how `go-ipfs` and in general Hashicorp tools work. Makes it very easy to get started and with environment variables, you can control which daemon to connect to.

**Comment by ZenGround0** [comment]
Similar issue #153

**Comment by VictorBjelkholm** [comment]
Ay, searched but didn't find anything already open...
