### ISSUE TITLE
Cannot see help of `ipfs-cluster-service` without `init` first

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/ipfs-cluster#173]
Had just installed `ipfs-cluster-service` and wanted to see the help so I run just `ipfs-cluster-service` but that started the service. Instead, I did `ipfs-cluster-service --help` but that fails because it's trying to load the `service.json` which doesn't exists yet (and should not be needed for seeing the help).

```
root@cluster-0:~# ./ipfs-cluster-service/ipfs-cluster-service 
11:42:57.572 ERROR    cluster: error reading the configuration file: open /root/.ipfs-cluster/service.json: no such file or directory config.go:368
error loading configuration: open /root/.ipfs-cluster/service.json: no such file or directory
```

**Comment by hsanjuan** [comment]
`ipfs-cluster-service --help` works for me without any config file. I'm not even sure how this happened in the first place.

**Comment by hsanjuan** [comment]
`ipfs-cluster-service --help` shows the help for me in the latest version, so I'm closing this. Re-open if somehow it still happens for you.
