### ISSUE TITLE
Harden sharness/lib/test-lib.sh

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#181]
Rework the shell scripts in this file to have more meaninful errors, and better resiliance when a previous sharness test has failed to run and leaves the docker container running.

Also, configuration folder should probably make sure there is no data subfolder when initializing.

**Comment by ZenGround0** [comment]
Note: looking at sharness source the `cleanup` function does not run in the case of a failure.  This appears to be behind a lot of the inter test failure issues as the expected tear down of cluster and ipfs does not happen.
