### ISSUE TITLE
Solving inter-node connectivity in kubernetes-ipfs

### ISSUE THREAD

**Issue by FrankPetrilli** [ipfs/ipfs-cluster#189]
For pods running on nodes connected from behind NAT, pod to pod communication inter-node does not pass traffic. I suspect a problem with sending VXLAN encapsulated traffic over ZT, and will be looking into this

**Comment by FrankPetrilli** [comment]
Modifying a line in `kube-flannel.yml` seems to have solved this problem after *much* trial and error:

        `command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--iface=zt0" ]`

**Comment by hsanjuan** [comment]
Wanna put these configs in a repo or somewhere?

**Comment by FrankPetrilli** [comment]
This is a change to `https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml`. We want to keep up-to-date with the latest version as we upgrade the cluster, but we'll need to make that change on each upgrade cycle. 

I'll put this in a branch in kubernetes-ipfs.

**Comment by FrankPetrilli** [comment]
This remains in a branch as a known modification to the flannel deployment YML file. As this has been resolved for the production cluster, I'm closing this issue for now.
