### ISSUE TITLE
How to listen on a WebSocket or WebTransport or WebRTC address, so that I can dial to the cluster from helia browser node

### ISSUE THREAD

**Issue by logesh2496** [ipfs/ipfs-cluster#1931]
I'm unable to connect to the IPFS cluster from browser helia node as I can only see tcp link when I start the ipfs cluster.

I aim to connect my browser helia(js-ipfs) node to the ipfs cluster. So need on of the WebSocket or WebTransport or WebRTC address to do that. 

Thanks

**Comment by hsanjuan** [comment]
I haven' t tried, but you should be able to add websocket, webtransport or whatever listen_multiaddresses in the configuration (only tcp and quic enabled by default):

```
    "listen_multiaddress": [
      "/ip4/0.0.0.0/tcp/9096",
      "/ip4/0.0.0.0/udp/9096/quic"
    ],
```

Let me know if that works.

**Comment by Skylerspencer** [comment]
Ok

**Comment by hsanjuan** [comment]
Add multiaddresses for the protocols you want to listen on, i.e websockets.

**Comment by hsanjuan** [comment]
i.e.

```
 "listen_multiaddress": [
      "/ip4/0.0.0.0/tcp/9096/ws",
    ],
```
