### ISSUE TITLE
Update ipfs-cluster to make use of hRaft LeaderObservation type 

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#211]
Track the reversion of commit b7e8a11 in hashicorp raft referenced here https://github.com/hashicorp/raft/issues/254 and update consensus/raft/raft.go to make use of observers in the function WaitForLeader.

**Comment by lanzafame** [comment]
If I understand correctly, this is no longer blocked by hashicorp/raft#254 as of hashicorp/raft#259.

@hsanjuan is this as simple as uncommenting the code in `raftWrapper.WaitForLeader`?

**Comment by hsanjuan** [comment]
It's blocked because it requires a prior update of the gxed raft, which involves updating some deps below (since we're at it). And `raft` hasn't had an official `tag` since 1.0.0, that includes this change. Since generally things work on this front, I'm not in a hurry to do this.

**Comment by hsanjuan** [comment]
wop, a new Raft release is out and this is not blocked anymore after #769

**Comment by kishansagathiya** [comment]
Using LeaderObservation does not achieve any extra good results here, just creates problems.

Currently we waitForLeader when a new peer gets added. If you use LeaderObservation type, you might get stuck. Leader could get elected before even you register it in WaitForLeader, in which case you will never observe it. So, if using `LeaderObservation` type, it has to go in a goroutine like `observePeers`

But even then, it is likely that leader will remain same after a new peer is added, in which case you will never observe a new leader and are stuck(actually context will timeout) at `WaitForLeader`.

So, it appears to me that if we were to use it, we require some design changes that code.

**Comment by hsanjuan** [comment]
This is just removing the 32-bit safeguard and uncommenting a few lines

**Comment by hsanjuan** [comment]
Keep the `ticker`
