### ISSUE TITLE
Pin subtree larger than any one ipfs node

### ISSUE THREAD

**Issue by ian-gtv** [ipfs/ipfs-cluster#212]
Is it in scope for ipfs-cluster to be able to handle pinning a single large merkletree which is too big to fit on any one node - so it would have to be a collaborative pin of different parts on different nodes?

**Comment by hsanjuan** [comment]
Yes, this is in scope mid-to-long-term. It has to do with importers and IPLD selectors. The short-term work about this (this quarter) involves studying all the pieces involved coming up with a strategy/approach to the problem.

**Comment by ZenGround0** [comment]
Anyone interested in following along with this can refer to PR #268

**Comment by hsanjuan** [comment]
I will close this as part of the issue cleanup. When we have IPLD selectors and IPFS support for sharding we will re-open or re-create an issue for this.
