### ISSUE TITLE
File added to a private cluster peer is accessible from public peers

### ISSUE THREAD

**Issue by cb-tr** [ipfs/ipfs-cluster#225]
I am using ipfs-cluster to have a private network of peers.
- To make sure the uploaded file is not accessible to any public peer which is not the part of cluster.
- To replicate the file to x number of peers to ensure the availability of file. 

**Steps performed:** (After updating the `.ipfs/config`'s _**bootstrap**_ with the multi-addresses of my peers)
1. Ran `ipfs-daemon` to start the server. 
2. Using `ipfs-cluster-service` created 3 nodes having same secret key and bootstrapped them to the cluster.
3. Then using `ipfs` added a file.

**Concerns:**
- The hash I received after adding the file is also accessible from https://ipfs.io/ipfs/<hash>
- Whenever a peer goes down the cluster misbehaves and sometimes the peers stops as well.

Please help me to resolve the concerns I mentioned above.
Also, can you suggest me a way to dynamically update the `replication_factor` to all the peers in runtime.

**Comment by hsanjuan** [comment]
@cb-tr, ipfs does peer discovery by other means than just the bootstrap nodes in the configurations (mDns). If just one reachable node is misconfigured, or has been contacted by some ipfs node outside your setup, it will leak. You need to use Private Networks (https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks) to ensure that doesn't happen.

> Then using ipfs added a file.
You need to tell cluster to pin that file too

> Whenever a peer goes down the cluster misbehaves and sometimes the peers stops as well.

How many peers do you have? Can you provide more details, logs etc? Do you mean the ipfs peer or the cluster peer stops?

**Comment by cb-tr** [comment]
@hsanjuan Thanks a lot for a quick response!

I followed the above mentioned [doc](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks) for setting up the private network and it worked perfectly.


> How many peers do you have? Can you provide more details, logs etc? Do you mean the ipfs peer or the cluster peer stops?

I found one similar [issue](https://github.com/ipfs/ipfs-cluster/issues/160) where I can follow up on that. 

So closing this one.
Cheers!
