### ISSUE TITLE
Logging facilities listed twice for twice the confusion

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#240]
It took me too long to figure out why I was not seeing log output after adding a new facility in logging.go.  Turns out there is another list of facilities in ipfs-cluster-service/main.go that only applies in the case the debug flag is not passed in.  The two lists should be consolidated so that facilities need to be added only once.  This should be a pretty quick fix.

**Comment by hsanjuan** [comment]
actually one is internal and used for controlling the output during testing and the other one is more user-facing. I would have to think if consolidating both has a downside in this regard.
