### ISSUE TITLE
Work on kubernetes-ipfs documentation, modularization, issues and improvements

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#245]
- Create a guide laying out all the DSL features with examples
- Rework the READMEs to be clear and concise about how to run the tests
- Modularize the current codebase so it's easier to maintain, and include any improvements along the way

**Comment by FrankPetrilli** [comment]
DSL features are lightly documented in https://github.com/ipfs/kubernetes-ipfs/blob/master/readme.md, and examples are provided via the real-world tests.

Regarding documentation on running the tests, is this pointed towards public users who are running their own Minikube/Kubernetes, or internal users who want to run tests against the production cluster?

Modularization will come with automation discussed in #244.

**Comment by hsanjuan** [comment]
The readme does not start to cover the complexity of the current dsl not is really useful when writing tests for something from scratch or trying to understand what's there. For example, a proper guide needs to describe the langauge in depth,  like these notes https://github.com/ipfs/kubernetes-ipfs/tree/master/docs and include easy examples.

The documentation is pointed towards public running in both minikube or a real arbitrary cluster, or our cluster.

**Comment by FrankPetrilli** [comment]
As with the priority:medium tasks, this has fallen to a later time so that higher priority tasks can be given the time to be completed. This will be my primary task as we move into Q1 unless preempted.
