### ISSUE TITLE
Make prometheus/graphana metric gathering work with ipfs-cluster test-suite

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#247]
This probably need enabling metric export in cluster

**Comment by FrankPetrilli** [comment]
As discussed in the ipfs-cluster standups, the priority:high items took priority over these issues for completion as of end of Q4. As we move into Q1 2018, we can consider these again as we originally discussed in the scope of work document.

**Comment by ZenGround0** [comment]
Correct me if I'm wrong but this seems blocked on metrics and k8s-ipfs test triggering.
