### ISSUE TITLE
Design and collect interesting metrics

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#248]
Related to #247 

see what metrics are interesting to collect and see what changes we need to do to expose them.

**Comment by hsanjuan** [comment]
We should expose a prometheus endpoint like ipfs does and offer the default go metrics with it.

**Comment by FrankPetrilli** [comment]
The below is noted with the following caveat:

Prometheus and grafana are running within the cluster, I just need an endpoint added into ipfs-cluster to provide data to prometheus. From a Kubernetes perspective, this is complete however.

As discussed in the ipfs-cluster standups, the priority:high items took priority over these issues for completion as of end of Q4. As we move into Q1 2018, we can consider these again as we originally discussed in the scope of work document.
