### ISSUE TITLE
Deadlock on peer removal raftconfig.shutdownOnRemove = true

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#251]
Issue to track deadlock found when changing default to shutting down the raft component when its peer is removed from consensus.  

Commonly fails on `TestClustersPeerRemoveSelf`, `TestClustersPeerRemoveLeader`, or `TestClustersPeerRemove`.  The failure occurs when the nth peer (I've seen 1 and 4) is up for removal.  The nth peer checks for removal in `watchPeers` by calling consensus.Peers().  This calls raft.Peers() which blocks on a `configurationFuture.Error()` call indefinitely (verified from stack trace).  The other peers' calls to `watchPeers` do not block.  Other calls to the future `Error()` function are seen blocking in the stack trace (perhaps from other goroutines of the nth peer or maybe in other goroutines of remaining peers).

This failure occurs both with and without raft calling `Snapshot()` in `Shutdown()`.

**Comment by hsanjuan** [comment]
Note: as of now, raftconfig.shutdownOnRemove = false and we don't have a compelling reason to change it (this problem might be a compelling reason to leave it like that). Will update if that changes.

**Comment by hsanjuan** [comment]
Closing this. I think it was fixed (I think we improved test setup and changed some things on these).
