### ISSUE TITLE
Code quality: address codeclimate issues

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#273]
Codeclimate has surfaced a bunch of issues, like files too long, functions too complex or code duplicates. Some of them are valid, some of them are not really valid. The codeclimate interface allows to confirm/invalidate some of the stuff.

After that we can use this issue to reference all PRs which address codeclimate things.

**Comment by kishansagathiya** [comment]
This is a little big refactor than I thought. Coding would be pretty straight forward once we agree on how to refactor this.
Let me know if this looks like a good plan to you

1. Move setting up the app object to a different file, say app.go
2. Move all api.Flags to a separate function and separate file say `flags() []cli.Flag`
3. Create a `commands` package. commands.go will contain `Commands() []cli.Command`. Each command would be in a separate file with a function like `Add() cli.Command` for add command.

**Comment by kishansagathiya** [comment]
^ @lanzafame

**Comment by kishansagathiya** [comment]
I think we can just close this or at least remove high priority from this.
