### ISSUE TITLE
Users should be able to lend their disk space.

### ISSUE THREAD

**Issue by dimitarvp** [ipfs/ipfs-cluster#28]
One way I'd help with IPFS' adoption would be to lend 100-500GB of my spare hard disk space. I'd like to simply be able to start up an IPFS software piece and instruct it to be in "lending mode" -- I don't care what gets hosted on my machine if it helps the network, to put it bluntly.

EDIT: I can't see a way how to apply the `user-story` label here.

**Comment by hsanjuan** [comment]
Related to #7

**Comment by 20zinnm** [comment]
@dimitarvp I take it limiting the allocation of disk space is a component of this? Thus, #41 is related.

**Comment by Kubuxu** [comment]
Problem is that design of consensus protocols for trusted cluster members that are not evil is much easier from design of cluster where members can (and will lie and so on). It is possible but will require quite a lot of thought.

I hope this short explanation will bring some perspective. It is possible to do hybrid design, where content is distributed among trusted members and then other can pick up some content that needs additional support and help distributing it.

**Comment by NatoBoram** [comment]
One way of doing it would be to have [read permission](https://github.com/ipfs/ipfs-cluster/issues/786) on a [logical cluster](https://github.com/ipfs/ipfs-cluster/issues/785).

**Comment by hsanjuan** [comment]
The `--consensus crdt` mode and the rpc authorization now allows users to effectively lend their disk space. so I'm closing this.

**Comment by dimitarvp** [comment]
Is there a high-level overview of the CRDT consensus feature?

**Comment by lanzafame** [comment]
@dimitarvp yes, but as it stands those docs have not been released just yet. The docs will land at the same time that CRDTs feature is officially released, currently it is only in a release-candidate.
