### ISSUE TITLE
Can ipfs-cluster sync frequently changing files across multiple nodes?

### ISSUE THREAD

**Issue by ksanderer** [ipfs/ipfs-cluster#281]
I'm looking for a solution to sync frequently changing files (create+append) across multiple nodes. 

Files contain finance trade history data (timestamp, price, size) with partitioning by exchange, symbols, and dates. For example `/storage/poloniex/ETH/BTC/2018/01/01` (maybe less granular but that doesn't matter on the current topic).

I have few questions corresponding to ipfs-cluster usage:

1. Each cluster node running data collection process that can retrieve a new batch of data and write to the appropriate file. So we need then to sync this data with other clusters. Does each cluster node have rights to initiate file change and sync process?

2. Is it possible to grant read-only access to the files for third parties? Is it possible to limit file access with API keys or something similar?

3. Does file syncing process transfer only file diffs (`changes`) or the whole file?

4. What if two clusters will update one file and then try to sync it? Do we need to lock file after the update until syncing with each node is done?

**Comment by hsanjuan** [comment]
Hi,

ipfs-cluster works on top ipfs (by coordinating ipfs nodes), so any file syncing is constrained by how ipfs works.

> Each cluster node running data collection process that can retrieve a new batch of data and write to the appropriate file. So we need then to sync this data with other clusters. Does each cluster node have rights to initiate file change and sync process?

Each cluster node can tell other cluster nodes to tell their ipfs daemons to pin content, which will be then obtained from whoever provides it in the ipfs network and stored.

> Is it possible to grant read-only access to the files for third parties? Is it possible to limit file access with API keys or something similar?

the ipfs daemon offers a read-only interface (gateway) to ipfs content

> Does file syncing process transfer only file diffs (changes) or the whole file?

If new content is added, there will be a new hash for that file (idenifier), and depending how it is chunked, all or some of its parts will be new. Non-changed blocks of files will not need to be retrieved again by ipfs daemons holding them, but new blocks will.

> What if two clusters will update one file and then try to sync it? Do we need to lock file after the update until syncing with each node is done?

ipfs is content addressed. Content which is written is never changed. You cannot change a file, you can only create new files (which may be based on the previous, or not). I suggest you become familiar with how ipfs works as it probably clears up much of your confusion. In short, you don't need to lock anything.

**Comment by ksanderer** [comment]
Thanks for pointing out!

**Comment by ZenGround0** [comment]
I will add that ipfs has a collection of files subcommands (run `ipfs files` for more info) providing a mutable file system interface built on top of the content addressed, immutable merkle DAG that ipfs stores.  ipfs-cluster could be extended to aid in managing shared mfs directories across nodes to take care of the problems you mention (provide more precise access control, use consensus to organize syncing, intelligently manage diffs), but as of right now we haven't given this any thought.

You could use ipfs-cluster's ipfs proxy to instruct the ipfs deamon to run files commands and then

**Comment by hsanjuan** [comment]
Related to #166 (dup?)

**Comment by ZenGround0** [comment]
Good find, I missed that earlier.  Yeah this #166 and #3 have a lot of overlap.
