### ISSUE TITLE
How to replicate actual data?

### ISSUE THREAD

**Issue by mikhail-manuilov** [ipfs/ipfs-cluster#289]
It's very unclear in documentation that `ipfs-cluster` only replicating ipfs hashes (CIDs) and no data, cause it only adds data to connected `ipfs` daemon and not replicates any data at all.
My added data to my `ipfs-cluster` is lost because of false belief due misunderstanding that it's created for content replication.

Is it possible to automatically replicate data across multiple `ipfs` daemons?

**Comment by hsanjuan** [comment]
ipfs-cluster tells ipfs daemons to recursively pin CIDs. CIDs are roots of trees which include the data at the leaves. When you pin a CID in cluster, the associated ipfs daemons replicate the tree (the data) according to the replication factor.

Cluster IS created for content replication. It helps ipfs daemons replicate merkle trees. The documentation is correct on that regard.

**Comment by ZenGround0** [comment]
@mikhail-manuilov adding on to @hsanjuan's response it is unexpected that your data would not be replicated across your cluster.  By default cluster replicates all pins across all nodes.  For example say I set up a cluster of 3 nodes and on the first ipfs node add the string "test" to ipfs and then pin the hash to the cluster (Qme...HVH) with `ipfs-cluster-ctl pin add Qme...HVH`.  After doing this I can check that cluster has allocated all three ipfs nodes to pin this hash by running `ipfs-cluster-ctl status Qme...HVH`.  I get as output:
```
Qme...HVH :
    > Peer <pid1> : PINNED | <TS>
    > Peer <pid2> : PINNED | <TS>
    > Peer <pid3> : PINNED | <TS>
```
which tells me cluster has assigned all ipfs nodes to pin this data.  Furthermore I can check that ipfs is actually doing what it is told.  On every machine I run `ipfs pin ls` and I see `Qme...HVH recursive` as part of the output list.

Are you seeing anything different when running the above checks?  Are you using the default configuration?

**Comment by hsanjuan** [comment]
@mikhail-manuilov please re-open if anything's not clear

**Comment by meteorplus** [comment]
So in other words we can remove the file after it's pinned? Because it is getting replicated on other nodes?

**Comment by hsanjuan** [comment]
@meteorplus you can unpin a file from cluster, which will unpin from ipfs. The rest is a question about removing content from ipfs. Here's a thread pointing to other thread where this has been explained: https://discuss.ipfs.io/t/how-to-delete-the-files-in-ipfs/2972/2

**Comment by meteorplus** [comment]
@hsanjuan I didn't mean remove it from the network I meant removing the file locally and it will still be available with the replication!

**Comment by hsanjuan** [comment]
you `pin` a CID. That implies that the file referenced by that CID is already in the network.

If you `add` a local file to cluster,  then you can remove it as it is stored in the ipfs-datastores.

**Comment by meteorplus** [comment]
@hsanjuan so if ipfs add file -pin then after a while like a day or so, then just rm it from the local disk it can be loaded from other nodes because it was replicated ?

**Comment by hsanjuan** [comment]
because it was added, meaning it was chunked and stored in `.ipfs/blocks`. Unless you are using ipfs `filestore` feature.
