### ISSUE TITLE
State migration problems

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#297]
This issue is to document issues when performing state ugprades.

After deploying a new version of cluster in my test setup, it has correctly shown the error saying that the state needs an ugprade.

I have done `ipfs-cluster-state upgrade` correctly in all peers.

After starting the peers, then the following error has started to appear repeteadly:

```
14:20:54.765 ERROR libp2p-raf: error decoding snapshot: reflect: reflect.Value.SetString using unaddressable value fsm.go:126
14:20:54.765 ERROR       raft: Failed to restore snapshot: failed to restore snapshot 1000-442-1516371654704: reflect: reflect.Value.SetString using unaddressable value logging.go:86
```

I have the proceeded to stop the peers and run `state export` followed by `state import` in one node and `state clean` in every other node. This has resulted in a message about:

```
14:23:32.612 ERROR  consensus: Raft peers do not match cluster peers from the configuration. raft.go:159
14:23:32.612 ERROR  consensus: This likely indicates that this peer has left the cluster and/or raft.go:160
14:23:32.612 ERROR  consensus: has a dirty state. Clean the raft state for this peer raft.go:161
14:23:32.612 ERROR  consensus: (/home/hector/.ipfs-cluster/ipfs-cluster-data) raft.go:162
14:23:32.612 ERROR  consensus: bootstrap it to a working cluster. raft.go:163
```

(I don't know if it's intended that the peerset is reduced).

After that I have removed the peers from the configuration on that node and started it. Then pointed every other node to it (which had clean states) and bootstrapped them.

This has started the cluster, but now it seems only one node has a state, the others have not received the full state in the original node and thus are not tracking the pins (`ipfs-cluster-ctl status` shows only 1 node in the list for every pin and `ipfs-cluster-ctl pin ls` is empty in the nodes that had a clean state).

The snapshot metadata in peer with the imported state shows that the index is 1, which would be the same for a clean peer, so it may be that raft does not sent the snapshot to other peers because they think they are up to date (?)

**Comment by hsanjuan** [comment]
manually importing the exported state in every node has allowed me to recover the cluster, but yeah, it should not be like this.

**Comment by ZenGround0** [comment]
Update: @hsanjuan and I have had trouble reproducing this failure.

**Comment by hsanjuan** [comment]
I have managed to reproduce the problem, when the migration happens on a peer that is behind the latest index:

  1. Bring up a cluster on `0.3.1`
  2. Pin 3 things
  3. Kill one of the peers
  4. Add another 2 things
  5. Kill everyone
  6. Upgrade everywhere
  7. Start peers


The master will repeteadly show:

```
17:48:25.118 ERROR       raft: Failed to install snapshot 6-7-1516729688290: failed to restore snapshot 6-7-1516729703881: reflect: reflect.Value.SetString using unaddressable value logging.go:86
17:48:25.118 ERROR       raft: Failed to send snapshot to {Voter QmQDuHSz5kEA4XyAToTNqN2EZm43PS5jwwtfse76JUYFMp QmQDuHSz5kEA4XyAToTNqN2EZm43PS5jwwtfse76JUYFMp}: failed to restore snapshot 6-7-1516729703881: reflect: reflect.Value.SetString using unaddressable value logging.go:86
17:48:25.207 ERROR       raft: Failed to get log at index 4: log not found logging.go:86
```
The node that was killed first will repeteadly show:

```
17:48:32.020 ERROR   mapstate: reflect: reflect.Value.SetString using unaddressable value map_state.go:156
17:48:32.020 ERROR libp2p-raf: error decoding snapshot: reflect: reflect.Value.SetString using unaddressable value fsm.go:126
17:48:32.020 ERROR       raft: Failed to restore snapshot: failed to restore snapshot 6-7-1516729710671: reflect: reflect.Value.SetString using unaddressable value logging.go:86
```
