### ISSUE TITLE
Multi-peer cluster migration test

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#299]
We have a few sharness tests already but it would be good to trigger a test on every PR that verifies that all old state formats migrate correctly (or don't need to migrate) to the state format used in the current version of the latest build across a cluster of multiple nodes.  

This can be a kubernetes-ipfs test.  It will require coming up with a way to automatically generate state snapshots that need migration from a selection of old formats.  The naive manual way is to include these files in the dockerfile-test image during dockerfile builds.  We should come up with something better though.

**Comment by hsanjuan** [comment]
We removed migrations and adopted protobufs which must be kept backwards compatible, so closing this for the moment.
