### ISSUE TITLE
make ipfs-cluster-service aware of log entries in the stable store

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#302]
From raft's point of view the snapshot of the cluster state (state.bin) and the raft peer's metadata associated with this snapshot (meta.json) are not the entire story of the consensus state.  There are also log entries in the raft.db boltdb stable store that have consequences on the raft peer's configuration and on using cluster, notably the most up to date raft peers are in this store and you can be burned trying to figure out why raft and cluster peers don't match when the config and meta.json match.

It should be relatively straightforward to read from the store using raftboltdb or maybe something else.  If it only peer membership that matters for cluster perhaps an endpoint to read the raw kv store is unnecessary and all we want is a `state peers` command that is aware of both the snapshot and stable stores.

Also possible that this is not very useful for anyone other than people debugging cluster migration issues and we don't need this.

**Comment by hsanjuan** [comment]
It's not simple, the log entries need to be [re]played (or applied) to the state. There is raft recovery code doing that in raft but it's a bit complex and relies on internals.

If the state commands cannot be run while cluster is running, and if a snapshot is taken everytime cluster stops, then, in the regular case, there should not be anything to be applied to the latest snapshot.

**Comment by hsanjuan** [comment]
Realistically I don't think we'll work to fix this. If the last snapshot is not up to date it should fetch the rest from other healthy peers that did not crash before persisting the data.
