### ISSUE TITLE
Add tests for migration scenarios

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#304]
* Should test that after a migrations, all nodes catch up correctly, including those that were trailing behind and do not have all the updates: described #297
* Should test the fix in #303 (bootstrap to a node with an imported state)

Probably they can be part of the `ipfscluster` module tests, since it is easy there to bring up clusters, but will have to import utilities from `ipfs-cluster-service`, or decide if it makes sense to extract that to a general `migrations` module.

**Comment by ZenGround0** [comment]
We could also test using kubernetes ipfs or launch multiple cluster peers using sharness (see #299)

**Comment by hsanjuan** [comment]
I'd rather not use sharness or kubernetes-ipfs for things that can be tested not using sharness or kubernetes-ipfs. Because they are a pain to debug.

**Comment by hsanjuan** [comment]
Since we removed migrations altogether, this can be closed.
