### ISSUE TITLE
ipfs-cluster-ctl times out very quickly on longer operations

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#323]
`Post http://127.0.0.1:9094/pins/recover?local=true: net/http: request canceled (Client.Timeout ele awaiting headers)`

My guess is that the Client is configure with some default timeouts.

* It should be configurable (as part of the rest/client config)
* There should be a flag to generally set timeouts in ipfs-cluster-ctl
* Default should be way higher than right now

**Comment by lanzafame** [comment]
@hsanjuan I have had a look into this, and points 1 and 2 are already the case, the rest/client has a timeout configuration and ipfs-cluster-ctl has the `--timeout/-t` flag for setting that timeout variable. I have raised the timeout default value to 120 seconds, #334 , though am not sure what the idle would be in this scenario.
