### ISSUE TITLE
Travis failures don't always register

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#324]
Certain tests launched by `go test` on Travis don't propagate failure to the output signal of the testing script.  This should be investigated and fixed so that our CI doesn't ignore these failures.

**Comment by VictorBjelkholm** [comment]
Unless this is regarding some unique script for running tests on Travis, this should happen on all CIs as the basic idea is "if command fails with != 0, there is a error". So should see this on Jenkins as well.

**Comment by hsanjuan** [comment]
This needs a link or something to one of such failures/sucesses. Otherwise it's hardly actionable.

**Comment by ZenGround0** [comment]
https://travis-ci.org/ipfs/ipfs-cluster/builds/346587967?utm_source=github_status&utm_medium=notification This is the log of a passing travis run.  You'll notice several test failures however.  For example Line 2760, Line 2866, Line 2589.

**Comment by hsanjuan** [comment]
possibly a problem with the `coverage.sh` script. Go 1.10 supports coverage from multiple packages so we won't need it anymore.
