### ISSUE TITLE
Monitoring component revamp

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#336]
The monitoring component (and system) is very basic. It's meant to be a Peer monitor, so it should track the state of some peers and notify if one of them goes down.

The component **in the leader**, receives `api.Metric` information from the main `Cluster` components of all peers regularly. These includes the `ping` metric and the metric provided by the configured `Informer`.

It keeps the last metrics stored in a sliding Window although right now it only uses the last one. It should be able to use previous metrics to make more complex decisions.

A goroutine performs a check on a certain `CheckInterval`:

* Obtains the cluster peers
* Check metrics for all peers

If the last metric of any of the types for a peer has expired, it will send and `alert` to the main cluster component over a channel.

The main cluster component can then use that to re-allocate pins if need-be (i.e. they are under their minimum replication factor).

There are a number of improvements:

* Consider switching back to a broadcast mode where all monitoring components in all peers receive metrics from all peers
* The happy trick to not have a booming of metrics reporting was to send metrics only to the cluster leader, while having the leader broadcast its own metrics to everyone. Only the leader acts on alerts (because it's the node that knows all the metrics) and can trigger re-pins in a peer goes down. If the leader goes down, the new leader will hopefully see the expired metric from the old leader and do the same. But if two peers go down, and one is the leader, whoever is the new leader will not have a way to know that yet another peer has gone down.
* Considering how small the metric information is, and how often we report by default, it might be no problem to switch to broadcast-to-all mode. This would allow any peer to detect that any other peer is down.
* Still, only one peer should trigger re-allocation. It's not good that we depend on a `leader` on any component as we should be able to switch consensus implementations to something without leader in the future. How can we handle re-allocations without relying on a leader from the consensus layer? How do we choose the node?
* Normally, applications don't self-heal. Instead you have an external application (a monitoring system Prometheus or Icinga) which tracks your health metrics and have their own redundancy, high availability setup). If your application dies, the monitoring system is not affected because it's running separately. In cluster, if the peer dies, the monitoring dies with it.This makes me wonder if cluster monitoring should be approached as a separate application on top of cluster, which can evaluate when peers are down and re-trigger pins in such cases.
* Detecting failures and triggering alerts should be a bit more sophisticated as checking if the last metric is expired. Having an Accrual failure detector for this, using the window of metrics, would be really cool. This is a go implementation: https://github.com/cyberdelia/accrual (paper: http://fubica.lsd.ufcg.edu.br/hp/cursos/cfsc/papers/hayashibara04theaccrual.pdf) . I think it uses polynomial approximations to the actual function (I checked this years ago).
* With the min/max replication factor feature, we have some leeway so when a node dies, the pins won't be re-allocated right away as long as the content is still above it's minimum replication factor. However, I think the peer that is gone is removed from the allocations list. It should probably be left in the allocations list as long as it's part of the cluster peers, so that when it comes back again it can keep tracking the content that it was tracking before (and bring the replication factor back up). This brings other problems though: figuring out if that peer is still holding that content, handling the case when you have re-allocated to other peers already because the replication factor was below the minimum (avoid over-allocations) etc. This has to do with the pintracker too (#308 ), since it's the component that should realize that ipfs is pinning something that it's not allocated to itself (even though it's in the pinset), and then should maybe request that the peer is made part of the allocations (if under-allocated), or unpin the content. Even worse, if the content is over allocated but one of the allocations has not finished pinning it, it should 1) allocate itself, 2) de-allocate whoever is still pinning it, and cancel that operation.
* Overall, this is tricky with lots of potential for very serious bugs (trigerring re-pinning for Terabytes of data because a peer went down for a bit even if it came back later is no good. Unpinning something because we think it's overpinned but it's actually no is no good either). So we should make sure we think this well and approach things in the safest ways.

**Comment by hsanjuan** [comment]
Status update: there has been a lot of progress here. The pubsub monitor will allow to efficiently broadcast metrics to large clusters. The new pintracker handle pinning/unpinning in much better ways. The disable_repinning option allows to skip repinnings if peers are down.

Still pending are the dependence on Leader #413 , the Accrual failure detector and general improvements.

**Comment by lanzafame** [comment]
@hsanjuan the self healing dot point ends with `Of course it's` do you remember what the rest of that sentence was going to be or should it be removed?

**Comment by hsanjuan** [comment]
i can't remember. removed it

**Comment by hsanjuan** [comment]
The main gist of this (accrual, not relying on leader, pubsub) is done. Closing...
