### ISSUE TITLE
Rework README, ROADMAP.md docs

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#337]
* The readme should be explicit on the feature set and the current main issues
* The roadmap should be up to date and not defer to the OKRs, it should list past achievements and future goals
* The guide should expand on the debugging parts. It should have recommendations for running cluster in production and how to work around some of the problems.
* Update captain's log too.

**Comment by hsanjuan** [comment]
Related #347

**Comment by hsanjuan** [comment]
# Roadmap

## Current feature set:

* Pin replication with maximum and minimum replication factor in your cluster
* Automatic re-pinning on downtime events
* Evenly-distributed pins according to repository space of each ipfs daemon
* World wide setup possible (higher latency scenarios supported)
* Painless upgrades (migrations)
* Pin-set exports and imports
* Clusters can grow (bootstrap new peers) and decrease (peer removal) while live
* REST-y API and API client (in Go) with 100% API coverage provided. HTTPS and basic authentication supported.
* ipfs-proxy allows to drop-in cluster in place of ipfs-daemon API, turning ipfs-pin requests to cluster-pin requests.
* Runs independently from go-ipfs, uses the go-ipfs API.
* The ipfs-cluster guide provides comprehensible overview of "how ipfs-cluster works".

## Current problem set:

* Bad UX for large pins (or things that take long time to pin). Pin operations don't happen concurrently.
* Unclear about the escalability limits:
  * Tested with 10 cluster peers on a global setup
  * Repository size of around 70 GB/each
  * ~2000 pins/peer
* Repository stat very slow on IPFS, means a problem handling larger repositories
* No peer autodiscovery
* No pin sharding
* Lack of documentation on how to run a production cluster.
* ipfs-cluster is not meant for collaborative pinning among groups of strangers (uses a shared secret among peers).

## Roadmap:

### Short term (next Quarter)

* Key functionality extraction from go-ipfs / importers (ongoing)
* Sharding support prototype (ongoing)
* Improve UX to handle larger files / concurrent pin operations (several fronts, some ongoing)
* Efficient repository disk usage in IPFS (ongoing)
* Reference guide to setup, manage and operate a production cluster.
* First metrics are exposed.
* Live large-storage cluster operated and maintained by us (IPFS) consolidates all our pinsets. (ongoing)

### Mid term (6-8 months horizon)

* Collaborations with different players interested in using ipfs-cluster/ipfs to store large datasets.
* Good sharding support for at least ~1TB datasets (package repositories).
* We have metrics to have an idea of how big a cluster can grow (peers, pinset, repository size), where degradation start, critical paths in the application performance.
* Project website

### Long term (~1 year+)

* ipfs-cluster+ipfs are used to ingest and store very large volumes of data in production
* Really strong testing and metric collection pipelines
* Additional chunking/sharding/encoding strategies. FEC support.
* Exploring new possibilities for the consensus layer
* Exploring how cluster can support collaborative archival efforts (between strangers)

**Comment by hsanjuan** [comment]
@ZenGround0 can you have a look here and see if I left something out?

@flyingzumwalt feedback on the roadmap? @mr0grog perhaps you too have some feedback on roadmap?.

**Comment by ZenGround0** [comment]
The two big things I see missing are probably both long term
* exploring support for a rich set of allocation strategies e.g. by geographic location or as a function of access patterns
* Good support for composite clusters

Note that the two are potentially related as composite clusters could be an avenue for implementing different allocation strategies.  If allocation strategy exploration leads to configurable rebalancing of pinsets then these efforts will be useful/reusable for FEC support.

I don't know how strong the use case is for using js-ipfs nodes in a cluster but AFAIK we aren't testing this and maybe we should.  At the very least it proves that we are being agnostic to the implementation behind the ipfs api.

Something very general and very long term is extending the use of cluster to coordinate ipfs daemon state beyond an allocated pinset.  Maybe sharing parameters through consensus to ensure a more efficient bitswap guild, perhaps a registry of ipld-resolvers to download, and potentially many others.  This would all need to be motivated on a product level and might bloat cluster beyond the boundaries of a unixy comprehensive tool but could address valuable needs.

**Comment by hickscorp** [comment]
> Bad UX for large pins (or things that take long time to pin). Pin operations don't happen concurrently.

It would be nice to elaborate on this point. Does that mean:
- That pinning concurrently would crash?
- That it would timeout?

Essentially: what would a consumer expect from the response if a concurrent pinning would occur.

**Comment by hsanjuan** [comment]
> Is concurrent pinning - in fact - supported? 

Sorry, it is now. This issue was created before it wasn't.

I think your questions will be answered in the new documentation in cluster.ipfs.io (when it's all written down):

> Is the shared secret enough to ensure a closed-circuit of cluster related operations?

Shared-secret ensures only that the cluster peers communcations are protected and only a party with that secret can read/write to the internal RPC endpoints (tcp/9096).

> Would it be possible to have TLS / SSL enabled on the cluster related ports?

You can enable it for the API (tcp/9094) by setting the cert path and key path in the restapi section of the configuration. You can also access the HTTP API through libp2p (:9096 - with shared secret, or with a custom libp2p host on a different port). This is very new and it's not documented yet, but more info at #349 .

> When it comes to the IPFS proxy itself, would it follow the strategies defined on the IPFS daemon itself (Eg authentication, etc)? A link to the IPFS relevant docs might be good here.

The IPFS daemon does not have authentication. For all non-handled endpoints (everything except pin/add pin/rm, pin/ls, /add) it should. For the rest, it's true we hijack the requests and in the process don't respect some things (CORs settings for example). I'm going to open an issue. Primarily, I recommend using the Cluster API and not the Proxy as it's been a while we have looked into it. #382

**Comment by hsanjuan** [comment]
We have reworked everything and put it in the website
