### ISSUE TITLE
ipfs-cluster-ctl pin/add pin/rm should have a --wait option

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#338]
Just like we provide a --no-status option, there should be a --wait option which doesn't return until the pin has reached PINNED status or has been fully unpinned.

It should do this by regulary querying `status <cid>` on the pin and waiting for all PINNING to either be PINNED or PIN_ERROR.

Before exiting, it should print the final status.

I think this WaitForPin/Unpin function should be provided as an utility/method in `rest/client`, and re-used by ipfs-cluster-ctl. Open for proposals but `func client.WaitFor(targetStatus, checkInterval) <- channel Status` is one option.

**Comment by lanzafame** [comment]
If `func client.WaitFor(targetStatus, checkInterval) <- channel Status` is returning a `Status` every `checkInterval` on the returned channel, what is the requirement for the `targetStatus` parameter?

**Comment by lanzafame** [comment]
scratch that, I understand why now :)

**Comment by hsanjuan** [comment]
Yeah, target would be Pinned/Unpinned :)

**Comment by lanzafame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#338](https://trello.com/c/po1OdAfA/2-338)

**Comment by hsanjuan** [comment]
#348
