### ISSUE TITLE
Looking ahead: ipfs-cluster and pluggable consensus

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#351]
This is a tracking issue for ipfs-cluster pluggable consensus.  Note that this is a far reaching goal and isn't likely to show up as an implementation here for a significant amount of time.

Recent attention to the [IPFS Consortium](https://github.com/ipfsconsortium) brought up some discussion about ipfs-cluster and consensus.  An [original goal](https://github.com/ipfs/notes/issues/58) of ipfs-cluster was to eventually support a pluggable consensus model and in particular eventually a Byzantine Agreement consensus model.  The recent discussion following discovery of consortium brought up the possibility of DAO-based consensus where the pin set is managed by an Ethereum (or other execution system) contract.

@hsanjuan has also surfaced the idea of using pubsub at the consensus layer (deep in the comments of https://github.com/ipfs/ipfs-cluster/pull/215)

If there is sufficient motivation for this extension to ipfs-cluster it will require a great deal of planning and redesign.  Some basic questions we could ask ourselves and thoughts to consider:
- will the cluster codebase by default include access to different consensus paradigms? i.e. through a command line flag?  Probably this will be the case for a few important variations (BA).  What about leaving the code base extensible to interact with other consensus implementations that are not explicitly bundled with cluster? What does that interface look like and how will configuration and integration work?
- Where is our code explicitly dependent on raft? Hint: a lot of places.  How can we restructure the code to abstract away all consensus dependent operations within the consensus module.  Even harder how can we rethink the consensus interface to deal with solutions that are significantly different, for instance in the DAO example not only is their no notion of a cluster leader but the source of truth is not even a cluster peer.  
- Nailing down clusters' vision for peer authentication and security models is probably going to be a key part in enabling pluggable consensus.

**Comment by hsanjuan** [comment]
> Where is our code explicitly dependent on raft? Hint: a lot of places

Not so many. Actually 3 places (plus some in the tests), all related to monitoring (see #336 ).

**Comment by hsanjuan** [comment]
And it's not a raft dependency, it's a dependency on a consensus implementation that can provide a stable Leader().

**Comment by hsanjuan** [comment]
Closing this as fixed, we now merged support for two consensus layers (and can add easily more). Repinning dependency is going to be  fixed in #714
