### ISSUE TITLE
Package context warning on make 

### ISSUE THREAD

**Issue by nothingismagick** [ipfs/ipfs-cluster#354]
Following the instructions to build ipfs-cluster using this:

`go get -u -d github.com/ipfs/ipfs-cluster`

I got the following warning: 

`package context: unrecognized import path "context" (import path does not begin with hostname)`

This is just a warning, I was able to make ipfs-cluster without problems.

`$ go env` results >

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by hsanjuan** [comment]
Hi, use a newer version of go (recommended 1.9.x).

**Comment by nothingismagick** [comment]
Ok.
