### ISSUE TITLE
ipfs-cluster-ctl basic authentication does not work with some special chars

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#366]
If the password contains special chars (`$` for example) it's truncated silently at some point.

Also `:` in the password causes and error and probably should not.

This seems ipfs-cluster-ctl related only. The rest/client seems to work well regardless of the password.

**Comment by s1na** [comment]
@hsanjuan `$` sign does lead to truncating, but for me it was fixed when I escaped it with `\`. The `:` seems to be working fine. Have you faced a problem with another character?

**Comment by hsanjuan** [comment]
I'll check again

**Comment by hsanjuan** [comment]
Ok it's fine :)
