### ISSUE TITLE
Option to disable repinnings

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#369]
For the cluster section of the configuration: `disable_repinning` should ensure no repinning happens when a node goes down (`repinFromPeer`). This is useful when doing certain types of maintainance, or simply when not wanting to rely on the monitoring system which needs a revamp.

**Comment by s1na** [comment]
I would like to work on this if possible.

**Comment by hsanjuan** [comment]
@s1na sounds good, I have invited to as collaborator to the project so you can push branches directly to this repo and make PRs from them. Thanks for your interest!

**Comment by ehsan6sha** [comment]
why is this parameter set to true by default? Don't we want the repinning to happen if the number of pins for a specific cid falls below the threshold?

**Comment by hsanjuan** [comment]
> why is this parameter set to true by default? Don't we want the repinning to happen if the number of pins for a specific cid falls below the threshold set by replication_factor_min ?

Because if you have 1M CIDs and one peer goes down temporally for whatever cause you may not want 1M CIDs automatically relocated somewhere else with the amount of bandwidth and write costs that carries, you may want to actually fix the original peer and bring it back up.
