### ISSUE TITLE
ipfs-cluster-ctl health: report whether cluster is stable

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#374]
When setting up a cluster, it would useful to know when the cluster has become stable after adding a peer(s). A command with following example output would be useful:
```bash
$ # Example Stable State
$ ipfs-cluster-ctl health
Cluster: Stable
Leader: QmNpXvAXVbEmfXnBfBuexa9KufGKLj2Bsf187s4pBwjDTQ | <hostname> | <health>
Followers: 
  - QmdVqxKtQMJo78QFTTvC3wDmDn3hr16apuTxT7UdZ2VHoU | <hostname> | <health>
  - QmeqKDbL3vSNp1NCt6SmZm59BftWFEsYjpJekPqNeRTBVe | <hostname> | <health>
```

```bash
$ # Example Unstable State
$ ipfs-cluster-ctl health
Cluster: Unstable (No Leader)
Candidates: 
  - QmNpXvAXVbEmfXnBfBuexa9KufGKLj2Bsf187s4pBwjDTQ | <hostname> | <health>
  - QmdVqxKtQMJo78QFTTvC3wDmDn3hr16apuTxT7UdZ2VHoU | <hostname> | <health>
Peers: 
  - QmeqKDbL3vSNp1NCt6SmZm59BftWFEsYjpJekPqNeRTBVe | <hostname> | <health>
```

```bash
$ # Example Health of Single Node
$ ipfs-cluster-ctl health QmNpXvAXVbEmfXnBfBuexa9KufGKLj2Bsf187s4pBwjDTQ
Health: QmNpXvAXVbEmfXnBfBuexa9KufGKLj2Bsf187s4pBwjDTQ | <hostname> | <health> | <leader|candidate|follower>
```

@hsanjuan @ZenGround0 thoughts on whether you would find this useful?

**Comment by hsanjuan** [comment]
This is too raft-specific, in principle. But exposing who is the leader if there is one (maybe in `id` directly) might be handy. However, ideally, I'd like that it did not matter at all (hide all consensus-specific stuff from the user). What I want to expose in the `health` command is monitoring metrics collected by the monitor component.

**Comment by lanzafame** [comment]
If you remove the `Candidate` stuff from the above examples, then the output all falls into the `Consensus` interface methods. It would at least allow you to know when the cluster was stable.

**Comment by hsanjuan** [comment]
The problem being that `Leader()` should not be a `Consensus` component method :) Maybe the `Consensus` should provide `Ready()`, or `Available()` or `Connected()`

**Comment by lanzafame** [comment]
Ahh right 😄

**Comment by hsanjuan** [comment]
I'd be happy to take contributions improving information reported by the `/health` endpoint

**Comment by hsanjuan** [comment]
Actionables:

* Human-sizes for `freespace` metrics. Display whether if metric is expired or something like "expires in 3 minutes".
* `ipfs-cluster-ctl health metrics` hits the the metrics endpoint which returns a list of available metrics and displays to user

**Comment by kishansagathiya** [comment]
> ipfs-cluster-ctl health metrics hits the the metrics endpoint which returns a list of available metrics and displays to user

You mean it should work without passing the metrics name?

**Comment by hsanjuan** [comment]
> > ipfs-cluster-ctl health metrics hits the the metrics endpoint which returns a list of available metrics and displays to user
> 
> You mean it should work without passing the metrics name?

I mean not passing a metrics name should produce a list of available metric names that can be used.

**Comment by kishansagathiya** [comment]
Message for squashed commit

```
`health metrics` improvements

- Human-sizes for freespace metrics. Display whether if metric is
expires in something like "expires in 3m".
- When not passing metric name `ipfs-cluster-ctl health metrics` hits
the the metrics endpoint which returns a list of available metrics and
displays to user
- Humanize metrics output
- Sort metrics output
```
