### ISSUE TITLE
Can ipfs-cluster be used on different lan

### ISSUE THREAD

**Issue by healthwallet** [ipfs/ipfs-cluster#375]
I have a variety of problems with multiple LAN deployments. Have other people used it on multiple lan?

**Comment by lanzafame** [comment]
@healthwallet could you please provide a more concrete example of what you are attempting? cheers

**Comment by hsanjuan** [comment]
We have enabled libp2p NAT hole punching in our latest release. I'm closing this for the moment. Report back if you have any feedback.
