### ISSUE TITLE
ipfs webUI through the cluster ipfs proxy does not work well

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#379]
* There are errors parsing json in the console. This means something is not being proxied as expected but I haven't investigated what's the problem exactly.

 WebUI requests return as 403 forbidden.

**Comment by hickscorp** [comment]
For me, the cluster simply doesn't proxy the IPFS daemon at all. See https://github.com/ipfs/ipfs-cluster/issues/376 .

**Comment by hsanjuan** [comment]
Yes, correct, I was just coming to post this. Thanks @hickscorp

**Comment by hsanjuan** [comment]
Side note: is not CORS per se, it's CRLF protection which checks the Referer header and matches against values defined for the CORS headers (because in the end that's the list of acceptable referers too).
