### ISSUE TITLE
Proxy endpoint doesn't respect IPFS header policies for hijacked paths

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#382]
IPFS enforces a bunch of stuff regarding CORs, CRLF attacks protection etc. Hijacked requests don't do any of that.

We need to let the user provide IPFS-like API configuration for the proxy, with whatever headers there are etc, and work just like ipfs would work, with the difference that we would still be hijacking the requests.

**Comment by LEonGAo1991** [comment]
@hsanjuan Can I give a try on this one?

**Comment by hsanjuan** [comment]
@LEonGAo1991 sure. Can you figure out which options need to be added first and what approach you plan to take (apply to all proxy requests vs. apply to those handled by cluster only etc) and post it here? I haven't given too much thought to this yet..

**Comment by hsanjuan** [comment]
Possible approach:

* Store ipfs headers and values in a `http.Header` object.
* If the object is `nil`, before any non proxied request, make an `/id` ipfs request to ipfs.
* Extract headers from that response and store them in the `Header` object.
* The list of headers to extract can be part of a pre-configured list: those related to CORS at least, `Trailer` too (why does /id has a `Trailer`?). Since the user can configure custom headers, we might as well copy everything except `Date`, `Server` etc.
* Use the `Header` object to copy any headers from it to the headers of the http.Response in non-proxied requests.
