### ISSUE TITLE
Add "the peer you are trying to start is running a different version of IPFS-cluster" to start error messages

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#388]

**Comment by s1na** [comment]
Is this for when the user starts the service with pre-configured peers? should it stop in case one of the peers has a different version running?

**Comment by hsanjuan** [comment]
It's just adding an extra explanation here: https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go#L497 and https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go#L438
