### ISSUE TITLE
Meeting notes - 2016-07-08 17:00Z

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/ipfs-cluster#4]
Participants:
@whyrusleeping
@hermanjunge 
@jbenet 
@christianlundkvist
# Notes

daemon startup:
- read config (whats in the config? do we even need a config?)
- join cluster (clusterID)
  - autodiscovery mechanisms?
    - mdns
    - ipfs service discovery
  - manually specify hosts
- get pinset (how? ask master?)
  - question: are pinsets replicated across all nodes?
    - pinset could just be a single hash, consensus to agree on that hash
  - when new nodes join, how are existing pinsets re-striped?
    - at first, this could be static. no restriping
- once you have pinset, ensure you have all content specified
- serve API

Api endpoints:
- control port
- 'ipfs' API port
- inter-cluster rpc port
# dev timeline
- step zero:
  - skeletons of clusterd and cluster-control
- step one:
  - single node cluster
- step two:
  - many nodes, fully mirrored
- step three:
  - fancier striping option

Tasks:
- [x] @whyrusleeping will make skeleton programs (ipfs-clusterd)
- [ ] @hermanjunge will start working on containerization orchestration / CI 
- [ ] @hermanjunge will flesh out 6 deployment use cases
- [ ] @JLilic and @hermanjunge to flesh out business use cases (??)
- [ ] @jbenet working on transports and pipe stuff (libp2p)
- [ ] @jbenet and @christianlundkvist work on consensus interface
- [ ] @jbenet fleshing out spec skeletons for API pieces and so on

https://github.com/ipfs/ipfs-cluster/issues/1#issue-163453108

**Comment by jbenet** [comment]
Hey everyone, the IPFS team was out of commission for a while in Lisbon. We're back, and can carry this on. 

@christianlundkvist i'm in NYC, happy to get together and work on consensus interface and other things.

**Comment by hermanjunge** [comment]
Hey @jbenet same for me, at least, had a long travel to HQ in Brooklyn and to a conference in Japan, plus onboarding to the member of the INFURA project. Good thing is that I can allocate a lot more of bandwith to cluster :-)

Will take care of the basic DevOps issues (setup CI/CD), as @whyrusleeping already built a skeleton.

**Comment by jbenet** [comment]
- @hermanjunge love your avatar ❤️ 👍 
- sounds good.

**Comment by jbenet** [comment]
Do we want to schedule a call next week to pick back up?

**Comment by hsanjuan** [comment]
Heads up, I'm going to take over this, plug it to libp2p-raft and try to get a minimal implementation where all members of a cluster pin an item. There are pieces missing (mountable pipelines -which I cannot find described anywhere, discussions about the Consensus interface etc.) so I'll have to work my way around some things but at least this will get a push to make something usable in whats left of Q4.
