### ISSUE TITLE
Unable to make/build locally

### ISSUE THREAD

**Issue by postables** [ipfs/ipfs-cluster#404]
Unable to make/build ipfs-cluster locally
```
solidity@pop-os:~/go/src/github.com/ipfs/ipfs-cluster$ make
Downloading gx
Makefile:41: recipe for target 'deptools/gx_v0.12.1' failed
make: *** [deptools/gx_v0.12.1] Error 1
solidity@pop-os:~/go/src/github.com/ipfs/ipfs-cluster$ go version
go version go1.10.2 linux/amd64
solidity@pop-os:~/go/src/github.com/ipfs/ipfs-cluster$ uname -a
Linux pop-os 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hsanjuan** [comment]
Run the Makefile steps manually and see which one fails, bacause as you can see, the information you provide does not give many clues:

```
        @echo "Downloading gx-go"
        @mkdir -p ./$(deptools)
        @rm -f $(deptools)/gx-go
        @wget -nc -q -O $(gx-go_bin).tgz https://dist.ipfs.io/gx-go/$(gx-go_version)/$(gx-go)_$(bin_env).tar.gz
        @tar -zxf $(gx-go_bin).tgz -C $(deptools) --strip-components=1 gx-go/gx-go
        @mv $(deptools)/gx-go $(gx-go_bin)
        @ln -s $(gx-go) $(deptools)/gx-go
        @rm $(gx-go_bin).tgz
```

**Comment by hsanjuan** [comment]
@postables what version of Make are you using? What OS?

**Comment by postables** [comment]
@hsanjuan  sorry for the delayed response! Since then I have downloaded and installed gx, and have the ipfs daemon running and the installation process went okay. I think that maybe because I had not installed gx before hand that was causing an issue. While I was reading up on gx if I recall it mentioned that it works better with the ipfs daemon running, so perhaps that had something to do with it as well.
