### ISSUE TITLE
No existing helper to create default config for api/rest/client ?

### ISSUE THREAD

**Issue by postables** [ipfs/ipfs-cluster#407]
Just wanted to see if I Was missing something, but it doesn't appear that there exists a helper method to create a default config? If this is case I'll be writing my own helper method and will submit a PR.

Package: https://godoc.org/github.com/ipfs/ipfs-cluster/api/rest/client

**Comment by postables** [comment]
The method `NewClient` will populate missing fields in the config struct as needed.
If possible that information should be added to the godoc.

**Comment by hsanjuan** [comment]
You can make documentation PRs too :)
