### ISSUE TITLE
Pins should support a replication factor

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#41]
A Pin should not need to be pinned in every cluster member. We should be able to say that a pin needs to be pinned in 2, 3 cluster members.

We will start with a general replication factor for all pins, then maybe transition to replication factor per-pin.

These are thoughts for the first approach.

Replication factor `-1` means Pin everywhere. If replication factor is larger than the number of clusters then it is assumed to be as large.

### Pinning

We need a `PeerMonitor` component which is able to decide, when a pin request arrives, which peer comes next. The decision should be based on pluggable modules: for a start, we will start with one which attempts to evenly distribute the pins, although it should easily support other metrics like disk space etc.

Every commit log entry asking to Pin something must be tagged with the peers which are in charge. The Pin Tracker will receive the task and if it is tagged itself on a pin it will pin. Alternatively it will store the pin and mark it as `remote`.

If the `PinTracker` receives a Pin which is already known, it should unpin if it is no longer tagged among the hosts that are in charge of pinning. Somewhere in the pipeline we probably should detect re-pinnings and not change pinning peers stupidly.

### Unpinning

Unpinning works as usual removing the pin only where it is pinned.

### Re-pinning on peer failure

The peer monitor should detect hosts which are down (or hosts whose `ipfs` daemon is down).Upon a certain time threshold ( say 5 mins, configurable). It should grep the status for pins assigned to that host and re-pin them to new hosts.

The peer monitor should also receive updates from the peer manager and make sure that there are no pins assigned to hosts that are no longer in the cluster.

For the moment there is no re-rebalancing when a node comes back online.

This assumes there is a single peer monitor for the whole cluster. While monitoring the local ipfs daemon could be done by each peer (and triggering rebalances for that), if all nodes watch eachothers this will cause havoc when triggering rebalances. The Raft cluster leader should probably be in charge then. But this conflicts with being completely abstracted from the consensus algorithm below. If we had a non-leader-based consensus we could assume a distributed lottery to select someone. It makes no sense to re-implement code to choose a peer from the cluster when Raft has it all. Also, running the rebalance process in the Raft leader saves redirection for every new pin request.

### UX

We need to attack `ipfs-cluster-ctl` to provide more human readable outputs as the API formats are more stable. `status` should probably show succinctly which pins are underreplicated or peers in error, 1 line per pin.

**Comment by 20zinnm** [comment]
I'd like to be clear. Is this pinning blocks or pinning merkel dags that describe files? I.e., say I use `ipfs add shakespeare.txt` and get a hash there representing the file--if I add that to the cluster, will the cluster distribute the file in the way you describe or distribute the individual blocks?

Also, can this support clusters where nodes have limits that vary?

**Comment by hsanjuan** [comment]
@20zinnm right now its not pinning blocsk individually. It's equivalent to `ipfs pin add`. It will distribute the file.

> Also, can this support clusters where nodes have limits that vary? yes, it should not be difficult to implement custom strategies for different limits.

**Comment by 20zinnm** [comment]
@hsanjuan I've been doing some reading concerning the Raft consensus algorithm you use in ipfs-cluster, and I wonder why a model like this wouldn't work:
1. Leader receives request to pin IPFS file.
2. Leader commits a message like 'ADD [hash]' or something.
3. Followers receive the request and break it down to individual blocks.
4. Followers then decide whether or not they have the capacity to keep specific blocks.
5. Should a follower decide to keep a block, it proposes a change to the log with the block hash (and if in an untrusted environment a proof of retrievability <sup>[1]</sup>).
6. The leader will commit it (or, if in an untrusted environment, will commit it after verifying the proof).
7. Followers prioritize blocks to keep based upon how many others are included in the state as keeping the block.

This would allow for fine-grained distribution and replication at the block level to maximize the utilization of peers and allow them the ability to chose whether or not to take blocks. This is advantageous because it allows for heterogeneous peers (my raspberry pi with a gigabyte and a rack in the cloud with a petabyte can participate on the same cluster).

[1]: https://eprint.iacr.org/2008/175.pdf

**Comment by hsanjuan** [comment]
Hello @20zinnm ,

As it was pointed out on irc, while your proposal offloads the tracking decision to the nodes, it does not allow to provide balancing strategies where comparison between nodes are needed (i.e. geographically or network-topology based decisions).

Regarding block-level tracking, as I said, on this first approach we will not do it. A number of reasons were also provided on [irc](https://botbot.me/freenode/ipfs/2017-02-09/). I think you can accommodate your use case by sending the block hashes to cluster rather than the main hash, as cluster does not make distinctions. Would that work for you?

**Comment by hsanjuan** [comment]
PR is in.The re-pinning on host failure has been moved to #45.

**Comment by 0zAND1z** [comment]
What is the default replication factor in an ipfs-cluster?

Would love to know that.

**Comment by lanzafame** [comment]
It's defined in the config file, found by default at
`~/.ipfs-cluster/service.json`

**Comment by 0zAND1z** [comment]
Thanks.

What's the range for these replication factor variables here?

I see the https://cluster.ipfs.io/documentation/configuration/#the-cluster-main-section describing the default values for replication factor, but not the range of values.

**Comment by lanzafame** [comment]
Min is 0, max is whatever fits inside a golang int, and -1 has the special
meaning of all peers.
