### ISSUE TITLE
metrics.Store should eventually get rid of old peers

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#410]
The `metrics.Store` type is used to store metrics from different peers. The `metrics.Checker` will check metrics and trigger alerts if they are expired and belong to peers in the peerset.

The problem is: if a peer is removed from the peerset (from the cluster), the `Store` will still keep a key containing the metrics.Window for that peer, as this is never cleaned up.

In a potential scenario with a huge number of coming and going peers, these entries should be deleted from the map, at least when they are no longer in the peerset.

**Comment by evalsocket** [comment]
Hey @hsanjuan  new on ipfs-cluster. Any additional info regarding that issue ?

**Comment by hsanjuan** [comment]
There is not much else to say... the easiest is that https://github.com/ipfs/ipfs-cluster/blob/master/monitor/metrics/store.go  runs a goroutine that periodically cleans up expired peers (but only long after they have expired).

**Comment by evalsocket** [comment]
Did you decide any time period for clean up down peer map

**Comment by hsanjuan** [comment]
Make it configurable? Default to 1h.

**Comment by evalsocket** [comment]
Please review the implementation 
https://github.com/evalsocket/ipfs-cluster/blob/master/monitor/metrics/store.go

**Comment by evalsocket** [comment]
@hsanjuan Are we saving the time when peer goes down in metrics.Store variable window

**Comment by kishansagathiya** [comment]
@evalsocket raise a pull request

**Comment by lanzafame** [comment]
@evalsocket also I suggest having a look at [`time.NewTicker`](https://golang.org/pkg/time/#NewTicker)

**Comment by evalsocket** [comment]
@lanzafame I am implementing time.NewTicker. @kishansagathiya Currently i working on it and It's incomplete

**Comment by hsanjuan** [comment]
@lanzafame any chance that this can happen along the metric window changes? (I understand this problem still exists?)

**Comment by hsanjuan** [comment]
For inspiration: https://github.com/whyrusleeping/timecache/

**Comment by kishansagathiya** [comment]
From studying the code it seems like this is already taken care of 
`Checker.Watch` --> `Checker.CheckPeers/CheckAll` --> `Checker.alert()` if a metric failed for a peer (if a peer failed for a metric also considers expiry of metrics)  --> alert would remove metrics for a peer if number of alerts crossed a threshold
