### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by 20zinnm** [ipfs/ipfs-cluster#42]
The `os/etcd/rafthttp` Raft HTTP implementation (https://github.com/coreos/etcd/tree/master/rafthttp or https://godoc.org/github.com/coreos/etcd/rafthttp) can use TLS to secure communication, which in turn is capable of mandating the client be authenticated, allowing you to specify a CA to validate client certificates (https://godoc.org/crypto/tls#Config). We could use this to our advantage to add authentication to ipfs-cluster by having the cluster accept a configured certificate and a certificate authority that it uses to keep the cluster tight. Kubernetes or similar would be responsible for the CA and Certificate generation.

**Comment by hsanjuan** [comment]
@20zinnm I'm waiting on the Private Networks feature which should be coming soon for this: https://github.com/ipfs/go-ipfs/issues/3313

libp2p channels are already encrypted.

**Comment by hsanjuan** [comment]
PNets are now ready on latest libp2p and I updated the libp2p deps that day so this should be implemetable now.

**Comment by hsanjuan** [comment]
#109
