### ISSUE TITLE
Transition /ipfs multiaddr handling to /p2p

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#431]
See https://github.com/multiformats/multiaddr/pull/64 and https://github.com/multiformats/go-multiaddr/pull/66. 

Places where we manually add `/ipfs/`:
api/util.go:45
api/util.go:61
pstoremgr/pstoremgr.go:106
api/rest/client/client_test.go:63
peer_manager_test.go:36
consensus/raft/consensus_test.go:31
ipfscluster_test.go:238

**Comment by hsanjuan** [comment]
ah, finally. We need to wait until this is bubbled in libp2p.

**Comment by hsanjuan** [comment]
This can be done now
