### ISSUE TITLE
Error when run ipfs-cluster-service on BeagleBone or Raspberry PI

### ISSUE THREAD

**Issue by hp1909** [ipfs/ipfs-cluster#433]
I downloaded ipfs-cluster-service for arm into my Raspberry PI and run ipfs-cluster-service daemon. But I totally received this error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11540]

goroutine 46 [running]:
sync/atomic.addUint64(0x131c005c, 0x1, 0x0, 0x131c9150, 0x8)
	/usr/lib64/go/1.9/src/sync/atomic/64bit_arm.go:31 +0x4c
gx/ipfs/QmduQtUFqdq2RhM84yM2mYsdgJRAH8Aukb15viDxWkZtvP/go-libp2p-floodsub.(*PubSub).Publish(0x131c0000, 0x716b54, 0xf, 0x13124630, 0x5d, 0xa2, 0x0, 0x1e)
	gx/ipfs/QmduQtUFqdq2RhM84yM2mYsdgJRAH8Aukb15viDxWkZtvP/go-libp2p-floodsub/pubsub.go:556 +0x64
github.com/ipfs/ipfs-cluster/monitor/pubsubmon.(*Monitor).PublishMetric(0x12d5caa0, 0x70dc03, 0x4, 0x12d16c60, 0x22, 0x0, 0x0, 0xa5f1d075, 0x1531f22e, 0x1, ...)
	github.com/ipfs/ipfs-cluster/monitor/pubsubmon/pubsubmon.go:193 +0x39c
github.com/ipfs/ipfs-cluster.(*Cluster).pushPingMetrics(0x12d64320)
	github.com/ipfs/ipfs-cluster/cluster.go:232 +0xc0
created by github.com/ipfs/ipfs-cluster.(*Cluster).run
	github.com/ipfs/ipfs-cluster/cluster.go:340 +0x48
```

**Comment by hsanjuan** [comment]
@hp1909 ouch... it seems pubsub is not compatible with ARM. I think this comes from:

https://golang.org/pkg/sync/atomic/#pkg-note-BUG

I'll report this to pubsub. In the meantime, can you try running `ipfs-cluster-service daemon --monitor basic`

**Comment by hsanjuan** [comment]
(Note that we have some bugs in the latest 0.4.0 RC version), new release coming next week.

**Comment by hp1909** [comment]
Hope you will fix this error. :D Thanks in advance because I tried to used this in my IoT platform.

**Comment by hp1909** [comment]
Can you add the pubsub API like `ipfs pubsub pub topic message`?

**Comment by hsanjuan** [comment]
@hp1909 cluster uses pubsub internally. You need to run the ipfs daemon next to the cluster peer and that provides you with `ipfs pubsub`.

I'm not sure what you want to do with it though, maybe I'm misunderstanding...

**Comment by hp1909** [comment]
I mean that I can use `ipfs-pubsub` in ipfs cluster or not. 
I seem like this: https://ipfs.io/blog/25-pubsub/
