### ISSUE TITLE
Pin add:  Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by ekanath25** [ipfs/ipfs-cluster#434]
Hi,

I had tried to add a pin, it gives timeout error,
`ipfs-cluster-ctl pin add QmSYWY5HbT25kk4X9edtZHtvkX9H9zRyFbbKp1ENqN4cTx
QmSYWY5HbT25kk4X9edtZHtvkX9H9zRyFbbKp1ENqN4cTx :
    > Peer QmSYWY5HbT25kk4X9edtZHtvkX9H9zRyFbbKp1ENqN4cTx : ERROR | Post http://127.0.0.1:5001/api/v0/pin/add?arg=QmSYWY5HbT25kk4X9edtZHtvkX9H9zRyFbbKp1ENqN4cTx&recursive=true: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

Please help me to solve this error. Thanks in advance

**Comment by hsanjuan** [comment]
The pin request times out. Also, why is your pin CID the same as your Peer ID?

**Comment by ekanath25** [comment]
I tried in windows10 with Ipfs address getting the same error. 

`ipfs-cluster-ctl pin add QmbeQXoWQFKAt4QYdcdEwT9KmdSS6VYpWyqMepAmby791K
QmbeQXoWQFKAt4QYdcdEwT9KmdSS6VYpWyqMepAmby791K :
    > Peer QmSYWY5HbT25kk4X9edtZHtvkX9H9zRyFbbKp1ENqN4cTx : ERROR | Post http://127.0.0.1:5001/api/v0/pin/add?arg=QmbeQXoWQFKAt4QYdcdEwT9KmdSS6VYpWyqMepAmby791K&recursive=true: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
