### ISSUE TITLE
There should be an api.Client which supports load balancing among multiple cluster peers

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#448]
#### Basic information

* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement

#### Description

Following #447, a new client implementation would take multiple `*client.Configs` (or take one with multiple peer addresses) and maintain multiple `api/rest/client`s internally . When a request comes, it should round-robin, or randomly select a client. When a network error occurs, it should retry with a different peer.

**Comment by hsanjuan** [comment]
Blocked on #447

**Comment by hsanjuan** [comment]
No longer blocked as #447 is resolved.

**Comment by lanzafame** [comment]
Blocked by #561.

**Comment by kishansagathiya** [comment]
https://github.com/ipfs/ipfs-cluster/pull/561 is merged, removing `blocked` tag

**Comment by kishansagathiya** [comment]
@hsanjuan Let me know if I understand this correctly.

You want a new client implementation whose job would be load balancing. Any request would first come to cluster leader's load balancing client which would pass it on(reverse proxy?) to rest api clients of cluster peers.

**Comment by lanzafame** [comment]
We are trying to get rid of any kind of cluster leader, so it wouldn't make sense to give the current one any more responsibility. Not sure what the solution is in this case.

**Comment by hsanjuan** [comment]
Hi, the leader has nothing to do here. We have a `client` interface:

https://github.com/ipfs/ipfs-cluster/blob/master/api/rest/client/client.go#L40

and a default implementation for it:

https://github.com/ipfs/ipfs-cluster/blob/master/api/rest/client/client.go#L174

The default implementation uses a single API endpoint (APIAddr).

This feature is about having a `client` implementation to which you can provide multiple cluster REST API endpoints and which will do load balancing between them. Internally, it will keep a default client pointing to each of the given APIAddrs. The logic of this is mostly around choosing which client to use.

**Comment by DarkBlaez** [comment]
Fundamentally, load balancing should be done external to ipfs-cluster. There is absolutely no reason to put any level of lad balancing within the software. This can easily be handled external. Remember even Kubernetes will balance across POD instances if this is spun up in such. API calls to any node in the cluster could be fronted with a load balancer using any number of methods.

-DB

**Comment by hsanjuan** [comment]
I absolutely would not want to have to throw nginx or let alone kubernetes where a client can just be aware of different endpoints (via dnsaddr resolution) and repeat the requests on failure or simply select them at random.

Anyways this is supported already and joins the list of features that you can easily handle externally (ssl cert config, basic auth) but are still part of the code because they ratio of convenience vs complexity is very good for many actual use cases. No one is forced to use it though.
