### ISSUE TITLE
Support PinPath, UnpinPath (resolve before pinning)

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#450]
#### Basic information

* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement

#### Description

Currently, Cluster operates on CIDs. `Pin()`, `Unpin()` work given a CID, but not given a path like `/ipfs/<hash>/something/else`, or `/ipns/something`.

The main component should provide `PinPath` and `UnpinPath` at least, and resolution to obtain the CID should happen via the IPFS daemon (ipfs connector component).

Thus, we'd have `func PinPath(path string, p api.Pin) error` and `func UnpinPath(path string`)`.

The only thing these functions would do is to resolve the path to a *cid.Cid and call the original functions. Resolving requires modifying the IPFSConnector interface and implementation with a new method.

---
The second part of this PR is to support path-pinning and unpinning in the `api/rest` component, the `api/rest/client` and have `ipfs-cluster-ctl pin add` and `pin rm` take paths just as they take Cids.

The `POST /pins/{hash}` endpoint is used to Pin a Cid. Perhaps it is worth to implement path-pinning by supporting `POST /pins/ipfs/<path>` and `POST /pins/ipns/path`. Same for Unpin (`DELETE`).

The `api/rest` route handler should realize and call `Pin` (as now) or `PinPath` (a new rpc method), as needed.

Note that https://godoc.org/github.com/ipfs/go-ipfs-path#ParsePath is here to help, and that we should use `IsJustAKey()` to shortcut paths like `/ipfs/<cid>` to a *cid.Cid directly, without needing to resolve those.

https://godoc.org/github.com/ipfs/ipfs-cluster/api#Pin

**Comment by cd10012** [comment]
Hi sorry if this is a bit of a naive question, but I am having a tough time figuring out how to call `Pin()`and `UnPin()` w/ the parameters I have. Do I need to make an RPC call inside `PinPath`? It seems like that would be handled by those functions instead...

Also what should I do with the file path? I'm assuming this will be needed for the REST request. Thanks in advance 🙌

**Comment by hsanjuan** [comment]
hey @cd10012 , I will explain in the PR, it's easier.

**Comment by kishansagathiya** [comment]
@hsanjuan 
> Thus, we'd have func PinPath(path string, p api.Pin) error and func UnpinPath(path string)`.

is `api.Pin` a mistake ?

don't you need something like this
```
	PinPath(ctx context.Context, path string, int) error
	UnpinPath(ctx context.Context, path string) error
```

**Comment by kishansagathiya** [comment]
> ipfs-cluster-ctl pin add and pin rm take paths just as they take Cids.

**Comment by hsanjuan** [comment]
> @hsanjuan
> 
> > Thus, we'd have func PinPath(path string, p api.Pin) error and func UnpinPath(path string)`.
> 
> is `api.Pin` a mistake ?
> 
> don't you need something like this
> 
> ```
> 	PinPath(ctx context.Context, path string, int) error
> 	UnpinPath(ctx context.Context, path string) error
> ```

We use `api.Pin` as a wrapper for multiple pin options (replication factors, allocations, name etc.). You can see it as `opts api.Pin` if you prefer.

**Comment by hsanjuan** [comment]
> > ipfs-cluster-ctl pin add and pin rm take paths just as they take Cids.
> 
> Without any option say `--path` ?

No, it should be the same passing a CID or path.

**Comment by kishansagathiya** [comment]
> We use api.Pin as a wrapper for multiple pin options (replication factors, allocations, name etc.). You can see it as opts api.Pin if you prefer.

Any reason we are not using that with Pin() in ipfs connector?

**Comment by kishansagathiya** [comment]
Also shouldn't we mix this with Pin() and Unpin() instead of
```
	PinPath(ctx context.Context, path string, int) error
	UnpinPath(ctx context.Context, path string) error
```
to keep things uniform with ipfs ?

**Comment by kishansagathiya** [comment]
I just realized that `ipfs pin` is capable of pinning and unpinning by accepting strings. However just given an ipns hash it can't, which shouldn't be a problem given that there is no way to tell if a some hash in an ipns hash or not except by trying to resolve it.

**Comment by hsanjuan** [comment]
> > We use api.Pin as a wrapper for multiple pin options (replication factors, allocations, name etc.). You can see it as opts api.Pin if you prefer.
> 
> Any reason we are not using that with Pin() in ipfs connector?

Need for it has not arisen. But it can be changed if it does.

> Also shouldn't we mix this with Pin() and Unpin() instead of
> 
> ```
> 	PinPath(ctx context.Context, path string, int) error
> 	UnpinPath(ctx context.Context, path string) error
> ```
> 
> to keep things uniform with ipfs ?

Things will be uniform with IPFS at the user level. A path and a Cid are two very different things which deserve different handlers in the Go API imho. The REST API endpoint proposal above still sounds good to me.



> I just realized that `ipfs pin` is capable of pinning and unpinning by accepting strings. However just given an ipns hash it can't, which shouldn't be a problem given that there is no way to tell if a some hash in an ipns hash or not except by trying to resolve it.

That's because `ipfs pin` takes paths only (`/ipfs/Qmm..` or `/ipns/Qmm..`), with the convenience that non-prefixed items are assumed to be `/ipfs/`.

**Comment by kishansagathiya** [comment]
It doesn't seem like gorilla mux have way to add patterns like `/ipfs/<hash>/*`, I am gonna look for a while if nothing works out we can do the way go-ipfs has done by adding path in the query, like `/(ipfs|ipns)?arg=<path>`

@lanzafame do you have ideas on how to do this? We can probably put a function for route matching, but then it would be inconsistent as we have patterns for all other endpoints
