### ISSUE TITLE
Extract the IPFS Proxy from ipfshttp and make it an api module

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#453]
#### Basic information

* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [x] Enhancement

#### Description

The `ipfshttp` IPFSConnector implementation includes the so called IPFS Proxy. And endpoint which offers an IPFS API, hijacking some interesting requests and forwarding the rest to the ipfs daemon. This is, in essence, an API Component implementation for Cluster, but it is mixed with the IPFS Connector (whose only task should be to talk to ipfs).

So,

* The whole Proxy code should be moved to `api/ipfsproxy` and be just another Cluster API implementation.
* The new component will need the ipfs daemon location as part of its configuration. Note this option will be duplicate in the `ipfshttp` and `ipfsproxy` configuration sections.
* Related and needed along with this #452

**Comment by kishansagathiya** [comment]
@hsanjuan I have started working on this one.
Just to make sure if I am getting it right, after this change our configuration should look kinda like this,
```
"api": {
  "restapi": {
    "http_listen_multiaddress": "/ip4/127.0.0.1/tcp/9094",
    "read_timeout": "0s",
    "read_header_timeout": "5s",
    "write_timeout": "0s",
    "idle_timeout": "2m0s",
    "basic_auth_credentials": null
  },
  "ipfsproxy":{
    "proxy_listen_multiaddress": "/ip4/127.0.0.1/tcp/9095",
    "node_multiaddress": "/ip4/127.0.0.1/tcp/5001",
    "proxy_read_timeout": "0s",
    "proxy_read_header_timeout": "5s",
    "proxy_write_timeout": "0s",
    "proxy_idle_timeout": "1m0s",        
  }
},
"ipfs_connector": {
  "ipfshttp": {
    "node_multiaddress": "/ip4/127.0.0.1/tcp/5001",
    "connect_swarms_delay": "30s",
    "pin_method": "refs",
    "ipfs_request_timeout": "5m0s",
    "pin_timeout": "24h0m0s",
    "unpin_timeout": "3h0m0s"
  }
},
```
right?

**Comment by hsanjuan** [comment]
> Just to make sure if I am getting it right, after this change our configuration should look kinda like this,

correct
