### ISSUE TITLE
Notes on apis, adoption, and more.

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-cluster#479]
**important note to the reader**. I'm jotting some notes down here, mostly for myself to have for a discussion with @hsanjuan later. I don't have full context of what's been going on, sorry, so it may be that other issues go way in-depth into relevant reasonings here that I'm not familiar with yet. I wanted to write these first and put them here due to limited time. So please excuse mistakes, lack of understanding, etc.

---

**thinking about apis/adoption.** When deploying https://github.com/ipfs/ipfs-hubot -- @hsanjuan and i discussed how to get onto cluster. We discussed that: right now, ipfs-cluster's proxy ipfs-api does not support simultaneous pins (two pins block waiting for each other), nor labels (because ipfs api does not have pinset labels). that in the long run, ipfs-hubot should support cluster directly. this got me a bit concerned because ipfs-hubot should be a super simple tool and should not have to do anything extensive.  (of course, if hubot wants to also manage a cluster and do more stuff, that's definitely worth implementing cluster support for, but not just the simple "pin this path please" use case). anyway, I've been thinking about this, and thinking about how ipfs is getting used by a bunch of applications, and here is output from that thinking.

**lowest barrier adoption**. we should aim for the lowest possible barrier of adoption for cluster, and only ask users to enhance their understanding as necessary. This means that ideally most applications (most applications are very simple) should be able to transition from relying on a normal ipfs node to relying on an ipfs-cluster simply by changing the api endpoint. (i think this is already the case, just has some problems as discussed above).

**change api endpoint and done**, we should aim for ipfs-cluster adoption to be as easy as "change an api endpoint and done". of course, running and managing a cluster is much more work, but for the end user/developers, it shouldnt mean a lot more work re-building apps.

**minimize apis**. every additional api, and set of apis, creates significant burden on users and friction to adoption. This is because the impact of apis tends to be combinatoric, not linear (`n` different apis can combine in `n!` ways -- ofc not all valid, but it is cognitive load). this is really bad for (a) documentation needs, (b) client apis in `k` different languages, (c) user programs, (d) cognitive load on users. So, as much as we can, we should always seek to introduce the fewest apis we can for the widest set of users. of course, it is unavoidable to introduce more apis to expose more and more complex functionality to users, but in general users should be able to move from the extremely simple (very few apis) to more and more complex use cases (more apis, lower level things) as they need to.

**pinning api.** as much as possible, the pinning API for both tools should be the same -- this is one of those things where we want to keep adoption barriers low, and making one api that both tools follow is going to mean way less complexity for users long-term (of course, go-ipfs may not support some features, just the important thing is keeping one api, not making 2 different apis. 2 apis would create much confusion in user bases ("oh you gotta pin it this other way with cluster") -- same point as above)

**pinning api enhancements** naturally, ipfs-cluster will have much more creative pinning use cases, and will yield more product surface area to incorporate into the data structures and interfaces we want to use for pinning. So it is natural for ipfs-cluster to drive that fwd in ways go-ipfs and js-ipfs cannot. And it's also natural and ok for some features to not work in non-cluster ipfs. that should be an ehancement/extension of the api, not a separate api.

**simultaneous pinning.** go-ipfs (and js-ipfs) should support simultaneous pinning. im not sure why it doesn't. this may be a bug, or an enhancement. this shouldnt be that hard to do.

**pinset labels.** Sidenote on labels: pinset labels are awesome and should be supported by go-ipfs too long-term. there's probably a bunch of pinset api things that will become clear through cluster and not go-ipfs, and should really be supported by both.

**separating pinning api?.** it may be worth separating the pinning code out of go-ipfs and create a common interfaces both tools expose. It may be that go-ipfs errors out in some cases.

**dev meetings.** These are perfect things to discuss at the berlin dev meetings and align everybody -- i think we can surface all the necessary context and discuss in high bandwidth and make decisions together quickly.

**keeping dev velocity high**. all this said, it is important to keep dev velocity high and not make it hard for ipfs-cluster to experiment by piping any interesting ideas or experiments through some kind of agreement process with go-ipfs. I think the right way to walk this line is to keep experimenting with cluster, just aim for things to bubble up into "the pinning api" (one), and features can be marked as experiments or "may change soon" until they're decided on.

**Comment by hsanjuan** [comment]
Closing this. Discussion clarified that the proxy endpoint works as expected and facilitates easy adoption and the pinbot was deployed correctly using it. We have a milestone gathering proxy issues https://github.com/ipfs/ipfs-cluster/milestone/19, that can be used to track progress on this front.
