### ISSUE TITLE
Proxy pin/unpin should resolve paths before cluster-pinning/unpinning

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#480]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement

#### Description

When we hijack the pin/add and pin/rm commands in the IPFS Proxy, we should resolve the argument, as it may well be a path and not a CID that cluster can pin.

This implies adding a method to resolve a path from IPFS in the `ipfshttp` component, investigating what errors are returned from IPFS pin/add and pin/rm when resolution fails and making sure we return the same.

**Comment by hsanjuan** [comment]
This can be on top of #450

**Comment by kishansagathiya** [comment]
Resolved by https://github.com/ipfs/ipfs-cluster/pull/690
