### ISSUE TITLE
Pin expiration

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#481]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement

#### Description

IPFS Cluster could automatically expire Pins given an expiring date, associated to the Pin. The pinset could be watched regularly and unpins triggered for expired items.

This would probably be a feature of the main component, as pin parameters are handled from there. It would imply storing expiry dates associated to Pins in the state.

Note, unpinning from cluster would just mean that content in the IPFS nodes can be garbage collected, but not that the content will stop being available from the network (if it has been fetched from somewhere else).

**Comment by jmank88** [comment]
I am interested in working on this feature. I haven't explored the code enough yet. Any tips on where to start? Or ideas about how the commands should work? e.g. some sort of `--expire` flag for `add` and `pin add` seems like a no-brainer, but should `pin ls --filter` understand expirations? Should `ls status` include expirations by default?

**Comment by hsanjuan** [comment]
Should we keep expired pins around (in the cluster state in an `EXPIRED` state), or should we just have them disappear after expiration. The latter is simpler. There is a `StateSync` function in `cluster.go` that gets triggered regularly (every `cfg.StateSyncInterval`) and loops all pins in the state. This function seems like the most straightforward place to check if a pin has expired and trigger an unpin for it.

This would mean that pins are removed at most <StateSyncInterval>-minutes after they have expired. I don't think it's a strong requirement for people that pins are removed exactly at the moment they expire (but this could be improved in the future).

The `PinOptions` type would need to be extended with an `Expire time.Time` field, including the protobuf version of it (an `int64` would work I guess).

If pins are simply unpinned, there is no more to do. If they are to be kept in `expired` state, then the pintracker should handle this new PinStatus (similar to the `remote` one).

Does this help?

**Comment by jmank88** [comment]
> Does this help?

Yes, thank you. I'll start hacking.

**Comment by jmank88** [comment]
Is there a `go:generate` command or something to regenerate `api/pb/types.pb.go` that I am overlooking?

**Comment by hsanjuan** [comment]
> Is there a `go:generate` command or something to regenerate `api/pb/types.pb.go` that I am overlooking?
> 
> Edit: I added a `//go:generate protoc --go_out=. types.proto`

good idea, i just ran it manually but this is much better.
