### ISSUE TITLE
Move `ipfs-cluster-service` and `ipfs-cluster-ctl` to `cmd/`

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#485]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement

#### Description
Move `ipfs-cluster-service` and `ipfs-cluster-ctl` to `cmd/` directory to follow "standard" project structure.

**Comment by kishansagathiya** [comment]
@lanzafame I have tried to attempt this issue with https://github.com/ipfs/ipfs-cluster/pull/521. Plz review whenever you find time.

**Comment by hsanjuan** [comment]
Fixed by #521 #556
