### ISSUE TITLE
Peer allocation strategies: Disk-space Informer and Allocator and other strategies

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#49]
The replication factor feature (#46) is ready (as described in the [Captain's log](CAPTAIN.LOG.md)). This adds the possibility of adding different pinning strategies.

Currently we only have a dummy [`numpin`](https://godoc.org/github.com/ipfs/ipfs-cluster/informer/numpin) Informer and a [`numpinalloc`](https://godoc.org/github.com/ipfs/ipfs-cluster/allocator/numpinalloc) PinAllocator for it.

It would be really useful to have other informers, which fetch different metrics, and other allocators which implement different strategies, for example a disk-space metric and allocator.

They just need to implement the [`Informer` interface](https://godoc.org/github.com/ipfs/ipfs-cluster#Informer) and the [`Allocator` interface](https://godoc.org/github.com/ipfs/ipfs-cluster#PinAllocator) respectively. The existing examples show how this is done in a simple way.

**Comment by hsanjuan** [comment]
@20zinnm you were looking for ways to contribute? Would you like to take at stab at this? It is a good starting point to get familiar with Cluster.

**Comment by 20zinnm** [comment]
I can take a look at it @hsanjuan.

**Comment by 20zinnm** [comment]
@hsanjuan To be clear, does creating a new Informer/Allocator include implementing it, or can clusters deal with incompatibilities?

**Comment by 20zinnm** [comment]
Also, I think we need to clean up the project layout.

**Comment by hsanjuan** [comment]
@20zinnm What do you mean incompatibilities?

And yes, creating means implementing it.

**Comment by 20zinnm** [comment]
So what, exactly, do I need to implement?
I followed the chain and figured I needed to update (a) the rpc, (b) the HTTP server. Am I missing something? @hsanjuan

**Comment by hsanjuan** [comment]
@20zinnm no, you just need create two modules, one Allocator and one Informer which implement the respective interfaces as the `numpinalloc` and `numpin` do. You don't need to worry about anything else in Cluster. Everything is linked above. These modules should cluster to work with a disk-space allocation strategy which would pin to the peers with more free space.

**Comment by 20zinnm** [comment]
@hsanjuan So say I'd like to make a `capacity` informer to allow peers to broadcast a quantifiable capacity. Would I then need to add to the protocol?

**Comment by hsanjuan** [comment]
@20zinnm you just need to implement the informer and the allocator. The informer has a `GetMetric()` method which gets regularly called.
