### ISSUE TITLE
Upgrading and backups

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#51]
There are a number of pain points if the consensus state format changes upon an upgrade.

Currently, persistence is obtained via Raft snapshots which are loaded on boot and written on shutdown (at least). Raft snapshots format is coming from `go-libp2p-raft` FSMSnapshot implementation, which is just a serialization of the state using msgpack.

If the state changes, loading the snapshot is likely to break. Also, this format is unreadable to the user and hard to work with.

A few thoughts about tackling this:

* [x] ipfs-cluster should store a readable, easy to work with, json backup of the state on shutdown. [DONE]
* [ ] There should be a pain-free procedure (at the very least documented) to load and old backup onto a newer `State` (a migration). This is potentially tricky on a large cluster:
  * Raft snapshots need to be removed [manually?] or Raft will attempt deserializing them on top of a newer version of the state.
  * Raft may also replay log entries on boot, which does not make sense if snapshots have been removed, so probably all Raft data needs to be cleaned up upon upgrade.
  * If Raft starts with a clean state after an upgrade, the new state could load the old backup and migrate it to the new format. With that state, we could directly run a rollback operation (which replaces the whole clean Raft state with the migrated version). However `go-libp2p-consensus` rollbacks are not very specific and this would work only because it's the way `go-libp2p-raft` does it at the moment.
  * An alternative it is to let cluster replay and commit every entry on the old state. This might be slightly cleaner. Replaying would need to make sure allocations remain the same as in the imported state.

**Comment by ZenGround0** [comment]
I am comfortable adding this feature as a subcommand of ipfs-cluster-ctl ex: `ipfs-cluster-ctl migrate`, at least for now.  go-ipfs has a separate tool for this downloaded on the fly, but apparently this is to keep the binary size down (see screenshot) which I don't see as an issue with adding this functionality to ipfs-cluster.

![screen shot 2017-10-30 at 4 18 15 pm](https://user-images.githubusercontent.com/5515260/32193796-c6514518-bd8e-11e7-8a70-c756fa24e4df.png)
