### ISSUE TITLE
[enhancement/feature] - auto-repin

### ISSUE THREAD

**Issue by TroyWilson1** [ipfs/ipfs-cluster#516]
[enhancement/feature]

#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [x] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [x] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description
When adding an additional node to a ipfs-cluster-service it would be nice to have the option to do something like:
`$ ipfs-cluster-service daemon --join <bootstraper addr> --auto-re-pin`

This feature would simplify spinning up a new node and just start auto pinning all the content from the existing cluster nodes. This could cause a problem if your adding a node with less storage to an existing large cluster but, if your scaling up to a larger node this would be great help.  

  License: MIT
  Signed-off-by: Troy Wilson <troy@merchantguy.com>

**Comment by TroyWilson1** [comment]
[enhancement/feature]

**Comment by TroyWilson1** [comment]
enhancement/feature /lables

**Comment by TroyWilson1** [comment]
label:enhancement/feature

**Comment by hsanjuan** [comment]
It should be the case that, when content is pinned with replication factor -1 (pin everywhere), any new node joining will also pin the content.

**Comment by hsanjuan** [comment]
@TroyWilson1 I have checked in 0.5.0-rc1 and the behaviour is that a new joining node will automatically pin the content as you expect. This should also be the case in 0.4.0, unless there is a bug I'm unaware of.

I am assuming that your new peer correctly joined the cluster and that you got the `** IPFS Cluster is READY **` message when bootstrapping.

 When you say that the content is not pinned in the new peer, do you mean:

* ipfs-cluster-ctl status shows UNPINNED for the new peer? Or does it not show the new peer at all?
* Does running ipfs-cluster-ctl  in the new peer show the pin set correctly (with replication -1)?
* Something else?

**Comment by TroyWilson1** [comment]
I'm new to this so I think I did the join wrong. I just bootstrapped the new additional node to the cluster. I didn't use --join or anything like that on adding the second node. I think that may be why it didn't auto pin. What is the proper command to add a new node to an existing cluster that have items already pinned?

**Comment by hsanjuan** [comment]
I think `--join` is not even a flag. I guess you mean `--bootstrap` (or `-j`)/

You need to follow the steps as indicated here: https://cluster.ipfs.io/guides/quickstart/#step-1-add-new-members-to-the-cluster , with:

`ipfs-cluster-service daemon --bootstrap <your peer multiaddress>`

Your new peer should say it's ready and print a message about having joined the cluster, and the other peer should print a message about the new peer joining.

**Comment by TroyWilson1** [comment]
Ok, I did `ipfs-cluster-service daemon --bootstrap <your peer multiaddress>` to add the second peer to a cluster. After doing so I did a `ipfs-cluster-ctl status` and there were zero pinned content even though the first cluster node had content pinned before the bootstrap. My question/suggestion was to have a option when adding a new peer the pinned content would start auto-pinning to the second peer. Maybe that works when I add a third peer but, I have not seen it work with the first one and was looking for an option for auto-pinning to start.

**Comment by hsanjuan** [comment]
Hmm auto-pinning should just happen as you did it. You could test again by removing that peer: `ipfs-cluster-ctl peers rm <peerID>` and re-bootstrapping it just the same as you did (this will not touch the stuff pinned in ipfs).

How long did you wait before checking `status`? It is very weird that it came back empty. It would only explain it if it was still syncing the state not fully ready, but that should be matter of seconds. If this happens, I'd be interested in seeing any log messages during this process, particularly of the joining peer launched with `ipfs-cluster-service --loglevel debub daemon --bootstrap <>`.  I also would like to know if `ipfs-cluster-ctl pin ls` in the new peer also comes back empty.

**Comment by TroyWilson1** [comment]
I did the `ipfs-cluster-ctl peers rm <peerID>` waited a couple seconds and did a stats. Everything was pinned and good to go. I also did the debug bootstrap and everything looked normal with no errors. I guess auto-pinning works. I will have to try it again when I add the next peer to the cluster. I will keep you posted with any additional updates.
