### ISSUE TITLE
I use ipfs-cluster version 0.5.0 like that ：ipfs-cluster-ctl -l /ip4/10.58.10.92/tcp/9094 add ./hello.py ./service.json added QmXCcepqiWBmbH2EG6kubQwBpW8kxnoGmAxkngHXyqnryR hello.py added QmVBL6A2EECAtTEhS67rLD5khB1WEoek4cYeqdryc5kpjV service.json added QmeNCAKmjkcyfPKCk1Rhjq7V4ZmBn4uACgDVpFByrAo7H2 ，but the first file can not find in the cluster,second one can find in the cluster.And i use api , it is the same

### ISSUE THREAD

**Issue by tututt** [ipfs/ipfs-cluster#524]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

**Comment by lanzafame** [comment]
@tututt can you please edit the issue so the bug is in the description not the title?
