### ISSUE TITLE
ipfs-cluster-ctl add remain a bug

### ISSUE THREAD

**Issue by tututt** [ipfs/ipfs-cluster#525]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

when i use ipfs-cluster-ctl like this: 

`ipfs-cluster-ctl -l /ip4/10.58.10.92/tcp/9094 add ./nohup.out ./yum.repos.d.tar `

return that:

```
added QmaV9WtquNMVNu4441B4BuMJ85fpsyUS5hqTqr4dqJbFcj nohup.out
added QmWm7GVAVc7FGWekMsWoYxYtewfpTCLH4rfuvF7QXbmTrd yum.repos.d.tar
added QmRNZiJoPv9F4c7joxFbwmJ8EuVSxBqn7xK7NkWkfL9Njb 
```

but when i pin ls the first file cid,like that :

`ipfs-cluster-ctl -l /ip4/10.58.10.92/tcp/9094 pin ls QmaV9WtquNMVNu4441B4BuMJ85fpsyUS5hqTqr4dqJbFcj`
it returns:

```
An error occurred:
  Code: 404
  Message: cid is not part of the global state
```

At the same time,pinning the second file cid is the same.

I only can pin ls "QmRNZiJoPv9F4c7joxFbwmJ8EuVSxBqn7xK7NkWkfL9Njb".

**Comment by hsanjuan** [comment]
Hello, `QmRNZiJoPv9F4c7joxFbwmJ8EuVSxBqn7xK7NkWkfL9Njb` is the root hash for a folder with `nohup.out` and `yum.repos.d.tar` in it and it's pinned recursively.

If you'd like to pin the files separately, you should call `ipfs-cluster-ctl add` on each of them. Then you will be able to do `pin ls` on the Cids of each file as you expect.

**Comment by tututt** [comment]
@hsanjuan why is it designed like that, add more than one file, and the files will be on the same ipfs service?

**Comment by tututt** [comment]
@hsanjuan Another question, what the "Shard" in "AddParams" struct  do? Thanks for replying

**Comment by hsanjuan** [comment]
@tututt it's designed to be able to add multiple files and get a single IPFS root CID (so basically getting a folder).

The `Shard` parameter relates to the sharding feature and should not be used yet.

**Comment by hsanjuan** [comment]
@tututt it selects a number of peers (per the chosen replication factor) and adds directly to all of them, and then cluster-pins on them.

**Comment by tututt** [comment]
@hsanjuan Is the file stream send from the leader to other cluster peers? And what different from "ipfs-cluster-ctl pin add"（please reply by Code flow， because i am trying to use ipfs and ipfs-cluster 
 to do my program, thanks

**Comment by hsanjuan** [comment]
@tututt, no, the file stream is read in the local peer, chunked in the local peer and the resulting blocks are `BlockPut` to the allocated destinations.

This starts here:

https://github.com/ipfs/ipfs-cluster/blob/master/adder/adder.go#L84

and uses:

https://github.com/ipfs/ipfs-cluster/blob/master/adder/local/dag_service.go#L46

**Comment by tututt** [comment]
@hsanjuan I understood it ,thanks for help
