### ISSUE TITLE
Unformatted JSON returned while adding multiple files in IPFS cluster ADD REST API

### ISSUE THREAD

**Issue by aswin-ideas2it** [ipfs/ipfs-cluster#526]
In IPFS cluster 0.5, While adding multiple files in IPFS cluster through the new  ADD REST API endpoint,

/add?replication-min=<min_replication>&replication-max=<max_replication> 

An unformated JSON is returned,

Eg: 
{"code":0,"message":"","Name":"test1.jpg","Hash":"QmPxBet4MHo93b9nCE2FYRtDTowVA3bMRdDBZcYAiBkZKN","Size":"4696045"}
{"code":0,"message":"","Name":"test2.jpg","Hash":"QmfJ8fzLwCmuvxNG8RH41RmmjGzMrXw38pjP85EJSiXKJ4","Size":"4696045"}

It should have been an array of objects.

**Comment by hsanjuan** [comment]
Hi, this is not a bug (it's a feature). `/add` response is a streaming response and mimics what ipfs `/add` does (for the moment). Perhaps you'd like to turn this into a feature request asking to support a `stream=false` parameter and return a single complete json response, or something else, whatever your usecase is, and we'll consider it if there is good reasoning behind it.

**Comment by aswin-ideas2it** [comment]
Thanks @hsanjuan! I'll add that as a feature request.

**Comment by Elexy** [comment]
@aswin-ideas2it if you added the feature request, could you link it here? I tried searching and can't find it.

**Comment by hsanjuan** [comment]
@Elexy i don't remember having seen it but you can add it yourself :+1:
