### ISSUE TITLE
Unable to recover from "CLUSTER_ERROR: the state on this node is not consistent"

### ISSUE THREAD

**Issue by postables** [ipfs/ipfs-cluster#530]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

I have two IPFS nodes, each running IPFS, and IPFS Cluster. On one node I removed a pin, which triggered the error mentioned in the issue title. I've been unable to recover from this error, despite having pinned the item again both on IPFS, and IPFS cluster. I attempted running the recover command which gives me:

```
....:~$ ipfs-cluster-ctl recover --local QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
An error occurred:
  Code: 500
  Message: the state on this node is not consistent
```

Cluster Version: 0.5.0
IPFS Version: 0.4.17

**Comment by lanzafame** [comment]
@postables How did you remove the pin from just one peer? Does the pin appear in the output of `ipfs-cluster-ctl pin ls`? If so, try doing a `ipfs-cluster-ctl recover <cid>` without the `--local`.

**Comment by postables** [comment]
hey @lanzafame  thanks for the response. So I remove the pin via `ipfs pin rm .....` I stupidly forgot to enable the experimental pinset tracker in the latest IPFS Cluster release which uses IPFS to keep track of the pinset, so I did this to try out that new feature.

No it does not:
```
ipfs-node-1:~$ ipfs-cluster-ctl pin ls QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
An error occurred:
  Code: 404
  Message: the state on this node is not consistent
```

```
ipfs-node-2:/var/log/temporal$ ipfs-cluster-ctl pin ls QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
An error occurred:
  Code: 404
  Message: the state on this node is not consistent
```

```
ipfs-node-2:/var/log/temporal$ ipfs-cluster-ctl recover  QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv :
    > Peer QmWBChgkvjcfs7fZCFTqC4B6u3ZiL4HSTS7qimdDhLb8zK : PINNED | 2018-09-07T23:36:47Z
    > Peer Qmdnjprxk2RxcfxW2bpMW165xjhFYaCZsVwi64xrRnHnBh : PINNED | 2018-09-08T05:11:45Z
ipfs-node-2:/var/log/temporal$ ipfs-cluster-ctl pin ls QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
An error occurred:
  Code: 404
  Message: the state on this node is not consistent
```

**Comment by hsanjuan** [comment]
@postables you should not attempt to unpin things in cluster with ipfs. That's not what the stateless pintracker does, sorry if there is confusion in that regard.The stateless tracker is just a memory optimization over the default one.

That said, your error is unrelated. Your error comes from a bad state format in raft. I am not sure you you got there though. I suggest you re-bootstrap `ipfs-node-2` cluster peer to your other one (`ipfs-cluster-service daemon --bootstrap <ipfs-cluster-node-1-multiaddr>`. This should re-initialize the state.

**Comment by postables** [comment]
@hsanjuan No worries that's quite alright, i won't do that again. Is it possible for the raft state to permanently become corrupted? I shutdown ipfs cluster on `ipfs-node-2` and did a state clean up using:
`ipfs-cluster-service state cleanup`. After that was running I attempted to bootstrap to `ipfs-node-1`, which unfortunately still lead to the same error.

I then shutdown ipfs cluster on `ipfs-node-1` and repeated the same steps i did on `ipfs-node-2` which unfortunately still lead to the same issue.

**Comment by hsanjuan** [comment]
@postables what do the logs say? There should be an `error decoding op` or an `error applying Op to State`.

Boostrapping automatically cleans your state so you don't need to do that separately. Try running the `state export` and `state import` procedure as shown here: https://cluster.ipfs.io/documentation/upgrades/#troubleshooting-upgrades

Note that since you have cleaned up your state in both of your peers now, you may have to rename the backup folder which actually contained the original pinset.

I am not sure what's causing your state to become `inconsistent`, maybe it's a corrupted op in the raft log. Full logs from peer start to getting one of those error messages would be very valuable.

**Comment by postables** [comment]
Sorry for the late reply! I've attached a copy of the logs here: https://ipfs.io/ipfs/QmabZQF7PNs3wV5iFsbynN93vMKiqqgtyHYpThQihRvNWH

**Comment by hsanjuan** [comment]
Hey, I believe we've merged a logging improvement that will log exactly what cannot be decoded here:

`[0;37m18:48:24.905 [31mERROR [0;34mlibp2p-raf: [0merror decoding op: [pos 9]: no matching struct field found when decoding stream map with key Cid [0;37mfsm.go:72[0m`

I think that Raft is trying to apply log entries which cannot be deserialized into the state Operation type (did this start after an `state upgrade`?). It's very weird. Anyway there should be sligthly more information if this ever happens again after the next release.

**Comment by postables** [comment]
Awesome, I'll monitor my logs after the next upgrade and see if this issue no longer presents itself. Thanks.

**Comment by hsanjuan** [comment]
I will close this for the moment. Re-open if new information comes up. I think the raft log on that peer got corrupted somehow.
