### ISSUE TITLE
Update to new Cid type

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#535]
#### Basic information

* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [x] Enhancement

#### Description
go-cid v1.0.0 has moved the cid type from being backed by a `struct{ string, string, multihash }` to a `struct{ string }`. This has performance benefits which cluster would benefit from, especially the mappintracker.

The PR for this change will be merged within the week, see https://github.com/ipfs/go-cid/pull/71

**Comment by hsanjuan** [comment]
Fixed by #544
