### ISSUE TITLE
Add `make prcheck`

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#536]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [x] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description
Going through a Travis run I see that we do the following
```
make deps
make check
make service
make ctl
make test
```

It would be nice to have a single make target that I can run and check if I am ready to push my PR, say `make prcheck`

**Comment by hsanjuan** [comment]
also `make test_sharness`. Sounds good to me if you want to take a stab at this.

**Comment by kishansagathiya** [comment]
I believe we would need to run `make install` as well before `make test_sharness`, otherwise tests would be running for whatever the version that is currently installed.
