### ISSUE TITLE
build project error

### ISSUE THREAD

**Issue by tututt** [ipfs/ipfs-cluster#539]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [ ] Linux
  * [x] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

I build ipfs-cluster:
go into ipfs-cluster folder,and "make all",then meet that "# github.com/ipfs/ipfs-cluster/api
../../go/src/github.com/ipfs/ipfs-cluster/api/types.go:191:6: cannot use c (type cid.Cid) as type *cid.Cid in field value
../../go/src/github.com/ipfs/ipfs-cluster/api/types.go:258:6: cannot use c (type cid.Cid) as type *cid.Cid in field value
../../go/src/github.com/ipfs/ipfs-cluster/api/types.go:805:12: cannot assign cid.Cid to ref (type *cid.Cid) in multiple assignment
../../go/src/github.com/ipfs/ipfs-cluster/api/types.go:812:6: cannot use c (type cid.Cid) as type *cid.Cid in field value"
and  go to "go-cid" project , find that type mismatch，i think go-cid version is run. How to do with it

**Comment by hsanjuan** [comment]
Please read the documentation: https://cluster.ipfs.io/documentation/download/#installing-from-source .You should run `make install` or `make build`. `make all` assumes your dependencies are rewritten already.

**Comment by hsanjuan** [comment]
Sorry, I was too harsh here. `make all` should not fail like this and it's not very nice that it does. We'll fix it!

**Comment by tututt** [comment]
@hsanjuan，i have a suggestion, it is better to use package which same as the package on github.

**Comment by hsanjuan** [comment]
@tututt what do you mean?

**Comment by tututt** [comment]
@hsanjuan Now in ipfs-cluster project, it import package like this: ""github.com/ipfs/go-ipfs-cmdkit/files"", after "make install", it change to "manet "gx/ipfs/QmV6FjemM1K8oXjrvuq3wuVWWoU2TLDPmNnKrxHzY3v6Ai/go-multiaddr-net". Why use the first one package

**Comment by hsanjuan** [comment]
@tututt we use [gx](github.com/whyrusleeping/gx) to fix our dependencies. Gx works by rewriting import paths to those of the fixed dependency. go-ipfs-cmdkit will be rewritten into something else, and probably placed in a different line as before (because of gofmt).

This allows to be sure that the project can always be built. Something that does not always work without rewriting (like right now, because how the `cid` package changed upstream).

**Comment by tututt** [comment]
@hsanjuan OK， I see

**Comment by kishansagathiya** [comment]
Resolved with https://github.com/ipfs/ipfs-cluster/commit/a6111908e9f50e9b9d452f9559e04110264d9214
