### ISSUE TITLE
IPFS Private Network and data Replication (Private Network against IPFS Cluster)

### ISSUE THREAD

**Issue by mike-ngu** [ipfs/ipfs-cluster#541]
Hello Permanent Community!

I'm working on the project where I need to deploy Private IPFS network and automaticly replicate data beetwen all participant nodes.

And I little bit confused should I use Private Network or IPFS Cluster or their combination?
 
Private network allow me to isolate my nodes from IPFS public network but it doesn't replicate data and the only way I see to implement that it manualy(or with some script) pin hash of the file to/from all nodes.

In it's turn ipfs-cluster allows me to replicate data but it does not isolate my network from public gateway....

So how can I combine this two features or what the best way to build Private Network with data replication?

And my second question in case of using IPFS Cluster how can I interact with the network from my NodeJS app?
Can I use "ipfs-api" module to interact with ipfs-cluster network?
Should I use for example "ipfs-cluster-ctl add myfile.txt" or "ipfs add myfile.txt" and what's the difference between them in this case?

Thanks in Advance!

**Comment by lanzafame** [comment]
Hi @mike-ngu, you need to use a combination of a private IPFS network and IPFS Cluster. 

Each IPFS Cluster peer communicates with a local ipfs daemon. If that daemon is connected to the public network then files pinned via ipfs-cluster will be available on the public ipfs network. If the daemon is connected to a **private** network then files pinned via ipfs-cluster will **not** be available on the public ipfs network.

To interact with ipfs-cluster, I suggest the HTTP API outlined [here](http://127.0.0.1:8080/ipns/cluster.ipfs.io/developer/api/) and in more detail [here](https://godoc.org/github.com/ipfs/ipfs-cluster/api/rest/client). 

> Should I use for example "ipfs-cluster-ctl add myfile.txt" or "ipfs add myfile.txt" and what's the difference between them in this case?

`ipfs-cluster-ctl add myfile.txt` does the same job as `ipfs add myfile.txt` plus it then pins `myfile.txt` to ipfs-cluster. If the file you want to pin to ipfs-cluster is already on ipfs, i.e. you already have the files cid(hash), then you want to use `ipfs-cluster-ctl pin add <cid>` or via the HTTP API, it would be a `POST` request to  `<ipfs-cluster-addr>:9094/pins/{cid}`.

Hopefully, that answers your questions.

**Comment by hsanjuan** [comment]
Hello @mike-ngu , please  avoid posting duplicates. I'm closing this in favour of:

https://discuss.ipfs.io/t/ipfs-private-network-and-data-replication-private-network-against-ipfs-cluster/3865/2

**Comment by mike-ngu** [comment]
Thank you @lanzafame for your answer, you helped me find the missing puzzle)

**Comment by mike-ngu** [comment]
Hi @hsanjuan, I'm sorry for duplicates
