### ISSUE TITLE
BlockAllocate rpc returns all peers when replication factor -1 but should return healthy ones only

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#543]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement

#### Description

The bug is here: https://github.com/ipfs/ipfs-cluster/blob/master/rpc_api.go#L205

When the adder allocates and replication factor is `-1`, we return all cluster peers. This ends up having the adder try to put blocks to peers which are down. We should use `LatestMetrics` instead from the monitor, with the "ping" metric type. And return the peerset extracted from those metrics (which are valid cluster peers).

**Comment by mike-ngu** [comment]
Hi guys!

Could you tell me please when are you planning to fix this bug and what I need to do to apply this updates?

If I not mistaken current version of IPFS is v0.4.17 and ipfs-cluster-service is version 0.5.0.
Does this mean that I have to wait until the next release to have this updates in my IPFS package?

**Comment by mike-ngu** [comment]
can't wait to test it

Thank you!

**Comment by hsanjuan** [comment]
Hello @mike-ngu , the a release candidate with this fix is available here: https://dist.ipfs.io/ipfs-cluster-service/

**Comment by mike-ngu** [comment]
Hello @hsanjuan,

Thank you for notification.

Just to clarify, to get last bug fixing I need to install `ipfs-cluster-service` package with version `v0.6.0-rc1` ?

**Comment by hsanjuan** [comment]
yes, correct
