### ISSUE TITLE
API to Upload, Read and Get Size

### ISSUE THREAD

**Issue by narayanprusty** [ipfs/ipfs-cluster#545]
There is no REST API to upload a file. I want to create a webpage where users can upload a file and in backend I can store it in ipfs-cluster and pin it.

Also there is no API to read a file or get size of a file. I want to display these info on the page.

**Comment by lanzafame** [comment]
> There is no REST API to upload a file. I want to create a webpage where users can upload a file and in backend I can store it in ipfs-cluster and pin it.

You are looking for the [`/add`](cluster.ipfs.io/developer/api/) endpoint. 

> Also there is no API to read a file or get size of a file. I want to display these info on the page.

IPFS Cluster proxies the IPFS daemon's HTTP API, so if you want to hit any of the IPFS API endpoints via cluster, make your http requests against `/ip4/127.0.0.1/tcp/9095` (default address; see `ipfs_connector.ipfshttp.proxy_listen_multiaddress` for what it is for your current cluster or if you want to change it.).
