### ISSUE TITLE
Put ipfs-cluster in dist.ipfs.io

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#55]
Let users download and install it easily.

**Comment by Kubuxu** [comment]
Maybe it would be more fitting to introduce it to jenkins and store artifacts there? dist.ipfs.io is slow to prep, build and update. If development of ipfs-claster will be as rapid it was, version on the dist page will be always outdated.

**Comment by hsanjuan** [comment]
@Kubuxu It's a good point, but it should be ok to release cluster with same cadence as go-ipfs, and dist.ipfs.io offers better UX than sending a user to jenkins (i.e. for automated deployments which already grab go-ipfs and could grab cluster in the same fashion). I will make sure that there is a note saying these are experimental builds and that the latest version can be built manually.

**Comment by hsanjuan** [comment]
It's done, https://github.com/ipfs/infrastructure/issues/258
