### ISSUE TITLE
IPFS proxy should handle /add requets and pin the added items in cluster

### ISSUE THREAD

**Issue by bgadmin** [ipfs/ipfs-cluster#57]
It would be great to have option for auto pinning objects that are added/pinned with ipfs daemon.

Steps: 
- ipfs add
- ipfs pin
- ipfs-cluster auto pins and therefore all items are propagated automatically

**Comment by hsanjuan** [comment]
@bgadmin ipfs cluster runs an ipfs API proxy which intercepts pin/unpin/pin ls requests.

The ipfs tool uses the ipfs HTTP API when running commands and the daemon is running. So if you use the `ipfs --api <cluster proxy url> pin add` or simply swap the ports and run cluster proxy on port 5001 (and the ipfs daemon somewhere else), what you want should just work.

**Comment by bgadmin** [comment]
OK thanks, this changes things, however, if I add items to ipfs daemon remotely over daemons API, how can I do what you mentioned with cluster?

Basically I would like to  call "add" API to add item to ipfs and propagate that to all cluster nodes.

As I understand pin add only pins items that are already in ipfs, correct me if I'm wrong.

Scenario: application receives request to  add object to remote ipfs node, app adds item over API and then it should propagate to other nodes with clusters pin.

So far I understand that IPFS cluster can only pin objects that are already in ipfs network, so the first add command/API should be issues with daemon and then pinned with cluster.

Thanks!

**Comment by hsanjuan** [comment]
@bgadmin `ipfs-cluster-ctl pin add $HASH`==`<GET ipfs_proxy/api/pin/add?arg=HASH`>==`<POST cluster_api/pin/$HASH>`. 

All these do a "cluster pin" and will eventually trigger an `ipfs pin add` operation. When you do `ipfs pin add`, downloads the content if its not added locally and pins it. So I think this would work as you expect. You just need to make your API calls to the proxy provided by IPFS cluster or to the IPFS Cluster API directly.

If it is the first time you are adding content (thus it cannot be downloaded from somewhere else), you can use the proxy offered by cluster to do the normal `ipfs add` (that will be just forwarded to the local ipfs daemon) and then pin (will be pinned in the cluster). Only the pin add/rm/ls operations are intercepted by cluster, the rest are transparently forwarded.

**Comment by jbenet** [comment]
@hsanjuan i think @bgadmin means they want to do:

```
ipfs add <file-or-content>
ipfs-cluster pin <hash-from-above>
```

Does 

```
ipfs --api=<ipfs-cluster-node> add <file-or-content>
```
work?

**Comment by hsanjuan** [comment]
ah, makes sense now of course... No that doesn't work. But it can be done rather easily and it's a good feature.

**Comment by bgadmin** [comment]
@jbenet @hsanjuan 
It would be nice to have command that add new objects and pins it across cluster :+1:

**Comment by bgadmin** [comment]
Hey @jbenet @hsanjuan just dropping by to ask how is it going with this issue? :)

**Comment by hsanjuan** [comment]
I've had no time to do this. As a workaround, you can `pin add` after adding.

**Comment by hsanjuan** [comment]
@bgadmin with some luck I can do this tomorrow

**Comment by bgadmin** [comment]
@hsanjuan it would be awesome :+1:

**Comment by hsanjuan** [comment]
@bgadmin it's in master. Can you try it out?

**Comment by bgadmin** [comment]
@hsanjuan yes sure, what is the command?

**Comment by hsanjuan** [comment]
`ipfs --api <clusteripfsproxy multiaddress> add <whatever>`

**Comment by bgadmin** [comment]
@hsanjuan 

This is error I'm getting:

ubuntu@le-prod-ipfs:[~]>ipfs --api /ip4/127.0.0.1/tcp/9095 add janbofajl 
goroutine 1 [running]:
runtime/debug.Stack(0xc4204efb90, 0xb400000000410dc2, 0x1)
	/home/whyrusleeping/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/home/whyrusleeping/go/src/runtime/debug/stack.go:16 +0x22
gx/ipfs/QmZuY8aV7zbNXVy6DyN9SmnuH3o9nG852F4aTiSBpts8d1/go-ipfs-util.ErrCast(0xc4204cb960, 0xca74a0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZuY8aV7zbNXVy6DyN9SmnuH3o9nG852F4aTiSBpts8d1/go-ipfs-util/util.go:37 +0x20
github.com/ipfs/go-ipfs/core/commands.glob..func7(0x1346f00, 0xc420018240, 0x13462e0, 0xc4204cb960)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:281 +0xde3
main.callCommand(0x133e520, 0xc4204c3940, 0x1346f00, 0xc420018240, 0x1435f60, 0x1410720, 0x0, 0x0, 0xbb74e7, 0xc4204efeb8)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:358 +0x4f8
main.(*cmdInvocation).Run(0xc4204c3840, 0x133e520, 0xc4204c3940, 0x1334360, 0xc4203301c0, 0x133e520, 0xc4204c3940)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:195 +0x116
main.mainRet(0x0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:160 +0x374
main.main()
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:67 +0x22
Error: cast error

**Comment by bgadmin** [comment]
@hsanjuan This is the error I'm getting when trying to add file:

ubuntu@le-prod-ipfs:[~]>ipfs --api /ip4/127.0.0.1/tcp/9095 add janbofajl 
goroutine 1 [running]:
runtime/debug.Stack(0xc4204efb90, 0xb400000000410dc2, 0x1)
	/home/whyrusleeping/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/home/whyrusleeping/go/src/runtime/debug/stack.go:16 +0x22
gx/ipfs/QmZuY8aV7zbNXVy6DyN9SmnuH3o9nG852F4aTiSBpts8d1/go-ipfs-util.ErrCast(0xc4204cb960, 0xca74a0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZuY8aV7zbNXVy6DyN9SmnuH3o9nG852F4aTiSBpts8d1/go-ipfs-util/util.go:37 +0x20
github.com/ipfs/go-ipfs/core/commands.glob..func7(0x1346f00, 0xc420018240, 0x13462e0, 0xc4204cb960)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:281 +0xde3
main.callCommand(0x133e520, 0xc4204c3940, 0x1346f00, 0xc420018240, 0x1435f60, 0x1410720, 0x0, 0x0, 0xbb74e7, 0xc4204efeb8)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:358 +0x4f8
main.(*cmdInvocation).Run(0xc4204c3840, 0x133e520, 0xc4204c3940, 0x1334360, 0xc4203301c0, 0x133e520, 0xc4204c3940)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:195 +0x116
main.mainRet(0x0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:160 +0x374
main.main()
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:67 +0x22
Error: cast error

**Comment by hsanjuan** [comment]
@bgadmin are you using the latest version from master? I'm pretty sure this happened on versions before the merge.

**Comment by bgadmin** [comment]
@hsanjuan well, I deleted whole cluster and downloaded from the start, this is my version:

ipfs-cluster-ctl version 0.0.5

**Comment by bgadmin** [comment]
@hsanjuan  Sorry my bad forgot to switch executables...

**Comment by bgadmin** [comment]
@hsanjuan  Tested it, seems ok, thanks !!! :+1:

**Comment by hsanjuan** [comment]
great @bgadmin thanks!
