### ISSUE TITLE
HTTP API: Logging

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#574]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [x] Enhancement

#### Description

Our HTTP API currently does not do any logging that includes request, return codes, duration etc... (webserver-like). We should enable this just like any other webserver. We should also have a way to log, in the case of authorized requests (with basic auth), which requests were performed by which user.

We likely want these logs to be specific to the API component and have them written out separately from the usual output, and stored somewhere (`/var/log/ipfs-cluster`?).

To discuss:

* Where to put these logs (if anywhere)
* If this should be enabled by default
* If this compels us to start using https://echo.labstack.com/ (and rewriting the API with it?)

cc. @lanzafame

**Comment by lanzafame** [comment]
@hsanjuan I don't understand the jump to using echo from needing a single
place to put logs

**Comment by koalalorenzo** [comment]
my 2 cents that maybe can help: echo is not really needed for what they have, sometimes using a framework is more painful than actually just integrating with the "lower level" api of go.

I am using a lot https://github.com/Sirupsen/logrus with some custom variables that are enabling different kind of logs and customisation to print to stdout vs stderr etc etc

**Comment by hsanjuan** [comment]
echo makes it super easy to add logging and some other things that are useful in APIs (auth, cors etc), but I'm happy not using it too.

**Comment by hsanjuan** [comment]
discussion

**Comment by hsanjuan** [comment]
Actionables here:

* A PR doing HTTP request logging for every request. By default printing them as DEBUG in the normal logs. A configuration option allows to specify a file-name to print those to a file.

**Comment by kishansagathiya** [comment]
https://httpd.apache.org/docs/1.3/logs.html seems to be a good resource about how to do this. We could use Common Log Format mentioned there.

**Comment by kishansagathiya** [comment]
things that we would want to log loglevel(error, access), host, time, method, path, protocol, status, error, response size

**Comment by hsanjuan** [comment]
Please see and use https://www.gorillatoolkit.org/pkg/handlers#LoggingHandler

**Comment by hsanjuan** [comment]
Also the custom one: https://github.com/gorilla/handlers/blob/master/logging.go#L253
