### ISSUE TITLE
Can't install ipfs-cluster on Alibaba Cloud Server

### ISSUE THREAD

**Issue by mike-ngu** [ipfs/ipfs-cluster#577]
One of my IPFS node deployed on the Alibaba Cloud Server in the Chinese region and others two nodes on the AWS.

And it looks like Great Chinese Firewall blocking your domain/ip `https://dist.ipfs.io`

```
git clone https://github.com/ipfs/ipfs-cluster.git $GOPATH/src/github.com/ipfs/ipfs-cluster
cd $GOPATH/src/github.com/ipfs/ipfs-cluster
make install
```
It can't finish `make install` command during ipfs-cluster installation and download all dependencies/packages.

Do you have some mirror server or any idea how this issue can be fixed?

![1211122](https://user-images.githubusercontent.com/10459616/47010074-b6d30a00-d146-11e8-8b6c-e94392dbc489.jpg)

Thanks

**Comment by hsanjuan** [comment]
Backlink: https://discuss.ipfs.io/t/ipfs-cluster-stop-working-when-one-of-the-node-goes-off/3885/16

**Comment by hsanjuan** [comment]
So gx and gx-go are not pulled from ipfs directly when possible. This should partially fix this. I wonder if dns resolution for *ipfs.io is blocked in China though, or just the IPs. Then /ipns/dist.ipfs.io is something that may not work still. @mike-ngu do you know?

**Comment by godcong** [comment]
i alway local build then push file up to server...

**Comment by hsanjuan** [comment]
I will close this for now. We have pretty much dropped Gx support and use go-modules now.
