### ISSUE TITLE
pin.add errors when using ipfs-api

### ISSUE THREAD

**Issue by kenshyx** [ipfs/ipfs-cluster#582]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description
When I'm using the ipfs api proxy provided by ipfs-cluster I get this error:
```
node_modules/ipfs-api/src/pin/add.js:19
callback(null, res.Pins.map((hash) => ({ hash: hash })))
TypeError: Cannot read property 'map' of undefined
```
I can reproduce this error just for the latest release v0.6.0 `pin.add(hash, {recursive: true}, cb)`

**Comment by kenshyx** [comment]
This works without errors when using the default go-ipfs http api.

**Comment by hsanjuan** [comment]
Next release should come in about a week

**Comment by kenshyx** [comment]
Ok, I'm gonna close this, thanks!
