### ISSUE TITLE
Proposal to remove snapcraft builds from ipfs-cluster

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#593]
#### Basic information

* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [x] Enhancement

#### Description

Publishing snaps is a time sink for me due to their constant annoyances. Either builds break, or the credentials expire, or the store build requires manual approval, or, as now, they make us go and explain why we need `classic` confinement and after all the explanations they just don't seem to take action anyway (https://forum.snapcraft.io/t/classic-confinement-request-for-the-ipfs-cluster-snap/8056/8).

In the meantime, Travis is red. Actually we cannot even publish snaps on the `stable` channel from Travis because they only take `edge` when pushing from Travis, and they don't document any workaround. I am trying to setup their build pipeline but, it must be a joke, their DNS server is not there to resolve `ipfs.io`:

https://build.snapcraft.io/user/ipfs/ipfs-cluster/361367

We also have not much documentation about how to configure and nothing to orchestrate a snap cluster setup. Stats report 30 active devices for cluster: https://snapcraft.io/ipfs-cluster/metrics?period=6m

Ideally, we would hand this to a community member interested in maintaining this packaging format in a way that the Cluster team doesn't have to be fully commited to its maintenance, documentation and support.

@brianmcmichael you're the only person I can identify using snaps, please feel free to drop in your point of view here.

**Comment by brianmcmichael** [comment]
I'm ok with this. I was using the snap because it was mentioned in the documentation and they are generally pretty easy to set up, but in production I went ahead with the precompiled binaries due to the confinement and user account management issues.

Snaps are probably better suited to traditional single-user style desktop apps anyways.

**Comment by hsanjuan** [comment]
They finally approved the `classic` confinement. I'll leave the snap until it breaks next time. Then I'll remove it.
