### ISSUE TITLE
Remove `proxy_` and `Proxy` from proxy config

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#616]
Remove `proxy_` and `Proxy` from proxy config objects without breaking compatibility with previous revisions

https://github.com/ipfs/ipfs-cluster/pull/576#issuecomment-441028133

**Comment by kishansagathiya** [comment]
```
type jsonConfig struct {
	ProxyListenMultiaddress string `json:"proxy_listen_multiaddress"`
	NodeMultiaddress        string `json:"node_multiaddress"`
	ProxyReadTimeout        string `json:"proxy_read_timeout"`
	ProxyReadHeaderTimeout  string `json:"proxy_read_header_timeout"`
	ProxyWriteTimeout       string `json:"proxy_write_timeout"`
	ProxyIdleTimeout        string `json:"proxy_idle_timeout"`
}
```

We have two kinds of addresses here, one for proxy and on ipfs node address. When we have fields like `read_timeout`, one can figure out that it is for `listen_multiaddress`, but do you think that the current way (starting with `proxy_`) provides a better distinction?

**Comment by hsanjuan** [comment]
I'm happy removing all the Proxy prefixes
