### ISSUE TITLE
A script to start multiple cluster nodes

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#619]
Do we have a script to start multiple cluster nodes(that belongs to same cluster)? Something like would help in manually trying out if PR change works well

**Comment by kishansagathiya** [comment]
Cool, I am going try them out, thanks.

**Comment by hsanjuan** [comment]
It's just matter of using two configuration folders (`-c`) and changing the ports otherwise. I'm going to close this for the moment.  IRC is probably a better place for quick questions like this.
