### ISSUE TITLE
Add ability to run Garbage Collector(ipfs repo gc) on all peers

### ISSUE THREAD

**Issue by mike-ngu** [ipfs/ipfs-cluster#628]
Hi)

It will be very useful to have an ability run IPFS garbage collector through IPFS-Cluster API. 

https://discuss.ipfs.io/t/is-it-possible-to-completely-delete-file-from-the-cluster/4482/7

**Comment by 0zAND1z** [comment]
Hi @hsanjuan , I do not see a due date for the milestone Q1 2019 Easy here: https://github.com/ipfs/ipfs-cluster/milestone/20 .

Can you please provide clarity potential dates for closing this? 
Also, do you need help, if no one has picked it up yet?

**Comment by kishansagathiya** [comment]
> I do not see a due date for the milestone Q1 2019 Easy here: https://github.com/ipfs/ipfs-cluster/milestone/20
Can you please provide clarity potential dates for closing this?

Ideally, this was supposed to be done in Q1(before April 1, 2019)
If you are in need of this feature, I can prioritize it sooner and get it in next one or two weeks

> Also, do you need help, if no one has picked it up yet?

Based on tags, yup. So, feel free to pick it up.

**Comment by 0zAND1z** [comment]
>  If you are in need of this feature, I can prioritize it sooner and get it in next one or two weeks(hopefully)

Oh yeah, that's great.  


> Feel free to pick it up.

Sure thing, we can hangout on the IRC and follow up on this?

**Comment by kishansagathiya** [comment]
> Sure thing, we can hangout on the IRC and follow up on this?

Yup


I think this would require
- Adding a method for garbage collecting in IPFSConnector https://github.com/ipfs/ipfs-cluster/blob/94a781ef21b5dcfa68c138b624ff0e091c2df50e/ipfscluster.go#L68
https://docs.ipfs.io/reference/api/http/#api-v0-repo-gc
- An RPC method say IPFSRepoGC https://github.com/ipfs/ipfs-cluster/blob/master/rpc_api.go
- A cluster method that would make that RPC call on each peer node https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go
- A REST API for GC, which should be added to the api client as well
- And finally cli support in `ipfs-cluster-ctl`
- tests

@hsanjuan @lanzafame can you confirm this?

**Comment by 0zAND1z** [comment]
`$ ipfs-cluster-ctl peers gc`

I am adding a sub-command under the `peers`.

Is that okay?

**Comment by kishansagathiya** [comment]
@0zAND1z 
I don't think it should go in `peers gc`, but don't worry about the command just yet.
