### ISSUE TITLE
Can we store the cluster secret inside the key store ?

### ISSUE THREAD

**Issue by gedw99** [ipfs/ipfs-cluster#629]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x ] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [ x] Enhancement
* [x] Operating system (mark as appropiate):
  * [ ] Linux
  * [x ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

The secret by default is stored in ~/.ipfs-cluster/service.json and was created by the "ipfs-cluster-service init" command.

I dont like that its so easy for anything else on the system to get the secret.

How about use the key store ? There are cross platform libs for accessing this in golang we can use.

**Comment by lanzafame** [comment]
MacOS isn't a normal production deployment option and is supported because
go has great cross platform support, do it isn't high on our priority list
but please feel free to contribute a PR that adds support for storing the
cluster secret in the key store.

**Comment by gedw99** [comment]
well its just for testing that i am on darwin.
For production i would run on linux when not inside docker. Then how to protect the secret ?
I guess your only focussed on docker environments where the secrret is shared on the ENV ?

**Comment by lanzafame** [comment]
Vault is a good option to store it and then you can write a small script to
glue the pieces together.

We are more just avoiding making overly opinionated choices about how
cluster is deployed. For example, I recently did a kubernetes deployment in
which case I used a Secret resource store and inject the cluster secret via
an environment variable to the container. Env vars are just a really good
interface point between a lot of infrastructure pieces.

**Comment by gedw99** [comment]
thanks - make sense..

not sure i can run vault across desktops because it will be the same catch 22 of it itself needing a secret i think :) boy turtels all the way down i tell ya :)

But i must admit i need a vault anyway for storing a ton of user credentials stuff. IPFS is maybe a good store for that if the data is encrypted at rest. not sure..

Gotta see how easy it is to run Vault without it being in a docker environment...

**Comment by hsanjuan** [comment]
> I dont like that its so easy for anything else on the system to get the secret.

It's easy for anyone in the system with read access to the `service.json` file. The file is created with 600 permissions (so only the owner can read/write it). It is the same for ~/.ipfs/config and the private key it contains. It is the same for ~/.ssh/id_rsa. This is why it is good practice to have a dedicated `ipfs` system user to run ipfs and cluster in production environments.

**Comment by gedw99** [comment]
thanks..
Ok thats a good point about the User and only it having access. It seems like a good way of using the OS itself for protection.

SO that means i have to run everything under a new user different from the normal desktop user, if i want to run this on desktops ? For automating this its going to require the user to make the user and run the install of ipfs under that new "ipfs" users first, and then logout and log in as a normal user ?

I wonder if its possible to automate that workflow on desktops ? I have faith in users but not that much faith you see..

**Comment by hsanjuan** [comment]
It would mean you don't have to share user accounts in the desktops, but if you do, you should probably run system services in their own users (just like apache, sshd and every other system service does). It is possible to use `ipfs-cluster-ctl` then directly from any user account, but not `ipfs` (it must be run with the same user or have the ipfs folder visible to the invoker).

**Comment by gedw99** [comment]
ok making sense.. thanks for the hand holding here.

One of the assumptions i did not make clear( since this issue started with just a keystore suggestion) is that i am shooting for allowing users in a LAN being able to run the cluster on their laptops.  No dedicated servers / NAS / etc.  Sharing outside the LAN is nothing to do with IPFS and will use other approaches like Cloudflare Ago tunnel for relaying data over https.
Later if they outgrow the many laptop storage approach then they add a few ARM computers to their LAN to the peer list to grow the local cluster storage. 
I have no idea yet what effect laptops leaving and joining the LAN will have .  It won't be too awful, since the router will give each laptop a static IP via the DHCP.  If the Cluster has enough peers it should just self heal so to speak i assume.

You probably have thought (and benchmarked) these use cases so feel free to holler about any suggestions you have. This is currently a experiment to see how far i can get without dedicated NAS boxes.

Also, if any of this is useful, happy to put on a github repo or PR it.

--

How to test this:
1. On my Mac, inside a docker swarm,  3 x IPFS cluster nodes. This is to simulate the ARM boxes.
2. On my Mac, locally, a single install of IPFS Cluster running under the "IPFSCluster" system account.
3. On my Mac, inside a VirtBox Windows 10, a single install of IPFS Cluster running under the "IPFSCluster" system account.

The Darwin and Windows real user accounts then run a simple Test Harness to see if things work and stay working as nodes leave and join.....

---

The automation:
So back to automating creation of user and services for Desktops ( win, Mac, Lin), I found some golang libs that do it without CGO. SO all good.  Will make provisioning easy.

Then i have to:
a. Run the Provisioning workflow from the real users account:
- 1. Make a "IPFSCluster" system user account.  
- 2. For that new "IPFSCluster" system account: Install and init ipfs cluster. ipfs-cluster-ctl will be exposed to other real user accounts so they can admin the cluster.
2. ipfs running inside the real user account.

**Comment by hsanjuan** [comment]
Why do you have an interest in users not knowing the cluster secret if they can control everything else?

**Comment by gedw99** [comment]
Thats the right question. You got me...

Initially my intent is so that any nasty software that gets installed under the real users account can not slurp up the secret and run amuk doing what it wants...
An example si the WanaCrypt0r 2.0, WannaCry and WCry incident, where users files are encrypted and held to ransom.
https://www.telegraph.co.uk/news/2017/05/13/nhs-cyber-attack-everything-need-know-biggest-ransomware-offensive/

**Comment by hsanjuan** [comment]
The secret is just protecting the communications between peers (and disallowing any peers that do not know it from communicating or triggering actions in a different peer) but does not protect the storage itself. If a malware is locally installed, it may well just use the Cluster API to the same effect. This quarter we want to add permissioned RPC/API endpoints which will make the cluster secret superfluous in a bunch of scenarios (this one I think too). There is some discussion here https://github.com/ipfs/ipfs-cluster/issues/610#issuecomment-440009948 . the tl;dr is that a shared cluster secret should not be what prevents one peer from controlling another one.

Also https://github.com/libp2p/go-libp2p-gorpc/issues/35. As of know, I think you should just move ahead installing cluster and ipfs on the regular user account since the gains of not doing so are small and do not compensate the complications, and improvements should happen rather soon.

**Comment by gedw99** [comment]
@hsanjuan thanks - very patient of you to listen and advise me.

I will take your advice and avoid the multi user complexity for OS accounts for now.
The RPC / API endpoints looks like a well needed aspect for my use cases. Once its ready in the code, will use it and see how it pans out for me.

Am going to close this as i think we have resolved the way forward. Feel free to ask me to reopen should you feel it needs to be...
