### ISSUE TITLE
Not able to make an interaction between two PC's using IPFS_CLUSTER

### ISSUE THREAD

**Issue by pranavdaa** [ipfs/ipfs-cluster#631]
#### Pre-check

* [x] IPFS cluster of both the devices are on same version that is 0.7.0
* [x] One node is windows 
* [x] Second is a ubuntu machine 
* [x] Both the machines are connected by the same WiFi hence belong to the same network
* [x] All my peers are configured using the same cluster `secret`
* [x] Both the peers have been initialized ->ipfs-cluster-service init and there service.jason file is created

#### Description

I have been trying to make an interaction beetween two pc's using ipfs-cluster .Have followed the https://cluster.ipfs.io/documentation/quickstart/ ie the quick starter guide but when i deploy start both the machines
1)on windows->`ipfs-cluster-service daemon`
2)on ubuntu-> `./ipfs-cluster-service daemon --bootstrap /ip4/192.168.0.103/tcp/9096/ipfs/Qmakp6u81YjRWDYXVQqnWecRwEp7isuF1wMSzACJ6mHmVW`
note 192.168.0.103 is the ip of the other machine and Qmakp6u81YjRWDYXVQqnWecRwEp7isuF1wMSzACJ6mHmVW is its ID
Then error occurs 
Windows ->
![image](https://user-images.githubusercontent.com/38764142/50573592-48c0e980-0dfd-11e9-85db-1372158b8e5b.png)
Ubuntu machine->
![image](https://user-images.githubusercontent.com/38764142/50573605-786ff180-0dfd-11e9-9d15-39d079ae95e3.png)
The service.json file of the windows is->
```
{
  "cluster": {
    "id": "QmRQSCCgugicTGUZihbUzuLzuGf7DEKp35ePwpcDDJ8kGB",
    "peername": "LAPTOP-6QU7RMTR",
    "private_key": "CAASpwkwggSjAgEAAoIBAQCq0TVcS95vf+VjM161VuoSFkA3Ke7X9wpdmryh5c88Z1dlX4UMMH5sGOE4XT0sar/i3WNCxMitcYeNKWSt7xtObrHB8X9YK4E8zU8opWwWt1zaXc+B1v/6NeOSPuvlNPAGb/4yGw/QZU42TBo1czTDeIiQPTNaDtAB29dAHyHVc5KH0NMi2Oh5NX32NHw71xjli+toeD1LXDtWCZkaPEU7eZXz89sVFBkjHn6LmMy9Su4p31GR7b68lX6UpLGaRYy3Ybegc07Z4k6nW1Zyp06eUjBgDW5OBGM+1UuKZqg+pvFNyCKNJO5VOBTl5Jofjvq+CwCKFvpxKFm7ikNDT6G3AgMBAAECggEBAINdy1zE2DcFtALbgc2SHwdz50TFUfLzARzFoKYdl4fLrfG/SRH7xW4aoDJ5uk8LdbDiM7Eop3CD7AxKtivxxB1IkhomQJotMwHwnx0SQxMhRx6EoM4o68mgYfiZvU8TrDg3LtWX7EyHbGPjmRBcHkrpypSrDHAJDj0vtdWRW7LMIjE9tP8up0O5spgAzaiYDobW46qmrwWmXrBMlOkwWfRwaXZUNSbncYjiZ5Psa1j48iPpklbqRWHbVMCdAV+YkcsgBLdYJd9UKIY3Ig6eUKNCuz5uX9eKMZQAEjzSkCv4YamTm0juYpmFUCV8J/A2p3CJ8UO8IDr8cc7mO/Boc/kCgYEAyzmUsliMGCp11zf9Lj5MSQpY4lC58UCt5RIytLVkCJFQ0+QpIX3t+YgM4wUmh5r0NYMv0d8peDVVo6Y4Xl8zBau3Bui1pMRANFEZhc7hlLx4TKKjWSRvKskY5MIRGU72DLC1J3Y3SE3hZNKmLfnooGJ0JiEc3EIbTtV/+NS6eP0CgYEA1y0owngHJO0dfoRLj/5Q05HY+5BdKv0/2y5NTdH/KenBO6U11YQB2acGkrDQAaoOIglSPLcwCSEoXZcyuz2pwB9w+Gji0CLMa0IEmSucPhExbZxR4Ork+Xx3vm5OJdF2I1E6rQyMSAwqFAvYzfYvqEsDgTRfyirH638woT5VLcMCgYB2Avz3R/YqflWp4chzFxgjfg+5dFlV4FJa6GNrjr4FP6VpNmAwI7mSos+g8Te7nV7cyE53mBizxnzxqC+plazCSUHikDYS9Se3ebTRgB58yakuD2+97yti9B4xkQRu5ux42BCKVtqpcRhG/RAlOK8+m42JKsdgnD7RW6eRrq6OXQKBgHWD5E7Q3pX8Ka9+8QWjDuF9NdOt9DQWO1mo3+8wUPrC/xVkFRKXFauY3K4ggnlmNnHARXmDUmiqAzGZ8crw0lRq13fTUIv7dUjetUQx3RLIsQX76Xu8zXCz2XHXLDbbPnnrUvBPeg2fFxv7nFxfp4dx8GgQAoCW/LhQrm5hbIOhAoGAPfwYRyp3MNLSiuyy1CHU794Eg+cpa4AUFxEf6fsz5Aom7qVF8n8GL1q8f5D0yZw76CRrvQk2OsJTRRMTQ/7QZEq1QNyGvtu3hf6jWeqpGFEff3Ayc6Gco+tyknKHCAeU+cDE54/8FPXBbnOXXYPRsNKF7nXhhLuBYja+sU+H3D4=",
    "secret": "304421f1e313c2997de0a6c93806146bc1377603cb6964591de88320692d6415",
    "leave_on_shutdown": false,
    "listen_multiaddress": "/ip4/0.0.0.0/tcp/9096",
    "state_sync_interval": "10m0s",
    "ipfs_sync_interval": "2m10s",
    "replication_factor_min": -1,
    "replication_factor_max": -1,
    "monitor_ping_interval": "15s",
    "peer_watch_interval": "5s",
    "disable_repinning": false
  },
  "consensus": {
    "raft": {
      "init_peerset": [],
      "wait_for_leader_timeout": "156s",
      "network_timeout": "150s",
      "commit_retries": 1,
      "commit_retry_delay": "200ms",
      "backups_rotate": 6,
      "heartbeat_timeout": "15s",
      "election_timeout": "155s",
      "commit_timeout": "500ms",
      "max_append_entries": 64,
      "trailing_logs": 10240,
      "snapshot_interval": "2m0s",
      "snapshot_threshold": 8192,
      "leader_lease_timeout": "500ms"
    }
  },
  "api": {
    "restapi": {
      "http_listen_multiaddress": "/ip4/127.0.0.1/tcp/9094",
      "read_timeout": "0s",
      "read_header_timeout": "5s",
      "write_timeout": "0s",
      "idle_timeout": "2m0s",
      "basic_auth_credentials": null,
      "headers": {
        "Access-Control-Allow-Headers": [
          "X-Requested-With",
          "Range"
        ],
        "Access-Control-Allow-Methods": [
          "GET"
        ],
        "Access-Control-Allow-Origin": [
          "*"
        ]
      }
    }
  },
  "ipfs_connector": {
    "ipfshttp": {
      "proxy_listen_multiaddress": "/ip4/127.0.0.1/tcp/10095",
      "node_multiaddress": "/ip4/127.0.0.1/tcp/4001",
      "connect_swarms_delay": "30s",
      "proxy_read_timeout": "0s",
      "proxy_read_header_timeout": "5s",
      "proxy_write_timeout": "0s",
      "proxy_idle_timeout": "1m0s",
      "pin_method": "refs",
      "ipfs_request_timeout": "5m0s",
      "pin_timeout": "24h0m0s",
      "unpin_timeout": "3h0m0s"
    }
  },
  "pin_tracker": {
    "maptracker": {
      "max_pin_queue_size": 50000,
      "concurrent_pins": 10
    },
    "stateless": {
      "max_pin_queue_size": 50000,
      "concurrent_pins": 10
    }
  },
  "monitor": {
    "monbasic": {
      "check_interval": "15s"
    },
    "pubsubmon": {
      "check_interval": "15s"
    }
  },
  "informer": {
    "disk": {
      "metric_ttl": "30s",
      "metric_type": "freespace"
    },
    "numpin": {
      "metric_ttl": "10s"
    }
  }
}
```

And that of Ubuntu is->
```
{
  "cluster": {
    "id": "QmWZ1T9c9ZU7VoWukwx7gKfQjGn1s9mehdLP5eamU2wyad",
    "peername": "tbcdev",
    "private_key": "CAASpwkwggSjAgEAAoIBAQCzbFotaAA0TqONPFZRQNcJFRMQdodRCcWUbHz/FHVYSzDPIYyrGxD5cGIlahL3hVZbDeXtS8JvtD49M0u1bPZzxZsP2DO46D10fSynIYZeApnXLYpJxgMaCaVz3Mekhy75NWY2iDeU9Hv/kEPrlmqB9agBYiBsGS3xngynqL4CyEmkvBadufPijv06xyKpx+BHBNukGrMNRdcPYlK2LzXzCr48jJk0IPpLYCQf7PKTVD9esgMsUx2HTc1TTm7mGLddcw+M4XP0oxYbduzf2not7xKqnOQ4oAtfkVBtYqVtlv97pqZf06ifjGoA+yafdgwAnWpFDRibF3GoBxQRyo1LAgMBAAECggEAS6m0uZMzCtviwqugJvG1/OGDQZ0KYVVCmd3KNHN3LL3AnoiiXoGyfc4zxV1fFDyJdyp8PL6HBz42RO69zYtevuGlC2B8J0zgpaAn1W8gz8I/B+vvdj7njfJlcF+5XRuY5oTrTrHQ5qLXK6W1zsKGtblXmQW9cHiJ1Gt3ILjbMCZ6l2nXgG2px1qR86d6pXCJowm5+5IvIcYjYYZIGCEYPdqw4qaZ15RHy+UzoUopxb/1til938olEqotVR1eHgfbnCZk03cczxXoxxToowAGMP1QjPONZUPuD8PSHtEUGGzN90YbIR4/UfR9j2I7VxmBPazbRABZPweHK4nUKpp/GQKBgQDBU1H8K25z22YQuHqfqwYwBkiiyblWm0kv/N2if61ApUuQO7w/BTZlg83Oil5k6+5bHx4b86k1L1eWNgjqMkj6w00tlHga7ZPh+QGvczDkuE9VMP5wCZhGpdyYuq3Gtc2iZwKPLyB97+jG3eP97sVc02zkDjmNsgTpnOtSMf17xQKBgQDtlz5pKRQ+pmL7Le2QUOYQOI19hphunDuTCiqQO8ILi2Ru2/Fev4v8CDCfuGMvA+QYThKG/snk0PFaLl+svg53/c7WypHcgQSW7umfR3AT46dghzmrd3arsMStvmdeJMG8j/U4kmImItgdx5Vxd1EiRFY02+oDIXVBCHWQdjAlzwKBgHv8YtU2SYU2TXQlzEcAmVxNe2Iju6DGwJ5tLvubpNKT8C1VkjpcrnFWobR322ggQ+LexyGoGHoKncKxbvA8Rb/FZ4b29DxY6AIB/8m1N8NITWDWpifWj3mnwB2XhAGv8WzZYbPQxqbeKUz5W9IswxjwY6KzWMf+RtZIlEdH1kj9AoGBAN/RfL/ALQwf3lrVF1i+fRyGyfOYWfzJPO31w8cAJHqPo9szYxxowcx5QqUUJItj1Pp4gceeOj9N/i+ARC0NFcA/3xxE1EevWs1836RmvdRev4yVluRKtAZljcJG/kWXxtKFovLaI4/df03+eG/dgRcQ3U0KZlbwq+7Js0aVsCHNAoGAGYn8YxMDr8gNuucsNnYLTIhIDbeOK9Mv2GiTBsyqCCDgCNspAod1Dw2+FJrjs6cniEMA68uZFgqPJQMdTfNXctKkloqtro13hETcNHBGK7ZQCkUH5CKnctPZTVZUOW79ds8SLp9r3slHokzpyPB6plT8JBU9bvd7CuDZpoaS23E=",
    "secret": "304421f1e313c2997de0a6c93806146bc1377603cb6964591de88320692d6415",
    "leave_on_shutdown": false,
    "listen_multiaddress": "/ip4/0.0.0.0/tcp/10096",
    "state_sync_interval": "10m0s",
    "ipfs_sync_interval": "2m10s",
    "replication_factor_min": -1,
    "replication_factor_max": -1,
    "monitor_ping_interval": "15s",
    "peer_watch_interval": "5s",
    "disable_repinning": false
  },
  "consensus": {
    "raft": {
      "init_peerset": [],
      "wait_for_leader_timeout": "156s",
      "network_timeout": "150s",
      "commit_retries": 1,
      "commit_retry_delay": "200ms",
      "backups_rotate": 6,
      "heartbeat_timeout": "15s",
      "election_timeout": "155s",
      "commit_timeout": "500ms",
      "max_append_entries": 64,
      "trailing_logs": 10240,
      "snapshot_interval": "2m0s",
      "snapshot_threshold": 8192,
      "leader_lease_timeout": "500ms"
    }
  },
  "api": {
    "restapi": {
      "http_listen_multiaddress": "/ip4/127.0.0.1/tcp/10094",
      "read_timeout": "0s",
      "read_header_timeout": "5s",
      "write_timeout": "0s",
      "idle_timeout": "2m0s",
      "basic_auth_credentials": null,
      "headers": {
        "Access-Control-Allow-Headers": [
          "X-Requested-With",
          "Range"
        ],
        "Access-Control-Allow-Methods": [
          "GET"
        ],
        "Access-Control-Allow-Origin": [
          "*"
        ]
      }
    }
  },
  "ipfs_connector": {
    "ipfshttp": {
      "proxy_listen_multiaddress": "/ip4/127.0.0.1/tcp/10095",
      "node_multiaddress": "/ip4/127.0.0.1/tcp/4001",
      "connect_swarms_delay": "30s",
      "proxy_read_timeout": "0s",
      "proxy_read_header_timeout": "5s",
      "proxy_write_timeout": "0s",
      "proxy_idle_timeout": "1m0s",
      "pin_method": "refs",
      "ipfs_request_timeout": "5m0s",
      "pin_timeout": "24h0m0s",
      "unpin_timeout": "3h0m0s"
    }
  },
  "pin_tracker": {
    "maptracker": {
      "max_pin_queue_size": 50000,
      "concurrent_pins": 10
    },
    "stateless": {
      "max_pin_queue_size": 50000,
      "concurrent_pins": 10
    }
  },
  "monitor": {
    "monbasic": {
      "check_interval": "15s"
    },
    "pubsubmon": {
      "check_interval": "15s"
    }
  },
  "informer": {
    "disk": {
      "metric_ttl": "30s",
      "metric_type": "freespace"
    },
    "numpin": {
      "metric_ttl": "10s"
    }
  }
}
```
Please have a look and respond.
Thnx in advance

**Comment by pranavdaa** [comment]
@kishansagathiya how exactly should i check that.I have checked that both are connected by running a localhost:5000 website on one pc and then using that pc's IP hosting that web-site on the other web-site.Does that solve ur query of peer-multiaddress connectivity?

**Comment by pranavdaa** [comment]
@lanzafame yes the ports are open

**Comment by pranavdaa** [comment]
@lanzafame and @kishansagathiya do we have to have the ipfs daemon when runing this program if yes then what should be its corresponding gateway id and api address.
My both the ipfs daemons look like->
![image](https://user-images.githubusercontent.com/38764142/50584914-5a0b0400-0e98-11e9-8a75-a28bdffe3ed9.png)

**Comment by pranavdaa** [comment]
![image](https://user-images.githubusercontent.com/38764142/50588460-27690780-0ea8-11e9-81e8-8b7780883a9f.png)
See this also

**Comment by hsanjuan** [comment]
Hi,

I see a bunch of things wrong. The screenshot from windows shows that it is trying connect to another peer (`Qm..*jj`) which does not correspond to the ubuntu peer. It also shows its peer ID is `Qm*kGB` which is not the peer you are bootstrapping to (`Qmakp6u81YjRWDYXVQqnWecRwEp7isuF1wMSzACJ6mHmVW`), but this peer also shows as one that the windows one is trying to reach.

You might be mixing Cluster PeerIDs with IPFS daemon peer IDs or simply mixing peer IDs from previous runs. I suggest that you run:

`ipfs-cluster-service state cleanup` on your both peers and try to follow the guide again. The windows peer should start normally as a single-peer cluster. Then bootstrap the ubuntu peer using the IPFS Cluster peer ID from the Windows peer (`--bootstrap /ip4/192.168.0.103/tcp/9096/QmRQSCCgugicTGUZihbUzuLzuGf7DEKp35ePwpcDDJ8kGB`).

**Comment by pranavdaa** [comment]
@hsanjuan I HAVE DONE THIS AND AFTER THIS THE WINDOWS IS RUNING IPFS DAEMON .BUT THE UBUNTU IS NOT ABLE TO CONNECT (BOOTSTRAP)TO THIS PEER.
I have not individually connected the ipfs peers before connecting ipfs-cluster .DO i need to do that??

**Comment by hsanjuan** [comment]
The screenshots you provide show that you are not bootstrapping to the cluster right peer and that the Windows peer thinks there are two other peers in the peerset which are wrong. Therefore you need to `cleanup` the windows peer and bootstrap the other peer correctly to that one. And if that doesn't work, then send the right logs which will for sure show a different error.

This all is independent from running the ipfs peers.

**Comment by pranavdaa** [comment]
@hsanjuan I will send you the latest screenshot in a moment but also look at https://cluster.ipfs.io/documentation/starting/#requirements which says ipfs has to be on.So ipfs-cluster and ipfs are connected to each other.

**Comment by hsanjuan** [comment]
> .So ipfs-cluster and ipfs are connected to each other.

Yes, via IPFS HTTP API. The errors you are getting are unrelated to running IPFS.

**Comment by pranavdaa** [comment]
I have made certain changes @hsanjuan @kishansagathiya @lanzafame please have a look and respond->https://github.com/pranavdaa/service.json-windows
![image](https://user-images.githubusercontent.com/38764142/50590615-bdedf680-0eb1-11e9-921a-eb416643687f.png)
![image](https://user-images.githubusercontent.com/38764142/50590629-c6dec800-0eb1-11e9-8754-d16f1d470d79.png)
![image](https://user-images.githubusercontent.com/38764142/50590638-d100c680-0eb1-11e9-8e37-130064e3df61.png)
![image](https://user-images.githubusercontent.com/38764142/50590645-d9f19800-0eb1-11e9-942c-86e62dd31c6c.png)
![image](https://user-images.githubusercontent.com/38764142/50590670-e83fb400-0eb1-11e9-8d42-5cf1af6f71d2.png)

**Comment by hsanjuan** [comment]
You're bootstrapping to the wrong ip. you are using 192.168.0.103 but the peer you're bootstrapping to runs on 192.168.0.108.

**Comment by pranavdaa** [comment]
were did see the id 192.168.0.108.Also how to change it My bootstrap command is at  192.168.0.103 
only.Still the problem

**Comment by hsanjuan** [comment]
`--bootstrap /ip4/192.168.0.108/tcp/9096/ipfs/Qm...4V`

**Comment by pranavdaa** [comment]
Also @hsanjuan 
![image](https://user-images.githubusercontent.com/38764142/50592077-951d2f80-0eb8-11e9-8bc5-c4be121141b0.png)
SO i believe they are connected .PLease confirm

**Comment by hsanjuan** [comment]
They are connected, but it seems the windows peer became unreachable/undialable.

**Comment by pranavdaa** [comment]
@hsanjuan so any suggestions or changes i should make or It is the problem of windows OS itself

**Comment by pranavdaa** [comment]
ok thanks for resolving my problem.
