### ISSUE TITLE
Proper JSON output from ipfs-cluster-ctl

### ISSUE THREAD

**Issue by Elexy** [ipfs/ipfs-cluster#632]
* [x] Version information (mark as appropiate):
  * [x] Master
  * [x] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [x] macOS
  * [x] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [x] Docker
  * [x] Snap
  * [ ] Other: `which?`

#### Description
I am programmatically adding the [benchmark results](https://benchmarks.ipfs.team) with [`ipfs-cluster-ctl`](https://github.com/ipfs/benchmarks/blob/master/runner/ipfs.js#L15) and need to return the SHA for presentation purposes. The current output with `--enc json` needs [additional work](https://github.com/ipfs/benchmarks/blob/master/runner/ipfs.js#L27) before it can be parsed as JSON. 

```
{"code":0,"message":"","Name":"test1.jpg","Hash":"QmPxBet4MHo93b9nCE2FYRtDTowVA3bMRdDBZcYAiBkZKN","Size":"4696045"}
{"code":0,"message":"","Name":"test2.jpg","Hash":"QmfJ8fzLwCmuvxNG8RH41RmmjGzMrXw38pjP85EJSiXKJ4","Size":"4696045"}
```
_Note the missing surrounding `[]` and commas between the objects._

As per [this issue](https://github.com/ipfs/ipfs-cluster/issues/526#issuecomment-418120772) I'd like to request a flag to return `non-streaming` json output which can be parsed by `JSON.parse` as is.

> Hi, this is not a bug (it's a feature). /add response is a streaming response and mimics what ipfs /add does (for the moment). Perhaps you'd like to turn this into a feature request asking to support a stream=false parameter and return a single complete json response, or something else, whatever your usecase is, and we'll consider it if there is good reasoning behind it.

**Comment by hsanjuan** [comment]
Thanks.

* We need a new `api.AddParams` entry `StreamOutput` associated `stream-channels` query parameter (because I think that ipfs `stream-channels` in IPFS does that but I'm not sure). Default set to true.
* `adderutils.go` should take a look at the value. If false, it should:
  * Do not set `X-Chunked-Output`
  * Do not set `X-Stream-Error` trailer
  * Do not use a `json.Encoder` to put AddedOutput items in the connection.
  * Instead it should:
    * Push output items to a slice
    * Encode and Send that slice when done adding
    * In case of error, make a proper http error response (and not use the trailer)

**Comment by hsanjuan** [comment]
Hmm, I was wrong about being enought with supporting `-Q` for json output. Checking relevant code I seems it needs every output item and not just the last so we need a little bit more work (client support for stream-channels=false). https://github.com/ipfs/benchmarks/blob/0ef06385810aa999bac7a51479a91ef44ae1ab95/runner/runner.js#L75

**Comment by Elexy** [comment]
Thanks @hsanjuan
