### ISSUE TITLE
REST API: Unpin a CID DELETE /pins/{cid} 404 (Not Found)

### ISSUE THREAD

**Issue by alx696** [ipfs/ipfs-cluster#639]
#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version 0.7.0, IPFS 0.4.18
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

1. add a file to mfs on one of the cluster node used js-http-client-api `ipfs.files.write`;
2. get the cid of the file, pin cid used ipfs-cluster rest api `fetch('http://127.0.0.1:9094/pins/cid', {method: 'POST'})`;
3. unpin cid used ipfs-cluster rest api `fetch('http://127.0.0.1:9094/pins/cid', {method: 'DELETE'})`. Not work, 404 (Not Found):
```
General:
Request URL: http://127.0.0.1:9094/pins/QmTqZK3WkWtoKmx62s3hpoTxvU1Cv2EokaudspyVoFxtB9
Request Method: OPTIONS
Status Code: 404 Not Found
Remote Address: 127.0.0.1:9094
Referrer Policy: no-referrer-when-downgrade

Response Headers:
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Fri, 11 Jan 2019 06:51:23 GMT
X-Content-Type-Options: nosniff

Request Headers:
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Access-Control-Request-Method: DELETE
Cache-Control: no-cache
Connection: keep-alive
DNT: 1
Host: 127.0.0.1:9094
Origin: http://127.0.0.1:1033
Pragma: no-cache
Referer: http://127.0.0.1:1033/ipfs.html
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

ipfs.js:262 OPTIONS http://127.0.0.1:9094/pins/QmTqZK3WkWtoKmx62s3hpoTxvU1Cv2EokaudspyVoFxtB9 404 (Not Found)
actionDiv.querySelector.addEventListener @ ipfs.js:262
14:51:23.197 ipfs.js:262 OPTIONS http://127.0.0.1:9094/pins/QmTqZK3WkWtoKmx62s3hpoTxvU1Cv2EokaudspyVoFxtB9 404 (Not Found)
actionDiv.querySelector.addEventListener @ ipfs.js:262
14:51:23.198 ipfs.html:1 Access to fetch at 'http://127.0.0.1:9094/pins/QmTqZK3WkWtoKmx62s3hpoTxvU1Cv2EokaudspyVoFxtB9' from origin 'http://127.0.0.1:1033' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
14:51:23.200 ipfs.html:1 Uncaught (in promise) TypeError: Failed to fetch
Promise.then (async)
actionDiv.querySelector.addEventListener @ ipfs.js:263
14:51:23.224 ipfs.js:262 Fetch failed loading: OPTIONS "http://127.0.0.1:9094/pins/QmTqZK3WkWtoKmx62s3hpoTxvU1Cv2EokaudspyVoFxtB9".
```

* `fetch('http://127.0.0.1:9094/pins/cid', {method: 'GET'})` work well;
* `fetch('http://127.0.0.1:9094/pins/cid', {method: 'POST'})` work well;

I have try to add `Access-Control-Allow-Methods DELETE` both ~/.ipfs/config and ~/.ipfs-cluster/service.json, but nothing happend. service.json:
```
  "api": {
    "restapi": {
      "http_listen_multiaddress": "/ip4/127.0.0.1/tcp/9094",
      "read_timeout": "0s",
      "read_header_timeout": "5s",
      "write_timeout": "0s",
      "idle_timeout": "2m0s",
      "basic_auth_credentials": null,
      "headers": {
        "Access-Control-Allow-Headers": [
          "X-Requested-With",
          "Range"
        ],
        "Access-Control-Allow-Methods": [
          "GET",
          "POST",
          "DELETE"
        ],
        "Access-Control-Allow-Origin": [
          "*"
        ]
      }
    }
  }
```

**Comment by kishansagathiya** [comment]
Before `DELETE`, it is making CORS preflight request  (`OPTIONS` request method) to check if the CORS protocol is understood.

`OPTIONS` request is not supported in rest api and thus 404

**Comment by hsanjuan** [comment]
Yeah, REST API doesn't support pre-flight `OPTIONS` requests. I've come to learn or refresh a lot about CORS in the last days. The problem is that `simple-requests` are only GET,POST,PUT, but not DELETE. So the browsers will not allow DELETE without supporting CORS preflights at all.

> @hsanjuan would #638 fix this?

No. We should fix it for next release though, before I forget how this works.

@alx696 thanks for the report. It's a bug. Fix coming this week.

**Comment by alx696** [comment]
@kishansagathiya POST /pins/{cid} only response status 202, no response content.

Looks like Cluster REST API handled, but filter DELETE Method. If fetch a not exists url on my go http server:
```
fetch('http://127.0.0.1:1033/pins/QmcS32tNZGVbZ5i5piF4HkGcUsyN37dcnEQvXaRAowopPU', {method: 'DELETE'}).then(response => {console.debug(response)})
17:31:42.337 Promise {<pending>}
17:31:42.337 VM4345:1 DELETE http://127.0.0.1:1033/pins/QmcS32tNZGVbZ5i5piF4HkGcUsyN37dcnEQvXaRAowopPU 404 (Not Found)
(anonymous) @ VM4345:1
17:31:42.337 VM4345:1 Response {type: "basic", url: "http://127.0.0.1:1033/pins/QmcS32tNZGVbZ5i5piF4HkGcUsyN37dcnEQvXaRAowopPU", redirected: false, status: 404, ok: false, …}
17:31:42.368 VM4345:1 Fetch failed loading: DELETE "http://127.0.0.1:1033/pins/QmcS32tNZGVbZ5i5piF4HkGcUsyN37dcnEQvXaRAowopPU".
```
`fetch('http://127.0.0.1:9094/peers/QmcmLBiPdhfN2UwsLUCCnFep7x2bpj3B436qTvz22zicZP', {method: 'DELETE'}).then(response => {console.debug(response)})` Have the same problem. 

@hsanjuan Yes, not support DELETE

**Comment by alx696** [comment]
@hsanjuan Please check the `api.restapi.headers.Access-Control-Allow-Methods` options of service.json.
```
        "Access-Control-Allow-Methods": [
          "GET"
        ]
```
only allow GET, but POST works well.

**Comment by hsanjuan** [comment]
@alx696 there is a branch here #640 that you can try if you feel adventorous. #644 has some details about configuration changes needed. Otherwise, wait for the next release (next week hopefully)
