### ISSUE TITLE
Some user feedback from a test session

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-cluster#64]
Here's some feedback from a user session. we tried it a bit-- got stuck then we moved to something else, but at least we got some info.

- Trying out ipfs-cluster
  - ipfs-cluster git repo should point to binaries
  - there is no `install.sh` script
    - maybe we should follow our standard thing (like go-ipfs and other tools do it)
    - but may be fine, after all this is meant more for servers
    - could call it `install-local.sh` if `install.sh` is misleading
- got a cluster up super easily, great!
- `ctl := ipfs-cluster-ctl`
- `service := ipfs-cluster-service`
- `ctl id`
  - should multiaddrs end with ipfs-cluster?
    - no, they shouldn't, just a libp2p endpoint
    - this should probably be mounted on the child node's libp2p node
    - go-ipfs does not yet support this. so this is fine as is now.
- `ctl status` may want to be `ctl pin status`
- `ctl peers ls` looks good
  - 2 cluster nodes connected
  - wish it gave me more info on connectivity (who's connected to who?)
    - but this may be a security issue-- meaning, in byzantine setting it doesn't. (leaks info, etc)
  - child ipfs nodes directly connected (and to the public network)
  - it errors if cluster peer not online.
- `ctl pin`
  - 20s delay on pinning a small file... not clear why. (how would we diagnose?)
- INFO log on pin may want to say when it has been replicated to everyone
  - consenus replicating the entry is not enough, we want to replicate the data too
  - looks like right now consensus is clearing (committed and done) after the pin entry
    - should maybe wait for data to be replicated / committed before clearing it in consensus
    - or maybe use 2 phases/ops: 
      - 1) `pin` (commits the pin to whole cluster), 
       - and 2) - `pin complete` (the pin has actually completed to enough of the cluster to count as consensus)
- added another peer, bad times
  - somehow got into a bad state, cannot connect peers
  - `ctl peers ls` on the leader takes a while
  - `ctl peers ls` does not say what address using to connect to peer.
    - important for debugging
  - we couldn't get the peers all talking to each other
- tested loosing a network interface (cable)
  - not connecting to peers over other interface
  - finally connected
  - looks to be libp2p issues.

**Comment by jbenet** [comment]
cc @whyrusleeping who took other notes, i think.

**Comment by jbenet** [comment]
@hsanjuan maybe close after you've read it / processed it as you want. I will try it one more time with my own machines soon and get you more feedback 👍

**Comment by hsanjuan** [comment]
> wish it gave me more info on connectivity (who's connected to who?) 
`--enc json` shows more info about the peerset as seen by each peer.

> looks like right now consensus is clearing (committed and done) after the pin entry

Not sure, about this, `ctl pin ls` shows the consensus state and allocations. Adding to consensus is phase 1 and happens fast. `ctl status` shows local status aggregated from cluster peers which, after a successful consensus entry, pin the hash. That is phase 2.

**Comment by whyrusleeping** [comment]
My notes:

- cluster-ctl peers ls doesnt actually tell me which address was used to connect to a given peer
  - it would be nice if it showed which multiaddr my active connection was using
- Reconnecting peers seems to mess with consensus, did the following:
  - start node1
  - start node2, join to node1
  - node2 pins object, it pins to both machines
  - node3 joins
  - node1 pins object, it seems to work on all machines
  - node3 leaves 
  - node2 leaves
  - node3 rejoins, fails with 'consensus start timing out'
- Pinning seems to be weird, I see pin state get updated, my node doesnt pin anything yet, then i see a log message saying that my node failed to verify it had the right pins or something (forgot to write down the exact message), and then *immediately* after that, a message saying my node pinned the thing sucessfully

**Comment by hsanjuan** [comment]
@whyrusleeping by `joins` and `leaves`, do you mean using `--bootstrap` or `peer add`? and did you use `peer rm`, or just ctrl-c the nodes?

Regarding the log messages, it's just confusing because it prints an error when it checks if ipfs has a pin before pinning (it won't pin if it has it already). When Ipfs does not have a pin it returns a 500 (which is indistinguishable from more serious errors though...). Anyway I'll make sure this gets fixed, it's been in the back of my head for a while.

**Comment by whyrusleeping** [comment]
@hsanjuan we were just ctrl+c'ing the nodes. For connects though we used `peer add`

**Comment by hsanjuan** [comment]
@whyrusleeping I don't manage to reproduce this. Not with 3 nodes at least. With 4 nodes yes. If you kill 3 of them and bring up one, it won't start because there is no majority to elect a raft leader (2 votes out of 4 peers).

By the way I have removed the weird pinning message you saw.
