### ISSUE TITLE
Testing: Add extra tests for Basic Authentication in "restapi"

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#645]
#### Basic information

* [x] Type (mark as appropiate):
  * [x] Enhancement

#### Description

Apparently we only test the basic authentication support in sharness. This is not ideal. We should test it in the `restapi` module (with different request methods, and paths, and with different users, valid and invalid ones).

**Comment by alekswn** [comment]
Hi,
I'm new to the project but very excited to contribute. 
Have dug a bit in `restapi_test.go` file, and I'm sure I can do this.
I'll take this issue if nobody minded.

**Comment by kishansagathiya** [comment]
@alekswn sure, go ahead and take it.
