### ISSUE TITLE
Ability to Add/Pin file only to certain nodes among one cluster.

### ISSUE THREAD

**Issue by mike-ngu** [ipfs/ipfs-cluster#646]
Hi There!

Some use cases, especially for enterprise solutions requires control to which certain nodes we want to add/pin file among one cluster.

So it will be good to have this feature in IPFS-Cluster.

This topic have been discussed with Héctor S.
"We don't support manual peer allocations per pin right now, but it can be done rather easily (open an issue)."
Here the link: https://discuss.ipfs.io/t/scalability-and-highload-big-private-network-and-ipfs-cluster/4509/2

Thanks

**Comment by mike-ngu** [comment]
If you already know how it will be implemented can you please give an example of CLI/API request, should I pass list of the peers id or how will it work?

**Comment by hsanjuan** [comment]
likely `?allocations=peerID1,peerID2`. Would that work?

**Comment by mike-ngu** [comment]
Yes, something like this)
Thank you!
