### ISSUE TITLE
Jenkins build passes when it is actually failing due to missing imports

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#651]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [x] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

![1548036735](https://user-images.githubusercontent.com/5924712/51449068-1d834780-1d76-11e9-9e74-29227fdbd605.png)

**Comment by hsanjuan** [comment]
Can you open this one in ipfs/infra or ipfs/testing? We don't control how
the test command is run ..
