### ISSUE TITLE
IPFS Cluster Does Not Behave Well On Machines With Multiple NICs

### ISSUE THREAD

**Issue by postables** [ipfs/ipfs-cluster#653]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Latest stable version
* [x] Type (mark as appropiate):
  * [x] Bug
* [x] Operating system (mark as appropiate):
  * [x] Linux
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io

#### Description

I'm unable to get an IPFS Cluster daemon to start on a machine that has multiple NICs with different IP addresses. This machine works fine and is able to join my cluster when I have just 1 NIC enabled. If I disable while I'm bootstrapping the node, it is visible by the rest of the nodes in my cluster, however eventually the node will timeout and IPFS Cluster will terminate with the following error.
```
17:19:28.854 ERROR    cluster: error waiting for leader: context deadline exceeded cluster.go:692
17:19:28.854 ERROR    service: bootstrap to /ip4/<good-node-ip>/tcp/9096/ipfs/QmQkjF84MYoBsBq5GnEi6kHXTmZvJDZNjnpoZjCgZanxVQ failed: error waiting for leader: context deadline exceeded daemon.go:162
17:19:29.689 ERROR    cluster: ***** ipfs-cluster consensus start timed out (tips below) ***** cluster.go:372
17:19:29.689 ERROR    cluster: 
**************************************************
This peer was not able to become part of the cluster.
This might be due to one or several causes:
  - Check the logs above this message for errors
  - Check that there is connectivity to the "peers" multiaddresses
  - Check that all cluster peers are using the same "secret"
  - Check that this peer is reachable on its "listen_multiaddress" by all peers
  - Check that the current cluster is healthy (has a leader). Otherwise make
    sure to start enough peers so that a leader election can happen.
  - Check that the peer(s) you are trying to connect to is running the
    same version of IPFS-cluster.
**************************************************
 cluster.go:373
17:19:29.689  INFO    cluster: shutting down Cluster cluster.go:440
17:19:29.689  INFO  consensus: stopping Consensus component consensus.go:176
17:19:29.689 ERROR       raft: NOTICE: Some RAFT log messages repeat and will only be logged once logging.go:105
17:19:29.689 ERROR       raft: Failed to take snapshot: nothing new to snapshot logging.go:105
17:19:29.689  INFO    monitor: stopping Monitor pubsubmon.go:155
17:19:29.689  INFO    restapi: stopping Cluster API restapi.go:461
17:19:29.689  INFO  ipfsproxy: stopping IPFS Proxy ipfsproxy.go:228
17:19:29.689  INFO   ipfshttp: stopping IPFS Connector ipfshttp.go:183
17:19:29.689  INFO pintracker: stopping MapPinTracker maptracker.go:119
```

Here's the `consensus` section of my configuration file
```json
  "consensus": {
    "raft": {
      "init_peerset": [],
      "wait_for_leader_timeout": "45s",
      "network_timeout": "45s",
      "commit_retries": 1,
      "commit_retry_delay": "200ms",
      "backups_rotate": 6,
      "heartbeat_timeout": "30s",
      "election_timeout": "30s",
      "commit_timeout": "50ms",
      "max_append_entries": 64,
      "trailing_logs": 10240,
      "snapshot_interval": "2m0s",
      "snapshot_threshold": 8192,
      "leader_lease_timeout": "500ms"
    }
  },
```

Things I have tried:
* bootstrap with  state that was active before enabling multi-nic
* bootstrap with a cleaned state

If I disable the multi-nic and go back to a single active NIC, everything works fine. If all else fails, I will create a bond the multiple nics together into a single logical NIC. I'm hoping that changes things.  For reference, the IPFS node on this server seems to be running just fine across the multiple NICs.

This was a major kick in my plans for redundant network links for my IPFS Cluster nodes :disappointed: 

edit:

During the initial bootstrap, all other nodes that are already part of the cluster can detect the peer that's currently bootstrapping, so im not quite sure why its unable to join.

**Comment by lanzafame** [comment]
@postables When starting the daemon with two NICs enabled, does the logs list both addresses in the `listening on: ...` set of addresses? i.e.:
```
/ip4/192.168.20.9/tcp/9096/ipfs/Qmb6hvXX4GKzVza7651PgxHGNznh8DPNg1FXVnsz3R1TGG // wifi  /ip4/192.168.1.42/tcp/9096/ipfs/Qmb6hvXX4GKzVza7651PgxHGNznh8DPNg1FXVnsz3R1TGG // nic 1
/ip4/192.168.1.43/tcp/9096/ipfs/Qmb6hvXX4GKzVza7651PgxHGNznh8DPNg1FXVnsz3R1TGG // nic 2
```
Note: I have ellided extra addresses.

**Comment by postables** [comment]
I have this working now, but to recap the conversation i had with lanzafame, it seems like the issue was a possible state corruption with me not initially starting the peers with multiple NICs. After adding the NIC, the proper step was to remove the multi-nic host from the cluster and then join to  cluster. Instead I first attempted to join the multi-nic host to cluster without first removing it.

Having started from a completely fresh cluster, this is no longer an issue. Thanks lanza!
