### ISSUE TITLE
Docker image issue

### ISSUE THREAD

**Issue by volodyad** [ipfs/ipfs-cluster#658]
when start cluster via docker image it shows
16:52:09.448 WARNI     config: raft section is empty, generating default config.go:333
16:52:09.448 WARNI     config: restapi section is empty, generating default config.go:333
16:52:09.448 WARNI     config: ipfsproxy section is empty, generating default config.go:333
16:52:09.448 WARNI     config: ipfshttp section is empty, generating default config.go:333
16:52:09.448 WARNI     config: maptracker section is empty, generating default config.go:333
16:52:09.448 WARNI     config: stateless section is empty, generating default config.go:333
16:52:09.448 WARNI     config: pubsubmon section is empty, generating default config.go:333
16:52:09.448 WARNI     config: monbasic section is empty, generating default config.go:333
16:52:09.448 WARNI     config: disk section is empty, generating default config.go:333
16:52:09.448 WARNI     config: numpin section is empty, generating default config.go:333
16:52:09.448 WARNI     config: tracing section is empty, generating default config.go:333
16:52:09.448 WARNI     config: metrics section is empty, generating default config.go:333
16:52:09.448 WARNI     config: ipfshttp section is empty, generating default config.go:333

seems config is broken and IPFS_API is not applied
seems issue related to latest docker build https://hub.docker.com/r/ipfs/ipfs-cluster/tags

Errors
17:18:30.941  INFO  consensus: existing Raft state found! raft.InitPeerset will be ignored raft.go:204
17:18:30.941  INFO    restapi: REST API (HTTP): /ip4/127.0.0.1/tcp/9094 restapi.go:443
17:18:31.022 ERROR   ipfshttp: error posting to IPFS: Post http://127.0.0.1:5001/api/v0/id: dial tcp 127.0.0.1:5001: connect: connection refused ipfshttp.go:426

**Comment by hsanjuan** [comment]
Hi, thanks for sending this. I can reproduce it on master.

As a workaround, can you run `ipfs/ipfs-cluster:v0.8.0` instead?

@lanzafame it seems I broke something in the configs very badly. Only the `cluster` section is created on `init`. Can you have a look?
