### ISSUE TITLE
Upload slow and then error

### ISSUE THREAD

**Issue by Elexy** [ipfs/ipfs-cluster#665]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description
For the js-ipfs benchmarks we are uploading performance files and benchmarks results to ipfs with ipfs-cluster-ctl and with the recent increase in files the upload takes very long and ultimately end with an error: `Post http://127.0.0.1:5001/api/v0/block/put?f=v0: dial tcp
 127.0.0.1:5001: connect: connection refused`
There are a total of 540 [files](https://gist.github.com/Elexy/780d4c1c31bc04dadf46cc1ac7d9bfd0), just over 1GB being uploaded in 1 command.

**Comment by hsanjuan** [comment]
@Elexy how long does it roughly take it to error? Hmm, I see a `too many open files` errors in the ipfs logs.

I have restarted the daemons and the cluster for the moment. Can you try again? I suspect an IPFS issue here. Might need to raise the limit of file descriptors or look further into why FDs are getting exhausted. I also see some memory problems.

**Comment by Elexy** [comment]
@hsanjuan It takes well over an hour of uploads before it errors.
I'll try it again now.

**Comment by Elexy** [comment]
It worked and the same bunch of files only took a few minutes now!!

**Comment by hsanjuan** [comment]
Ok, let's keep an eye on this. Good to hear! I'm closing for now, but we can re-open and keep commenting here if anything comes up.
