### ISSUE TITLE
Authorization for RPC

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#666]
Creating this to discuss IPFS-Cluster's use case of https://github.com/libp2p/go-libp2p-gorpc/issues/35, 

Things like,
- Which methods should be allowed and how, where to put authorization map,current configuration service.json or separate, etc.
I am inclined towards having a separate file for it, since this map can be big. 
- I was thinking that we can have roles, using which users could allow/disallow all methods belonging to that role. User can allow/disallow individual method, which would take precedence over the permissions to the role.
- Do we want to support any wildcards, etc.

**Comment by kishansagathiya** [comment]
I did a sanity check by not allowing any methods, which worked
```sh
13:10:43.969 ERROR  p2p-gorpc: error handling RPC: client does not have permissions to this method, service name: Cluster, method name: PeerAdd server.go:177
```

**Comment by kishansagathiya** [comment]
I believe for cluster to utilize authorization for RPC would make sense only after having CRDT-based consensus, right?

**Comment by hsanjuan** [comment]
> I believe for cluster to utilize authorization for RPC would make sense only after having CRDT-based consensus, right?

Possibly. I suggest we hide specific configuration from the user until we have a usecase which requires more flexibility. I don't think the users should handle directly the permission map as RPC API is internal.

@kishansagathiya can you make a list of existing endpoints, whether they are read/write, and what the perf impact of triggering them is (or on what it depends - otherwise leave a ? and me or @lanzafame will figure it out).

**Comment by kishansagathiya** [comment]
I was wondering what would happen if somebody repeatedly keeps hitting cluster APIs. I don't think we have anything to restrict people from hitting too many APIs or do we?

**Comment by kishansagathiya** [comment]
read, write and admin roles are quite straightforward, 
GET --> read
POST --> write
DELETE --> admin

I am going to see if any `GET` methods are revealing some information that might be misused.

**Comment by kishansagathiya** [comment]
I am will try running a cluster with trusted, follower model where followers can't do anything accept joining.

**Comment by kishansagathiya** [comment]
I have divided things as per 3 roles (read, write, admin), but now it seems inappropriate. We should just divide as per trusted/follower peer. In fact we need just need a list of methods allowed to followers (trusted can be allowed all methods)

Writing down the current division anyway (write and admin would mean change in cluster)

**Cluster component methods**
ID - read (shouldn't create any problems, if followers are able to use this)
Pin - write
Unpin - admin
PeerAdd - write
PeerRemove - admin
PinGet - read
Peers - read
ConnectGraph - read 
Status* - read
Sync* - write
Recover* - write
BlockAllocate- read

PinTracker and IPFSConnector doesn't seem like something that should be allowed to followers

**Comment by hsanjuan** [comment]
Can you actually list all the rpc methods with their full names and components? There are a few more than this

**Comment by lanzafame** [comment]
@kishansagathiya @hsanjuan technically, it is just the methods that are listed in `rpc_api.go`, as there are no calls to any other service other than the `Cluster` service.

**Comment by kishansagathiya** [comment]
Have updated the comment with all rpc methods. I will go through them once more to see performance impact. Do you guys have any tips on this? Things that I should see while approximating performance impact of triggering a method or would it be miscellaneous for each method?

**Comment by hsanjuan** [comment]
I think the main questions are:

* Is it an expensive call in an scenario with a very large pinset? (pinLs, Status)
* Is it an expensive call in an scenario with a very large peerset? (status, and any other that trigger a broadcast, like Peers)
* Does it need a potentially expensive operation from the ipfs daemon? (pin, refs etc).
* Is a remote trigger from a different peer ID necessary for the current functioning of cluster?

Take this an an exercise to read the codebase.

Please remove the `admin`. If anything divide them between operations that alter the internal state of the peer in some way and those that don't (read/write). Special place for those that don't alter the cluster peer state per se but do affect IPFS.

**Comment by kishansagathiya** [comment]
@hsanjuan I have finished the list. Now, I am thinking of minimum permitted operations for followers to be part of the cluster. Does that sound good to you?

**Comment by hsanjuan** [comment]
> @hsanjuan I have finished the list. Now, I am thinking of minimum permitted operations for followers to be part of the cluster. Does that sound good to you?

Think what the most constrained permission set is for raft peers and for crdt/follower.

**Comment by lanzafame** [comment]
@kishansagathiya I think that the number of times that some of the RPC endpoints are called should come into the perf analysis, i.e. `Consensus.Peers` is a light call but it is constantly called.

**Comment by kishansagathiya** [comment]
We can restrict followers with rpc authorization, but certain things dont require to make rpc calls to other peers and still they can impact the network or other peers
We can't stop followers from accessing its own methods. One such example is a follower calling its own LogPin. My understanding is that this would cause other peers to pin that content. Another is RmPeer.
How do we tackle situations like this?

Good time to define what we mean by followers
Followers
- Stay in the cluster
- Serve rpc requests made by trusted peers
- Pin content to itself depending on PinOptions

**Comment by kishansagathiya** [comment]
Followers would need permissions to run these on other nodes
1. PeerAdd (needs to join a cluster)
2. ID (For ConnectGraph to work, ConnectGraph-->Peers on all members, Peers --> ID on all members)

**Comment by hsanjuan** [comment]
For CRDTs, that I can see, every peer will need `PeerAdd`, `ID`, `TrackerStatus`,`TrackerStatusAll`, `IPFSRepoStat`.

> We can't stop followers from accessing its own methods. One such example is a follower calling its own LogPin. My understanding is that this would cause other peers to pin that content. Another is RmPeer. How do we tackle situations like this?

In the case of Raft LogPin, LogUnpin need  to be allowed. We don't need to tackle it at RPC level for CRDTs and they should be closed (updates from non trusted peers are ignored by consensus).

In the case of Raft BlockAllocate needs to be open for everyone too. Along with `TrackerRecover*`, `Sync*`.

Basic monitor also needs `PeerMonitorLogMetric` from everyone, but we are removing it.

**Comment by hsanjuan** [comment]
We also need to make the distinction for CRDTs between:

* Endpoints opened for everyone
* Endpoints opened for trusted peers
* The rest (closed/open only for local peer).

**Comment by hsanjuan** [comment]
We could have a `permission_policy` configuration option, which is hidden by default and autoselected based on the components used:

- `raft`: gets autoselected for `raft`
- `crdt_strict`: default for crdts. Only PeerAdd, ID open to the world. TrackerStatus,TrackerStatusAll open to trusted peers. This policy only allows to follow a pinset but gives no remote control of the peer to anyone (other than pinning/unpinning that happens through consensus).
- `crdt_soft`: can be manually set for crdts. Same as strict but with `IPFSRepoStat`, `IPFSBlockPut`, `TrackerRecover*`, `Sync*` opened for trusted peers. It basically allows trusted peers to add content directly and do admin tasks (sync, recover). Good for private crdt clusters.

**Comment by kishansagathiya** [comment]
@lanzafame 
> I think that the number of times that some of the RPC endpoints are called should come into the perf analysis, i.e. Consensus.Peers is a light call but it is constantly called.

That's in the current situation, where all peers are trusted. Untrusted peers can choose to call any endpoint as many times as they want. Which is why I think we would need some way to not serve request of particular peer if they show abnormal behaviour.

**Comment by kishansagathiya** [comment]
@hsanjuan 
> In the case of Raft LogPin, LogUnpin need to be allowed. 

With that case you can't have a notion of untrusted peers with raft, but I think that's fine. Go CRDTs!

**Comment by kishansagathiya** [comment]
@hsanjuan Call to `IPFSBlockPut` is used in `AddFile` method of cluster, which cannot be called by other peers since there is no corresponding rpc method. Nothing seems to be using Addfile method.
However `IPFSBlockPut` is used in `/add` rest API

Are you saying that followers should be allowed to add files?

**Comment by kishansagathiya** [comment]
> Endpoints opened for everyone

By everyone you mean followers?
> Endpoints opened for trusted peers (to discuss if BlockAllocate*, Sync* and TrackerRecover* may be open for trusted peers, or at least in some scenarios.

Shouldn't trusted peers be allowed access to all endpoint on all nodes
> The rest (closed/open only for local peer)

What do you mean here? A peer accessing its own methods? We can't restrict that, can we?

**Comment by kishansagathiya** [comment]
> We could have a permission_policy configuration option

Since we are providing fine grained permissions, permission policy map might get too big. I was thinking to keep that in a separate file. If we dont want to give fine grained permissions and just provide roles, than it make sense to have it in `service.json`

**Comment by kishansagathiya** [comment]
Followers would need permissions to run these on other nodes
1. PeerAdd (needs to join a cluster)
2. IPFSConnectSwarm (to run PeerAdd)
3. ID (For ConnectGraph to work, ConnectGraph-->Peers on all members, Peers --> ID on all members)
4. TrackerRecover*, Sync*, TrackerStatus

**Comment by kishansagathiya** [comment]
I am thinking of adding an extra folder in `~/.ipfs-cluster`, call it `permissions`. `permissions` would have files for each peer, say `<peer.ID>.json`. While running cluster, we would get a map from info stored in this file which we can use in our config.

My intention here is to make sure that files can either be modified by the user manually or by cluster automatically.

This way everytime a new peer bootstraps, we add a new auto-generated `<peer.ID>.json` based on `permission_policy`. After this point cluster won't edit any `<peer.ID>.json` files, but users can. Information about permission policy would be part of the source code. 

We can also provide quick way to edit permissions. New peers, when they join, they are untrusted/followers. They can trust them using say `ipfs-cluster-service trust <peer.ID>`

@hsanjuan @lanzafame thoughts?

**Comment by hsanjuan** [comment]
> @hsanjuan
> 
> > In the case of Raft LogPin, LogUnpin need to be allowed.
> 
> With that case you can't have a notion of untrusted peers with raft, but I think that's fine. Go CRDTs!

I never asked for that notion. What I don't think is necessary is that a random peer can call methods that fall outside the normal usage and which would either mean a bug or a misuse.



> @hsanjuan Call to `IPFSBlockPut` is used in `AddFile` method of cluster, which cannot be called by other peers since there is no corresponding rpc method. Nothing seems to be using Addfile method.
> However `IPFSBlockPut` is used in `/add` rest API
> 
> Are you saying that followers should be allowed to add files?

in `adder/util.go` you can see IPFSBlockPut is called to multiple destinations. In raft everyone should be able to call IPFSBlockPut. In `crdt_strict` no one should.`. In `crdt_soft` trusted peer should be able to call it (trusted peers should be able to add files anywhere where they are trusted).

Please let's not talk about *followers*. It leads to confusion between raft followers vs leader and crdt untrusted peers. Let's talk about "trusted peers" only in the context of CRDTs. In a Cluster using Raft, all cluster peers are considered equal in regards to this discussion.



> > Endpoints opened for everyone
> 
> By everyone you mean followers?

No, by everyone I mean everyone, trusted an untrusted peers.

> 
> > Endpoints opened for trusted peers (to discuss if BlockAllocate*, Sync* and TrackerRecover* may be open for trusted peers, or at least in some scenarios.
> 
> Shouldn't trusted peers be allowed access to all endpoint on all nodes
>

No, they should only be able to access those that IPFS Cluster needs for functioning. For example, `Pin()` is never called remotely in the cluster code. Thus it should not be allowed for anyone remotely to trigger that call.
 
> > The rest (closed/open only for local peer)
> 
> What do you mean here? A peer accessing its own methods? We can't restrict that, can we?

I mean the rest of endpoints should only be accessible locally.


 


> > We could have a permission_policy configuration option
> 
> Since we are providing fine grained permissions, permission policy map might get too big. I was thinking to keep that in a separate file. If we dont want to give fine grained permissions and just provide roles, than it make sense to have it in `service.json`

We are not going to let the user configure a permission map. The authorize function corresponding to each policy will be part of the code. We only let the user set a "policy" (and by default we set it for them). At least for the moment. We need to fully control and be able upgrade how permissions look like for each policy.



> Followers would need permissions to run these on other nodes
followers -> anyone.

> 
>     1. PeerAdd (needs to join a cluster)
Yes, everyone should be able to call this. 


>     2. IPFSConnectSwarm (to run PeerAdd)
Yes, in principle, but we might change/move this.

> 
>     3. ID (For ConnectGraph to work, ConnectGraph-->Peers on all members, Peers --> ID on all members)

I had not realized that ConnectGraph needs `Peers()` (and `IPFSwarmPeers`). We can try opening them for everyone, but if there are concerns we can sacrifice this feature and leave it functional only in Raft and for trusted peers in CRDT.
> 
>     4. TrackerRecover*, Sync*, TrackerStatus

For raft everyone can call these.

In `crdt_strict` tracker status should only be callable from trusted peers. in `crdt_soft` trusted peers can call Sync* and TrackerStatus*.  No untrusted peers should be able to call these endpoints.

> I am thinking of adding an extra folder in `~/.ipfs-cluster`, call it `permissions`. `permissions` would have files for each peer, say `<peer.ID>.json`. While running cluster, we would get a map from info stored in this file which we can use in our config.
> (...)

As pointed above, we are not letting users adjust permissions by hand. The only thing will be a hidden "policy" setting and a list of "trusted_peers" (probably in the CRDT config section). The moment we write down and make permissions configurable we lose the ability to upgrade them (or it becomes a big mess), when for example, we need to limit the scope of a policy, or we need to increase it. This will lead to peers with broken permissions one way or another. We can revise this in the future. For a start, Cluster should just work without the safest permission set without the user even touching or knowing anything.

**Comment by kishansagathiya** [comment]
> crdt_strict: default for crdts. Only PeerAdd, ID open to the world. TrackerStatus,TrackerStatusAll open to trusted peers. This policy only allows to follow a pinset but gives no remote control of the peer to anyone (other than pinning/unpinning that happens through consensus).

Without IPFSBlockPut trusted peers won't be able to use `add` command

**Comment by hsanjuan** [comment]
They will be able to use it locally (by setting allocations to themselves and replication factor to 1). We can add an extra flag to facilitate that.

**Comment by kishansagathiya** [comment]
Resolved by https://github.com/ipfs/ipfs-cluster/pull/775 and https://github.com/ipfs/ipfs-cluster/pull/773
