### ISSUE TITLE
add warning that configuration with environment variables for cluster wont show in service.json

### ISSUE THREAD

**Issue by petscheit** [ipfs/ipfs-cluster#667]
As I learned today, when configuring the ipfs-cluster-service with environment variables not all changes will be written to service.json, while others are.
For example, when setting the CLUSTER_SECRET environment variable, the secret will be written to the service.json file. When setting other variables like CLUSTER_REPLICATIONFACTORMIN the changed will take affect, but wont be written to service.json. I think it's pretty confusing and should be mentioned in the [docs](https://cluster.ipfs.io/documentation/configuration/#using-environment-variables-to-overwrite-configuration-values).

**Comment by hsanjuan** [comment]
Hi, we are working on a better approach at #663 where behaviour will be what you expect.

**Comment by hsanjuan** [comment]
Just merged #663 so this should be fixed.
