### ISSUE TITLE
Pin to cluster using Go API

### ISSUE THREAD

**Issue by akshitababel** [ipfs/ipfs-cluster#668]
I am running an ipfs cluster in the background and I want to pin an hash of a file I pushed to ipfs using go API. I want to use the same cluster running in background and not intialise new cluster. Can someone please explain using an example that how can I use the cluster running in background in my golang API and pin the hash.

**Comment by hsanjuan** [comment]
Hi,

If I understand you well, you can use the cluster go-api client: https://godoc.org/github.com/ipfs/ipfs-cluster/api/rest/client .

Alternatively you can use the go-ipfs Go API client configured against the Cluster proxy endpoint: https://cluster.ipfs.io/documentation/composite-clusters/#the-ipfs-proxy

**Comment by akshitababel** [comment]
@hsanjuan  If i have no peer connected in the cluster, and i try to pin the hash, will I get the msg failed to next-bad access

**Comment by akshitababel** [comment]
```
func ReplicateHash(hash string) error {
	ID, err := cid.Decode(hash)
	if err != nil {
		return err
	}
	var clt client.Client
	err = client.Client.Pin(clt, context.Background(), ID, 0, 8, "http")
	if err != nil {
		return err
	}

	return nil
}

```
I am using above function to pin a hash and in backhround i have ipfs cluster daemon running. Is this correct?

**Comment by hsanjuan** [comment]
You need to use https://godoc.org/github.com/ipfs/ipfs-cluster/api/rest/client#NewDefaultClient first. You are calling an interface method with an unconfigured client. I'm surprised it even compiles.

See https://github.com/ipfs/pinbot-irc/blob/master/main.go for an example on how to use `client`. Or https://github.com/hsanjuan/gx2cluster/blob/master/main.go#L109 .

Also, please don't ping people randomly.

**Comment by kishansagathiya** [comment]
This is more of a discussion or helping out a user. @hsanjuan close this?

**Comment by hsanjuan** [comment]
@kishansagathiya we also use issues to discuss and help users.

@akshitababel please re-open if you need more help, or head over to https://discuss.ipfs.io/c/help/help-ipfs-cluster. Thanks!
