### ISSUE TITLE
Error in the package

### ISSUE THREAD

**Issue by akshitababel** [ipfs/ipfs-cluster#669]
Installed the latest version of ipfs-cluster. There are some error in package:-
1. https://github.com/ipfs/ipfs-cluster/blob/master/adder/ipfsadd/add.go#L105
too many arguments in call to balanced.Layout
have (*helpers.DagBuilderHelper, error)
want (*helpers.DagBuilderHelper)

2. https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go#L746
c.dht.BootstrapOnSignal undefined (type *dht.IpfsDHT has no field or method BootstrapOnSignal)

**Comment by lanzafame** [comment]
@akshitababel how are you installing the dependencies? Try `make install`

**Comment by akshitababel** [comment]
I am using go get github.com/ipfs/ipfs-cluster.

**Comment by lanzafame** [comment]
Use `make install`

**Comment by hsanjuan** [comment]
@akshitababel there is very extensive and detailed documentation here, particularly on how to install/build: https://cluster.ipfs.io/documentation/
