### ISSUE TITLE
Architectural limits for scale?

### ISSUE THREAD

**Issue by gaillard** [ipfs/ipfs-cluster#672]
I noticed the tested deployments are not huge. But are there any known architectural / hacks / temporary solutions that prevent deployment at a scale of something akin to hundreds of thousands of nodes each with hundreds of thousands of pins?

**Comment by lanzafame** [comment]
The use of raft as the consensus mechanism between cluster peers is what
prevents such scale. This is something that is being addressed currently
with the development of a new consensus layer that uses CRDTs instead,
should allow for the scale you mention, though may be not immediately but
that is the goal.

**Comment by hsanjuan** [comment]
I should add that there are some additional limitations to reach coordination between hundreds of thousands of peers (top of my head, I cannot think of many examples that scale to hundreds of thousands of something). I'm happy reaching the hundreds for the moment.

On a second thought, theoretically, you could do cluster composition to any scale. But I haven't tried with hundreds of thousands of peers yet. :)

**Comment by hsanjuan** [comment]
I will close this for now (doing issue clean-up and this is not actionable). I'd encourage any further discussion to happen on https://discuss.ipfs.io .
