### ISSUE TITLE
feature request: full text and fact search using bleve

### ISSUE THREAD

**Issue by joeblew99** [ipfs/ipfs-cluster#68]
bleve is like elastic search, but 100% go.
Its mature and many projects use it.

For IPFS it would provide very powerful search.

Its also very easy to integrate.
dgraph got it in in just a week for example

https://github.com/dgraph-io/dgraph/issues/592

Please consider this at least and discuss.

**Comment by hsanjuan** [comment]
ipfs cluster does not hold data that you can run full text search on. I'm not sure I understand this request... can you ellaborate on what you would like to do?

**Comment by joeblew99** [comment]
i found a few projects on top of IPFS that do search now.
they are using elastic search, but i will fork and change to use bleve.

**Comment by gedw99** [comment]
Hey @hsanjuan picking this up again :)   

I think IPFS does have data you can index and search on. It can index and search anything as long as a mapper is present.

http://www.blevesearch.com/docs/Index-Mapping/

The way it works is really this: https://github.com/RoaringBitmap/roaring

**Comment by lanzafame** [comment]
@gedw99 Sorry, could you elaborate the use case of full-text search within the context of IPFS Cluster specifically?

**Comment by gedw99** [comment]
Enterprise level search is a combination of free text search and facetted search. Facetted search is like what Amazon looks like where the system automatically created categories you can search by.

So I just think that this sort of search is a great thing for a content system.

There is a nice cluster wrapper of bleve called blast that is a pretty good fit for ipfs cluster.

The link:

https://github.com/mosuka/blast

I am pretty sure the team will need support this usecase. But anyway a way o easily add it as a " Microservice" of sorts or " plugin" might be a suitable option too for the team.

Anyway i am curious to know what others think.

**Comment by lanzafame** [comment]
@gedw99 we are looking at supporting some very different datasets which will require very different index algorithms, i.e. geographical, genomic, archival. It may be worth looking at specing out some sort of `Search` interface that will allow for 'plug n play' of different indexing mechanisms, of which bleve would be a candidate.

**Comment by gedw99** [comment]
Well it's good you at least want search.

Pilossa I would also look at.great for huge data stores with very fast
indexing and retrieval.

Bleve interface is very simple. The blast project I referenced is a good
basis I think.

What serialisation and transports do you want to support ?
Do you want to make it work via a bus like NATS. Allows things to buffer
and catch-up of course. It's a pretty good way to join up different
databases / Microservice.

**Comment by eocarragain** [comment]
I think @vmx is the man to talk to about search on IPFS/IPLD in general (rather than ipfs-cluster specifically)? Agree with @lanzafame that different/configurable indexing strategies will be need for different data sets/use-cases/applications. Presumably more specific cases can be handled higher up the stack too.

**Comment by vmx** [comment]
If you're interested in search, please also follow/comment on the issue at the IPLD repo: https://github.com/ipld/ipld/issues/43

**Comment by gedw99** [comment]
Hey all

Had a look at the repo you suggested.

Noise is rust with nodejs API.

Don't mean to be a pain but.. nodejs on backend is not right. Ipfs is
golang on the backend and core search is a large area and should be in
golang.

I posted my proposal in the comments section as the readme asked.
