### ISSUE TITLE
Remove basic monitor

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#689]
I'd like to propose the removal of the `basic` monitor component, which is not used by default since a few releases ago the `pubsub` monitor was introduced.

Removing affects tests (which have setup code to run with either of them), `ipfs-cluster-service` (which can select it) and a travis stage.

Thoughts @lanzafame ?

**Comment by lanzafame** [comment]
@hsanjuan sounds good.
