### ISSUE TITLE
CIDs remain PINNING after restart 

### ISSUE THREAD

**Issue by taoxinyi** [ipfs/ipfs-cluster#695]
#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

I have 3 peers(peer1,2,3) and they are both connected well. Then I stop the `ipfs-cluster-service` on peer1 and add and pin some files on peer2, then reconnect on peer1 by using `ipfs-cluster-service daemon`, then the status of the files is always `PINING`. I've also restarted IPFS daemon and the status is still hanging. 

`ipfs diag cmds -v` on peer1, all the following CID are pinned during the downtime of peer1, and they keep hanging and cannot become `PINNED`.
```
6    refs       [QmfVNBKSMTSFVGr1NNQ7rgPg9iATSuxqUhpKDJkhSGw348]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:19  12m39.313528718s
7    refs       [QmQkcoajZV5D5GySjdHrfydaJs4XJCEEYPM3wdikRQKiy6]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:19  12m39.313188919s
9    refs       [QmUhUC7RyQu5BBxJkCSrEXMJ8yVCEpTRNMr2ctoXVQZVpZ]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:19  12m39.312623135s
25   refs       [QmYWV6i9kWiaizzAdLnQu5fbTZ4JjVyZZAu1DEHJ7pDaRf]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:20  12m39.117007801s
26   refs       [QmY7nH7XHUm5GYTYAmaN4w9vf8sZnx6rXe9RT3vdQ9ASTb]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:20  12m39.116701101s
27   refs       [QmcVrWhuwfjcdaeCauxC4Gikyvcv2Mzkpuz8jYTdbe5nEs]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:20  12m39.115900233s
30   refs       [QmdgcpDVdfqNLceVnq8snTJf346Pk9uvskS7AfCAj9UdXr]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:20  12m39.115487171s
31   refs       [QmSd5MotHEVHvzKTQnTbXcB3Y5EEEtQyhdTYEqyHfYSviJ]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:20  12m39.115084281s
32   refs       [QmbY6yFRgik3gB729JTDjLVT66osWCQtwrznWXUovc3wmA]  [encoding=json,format=<dst>,max-depth=-1,recursive=true,]  true    Mar  3 14:25:20  12m39.11490894s
111  diag/cmds  []                                                [encoding=json,stream-channels=true,verbose=true,]         true    Mar  3 14:37:59  749.139µs
```
Take `QmcVrWhuwfjcdaeCauxC4Gikyvcv2Mzkpuz8jYTdbe5nEs` for example:
```
root@iZwz95bh2113hlhycqk30qZ:~# ipfs-cluster-ctl status QmcVrWhuwfjcdaeCauxC4Gikyvcv2Mzkpuz8jYTdbe5nEs
QmcVrWhuwfjcdaeCauxC4Gikyvcv2Mzkpuz8jYTdbe5nEs :
    > instance-5eh429qh : PINNED | 2019-03-03T06:16:32Z
    > iZuf65lasa7ruhetcschmwZ : PINNED | 2019-03-03T06:16:32Z
    > iZwz95bh2113hlhycqk30qZ : PINNING | 2019-03-03T06:25:20Z
```
I assume the excepted behavior is that once peer1 becomes online, these CIDs pinned during its downtime should be be pinned. However, it stuck and hang on `PINNED`

Besides, when peer1 is down and I add&pin some files by peer2, peer3 has error
```
Failed to make RequestVote RPC to {Voter QmfFYQj1QtnuFAJyUs6UYCPALzmoVecGXsjgf3ZnEF4Psh QmfFYQj1QtnuFAJyUs6UYCPALzmoVecGXsjgf3ZnEF4Psh}: dial attempt failed: <peer.ID Qm*juKcwt> --> <peer.ID Qm*EF4Psh> dial attempt failed: context deadline exceeded
```
When I add&pin some files during this time, these CIDs will be `PINNING` on peer3 as well.

**Comment by hsanjuan** [comment]
This is an IPFS daemon issue. As you see, the commands have arrived. They are stuck on the go-ipfs side because that IPFS daemon cannot find providers for those new hashes. It status is `PINNING` it is because things are pinning on the ipfs side. Verify your ipfs daemon is finding providers for the content.

**Comment by hsanjuan** [comment]
It could also be that it's taking very long for ipfs to download the content

**Comment by hsanjuan** [comment]
>> Failed to make RequestVote RPC to {Voter QmfFYQj1QtnuFAJyUs6UYCPALzmoVecGXsjgf3ZnEF4Psh QmfFYQj1QtnuFAJyUs6UYCPALzmoVecGXsjgf3ZnEF4Psh}: dial attempt failed: <peer.ID Qm*juKcwt> --> <peer.ID Qm*EF4Psh> dial attempt failed: context deadline exceeded

That is normal, your peer is down, so errors are shown when connection attempts to it are made, but as you saw, the operation of adding a pin is correctly submitted.

**Comment by taoxinyi** [comment]
@hsanjuan I update the version of `ipfs` and it seems fine now. I have one problem though, will `ipfs-cluster-ctl pin add` make every node in the cluster copy the file on their own local disk? If not so, how to make that behavior in the cluster? Thanks a lot!

**Comment by hsanjuan** [comment]
@taoxinyi depends on the replication factors you have assigned for the pin, and the default.

The default is used when no replication factor is specified, and it's configurable in the `service.json` file. The value `-1` means "pin everywhere".

**Comment by taoxinyi** [comment]
@hsanjuan If I use `ipfs-cluster-ctl pin add` to upload a file in one node, all the other nodes in the cluster will automatically download the copy to local if `replication factor` is `-1`?

**Comment by hsanjuan** [comment]
@taoxinyi `ipfs-cluster-ctl pin add` does not upload, it asks the ipfs nodes to pin a file. If replication_factor_min and replication_factor_max is -1, then all ipfs nodes in the cluster will download and pin the file.

`ipfs-cluster-ctl add` does upload a file. The replication factor has the same meaning, with the difference that the resulting file blocks are pushed directly to their destinations.
