### ISSUE TITLE
proxy: "extract_headers_path" and "extract_headers_ttl" should be hidden options in the config

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#698]
@kishansagathiya can you take care of this one? I think it's just setting the default to ""  for the path. For the ttl, probably set to 0 and omit set manually to "" if value is 0 (instead of doing String()).

**Comment by kishansagathiya** [comment]
@hsanjuan Sure

**Comment by kishansagathiya** [comment]
Can you put some context on why we need this?

**Comment by hsanjuan** [comment]
These fields control some internals that the regular user should not mess with.
