### ISSUE TITLE
Cannot build on Android because the build script ignores the installed gx

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#703]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [ ] Linux
  * [ ] macOS
  * [ ] Windows
  * [x] Other : Android
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

Can't build on Android.

1. There's no `gx` for `android-arm64` on IPFS.io : https://ipfs.io/ipns/dist.ipfs.io/gx/v0.14.1/gx_v0.14.1_android-arm64.tar.gz
2. The build script completely discards the already-installed `gx`

```log
make install
make -C deptools gx
make[1]: Entering directory '/data/data/com.termux/files/home/go/src/github.com/ipfs/ipfs-cluster/deptools'
Downloading gx
rm -f gx
wget -nc http://127.0.0.1:8080/ipns/dist.ipfs.io/gx/v0.14.1/gx_v0.14.1_android-arm64.tar.gz || wget -nc https://ipfs.io/ipns/dist.ipfs.io/gx/v0.14.1/gx_v0.14.1_android-arm64.tar.gz
Connecting to 127.0.0.1:8080 (127.0.0.1:8080)
wget: server returned error: HTTP/1.1 404 Not Found
wget: not an http or ftp url: https://ipfs.io/ipns/dist.ipfs.io/gx/v0.14.1/gx_v0.14.1_android-arm64.tar.gz
make[1]: *** [Makefile:27: gx_v0.14.1] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/go/src/github.com/ipfs/ipfs-cluster/deptools'
make: *** [Makefile:40: gx] Error 2
```

Instead of using `wget`, the script should use `go get`. Since we're already building IPFS Cluster, I'm pretty sure no one would mind building `gx` alongside it.

**Comment by hsanjuan** [comment]
There is intentionality in a) using a pre-built stable version of gx that doesn't depend on the user environment b) trying to fetch it from IPFS. However your problems will disappear as soon as we switch to `go mod` (very soon).

**Comment by hsanjuan** [comment]
We introduced go.mod so this should be fixed.

**Comment by NatoBoram** [comment]
I *can* run `GO111MODULE=on go get -u .`, but `make install` is still stuck trying to build without `go.mod`.

```
make install
make -C cmd/ipfs-cluster-service install
make[1]: Entering directory '/home/nato/go/src/github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-service'
go install -ldflags "-X main.commit=543656aa832d6399e72f87f20e840d16abe93c11"
../../observations/setup.go:12:2: cannot find package "go.opencensus.io/exporter/jaeger" in any of:
	/snap/go/3584/src/go.opencensus.io/exporter/jaeger (from $GOROOT)
	/home/nato/go/src/go.opencensus.io/exporter/jaeger (from $GOPATH)
../../observations/setup.go:13:2: cannot find package "go.opencensus.io/exporter/prometheus" in any of:
	/snap/go/3584/src/go.opencensus.io/exporter/prometheus (from $GOROOT)
	/home/nato/go/src/go.opencensus.io/exporter/prometheus (from $GOPATH)
Makefile:12: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/nato/go/src/github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-service'
Makefile:20: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by hsanjuan** [comment]
We don't set GO111MODULE=on in the makefile explicitally, but it should work if you do.

**Comment by NatoBoram** [comment]
Considering it's impossible to build it without `

**Comment by hsanjuan** [comment]
It's not impossible, but yeah maybe. If you check out the repo outside $GOPATH it should just work though. Probably we can address this in #765 .
