### ISSUE TITLE
Need to migrate uuid package as github.com/satori/go.uuid is unmaintained

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#707]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

Need to move to either [github.com/google/uuid](https://github.com/google/uuid) in line with IPFS or to the community maintained fork of github.com/satori/go.uuid, [github.com/gofrs/uuid](https://github.com/gofrs/uuid).

This became apparent when attempting to introduce go modules to cluster. 

@hsanjuan I am going to default to github.com/google/uuid and move forward with that for now.

**Comment by hsanjuan** [comment]
Fixed by #708
