### ISSUE TITLE
Using ipfs-cluster-ctl add <url> when disk is full results in empty dir hash and no error code

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#709]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

##### What's happening

When the disk is full, using `ipfs-cluster-ctl add -w --chunker=rabin <url>` outputs the empty directory hash, `QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn`.

##### What should happen

The command should stop with an error code.

**Comment by hsanjuan** [comment]
Hmm, can you test what happens when you write a block directly to ipfs `ipfs block put` while your disk is full? (should fail)

**Comment by NatoBoram** [comment]
Sorry, I kinda cleaned up that node, I can't test it.

**Comment by hsanjuan** [comment]
I'm going to close this because it's an edge case, and I'm not sure about the fix.
