### ISSUE TITLE
`peers ls` (and possibly other broadcast commands) fail when a peer is down

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#715]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [x] macOS
  * [x] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [x] Built from sources
  * [x] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

Pretty sure this is null-multiaddress related: https://discuss.ipfs.io/t/has-anyone-seen-this-error-cannot-unmarshal-object-into-go-struct-field/5007/4

70% sure that fix involves fixing deserialization of our `types.go/Multiaddr` or is somewhat related (either Undef cids or multiaddresses).

**Comment by kishansagathiya** [comment]
> 70% sure that fix involves fixing deserialization of our types.go/Multiaddr or is somewhat related (either Undef cids or multiaddresses).

Yup, failing during unmarshaling https://github.com/ipfs/ipfs-cluster/blob/508131081124bc8289b762ffb7e0e0572798e9be/api/rest/client/request.go#L118

**Comment by kishansagathiya** [comment]
This is happening because if a peer in down, on `peer ls` IPFSID is empty. 
```
type IPFSID struct {
	ID        peer.ID     `json:"id" codec:"i,omitempty"`
	Addresses []Multiaddr `json:"addresses" codec:"a,omitempty"`
	Error     string      `json:"error" codec:"e,omitempty"`
}
```

If I just omitempty `ID` from `IPFSID`, thing would work with a message for the peer which is down, like
```
<peer.ID Qm*trvuVP> | ERROR: dial backoff
```

**Comment by kishansagathiya** [comment]
Resolved with https://github.com/ipfs/ipfs-cluster/pull/719
