### ISSUE TITLE
How to configure more than one addresses for "http_listen_multiaddress" in service.json

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#716]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [ ] Enhancement
  * [x] Help
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description
The detailed steps are below:
1.Set up a IPFS cluster with two nodes. It is successful.
2.In node1, use REST API to get pins:
curl 127.0.0.1:9094/pins
It is successful
3.Modify http_listen_multiaddress in service.json to "/ip4/0.0.0.0/tcp/9094", and then access the REST API from another node. It is successful.
4.Modify http_listen_multiaddress in service.json to "/ip4/0.0.0.0/tcp/9094,/ip4/192.168.1.2/tcp/9094" or "/ip4/0.0.0.0/tcp/9094 /ip4/192.168.1.2/tcp/9094". Restart ipfs-cluster-service, and it failed because the http_listen_multiaddress format can't be parsed.
So the question comes: how to configure more than one addresses for http_listen_multiaddress in service.json? What is the format? What is the delimiter between different addresses? It seems no documentation presents this. Thanks in advance.

**Comment by kishansagathiya** [comment]
@CoreyLin It is not possible to set more that one `http_listen_multiaddress`
https://github.com/ipfs/ipfs-cluster/blob/508131081124bc8289b762ffb7e0e0572798e9be/api/rest/config.go#L65-L66

**Comment by kishansagathiya** [comment]
I am not sure why you will need two listen multiaddresses.
Keep in mind that each peer sets listen multiaddress for its own on its service.json. So, if you are trying to set up for other peer you will have to do there on its own service.json.

**Comment by hsanjuan** [comment]
hi @CoreyLin , `/ip4/0.0.0.0/tcp/9094` should be the equivent to "listen on all interfaces", so you would not need the others in the list. Can you give more details about why you'd need more listeners?

**Comment by CoreyLin** [comment]
@hsanjuan @kishansagathiya For example, if the host of a peer has 3 network cards, namely 3 ip addresses. But in some cases, if the business requirement is that only listening 2 ip addresses out of 3. Currently I don't meet such business requirement, but I think it is a reasonable and common requirement. When I saw the field name starting with "multi", I intuitively thought more than one ip addresses can be configured. Can it be realized from technical point of view? Thanks.

**Comment by hsanjuan** [comment]
@CoreyLin a multiaddress is actually this: https://github.com/multiformats/multiaddr

> Can it be realized from technical point of view?

It can, and it's a perfect feature for an external contribution if you want to work on it ;)

**Comment by CoreyLin** [comment]
@hsanjuan Thanks very much for your help. I didn't get the multiaddr concept before.

IPFS cluster is a great project. 👍
