### ISSUE TITLE
Would cluster speed up ipfs?

### ISSUE THREAD

**Issue by hoogw** [ipfs/ipfs-cluster#717]
I have 2 node (workplace faster A and home slower B), hosting the same content. 
If I run cluster on those 2 node, client will loading from node A or node B?

Or cluster does not make client loading faster, irelative to ipfs.
Cluster only auto replicate content between A and B.   I only add content at A node once, not need to add same content again at B node, it will help to replicate over to B?

**Comment by hoogw** [comment]
Am I right, no mater you setup cluster or not, ipfs loading speed is same, 
loading manner has no change. 

cluster is irelavent, only helps on other side of ipfs, not speed up anything.

**Comment by hsanjuan** [comment]
I think you are right, content is still hosted an provided by ipfs. Cluster only asks IPFS daemons to pin content. Re-open if needed!
