### ISSUE TITLE
[docker] ipfs-cluster-ctl add https x509 error

### ISSUE THREAD

**Issue by jmank88** [ipfs/ipfs-cluster#730]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [x] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

Adding `https://` URLs results in an error:
```
> ipfs-cluster-ctl add <url>
An error occurred:
  Code: 0
  Message: <omitted>: Get <url>: x509: certificate signed by unknown authority
```
Pure `go-ipfs` handles the same URLs without error.

**Comment by hsanjuan** [comment]
is the `url` certificate signed by an unknown authority?

I'm not sure this is a bug. You may request a feature consisting in being able to bypass SSL errors though. Also, what do you mean go-ipfs handles the same url without errors? `go-ipfs` cannot "add  urls, do you mean the urlstore commands?

**Comment by jmank88** [comment]
The URL is from google firebase storage. `go-ipfs` can add URLs, as of this past week.

**Comment by hsanjuan** [comment]
Seeing that you added support from this in [go-ipfs-cmds](https://github.com/ipfs/go-ipfs-cmds/blob/master/cli/parse.go#L290) and that this is very similar to what cluster does here https://github.com/ipfs/ipfs-cluster/blob/master/api/rest/client/methods.go#L515, I am not sure the same `go-ipfs-files` code could result in a ssl error in cluster but not an ssl error go-ipfs.

Discarding that, it must be an issue with root certificates not being available in the system, particularly the cluster docker image. Are you running the go-ipfs docker image? Could you verify if this is actually the problem?

**Comment by jmank88** [comment]
I am running `ipfs/go-ipfs:master` alongside `ipfs/ipfs-cluster:latest` via docker-compose, and am able to add the same URL without error.

**Comment by jmank88** [comment]
Perhaps the cluster Dockerfile needs something like this? https://github.com/ipfs/go-ipfs/blob/master/Dockerfile#L33-L34

**Comment by hsanjuan** [comment]
yes, precisely, installing in the builder and copying to the final image (https://github.com/ipfs/go-ipfs/blob/master/Dockerfile#L46)

**Comment by hsanjuan** [comment]
Wanna submit a PR?
