### ISSUE TITLE
[Proxy] Intercept pin/update

### ISSUE THREAD

**Issue by ianopolous** [ipfs/ipfs-cluster#732]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description
It would be great to also intercept the pin update command. For us in [Peergos](https://github.com/peergos/peergos), 99% of our calls are pin update, and we'd love to use ipfs-cluster for large deployments.

**Comment by ianopolous** [comment]
My guess is this should be relatively easy to multiplex over the existing pin.add interception, using the same algorithm as in pin.update in go-ipfs, and sending the new roots to cluster pin rather than ipfs pin.

**Comment by hsanjuan** [comment]
Thanks for bringing this to our attention. I did not know that go-ipfs now included a `/pin/update` endpoint. We can easily simulate (1) Pin new pin 2) Unpin the previous). It is significantly more difficult to do it in a way that uses `pin/update` though, which is meant to be more efficient.

(labelled as bug since the proxy should handle all pin operations as cluster operations).

**Comment by ianopolous** [comment]
No worries, @hsanjuan. Note that unpinning the old root is optional (we always call it with unpin set to false, and use a separate call to pin.rm after we have committed the transaction externally). 
At least in that case your interception would only need to call cluster.pin, not cluster.unpin. 

Speed does matter though. We essentially have a huge CHAMP for a user's filesystem, and a write only modifies a leaf (and the log(n) nodes to the root) and so pin update is exponentially faster than just pin.

**Comment by ianopolous** [comment]
Could this use the same algorithm (dagutils.DiffEnumerate) as in go-ipfs and use the resulting pairs of hashes to send pin.update to the ipfs nodes that have the prior hash?

**Comment by hsanjuan** [comment]
> Could this use the same algorithm (dagutils.DiffEnumerate) as in go-ipfs and use the resulting pairs of hashes to send pin.update to the ipfs nodes that have the prior hash?

Cluster does not really have access to the DAGs that are pinned (only though IPFS). Doing this would require that Cluster has a specific `Cluster pin update` operation that ends up calling the `pin/update` one on the IPFS daemons that have allocated certain pin (and skips the normal pin-allocation codepath).  It's not super difficult, but it touches multiple cluster components.

I propose we do it the dumb way asap, and we put the efficient way on the todo list to do once we're done with the crdt things.

**Comment by hsanjuan** [comment]
@ianopolous so now you should be able to take advantage of this as `pin/update` is called on ipfs when pinning with cluster.

**Comment by ianopolous** [comment]
Fantastic! That's awesome! Looking forward to trying it out! Thank you so much.
