### ISSUE TITLE
repeating add results in 500 malformed HTTP response \x15\x03\x01\x00\x02\x02\x16

### ISSUE THREAD

**Issue by jmank88** [ipfs/ipfs-cluster#733]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [x] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

On a freshly started peer, executing a `ipfs-cluster-ctl add <url>` command is successful, but repeating the command (with same url) results in failures as soon as the second attempt, but sometimes later. Once it fails, it continues to fail on subsequent runs. Restarting the cluster container 'resets the state' in some way, and allows at least one initial success again before returning to the same state. The error is a bit cryptic:
```
An error occurred:
  Code: 500
  Message: Post http://127.0.0.1:5001/api/v0/block/put?f=v0: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
```
Perhaps this is only an indirect secondary failure, but the logs don't provide any more info.

**Comment by jmank88** [comment]
This actually appears to depend on time, not number of requests. The first request will fail, if enough time passes after start-up.

**Comment by jmank88** [comment]
Occasionally a different error will occur:
```
An error occurred:
  Code: 500
  Message: Post http://127.0.0.1:5001/api/v0/block/put?f=v0: net/http: HTTP/1.x transport connection broken: write tcp 127.0.0.1:34422->127.0.0.1:5001: write: broken pipe
```

**Comment by jmank88** [comment]
Possibly related, `id` returns this error:
```
> ipfs-cluster-ctl id
<cid> | <name> | Sees 1 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/<cid>
    - /ip4/172.23.0.4/tcp/9096/ipfs/<cid>
    - /p2p-circuit/ipfs/<cid>
  > IPFS ERROR: Post http://127.0.0.1:5001/api/v0/id: dial tcp 127.0.0.1:5001: connect: connection refused
```
However, I am able to hit `http://127.0.0.1:5001/api/v0/id` both from within the `cluster` container and outside docker.

**Comment by hsanjuan** [comment]
Weird. Are you able to block/put too, repeatedly, some random data to ipfs? Are there any chances that ipfs crashed but the container was auto-restarted and you didn't notice?

**Comment by jmank88** [comment]
> Weird. Are you able to block/put too, repeatedly, some random data to ipfs?

Yes, `ipfs block put` does not cause an error. In fact, no manual ipfs call errors (neither via the cli or curl).

> Are there any chances that ipfs crashed but the container was auto-restarted and you didn't notice?

Doesn't appear to be the case.

This does not seem related to any particular operation. It behaves more like a configuration problem, but the delayed effect is throwing me off. Could the success be a false positive? Does a successful add _necessarily_ mean that cluster successfully performed calls to ipfs synchronously? Or could it just mean e.g. that it was added to the cluster pin set, and will eventually make it to the nodes? I'll keep experimenting.

**Comment by jmank88** [comment]
Based on some googling, this could happen when attempting to make a HTTP request to an HTTPS endpoint, but I haven't explicitly configured HTTPS.

**Comment by jmank88** [comment]
This isn't exactly an explanation, but I resolved the problem by configuring the `node_multiaddress` fields in `service.json` manually. I didn't realize that the `IPFS_API` env var is only used on the initial run, and won't be picked up if changed later.
