### ISSUE TITLE
Installing from source appears to be broken

### ISSUE THREAD

**Issue by obo20** [ipfs/ipfs-cluster#736]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
* [x] Type (mark as appropiate):
  * [x] Bug
* [x] Operating system (mark as appropiate):
  * [x] Linux
* [x] Installation method (mark as appropiate):
  * [x] Built from sources

#### Description

Building from source with GoLang 1.12.1 seems to be broken.

I follow the instructions exactly, and receive the following error

```
matt@ubuntu-s-1vcpu-1gb-nyc3-01:~/go/src/github.com/ipfs/ipfs-cluster$ make install
make -C cmd/ipfs-cluster-service install
make[1]: Entering directory '/home/matt/go/src/github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-service'
go install -ldflags "-X main.commit=1889ea06f1840cfbd122a63d21ffc21f15c06d9f"
main.go:17:2: cannot find package "github.com/blang/semver" in any of:
	/usr/local/go/src/github.com/blang/semver (from $GOROOT)
	/home/matt/go/src/github.com/blang/semver (from $GOPATH)
../../adder/sharding/dag_service.go:16:2: 
.
. (repeated messages for about 20 other packages)
.
.
Makefile:12: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/matt/go/src/github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-service'
Makefile:20: recipe for target 'install' failed
make: *** [install] Error 2
```

It appears to be somewhat related to this error here: https://github.com/ipfs/ipfs-cluster/issues/92

Oddly, if I remove the "src" from the instructions listed in the documentation (which is the opposite of what the issue I linked says to do), then the installation succeeds, but ipfs-clusters files / dependencies are all over the place instead of the desired /src/ folder

```
git clone https://github.com/ipfs/ipfs-cluster.git $GOPATH/src/github.com/ipfs/ipfs-cluster
cd $GOPATH/src/github.com/ipfs/ipfs-cluster
make install

changes to

git clone https://github.com/ipfs/ipfs-cluster.git $GOPATH/github.com/ipfs/ipfs-cluster
cd $GOPATH/github.com/ipfs/ipfs-cluster
make install
```

My .profile file is as follows:
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export GOPATH="$HOME/go"
export PATH=$PATH:/usr/local/go/bin
PATH="$GOPATH/bin:$PATH"

**Comment by jmank88** [comment]
Looks like it could be a `go mod` problem. Do you have the env var `GO111MODULE=on` set? Alternatively, checking out the source somewhere outside of `GOPATH` will automatically turn on modules.

**Comment by obo20** [comment]
@jmank88 I do not have that env var set. I even set export GO111MODULE=off in my terminal and the make install command still failed

I agree though, this does seem to be an issue with GoLangs new modules.

**Comment by jmank88** [comment]
It must be set to `on`, or the project must be outside of GOPATH (with the default value of `auto`).

**Comment by NatoBoram** [comment]
One way I've found to make it work regardless is to download dependencies manually.

```shell
#!/bin/sh

# Make sure you're not in $GOPATH
cd

# Go Get - IPFS
go get -u -v -fix github.com/ipfs/go-ipfs

# Go Get - IPFS Cluster
rm -rf ~/go/src/github.com/ipfs/ipfs-cluster
go get -u -v -fix github.com/ipfs/ipfs-cluster

# Dependencies
go get -u -v -fix github.com/gorilla/mux
go get -u -v -fix github.com/hashicorp/raft
go get -u -v -fix github.com/hashicorp/raft-boltdb
go get -u -v -fix github.com/hsanjuan/go-libp2p-gostream
go get -u -v -fix github.com/hsanjuan/go-libp2p-http
go get -u -v -fix github.com/ipfs/go-fs-lock
go get -u -v -fix github.com/libp2p/go-libp2p-consensus
go get -u -v -fix github.com/libp2p/go-libp2p-pubsub
go get -u -v -fix github.com/libp2p/go-libp2p-raft
go get -u -v -fix github.com/rs/cors
go get -u -v -fix go.opencensus.io/vendor/google.golang.org/api/support/bundler
go get -u -v -fix google.golang.org/api/support/bundler
go get -u -v -fix google.golang.org/genproto/googleapis/rpc/status
go get -u -v -fix github.com/zenground0/go-dot
go get -u -v -fix github.com/prometheus/client_golang/prometheus
go get -u -v -fix github.com/prometheus/client_golang/prometheus/promhttp

# Make Install - IPFS
cd ~/go/src/github.com/ipfs/go-ipfs
make install

# Make Install - IPFS Cluster
cd ~/go/src/github.com/ipfs/ipfs-cluster
make install

cd
```

**Comment by obo20** [comment]
@jmank88 Thanks for the solution. Setting the variable to `on` fixed the issue for me. This is probably something that should be added to the documentation since I'd imagine most people don't know about this environmental variable

**Comment by jmank88** [comment]
Great!

IIRC, modules should be on by default in the next golang release. We're just in a weird transition period right now.

**Comment by hsanjuan** [comment]
Hi, sorry for the trouble everyone. Master is unreleased and includes the upgrade to go modules. The documentation only applies to the last tagged release and will be updated accordingly for the next release. It is necessary to `export GO111MODULE=on` to correctly build cluster (or do it outside the GOPATH).
