### ISSUE TITLE
[help wanted]ERROR  basichost: DiscoverNAT error: no NAT found natmgr.go:96

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#740]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [ ] Enhancement
  * [*] Help
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [x] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

When I start up ipfs cluster peer with the docker run command "docker run -v ~/.ipfs-cluster:/data/ipfs-cluster -e CLUSTER_SECRET=87891a1f34d9898a9bdfad16297305740ce33b6b7602b89f9061b00caf092b71 -p 9094:9094 -p 9095:9095 -p 9096:9096 ipfs/ipfs-cluster daemon", there is always an ERROR "ERROR  basichost: DiscoverNAT error: no NAT found natmgr.go:96" in the log output. Both ipfs cluster peers in my cluster have this error. What does this ERROR mean? Does it have any impact on the function of the peer? How to handle it? Thanks very much.

![2cfaa3fe383f632df3f168bc32d1cbb](https://user-images.githubusercontent.com/12689769/55768326-0cadbc80-5aaf-11e9-88aa-2d6703806832.png)

**Comment by CoreyLin** [comment]
The docker image ipfs/ipfs-cluster tag is latest which is published on 27th March.

**Comment by hsanjuan** [comment]
This is because the NAT Manager is enabled on the libp2p host and it logs that message as an error `ERROR`. We could silence `basichost` errors altogether but that seems overkill.

@Stebalien what do you think of making this message an `INFO` ?

**Comment by CoreyLin** [comment]
@hsanjuan At least I did not explicitly configure NAT manager when I deployed the ipfs cluster by docker. Can I understand that this error can be ignored since it doesn't impact ipfs-cluster function?

**Comment by hsanjuan** [comment]
@CoreyLin the cluster libp2p host enables it. The error can be ignored, yeah.

**Comment by CoreyLin** [comment]
@hsanjuan OK. Thanks for your confirmation.

**Comment by CoreyLin** [comment]
However, this error can cause ambiguity, especially for those who are just starting to use ipfs cluster, and they may feel that this error has an impact on the system.

**Comment by hsanjuan** [comment]
> However, this error can cause ambiguity, especially for those who are just starting to use ipfs cluster, and they may feel that this error has an impact on the system.

Agreed..

**Comment by Stebalien** [comment]
We've dropped it to an info, it'll be included in the next release.

**Comment by CoreyLin** [comment]
@Stebalien OK. Thanks.
