### ISSUE TITLE
[help wanted]interactive command bash with ipfs-cluster container

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#741]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [ ] Enhancement
  * [x] Help
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [x] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

I installed an ipfs cluster with two peers by docker, and it worked well. Commands can be executed successfully, such as "docker exec amazing_thompson ipfs-cluster-ctl peers ls". But there seems to be no interactive bash to interact with the container. When I executed "docker exec -it amazing_thompson bash", an error was reported.
Could any expert tell me whether or not the container of ipfs-cluster has an interactive window that allows me to enter the container and execute commands? Thanks very much.
Note: the docker image ipfs/ipfs-cluster tag is latest which is published on 27th March.
![914622a55d0d578dcebe8332f6e09dc](https://user-images.githubusercontent.com/12689769/55770335-84331a00-5ab6-11e9-8473-165e679a1b1b.png)

**Comment by kishansagathiya** [comment]
@CoreyLin Use `sh` instead of `bash`
try this `docker exec -it amazing_thompson sh`, it would work.

You can checkout the difference between `sh` and `bash` here https://stackoverflow.com/questions/5725296/difference-between-sh-and-bash

**Comment by lanzafame** [comment]
@CoreyLin we use a busybox container for the runtime ipfs-cluster container, which doesn't include a bash shell. It does have a `sh` shell available. If you **need** bash shell, feel free to edit the following line in the [Dockerfile](https://github.com/ipfs/ipfs-cluster/blob/master/Dockerfile#L30) to a container that includes bash and build it yourself.

**Comment by CoreyLin** [comment]
@kishansagathiya @lanzafame Thanks very much for your operation guide and furthur information. Just now I tried docker exec -it amazing_thompson sh and it worked well. Now it seems sh is enough for me. If necessary I would customize docker file on my own.
