### ISSUE TITLE
[REST API] 500 returned instead of 404 when request DELETE /pins/{cid} for cid that isn't pinned

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#742]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement

#### Description

Making a DELETE request to `/pins/{cid}` for a cid that isn't pinned, a `500` is returned instead of a `404`.

**Comment by kishansagathiya** [comment]
Could be done along with https://github.com/ipfs/ipfs-cluster/issues/657
