### ISSUE TITLE
[REST API] Version endpoint returns json object with capitalized key

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#743]
#### Description

```go
// Version holds version information
type Version struct {
	Version string `json:"Version" codec:"v"`
}
```

The json struct tag _should_ be `json:"version"`. @hsanjuan are we doing this for a compatibility reason with IPFS Companion or something like that? Can we make it consistent?

**Comment by hsanjuan** [comment]
I find it very weird that I would have introduced this bug.

* It should not be like this
* There might be a reason why this is like this
* I don't see that reason right now...

Let's change it.
