### ISSUE TITLE
[help wanted]result check of "ipfs-cluster-ctl pin add <cid>" command

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#744]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [ ] Enhancement
  * [*] Help
* [x] Operating system (mark as appropiate):
  * [*] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [*] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

I am reading https://cluster.ipfs.io/documentation/internals/#pinning-an-item , and have some questions about the process of "ipfs-cluster-ctl pin add" execution.

The third step is "Commiting the pin entry to the log" and the fourth step is "At this point, a success/failure is returned to the user, but cluster has more things to do". My question are:

1. What is the "the log" in step 3?Is it the output log of the "ipfs-cluster-ctl pin add" command, or some other log?
2. After the third step, will the ipfs-cluster-ctl pin add command exit?
3. After the end of the third step, actually cluster still has a lot to do, does it mean that even if "ipfs-cluster-ctl pin add" exits normally, it does not mean that CID has been successfully pinned by all ipfs daemon inside the cluster?
4. If the user needs to know exactly whether the CID has been successfully added, is it necessary to query through "ipfs-cluster-ctl status <cid>" command?

Could any expert help me with these questions? Thanks very much.

**Comment by hsanjuan** [comment]
>  What is the "the log" in step 3?Is it the output log of the "ipfs-cluster-ctl pin add" command, or some other log?

The Raft log. It means that the pin is commited to the consensus layer and once it is there every peer should have it.

>  After the third step, will the ipfs-cluster-ctl pin add command exit?

`ipfs-cluster-ctl pin add` does an additional `status <cid>` after one second automatically. There is a `--no-status` flag to prevent this.

>    After the end of the third step, actually cluster still has a lot to do, does it mean that even if "ipfs-cluster-ctl pin add" exits normally, it does not mean that CID has been successfully pinned by all ipfs daemon inside the cluster?

Particurly, while `pin add` is returning, cluster peers:

1) Get the new pin
2) Ask allocated IPFS daemons to pin it
3) Wait for it to finish

So no, when `pin add` returns, things have not normally finished pinning. There is a `--wait` flag that will wait until the item is pinned or an error happens (by calling `status` in the background).

> If the user needs to know exactly whether the CID has been successfully added, is it necessary to query through "ipfs-cluster-ctl status " command?

Better to call `pin ls <cid>` and check the `allocations`. We will change `pin add` to return this by default when using `--no-status`, but that does not happen yet.

`ls <cid>` is better because it is not a "broadcast" command and the local peer can answer. `status` has to query all cluster peers for status before returning.

**Comment by CoreyLin** [comment]
@hsanjuan Thanks very much for your support. So helpful!

I have just one little question:

> ls <cid> is better because it is not a "broadcast" command and the local peer can answer. status has to query all cluster peers for status before returning.

Official documentation https://cluster.ipfs.io/documentation/ipfs-cluster-ctl/#usage mentioned ipfs-cluster-ctl status "list current status of tracked CIDs (local state)". As I understand it, "ipfs-cluster-ctl status" only needs to read data from the local peer, and does not need to broadcast data to other peers in the whole network, right?

**Comment by hsanjuan** [comment]
Maybe it's badly expressed. Because the state is local to each peer, we need to go and fetch that state from every peer.

**Comment by CoreyLin** [comment]
> Because the state is local to each peer, we need to go and fetch that state from every peer.

OK. Can I understand that "ipfs-cluster-ctl status" will go to all peers to get their local state, and then return all together?

**Comment by hsanjuan** [comment]
> OK. Can I understand that "ipfs-cluster-ctl status" will go to all peers to get their local state, and then return all together?

Yes. The `--local` flag makes it only return information from the local peer.

**Comment by CoreyLin** [comment]
@hsanjuan Thanks very much. I will close this issue.
