### ISSUE TITLE
[help wanted]replication_factor_min and replication_factor_max must be the same for each peer?

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#745]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Description

I am reading https://cluster.ipfs.io/documentation/configuration/#the-cluster-main-section , 
 and it mentions we can configure replication_factor_min and replication_factor_max to specify the peer number to pin an item. Then my question is:

In an ipfs cluster with multiple peers (say, five peers), do these two parameters have to be configured the same for each peer? If not, what would happen and what's the logic behind it?

Could any expert please answer this? Thanks very much.

**Comment by hsanjuan** [comment]
Every pin has a per-pin replication factor (min and max). When this is not specified, the defaults from the configuration are used.

If the defaults are different between cluster peers, the pin objects will have different replication factors depending on the peer that was used to create/pin them.

**Comment by CoreyLin** [comment]
> If the defaults are different between cluster peers, the pin objects will have different replication factors depending on the peer that was used to create/pin them.

Could you please explain this sentence further? Suppose there are three peers: A, B, C in the ipfs cluster.For A,B,C, replication factor(min and max) are respectively 1,2,3. What happens if I execute "ipfs-cluster-ctl add" on peer A? Thanks.

**Comment by hsanjuan** [comment]
Then replication factor will be `1` for that pin because that's the default for the peer you are adding from.

**Comment by CoreyLin** [comment]
@hsanjuan Got it. So it depends on from which peer I add the content. Thanks.
