### ISSUE TITLE
[help wanted]What does output of "ipfs-cluster-ctl status" mean?

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#746]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [ ] Enhancement
  * [x] Help
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [x] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

I added a file using the "ipfs-cluster-ctl add" command, and then queried the status of the CID using "ipfs-cluster-ctl status" command.There are two items in the command output, and each item's key is something like a hash value. I don't understand what these two items mean. The official document only says "list current status of tracked CIDs (local state)". Can any expert please tell me what does it mean? Thanks very much.
![d027b00cd3faca95ac3c15fb8092cdc](https://user-images.githubusercontent.com/12689769/55784134-7bf0d400-5ae2-11e9-8423-bd1c27a438b4.png)

**Comment by kishansagathiya** [comment]
@CoreyLin 
Those hashes that you have highlighted are peer IDs on which content is PINNED(in this case)

**Comment by hsanjuan** [comment]
Those are actually peer names as set in the `service.json` file for each peer. Because on init the machine hostname is used, it would seem that it used the docker container ID and that's what you're seeing.

**Comment by CoreyLin** [comment]
@hsanjuan @kishansagathiya Thanks very much. Just now I confirmed that it is both "peername" in service.json and docker container ID of the peer.

**Comment by hsanjuan** [comment]
if the peername is empty it should display the peer IDs.

**Comment by CoreyLin** [comment]
@hsanjuan Got it. Thanks for your detailed explanation. 🙂
