### ISSUE TITLE
[question]remove remote peer from ipfs cluster

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#747]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Description

After reading the official documentation at https://cluster.ipfs.io/documentation/deployment/#removing-peers , I have some questions about removing peer from cluster.

Is "Ipfs-cluster-ctl peers rm <peerID>" able to remove the remote peers? For example, an ipfs cluster has three peers: A,B, and C. Can I execute "ipfs-cluster-ctl peers rm <peerID of B>" from peer A to remove remote peer B? If yes, what protocol and port is used to remove peer B? Thank you.

**Comment by CoreyLin** [comment]
@hsanjuan I see, now IPFS cluster must be run in trusted environment. If a malicious peer joins/invades the network, we cannot prevent it from destroying the network.

> With upcoming crdts this will change and peer add/rm will be mostly no-ops.

Sorry, I don't quite understand "crdts" and "no-ops". Could you tell me what do they mean?

**Comment by hsanjuan** [comment]
We are introducing a new consensus layer (called "crdt"). In this mechanism, peers joining and leaving the cluster will not trigger a change in the shared state like it happens now. Therefore joining and leaving a cluster will be no-operations as there is nothing to do. This also means that a peer will not be able to be forcefully removed from a cluster.

**Comment by CoreyLin** [comment]
@hsanjuan Thanks! I will read and learn #685
