### ISSUE TITLE
[question]Is it possible to start multiple peers with a fixed peerset by docker?

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#748]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Description

According to the official documents https://cluster.ipfs.io/documentation/starting/#starting-multiple-peers-with-a-fixed-peerset , ipfs cluster can be deployed in two ways, one of which is "Starting multiple peers with a fixed peerset". In this way, the ids of all the peers need to be configured in the init_peerset in the service.json file. According to my understanding, service. json file is generated after executing "ipfs-cluster-service init", that is to say, the whole process is to execute "ipfs-cluster-service init" first, then configure init_peerset in service.json, and then execute "ipfs-cluster-service daemon".

But in Dockerfile, "ipfs-cluster-service init" and "ipfs-cluster-service daemon" are executed sequentially and automatically in entrypoint.sh. Please refer to https://github.com/ipfs/ipfs-cluster/blob/master/docker/entrypoint.sh . There is no chance to manually configure init_peerset after executing "docker run" command. Can I understand that we can't start multiple peers with a fixed peerset by docker way, right? Thanks very much.

**Comment by CoreyLin** [comment]
@hsanjuan OK. Thanks for your reminder. In future, I will post questions on https://discuss.ipfs.io/.

> You need to mount a volume with the configuration when you launch the container.

It means that I need to prepare service.json on my own even before executing ipfs-cluster-service init. It indeed requires that the operator/user is very familiar with service.json. Am I right?

**Comment by CoreyLin** [comment]
I'm sorry for raising so many questions here. I'm very interested in ipfs and think it is a good and promising project. Anyway, I will raise new questions on https://discuss.ipfs.io/. But before that, could you please answer already raised questions in github? Thanks very much.

**Comment by hsanjuan** [comment]
Closing this for the moment.
