### ISSUE TITLE
[question]how to scale the capacity of IPFS cluster due to limitation of Raft network size

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#749]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Description

The ipfs cluster official documentation says "It is appropiate for small sized clusters (what small means is to be determined, but probably < 20 peers) running in trusted environments." in https://cluster.ipfs.io/documentation/deployment/#raft-consensus . I don't know much about Raft. From the description in this sentence, Raft is only suitable for small sized clusters. So I have two questions in my mind:

1. Could any expert please provide me with some references on Raft network size? I want to know more about the theory especially about Raft network size.

2. If the network size is suggested to be set to less than 20 peers, then how to scale and expand the capacity of IPFS private network and cluster if the amount of data it needs to store is huge and keeps increasing?

Thanks very much!

**Comment by hsanjuan** [comment]
#685 will allow scaling to hundreds.

Raft requires broadcasting and rountrips from/to the leader. You can probably scale it by adjusting the configuration accordingly to your network properties, but we don't know for sure how big it can get.

**Comment by hsanjuan** [comment]
Closing this for the moment
