### ISSUE TITLE
[question]can malicious peer execute pin rm command to arbitrarily delete existing data from a ipfs cluster

### ISSUE THREAD

**Issue by CoreyLin** [ipfs/ipfs-cluster#750]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Description

The official documentation(https://cluster.ipfs.io/documentation/ipfs-cluster-ctl/#usage) mentions a command "ipfs-cluster-ctl pin rm" that can be used to unpin a CID from the cluster. I understand this means that executing this command from a peer in the ipfs cluster will cause a CID to be removed from the cluster entirely.

I have a question, if a peer added to the ipfs cluster is a malicious peer (such as someone who illegally obtains the value of CLUSTER_SECRET and then joins the ipfs cluster), can this malicious peer execute the pin rm command to arbitrarily delete the existing data from the ipfs cluster? Could any expert please explain this? Thanks very much.

**Comment by CoreyLin** [comment]
And I noticed another sentence in the documentation(https://cluster.ipfs.io/documentation/deployment/#raft-consensus) "Raft is our default consensus implementation. It provides high availability, protection against network splits and fast state convergence. It is appropiate for small sized clusters (what small means is to be determined, but probably < 20 peers) running in **trusted environments**." This seems to imply that the ipfs cluster should run in a **trusted environment** and can't prevent malicious peer from deleting CIDs from the cluster, am I right?

**Comment by hsanjuan** [comment]
Closing this for the moment

**Comment by volodyad** [comment]
Hello, Have related question.
Can we disable "ipfs-cluster-ctl pin rm" operation so no one could execute it. In case someone get access to protected node we need to be sure that data will not be deleted. #710 do not solve this issue, if someone get access to the trusted peer - he will be able to delete data from the cluster.

**Comment by hsanjuan** [comment]
hey @volodyad !

If someone gets access to a trusted peer you will have other issues as well (like a malicious actor adding many many things until the storage is full)... usually if we want to offer a pin-only or add-only API to Cluster we put something on top of cluster. This can be a pinbot or simply a reverse proxy that only allows certain API endpoints.

All that said, if you can open a separate issue about this it would be great. Perhaps it would be useful to let the user configure which API endpoints should be enabled (or disabled).
