### ISSUE TITLE
ctl add --replication-value help output about default 0 value confusing

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#755]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [ ] Feature request
  * [x] Enhancement

#### Description

```
$ ipfs-cluster-ctl pin add -h
...
OPTIONS:
   --replication value, -r value          Sets a custom replication factor (overrides -rmax and -rmin) **(default: 0)**
   --replication-min value, --rmin value  Sets the minimum replication factor for this pin **(default: 0)**
   --replication-max value, --rmax value  Sets the maximum replication factor for this pin **(default: 0)**
...
```
It is correct to say that the default value is 0 but what this means in practice is that the `cluster.replication-min` and `cluster.replication-max` values defined in `.ipfs-cluster/service.json` will be used not that the default replication factor is actually 0.

**Comment by hsanjuan** [comment]
should apply also for `pin add`. I don't know if we can make the `(default: 0)` go away by not setting it (even though effectively it will default to 0).

**Comment by hsanjuan** [comment]
The actionables here:

* Make sure the command help explains what 0 means
* Investigate if it the `default: 0` can be removed somehow
* Might get away with it by making it a string flag and parsing the values...

**Comment by kishansagathiya** [comment]
Removing the text `default: 0` and explaining the policy in case rmin, rmax, r and user-allocations are not provided should be enough. It shouldn't matter to user how we implement default functionality.

**Comment by kishansagathiya** [comment]
One way is to let users set their own default policy. This could be a useful feature which would eliminate the need to pass replication parameters with every pin command.

**Comment by hsanjuan** [comment]
Users set their default policy in the configuration already. There is no need to pass replication parameters in every pin command. The `default: 0` gets added by the urfave/cli library.

Are the actionables not clear?
