### ISSUE TITLE
Best Practices When Architecting a CLI interface

### ISSUE THREAD

**Issue by pkafei** [ipfs/ipfs-cluster#757]
## Introduction

At Protocol Labs our end user is very often a developer. It is important for us to be mindful about creating interfaces that delight and engage the people we want to use and evangelize IPFS. Focusing on creating CLI best practices is a meaningful first step in creating a better user experience for developers. 

First off- why bother with the command line? This might be obvious to some programmers, but it is still useful to revisit why we are using an interface that has been around since the [early 70's](https://en.wikipedia.org/wiki/Unix_shell). The reason why the command line has stood the test of time because it offers users [more control and flexibility compared to a GUI](https://speakerdeck.com/efung/how-the-command-line-can-empower-you?slide=6). With that in mind, when we are creating command line tools, the most important goal to keep in mind is to create an interface that prioritizes speed and precision.

#### Terminal

A terminal is the input/output environment of a computer. Years ago a terminal use to be a physical device which was used for entering data. Terminals today are still used for input/output but are now software as opposed to hardware like in the olden days.

![](https://res.cloudinary.com/blockchain-side-hustle/image/upload/c_scale,h_252,q_74/v1555428587/original-terminal_yduh2k.jpg)

#### Bash 'Bourne-again-shell'

If you own a Linux or Mac machine then you probably already have bash on your machine- which stands for 'Bourne-again-shell'. The Windows-based system comes with 'MS-DOS-based' which is similar to bash but uses different commands. Bash is a Unix shell and command language that was created under the GNU Project. 

### Clear Error handling 📝⚡😊

Error should be kept clear and actionable. Whenever we have the opportunity we should value specific over general. Here are some good articles that cover error handling.

[How to write a good error message](https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4)  
[5 User Experience Tips for the Best Error Messages](https://freshsparks.com/user-experience-tips-best-error-messages/)

_Note: Articles assumes user is interacting with GUI, but there are still some valuable principles that are relevant to a CLI interface_

### Command-line should be self-documenting 📖🤓

Each command should precisely describe what function it provides. It is good practice to avoid overly verbose descriptions.
```
  TOOL COMMANDS
    config        Manage configuration
    version       Show ipfs version information
    update        Download and apply go-ipfs updates
    commands      List all available commands
    cid           Convert and discover properties of CIDs
```

### Organize into clear subcategories 📚😃
Be sure to put flags and arguments into easy to understand subcategories like so: 
```
SUBCOMMANDS
  BASIC COMMANDS
    init          Initialize ipfs local configuration
    add <path>    Add a file to IPFS
    cat <ref>     Show IPFS object data
    get <ref>     Download IPFS objects
    ls <ref>      List links from an object
    refs <ref>    List hashes of links from an object

  DATA STRUCTURE COMMANDS
    block         Interact with raw blocks in the datastore
    object        Interact with raw dag nodes
    files         Interact with objects as if they were a unix filesystem
    dag           Interact with IPLD documents (experimental)

  ADVANCED COMMANDS
    daemon        Start a long-running daemon process
    mount         Mount an IPFS read-only mountpoint
    resolve       Resolve any type of name
    name          Publish and resolve IPNS names
    key           Create and list IPNS name keypairs
    dns           Resolve DNS links
    pin           Pin objects to local storage
    repo          Manipulate the IPFS repository
    stats         Various operational stats
    p2p           Libp2p stream mounting
    filestore     Manage the filestore (experimental)
```

#### Command Prompt
If you have command-line instructions that show multiple lines of input, start each line of input with the `$` prompt symbol
```
$ adb shell
screencap /sdcard/screen.png
exit
$ adb pull /sdcard/screen.png
```

#### Use square Brackets around optional arguments
`ipfs daemon [--debug]`

For more command line advice checkout out [Developers Documenting command-line syntax](https://developers.google.com/style/code-syntax)

### Sources:
------------

https://medium.com/google-design/how-i-do-developer-ux-at-google-b21646c2c4df
https://eng.localytics.com/exploring-cli-best-practices/ 
https://programminghistorian.org/en/lessons/intro-to-bash

#### CLI API Packages Used at IPFS

https://github.com/urfave/cli  
http://yargs.js.org/

**Comment by hsanjuan** [comment]
We mostly follow these recommendations and is not cluster specific. It seems it would be most useful if this lived in a design recommendations or as part of some guide?

I'll close the issue as I don't see a clear actionable but we can continue the discussion despite it being closed.

**Comment by meiqimichelle** [comment]
This was meant to be a start of a guide, collecting best practices from PL work (to include Cluster) and other places. Then, we could use the guide as a reference to check if we can/should make any improvements. Opening it here was a way to get started in a place where the community could contribute or discuss.

**Comment by meiqimichelle** [comment]
The actionable is: record best practices. The next issue would be: review Cluster CLI against best practices for any gaps. After that: resolve/improve any identified gaps (if there are any). So, I'm not sure if closing this is the right move @hsanjuan. Alternatively, we can move it to the soon-to-be-public design community repo and continue work there, and come back to this repo for the next step, when it's ready. (I don't think this is a P0 so it might be a while till we close the loop.)

**Comment by hsanjuan** [comment]
> This was meant to be a start of a guide, collecting best practices from PL work (to include Cluster) and other places. Then, we could use the guide as a reference to check if we can/should make any improvements. Opening it here was a way to get started in a place where the community could contribute or discuss.

Well this was not part of the issue description so it was hard to guess what we had to do with it. The body of an issue is not the best place to drop a document to be discussed. That should rather be a PR creating that document wherever it should live (the new design-repo sounds like the optimal place), so that we can comment inline and iterate (separating discussion from content). In any case, issues in this repo are preferentially for bugs or features in the codebase.

Cluster-codebase specific actionables derived from this effort can be reported as issues here. Docs issues can be reported to the website repo. But as a say, for the moment our CLIs follow what's on this guide right now.

Thanks for understanding!
