### ISSUE TITLE
IPFS cluster javascript API Client

### ISSUE THREAD

**Issue by princesinha19** [ipfs/ipfs-cluster#759]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Latest stable version
* [x] Type (mark as appropiate):
  * [x] Feature request
* [x] Operating system (mark as appropiate):
  * [x] Linux
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io

#### Description
I was searching for some API through which I can store data, fetch data on IPFS cluster for javascript. It will be good if IPFS-Cluster team can provide any some such API for that.

If any repo or module is available for the same. Please tell me.

**Comment by kishansagathiya** [comment]
@princesinha19 
Currently we don't have a javascript API client, but we realized that we need one. I don't think we opened an issue for that, so thanks for opening this. Hopefully we will have a JS API client soon.

**Comment by hsanjuan** [comment]
For context, we were thinking of maybe generating it from Swagger docs too. But hand-made is also good.

**Comment by eiTanLaVi** [comment]
is it currently possible to connect via the proxy using ipfs-http-client lib ? if so, how?

**Comment by hsanjuan** [comment]
> is it currently possible to connect via the proxy using ipfs-http-client lib ? if so, how?

Pointing ipfs-http-client to the proxy port (9095).

**Comment by eiTanLaVi** [comment]
yeah been trying that but keep getting:
"SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at streamToValue (/Users/eitanlavi/workspace/blockchain-backend/ipfs-cluster-manual/node_modules/ipfs-http-client/src/utils/stream-to-json-value.js:25:18)\n    at concat (/Users/eitanlavi/workspace/blockchain-backend/ipfs-cluster-manual/node_modules/ipfs-http-client/src/utils/stream-to-value.js:12:22)\n    at ConcatStream.<anonymous> (/Users/eitanlavi/workspace/blockchain-backend/ipfs-cluster-manual/node_modules/ipfs-http-client/node_modules/concat-stream/index.js:32:43)\n    at ConcatStream.emit (events.js:187:15)\n    at finishMaybe (/Users/eitanlavi/workspace/blockchain-backend/ipfs-cluster-manual/node_modules/readable-stream/lib/_stream_writable.js:620:14)\n    at afterWrite (/Users/eitanlavi/workspace/blockchain-backend/ipfs-cluster-manual/node_modules/readable-stream/lib/_stream_writable.js:466:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"

**Comment by hsanjuan** [comment]
@eiTanLaVi what operation? try `curl`ing the same thing, it should show what is the response. It looks like maybe some html `<...`..

**Comment by eiTanLaVi** [comment]
sorry was a load balancer routing issue.. my bad. Works great now! Waiting for a nice webui for the cluster similar to that for the nodes! Amazing work either way

**Comment by kishansagathiya** [comment]
Some good folks have tried to implement a client library in JS. We should take a look and see if we can use it.

https://github.com/te0d/js-ipfs-cluster-api
https://github.com/cluster-labs/ipfs-cluster-api

**Comment by vasa-develop** [comment]
Hey all!

I recently released [**v0.0.3**](https://github.com/cluster-labs/ipfs-cluster-api) of **ipfs-cluster-api**.

This effort was started as the other implementation([https://github.com/te0d/js-ipfs-cluster-api](https://github.com/te0d/js-ipfs-cluster-api)) was 2 years old. I tried to add a PR but seems like it's no longer maintained.

So, I started [https://github.com/cluster-labs/ipfs-cluster-api](https://github.com/cluster-labs/ipfs-cluster-api).

**v0.0.3** features following main accomplishments:
- It supports ALL the commands supported by the latest `ipfs-cluster-ctl` (0.10.1)
- Includes Extensive documentation.
- Includes a lot of tests.

I invite all of you to TEST IT out & CONTRIBUTE. 
LET'S MAKE IT STABLE ENOUGH TO MAKE IT AN OFFICIAL ASAP.

Cheers,
vasa

**Comment by vasa-develop** [comment]
@eiTanLaVi I also created a sweet UI for managing nodes and data for a cluster.
I call it **Horizon**.
Here is a sneak-peek.

![horizon](https://user-images.githubusercontent.com/28847087/57322272-c6389580-7120-11e9-813e-aea60ce33b19.png)

I will make it public in a few days [**here**](https://github.com/cluster-labs/horizon)

**Comment by kishansagathiya** [comment]
Thanks @vasa-develop 
This horizon and client look amazing, we will surely try it

**Comment by eiTanLaVi** [comment]
Amazing @vasa-develop ! will check it out!

**Comment by vasa-develop** [comment]
Released [**v0.0.6**](https://github.com/cluster-labs/ipfs-cluster-api)

- Improved Documentation 📖
- Bugs🐞 KILLED 🔫

**Comment by hsanjuan** [comment]
Now that @vasa-develop has created a javascript API, should we adopt it  as part of our new "ipfs-cluster" org? Would you be open to that @vasa-develop ?

**Comment by vasa-develop** [comment]
@hsanjuan  Sure

**Comment by hsanjuan** [comment]
We now have: https://github.com/ipfs-cluster/ipfs-cluster-api
