### ISSUE TITLE
Separate identity and configuration

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#760]
Currently, we store the identity of a peer (the private key and the peer id) in the `service.json` file along with the actual configuration values. Also, the cluster secret should be separated out of the configuration. The goal is that a `service.json` from one cluster peer should be able to be used by another with zero changes, hence why the peer id also should be removed. The separated values should live in a file inside `~/.ipfs-cluster`.

**Comment by kishansagathiya** [comment]
@lanzafame 
So basically we need an `identity.json`, which would look kinda like
```
{
    "id": "Qm...............",
    "peername": "kishansagathiya",
    "private_key": "$privatekey",
    "secret": "$secret"
}
```
This seem rather small then I thought. Is that it or is there a catch?

Also
> The goal is that a service.json from one cluster peer should be able to be used by another with zero changes

What are our plans to use this property?

**Comment by hsanjuan** [comment]
> What are our plans to use this property?

To be able to let users run things like `ipfs-cluster-service --config /ipns/cats-cluster follow`

Where `/ipns/cats-cluster` is a cluster config that contains all the things which are common to all peers (so all, except private key, peer id, cluster secret).

**Comment by kishansagathiya** [comment]
Question:
If the peer has already initialized and does `ipfs-cluster-ctl init` again, do we keep the same identity or start afresh for that as well?
I think we should generate new identities, but just want to confirm.

**Comment by hsanjuan** [comment]
You cannot run init twice, only an `-f` flag that replaces the existing config with a new one, that should  be kept as is.

Note that there should be backwards compatibility. If `service.json` has the key then it should be picked from there.

**Comment by lanzafame** [comment]
@kishansagathiya @hsanjuan I just realised that the basic-auth configuration should be included in this separation issue.

**Comment by hsanjuan** [comment]
Hmm while private key is a mandatory parameter, basic-auth config (empty by default) can be overriden via env vars. Or simply we allow `ipfs-cluster-ctl init --template /ipfs/Qm...` and then the user can edit that file locally. So I say, let's not extract basic auth?

**Comment by hsanjuan** [comment]
I don't think `secret` should be separate either... it's the same for all peers. And `peername` should be left empty in templates so the hostname is used. I think the main point here is to be able to re-use identity.

**Comment by lanzafame** [comment]
>  I think the main point here is to be able to re-use identity.

I see it the other way around, the goal is to re-use the configuration regardless of the identity or which cluster a peer belongs to, hence the suggestion to remove the `secret`.

**Comment by hsanjuan** [comment]
The only thing not re-usable in a configuration is the peer-identity, that' why that's the only thing to be extracted.
