### ISSUE TITLE
UserAllocations support for `add`

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#761]
https://github.com/ipfs/ipfs-cluster/pull/647 introduced support for user allocations to `pin add`. Since `add` does pinning as well, it would make sense to add user allocations support for `add` as well

**Comment by kishansagathiya** [comment]
add metadata as well while at this?

**Comment by hsanjuan** [comment]
Prefer separate. One PR for allocations (missing in add) and one PR for metadata.

**Comment by kishansagathiya** [comment]
right now, if allocations are passed, still we assume replication factor as `pin everywhere`

I think if allocations are passed and replication factors are not, we should either only try to pin on allocations or consider replication factor as number of allocations

**Comment by hsanjuan** [comment]
I'm not sure what you mean. This should behave exactly like pinning with user-given allocations.

**Comment by kishansagathiya** [comment]
sorry, I meant changing the behaviour in pinning with user-given allocations.

**Comment by hsanjuan** [comment]
From the --help:

```
An optional allocations argument can be provided, allocations should be a
comma-separated list of peer IDs on which we want to pin. Peers in allocations
are prioritized over automatically-determined ones, but replication factors
would stil be respected.
```

This should be the same. If there is an issue with that we can address it separately later.
