### ISSUE TITLE
Fully remove Gx

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#765]
They don't bother anyone but probably will never be used again
This would mean getting rid off `deptools` as well

**Comment by hsanjuan** [comment]
And `package.json`

**Comment by pkafei** [comment]
@hsanjuan  Should `package.json` be completely deleted? It seems like we are[ still adding dependencies to it](https://github.com/ipfs/ipfs-cluster/commit/acbd7fda60c696dd51beb130c00b633f6c9073ea).

**Comment by hsanjuan** [comment]
> @hsanjuan Should `package.json` be completely deleted? It seems like we are[ still adding dependencies to it](https://github.com/ipfs/ipfs-cluster/commit/acbd7fda60c696dd51beb130c00b633f6c9073ea).

Yes, it can be deleted
