### ISSUE TITLE
Too many, too often test errors

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#774]
**Describe the bug:**

Error: `fatal error: runtime: out of memory`
It doesn't seem like this is happening because of any particular test, since both jobs are failing at different tests.

https://travis-ci.com/ipfs/ipfs-cluster/jobs/198517734
https://travis-ci.com/ipfs/ipfs-cluster/jobs/198517714

**Comment by hsanjuan** [comment]
Maybe related to https://github.com/ipfs/go-ds-crdt/issues/6

**Comment by hsanjuan** [comment]
Let's use this issue to track errors showing up in tests (let's paste them here). Usually this involves me spending a couple of days figuring out whether there is a bug, a timing issue, or libp2p as a problem.

```
--- FAIL: TestClustersReplication (10.16s)
    ipfscluster_test.go:1082: Expected 4 local pins but got 3
    ipfscluster_test.go:1083: [0xc005ba01e0 0xc005ba0240 0xc005ba02a0 0xc005ba0300 0xc005ba0360]
    ipfscluster_test.go:1087: Expected 1 remote pin but got 2
    ipfscluster_test.go:1082: Expected 4 local pins but got 5
    ipfscluster_test.go:1083: [0xc005ba15c0 0xc005ba1620 0xc005ba1680 0xc005ba16e0 0xc005ba1740]
    ipfscluster_test.go:1087: Expected 1 remote pin but got 0
```

```
--- FAIL: TestClustersPeerRemoveReallocsPins (11.85s)
    peer_manager_test.go:502: pin should not be allocated to the removed peer
```

**Comment by kishansagathiya** [comment]
I had to retry a bunch of times to pass this in `Main Tests with crdt consensus`

```
=== RUN   TestClustersReplicationFactorMin
panic: assignment to entry in nil map
goroutine 460325 [running]:
github.com/jbenet/goprocess.(*process).AddChildNoWait(0xc0bb374780, 0x139e340, 0xc0bb374de0)
	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:72 +0x18a
github.com/jbenet/goprocess/context.WithProcessClosing(0x1396160, 0xc0bab434c0, 0x139e340, 0xc0bb374780, 0xc0b888eea0, 0xc03c7eee90)
	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/context.go:85 +0x16e
github.com/jbenet/goprocess/context.OnClosingContext(0x139e340, 0xc0bb374780, 0xc0abdc89c0, 0xc0abdc89c0)
	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/derive.go:12 +0x4d
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).queryPeer(0xc0abc13a70, 0x139e340, 0xc0bb374780, 0xc09c483950, 0x22)
	/home/travis/gopath/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.10/query.go:270 +0x50
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).spawnWorkers.func1(0x139e340, 0xc0bb374780)
	/home/travis/gopath/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.10/query.go:226 +0x50
github.com/jbenet/goprocess.(*process).Go.func1(0xc0bb3fe320, 0xc0bb374780, 0xc0bb3747e0)
	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:112 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:111 +0x1f5
FAIL	github.com/ipfs/ipfs-cluster	133.303s
```

Looking at the logs it doesn't seem like problem is arising from cluster code base.

**Comment by hsanjuan** [comment]
> I had to retry a bunch of times to pass this in `Main Tests with crdt consensus`
> 
> ```
> === RUN   TestClustersReplicationFactorMin
> panic: assignment to entry in nil map
> goroutine 460325 [running]:
> github.com/jbenet/goprocess.(*process).AddChildNoWait(0xc0bb374780, 0x139e340, 0xc0bb374de0)
> 	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:72 +0x18a
> github.com/jbenet/goprocess/context.WithProcessClosing(0x1396160, 0xc0bab434c0, 0x139e340, 0xc0bb374780, 0xc0b888eea0, 0xc03c7eee90)
> 	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/context.go:85 +0x16e
> github.com/jbenet/goprocess/context.OnClosingContext(0x139e340, 0xc0bb374780, 0xc0abdc89c0, 0xc0abdc89c0)
> 	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/derive.go:12 +0x4d
> github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).queryPeer(0xc0abc13a70, 0x139e340, 0xc0bb374780, 0xc09c483950, 0x22)
> 	/home/travis/gopath/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.10/query.go:270 +0x50
> github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).spawnWorkers.func1(0x139e340, 0xc0bb374780)
> 	/home/travis/gopath/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.10/query.go:226 +0x50
> github.com/jbenet/goprocess.(*process).Go.func1(0xc0bb3fe320, 0xc0bb374780, 0xc0bb3747e0)
> 	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:112 +0x3c
> created by github.com/jbenet/goprocess.(*process).Go
> 	/home/travis/gopath/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:111 +0x1f5
> FAIL	github.com/ipfs/ipfs-cluster	133.303s
> ```
> 
> Looking at the logs it doesn't seem like problem is arising from cluster code base.

I reported that one and was fixed in goprocess.

**Comment by hsanjuan** [comment]
```
--- FAIL: TestClustersRebalanceOnPeerDown (5.08s)
    ipfscluster_test.go:1616: Not pinned as expected
```

**Comment by hsanjuan** [comment]
```
--- FAIL: TestClustersReplicationFactorMaxLower (2.41s)
    ipfscluster_test.go:323: dial attempt failed: 1 error occurred:
        	* QmcRKUQVw95vUBfzFsgehdRR1XPZrmnUyyzdRa7kadEQhg --> QmNrRDzXSbPVZCeqYS78vhXLLRfENhcioANYKMYvdTEPe8 (/ip4/127.0.0.1/tcp/41763) dial attempt failed: failed to negotiate security protocol: connected to wrong peer
```

**Comment by hsanjuan** [comment]
```
--- FAIL: TestClustersReplicationRealloc (5.20s)
    ipfscluster_test.go:1473: not enough peers to allocate CID. Needed at least: 3. Wanted at most: 3. Valid candidates: 0. See logs for more info.
```

**Comment by hsanjuan** [comment]
```
--- FAIL: TestClustersPeerRejoin (12.61s)
    peer_manager_test.go:744: re-joined cluster should have original pin
```

**Comment by hsanjuan** [comment]
```
--- FAIL: TestClustersReplicationOverall (9.27s)
    ipfscluster_test.go:1118: QmU8vYCfMXWL6AfuCEMRpZHW8PUhhZQr58tFPMZCpz5g3x: Expected 4 local pins but got 5
    ipfscluster_test.go:1122: QmU8vYCfMXWL6AfuCEMRpZHW8PUhhZQr58tFPMZCpz5g3x: Expected 1 remote pin but got 0
    ipfscluster_test.go:1118: QmRxkB9VdjaGkXu1fm6BLfLBDxypPQP7ptCACxzPiik5V8: Expected 4 local pins but got 3
    ipfscluster_test.go:1122: QmRxkB9VdjaGkXu1fm6BLfLBDxypPQP7ptCACxzPiik5V8: Expected 1 remote pin but got 2
```
stateless

**Comment by hsanjuan** [comment]
Closing this even though some tests still have failure tendencies (AddLocal)
