### ISSUE TITLE
Logical Clusters

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#785]
**Describe the feature you are proposing**

Right now, instances of IPFS-Cluster can only join *one single cluster*. Logical clusters would allow a single instance of IPFS-Cluster to join multiple *logical clusters*.

**Additional context**

Logical clusters would permit the creation of multiple clusters according to a topic, or a function, and to divide pins across peers. For example, if I want my ISO to be backed up on my 2 desktops but not on my laptop, but I want my music to be hosted on all 3 machines, I could create two logical clusters, one for the ISOs and one for my music, and have the two desktops join the ISO cluster and all 3 join the music cluster.

It's a simplistic view, but I can imagine this being used heavily in data centers to divide the content according to server's forces and weaknesses. I would also totally use it to join a public Ubuntu Archive cluster and my LineageOS mirror at the same time.

Taken from #783.

**Comment by hsanjuan** [comment]
Cluster already supports custom allocations so you can manually work-around this. Related (or the same as) #159 .

**Comment by NatoBoram** [comment]
Would that allow me to join two separate collaborative pinsets and donate storage?

**Comment by hsanjuan** [comment]
> Would that allow me to join two separate collaborative pinsets and donate storage?

No, but you can run two cluster peers to join two pinsets (just setting a custom config folder and new identity and changing ports). They can use the same ipfs daemon.

**Comment by hsanjuan** [comment]
I'm inclined to close this. Multiple subscriptions would require multiple CRDT DAGs, with mutiple datastore namespaces and notifications to multiple pintrackers. Multiple states would mean that "status <cid>" would need to select which of the subscriptions-state to use. Using a single state would mean dealing with the use-case of multiple subscriptions pinning in different ways, or unpinning what others pinned. In the end we'd end up with an much increased level of complexity for running the equivalent of what you can do now by launching two cluster peers on different ports (even if they talk to the same daemon). So not willing to put efforts this way.

**Comment by NatoBoram** [comment]
Could there be a setting or a command to facilitate this? For example, is there an `init` flag for setting random ports? Or a `daemon` flag to use random ports automatically?

**Comment by hsanjuan** [comment]
> Could there be a setting or a command to facilitate this? For example, is there an `init` flag for setting random ports? Or a `daemon` flag to use random ports automatically?

Can you open an issue about that? That should be doable. It might already work if you use "/tcp/0" in your listen multiaddresses though, but haven't tried.

**Comment by NatoBoram** [comment]
Here you go : #794
