### ISSUE TITLE
Read / Write Permissions

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#786]
**Describe the feature you are proposing**

Currently, when joining an IPFS Cluster, the IPFS-Cluster instance needs to set its `secret` to the cluster's `secret`. This `secret` gives the IPFS-Cluster node the permission to write to the state according to consensus.

I would like to separate this `secret` in two : A **write key** and a **read key**. Peers joining using the write key can still write to the cluster's state according to the consensus, but peers joining using the read key can only read the cluster's state after joining.

**Additional context**

This would immediately allow the creation of large-scale collaborative pinsets. Combined with #785 and a fix for #787, IPFS-Cluster would be able to be used as a replacement for the concept of mirrors itself.

Taken from #783.

**Comment by lanzafame** [comment]
A Cluster `secret` serves as the libp2p network key, so splitting it as you have suggested would be like having two cluster networks, one for read peers and one for write peers. Also please have a look at: https://github.com/ipfs/ipfs-cluster/pull/775 as a different solution to the problem.

**Comment by hsanjuan** [comment]
As mentioned in #783 , we have recently introduced RPC auth which allows to essentially do the same for CRDTs (trusted peers can write, non-trusted peers can only read). I will close this as I think the usecase is resolved.
