### ISSUE TITLE
Both consensus are bleeding peers

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#787]
### Additional information
 - OS: Ubuntu
 - ~~IPFS Cluster version:~~
 - Installation method: built from source

### Description

If there's network disturbance between a node and the rest of the cluster, that node becomes its own cluster and doesn't attempt to re-attach to the bootstrap target. This quickly leaves the cluster in a fragmented or irrecoverable state. Manual intervention is required to restore the cluster.

### Suggestion

Alternative 1 : Hooks

Peers should remember every peers and attempt to get them to re-join the cluster if they still have the correct secret. This would make a cluster resistant to change because other nodes would tell them to join back. Those with a different secret can be safely forgotten.

Alternative 2 : Call for help

Peers should remember the node used for the bootstrap process. If that node becomes unreachable, then the peer should attempt every minute to bootstrap again. This would make change propagate quickly since every node would be dependent on their bootstrap.

---

In environment where network disturbance is common place, IPFS-Cluster is currently absolutely unusable. Should existing consensus be adapted, or is a new consensus needed?

**Comment by hsanjuan** [comment]
The solution here is to attempt to regularly re-connect to bootstrap nodes like go-ipfs does. This can happen with the introduction of bootstrap nodes in the config file.

**Comment by NatoBoram** [comment]
That could make the `--bootstrap` option for `--consensus crdt` useless, changing the way we use `raft` and `crdt`.

## Raft

### Creating the cluster
```bash
ipfs-cluster-service daemon --consensus raft
```

### Joining the cluster
1. Update `cluster.secret`
1. `ipfs-cluster-service daemon --bootstrap /ip4/159.89.116.13/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY`

## CRDT

### Creating the cluster

```bash
ipfs-cluster-service daemon --consensus crdt
```

### Joining the cluster

1. Update `cluster.secret`
2. Add bootstrap peers in `consensus.crdt.bootstrap_peers`
3. Add trusted peers in `consensus.crdt.trusted_peers`
4. `ipfs-cluster-service daemon --consensus crdt`

Writing this, I just realized something. Picture this : 

```json
{
	"crdt": {
		"cluster_name": "nato-personal-files",
		"trusted_peers": [
			"uaaHMTPcnwKXrSp497rYPjVb",
			"uafmDBY2yM28TypzvnkJ3KRv"
		],
		"secret": "JPAkrBQ4W6HBm6e4Aw5g7BKk",
		"subscriptions": [
			{
				"cluster_name": "lineageos-on-ipfs",
				"bootstrap_peers": [
					"QHwSBkCapR3xYJJqzYSKX2a6"
				],
				"secret": "CvBftScDXFjgF5qr9tXC3ZYL",
				"storage_max": "10GB",
				"forward": true
			},
			{
				"cluster_name": "ubuntu-archive",
				"bootstrap_peers": [
					"umeuhjGdf2rES7K457Ec3T6j",
					"uZVPERUNLHk6zXzVLgDSZueB"
				],
				"secret": "evLBkTfwhYnt5Hn24mCBMJuV",
				"storage_max": "10GB",
				"forward": false
			}
		]
	}
}
```

Adding the `bootstrap_peer` to `trusted_peers` would be absolutely redundant. We know we're trusting them if we're bootstrapping to them in the first place. To me, what's authenticating them as trusted peers is the `secret`.

**Comment by hsanjuan** [comment]
The secret is a libp2p private network thing. It's not auth (discussion in #610 is related). There will not be "multiple cluster subscriptions" because you can run multiple cluster peers to do it.

While I tend to agree that `--bootstrap` should add the given peer as `trusted`, bootstrapping defines a location where a peer is located (not just a peer id). For crdts, the only thing bootstrapping does is to connect to a different peer. It does not need to be a "trusted" one. Internally, bootstrapping is a `ipfs-cluster-service` feature while `trusted_peers` is a crdt component thing.

**Comment by hsanjuan** [comment]
We had some discussion about how to approach this during standup (@lanzafame chime in if I missed something)

* We should attempt to keep connected to `trusted_peers`
* We should make use of the peerstore and attempt to connect to peers addresses on the peerstore during boot at some point
* We should save peers in the peerstore and re-use them next time.

This promted me to look into how things work:

* We load peer addresses from the peerstore in `daemon.go` but don't connect to them at that point because the DHT is not bootstrapped. But that should not matter since the DHT and pubsub have been created at that point, so I think this is a bug and we can safely connect at that moment.
* Join() connects (obviously)
* We save ALL known peerstore addresses in the peerstore file (not just current peers). This means that connecting on boot will attempt to open connections to all
* We don't use a connection manager (maybe we should)

I will come with a PR to address these things

**Comment by NatoBoram** [comment]
I want to test if the merge resolved the problem with `crdt`.

1. `ipfs-cluster-ctl peers ls`

```yaml
12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74 | nato-hu | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/135.23.195.89/tcp/11240/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.1.2/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.122.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
  > IPFS: QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/135.23.195.89/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.1.2/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.122.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/2002:8717:c359:0:3ec9:8c27:8f6e:2163/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/::1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY | lineageos-on-ipfs | Sees 2 other peers
  > Addresses:
    - /ip4/10.20.0.5/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
    - /ip4/159.89.116.13/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
  > IPFS: QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip4/159.89.116.13/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip6/2604:a880:cad:d0::17:2001/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip6/::1/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4 | hp-server | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4
    - /ip4/135.23.195.89/tcp/56043/ipfs/12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4
    - /ip4/192.168.1.3/tcp/9096/ipfs/12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4
  > IPFS: QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip4/135.23.195.89/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip4/192.168.1.3/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip6/2002:8717:c359:0:12f5:8d49:4d50:b0cc/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip6/2002:8717:c359:0:6631:50ff:fe5b:b589/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip6/::1/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
```

2. Rebooting my router. I should be back online after one minute, and I hope that within 10 minutes the peer will re-join the cluster.

3. After listening to [Mili - Rightfully](https://www.youtube.com/watch?v=7z4WJAEG3u8) thrice, time for `ipfs-cluster-ctl peers ls`.

```yaml
12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74 | nato-hu | Sees 0 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/135.23.195.89/tcp/11240/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.1.2/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.122.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
  > IPFS: QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/135.23.195.89/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/135.23.195.89/tcp/55065/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.1.2/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.122.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/2002:8717:c359:0:3ec9:8c27:8f6e:2163/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/::1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
```

Turns out that peers are still becoming their own clusters after network interruption and the `crdt` consensus is still bleeding peers. Issue should be re-opened.

```yaml
go-ipfs version: 0.4.21-rc3-2b41ca17e
Repo version: 7
System version: amd64/linux
Golang version: go1.12.5

IPFS Cluster version : 0.10.1+git35860d337f6b233c9dd240241a2c1c1adbc2d9b1

OS: Ubuntu 19.04 x86_64 
Kernel: 5.0.0-16-generic 
Uptime: 1 day, 3 hours, 21 mins 
Packages: 1949 (dpkg), 32 (snap) 
Shell: bash 5.0.3 
Resolution: 1920x1080 
DE: GNOME 3.32.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 4627MiB / 7917MiB 
```

**Comment by hsanjuan** [comment]
@NatoBoram the main questions to debug this would be:

* Does the peer you stopped try to connect to anyone? Does the connection drop? The logs should help here.
* How does the `peerstore` file look (do the contents make sense)?

**Comment by hsanjuan** [comment]
I have re-read this more carefully, you rebooted the router. This killed all connections and I think we cannot recover from a situation when the DHT goes to 0 peers. It's essentially a different issue than the one we addressed, but we'll provide a fix (basically re-bootstrapping regularly like ipfs). I'll ping you when something is in so you can test.

**Comment by hsanjuan** [comment]
@NatoBoram in branch `rpi-fixes` there is a fix for this. In my tests, peers that have been without connectivity automatically re-connect (after 30 seconds at most). Wanna try it out?

**Comment by NatoBoram** [comment]
I'll try it out as soon as I can! My SSD died last week, so I'll need some time to get my stuff back together.
