### ISSUE TITLE
Return authorization error when a follower attempts to pin something 

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#788]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: master

**Describe the bug:**

If a 'follower' peer attempts to pin a hash on a cluster, it gets the following:
```
> <peer_id> : CLUSTER_ERROR: failed to dial : all dials failed
* [/ip4/xxxx/tcp/9096] dial tcp4 xxxx:9096: i/o timeout
```
Which to me, suggests that I have a networking problem, i.e. libp2p, not that I am not authorized to pin to the cluster I am following.

**Comment by hsanjuan** [comment]
That's weird, a follower can actually pin (locally). Everyone is authorized to pin, it's just that if no one trusts that peer, that pin won't be taken into account. A follower does not know if it's trusted or not by others so it will allocate normally and pin.

What you see IS probably a networking problem. Authorization errors are filtered out silently from the `status` output.

**Comment by lanzafame** [comment]
Ahh yep, it was but I assumed it was an auth error because I knew that it should be for the two peers that gave me that error :upside_down_face:.

**Comment by hsanjuan** [comment]
phew!
