### ISSUE TITLE
service: --random-ports flag for init

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#794]
**Describe the feature you are proposing**

* An `init` flag to generate a configuration using random ports
* A `daemon` flag to use random ports

**Additional context**

In order to join multiple clusters, we have to start multiple instances of IPFS-Cluster and change the ports of each instances. It'd be nice to have something easy to set up secondary nodes with random ports.

If it's possible to use `/tcp/0` to get a random port on each startups, then I think there should have an `init` flag to set it up automatically once.

**Comment by vasa-develop** [comment]
I am working on something like [IPTB](https://github.com/ipfs/iptb) for IPFS Cluster. Is that what we are looking for here?

**Comment by lanzafame** [comment]
@vasa do you mean a plugin for IPTB? I have had that on my list for
quite some time and just haven't had the time.

**Comment by vasa-develop** [comment]
I don't think that it will be a plugin. Let's call it `IPCTB` just for that sake of the conversation.
It's a CLI which uses IPTB code for managing Libp2p peers.

**How will it work?**

- Initialize `n` number of cluster peers.

```
ipctb init --count n
```

**NOTE:** As cluster peers are not of much use until we have libp2p(IPFS) peers connected to each instance, should we initialize libp2p peers too(within this command)? So, this will initialize a number of Libp2p peers on separate ports and these peers will be mapped with the initialized cluster peers.

- Start the initialized cluster peers

```
ipctb start
```

- Connect CLI to a `n`th cluster peer (assume n = 0)
```
ipctb shell 0
```

> Now you can execute commands as if you were using IPFS Cluster CLI. Just replace `ipfs-cluster-crl` with `ipctb`

For eg.
- Get peer Id

```
ipctb id
```

These are some ideas. Is this what we are looking for @NatoBoram @lanzafame ?

**Comment by lanzafame** [comment]
@vasa you should be able to do that by writing a IPTB plugin is what I
meant. Check out the IPTB plugin in the
github.com/filecoin-project/go-filecoin repo for an example

**Comment by vasa-develop** [comment]
Oh! That's cool.
Thanks for pointing that out. I will use this approach then.
I will create a sample implementation, and we can see if it works for us ;)

**Comment by hsanjuan** [comment]
go-ipfs recently got a similar feature: https://github.com/ipfs/go-ipfs/blob/master/CHANGELOG.md#-initializing-with-random-ports

**Comment by hsanjuan** [comment]
Let's scope this convo: I have created an issue for the IPTB side: #817 

This issue is about having an `init` flag that configures random ports in the same fashion as go-ipfs (the implementer should look at go-ipfs and see how they choose the ports and grab inspiration from there).

**Comment by kishansagathiya** [comment]
I would rather like to have a shell script for this than put it in main cluster code, since this is clearly another layer on cluster.
Something like [ipfs-cluster-helper](https://github.com/kishansagathiya/ipfs-cluster-helper) (but that is outdated, very basic and for two peers only)

**Comment by hsanjuan** [comment]
Please investigate how IPFS does it and report back. It's functionality that is handy.

**Comment by kishansagathiya** [comment]
The PR used in IPFS https://github.com/ipfs/go-ipfs-config/pull/17/ (easy)
it adds an option `--profile=randomports` to tell that you want random ports

In case of IPFS, they are supporting random ports to stay uncensored (https://github.com/ipfs/go-ipfs/issues/5176#issue-337480033). If cluster could face such problem of port-banning by government (with collaborative cluster usecase mostly yes), it makes sense to support it.

But if it is just about testing you want more than just supporting random ports. Say you want to run a 10 node cluster, you want to automate those 10 `init` calls and then 10 `daemon` calls too.
