### ISSUE TITLE
Upgrade accrual failure detection to Weibull distribution

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#796]
See https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0173666&type=printable

It should only require updating the probability function in `monitor/metrics/prob.go`.

**Comment by lanzafame** [comment]
[`gonum/stat/distuv`](https://github.com/gonum/gonum/blob/master/stat/distuv/weibull.go) already has an implementation of the Weibull CDF function as well.

**Comment by hsanjuan** [comment]
Closing per #939 .
