### ISSUE TITLE
Sharness broken after https://github.com/chriscool/sharness/pull/90

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#797]
https://github.com/chriscool/sharness/pull/90 breaks our tests because sharness cannot find the right `functions.sh` file (we need to set some env variables I think).

In the meantime I'm reverting to using a previous version of the lib.

**Comment by chriscool** [comment]
Sorry I didn't know that you used the master branch directly. On other IPFS related projects I don't think the master branch is used.

It shouldn't be very difficult to fix though. Did you try to set SHARNESS_TEST_SRCDIR to the directory where one can find `sharness.sh`?

If you don't have time to take a look, I might try to fix this in the next few days.

**Comment by hsanjuan** [comment]
@chriscool no worries, it's my fault for pulling master blindly for this. The proper fix is not hard and not urgent. But thanks!
