### ISSUE TITLE
Bootstrap from loaded peerstore fails to connect to peers

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#805]
https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go#L153 this fails to actually 
"connect". As in it says it connects but `peers ls` doesn't show the supposedly connected peers.

**Comment by hsanjuan** [comment]
no, because `peers ls` only shows the peers once you receive `ping` metrics from them, even if you are connected before that. This is bad UI but workaroundable by inserting a metric when connection succeeds (like on `Join`)
