### ISSUE TITLE
PIN_ERROR: expected to find the pin in the response

### ISSUE THREAD

**Issue by postables** [ipfs/ipfs-cluster#809]
**Additional information:**
 - OS: [Ubuntu Server 18.04 LTS]
 - IPFS Cluster version: [0.10.1]
- IPFS Version [0.4.21]
 - Installation method: [dist.ipfs.io]

**Describe the bug:**

If running IPFS 0.4.21 and IPFS Cluster 0.10.1, due to the dependencies being used by IPFS Cluster 0.10.1, any pin requests will generally display the following error when running `ipfs-cluster-ctl status`

```
PIN_ERROR: expected to find the pin in the response 
```

This issue appears to be happening because go-ipfs is handling IPFS CID's in base32, while IPFS Cluster is handling CID's in base58. So far it doesn't appear that this issue is leading to any data loss, just a lot of noise.

Additionally it also looks like in certain cases, the following error may also be displayed:

```
PIN_ERROR: the item is unexpectedly not pinned on IPFS 
```

However this is not actually the case, as said CID is pinned across all the nodes in my cluster. This appears to be due to the same issue mentioned previously.

**Comment by hsanjuan** [comment]
This is either fixed by downgrading ipfs, or by using cluster from master, or by applying the fix in #808
