### ISSUE TITLE
Monitor: alerts never stop

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#812]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: master
 - Installation method: source

**Describe the bug:**

When the new monitor, alerts are triggered constantly whenever a peer dissapears. This causes re-pinning attemps constantly. We should probably not alert all the time, as some peers may as well never come back again. Possible related to #410 

@lanzafame maybe there's a simple fix for this?

**Comment by lanzafame** [comment]
@hsanjuan how many times/often should a be there be an alert for a peer that has disappeared? I have mostly implemented this feature, I just need to know the above to finish it off.

**Comment by hsanjuan** [comment]
> @hsanjuan how many times/often should a be there be an alert for a peer that has disappeared? I have mostly implemented this feature, I just need to know the above to finish it off.

Once, I guess.
