### ISSUE TITLE
Monitor: fake alerts

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#813]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: master
 - Installation method: source

**Describe the bug:**

In a 4 peer cluster with a freespace metric TTL of 5 minutes, cluster peers keep issuing for other peers "freespace" alerts even though they have valid metrics for all of them. Ping metric is sent every 45s and does not seem to trigger alerts.

I'm not sure if related, but this started happening very frequently after a peer re-joined. However, alerts refer to other peers too. Not all peers are alerting exactly the same thing or at the same time.

```
    "pubsubmon": {
      "check_interval": "15s",
      "failure_threshold": 3
    }
```

@lanzafame we cannot ship something that randomly alerts. The threshold is conservatiive. I don't think we should ever alert with valid metric.

Is the distribution value calculated per-peer? If I have a long metric ttl and shutdown a peer and then proceed to  re-start it, this may trigger 2 metrics coming relatively close (the last sent one and the one sent at re-start). i.e. if metrics should happen every 5 minutes, then this might send two metrics a few seconds apart. The next will be after 5 minutes again but maybe this is already tripping the system into sending an alert.

That does not explain why if triggers alerts for other peers too (unless it's somehow using the same distribution for all).

**Comment by lanzafame** [comment]
> Is the distribution value calculated per-peer?

Yes, see [here](https://github.com/ipfs/ipfs-cluster/blob/master/monitor/metrics/store.go#L149-L154). 

>  If I have a long metric ttl and shutdown a peer and then proceed to re-start it, this may trigger 2 metrics coming relatively close (the last sent one and the one sent at re-start). i.e. if metrics should happen every 5 minutes, then this might send two metrics a few seconds apart. The next will be after 5 minutes again but maybe this is already tripping the system into sending an alert.

I understand the edge case you are describing. I will investigate if that is true, and if so, I will adjust the checker/store/window to consider a distribution with all its metrics within the ttl value to be not a failure. I believe that should work. 

@hsanjuan could you paste some logs of when alerts for other peers have been triggered? cheers

**Comment by hsanjuan** [comment]
I just have things like:

```
21:03:32.212 WARNI    cluster: metric alert for freespace: Peer: QmYY1ggjoew5eFrvkenTR3F4uWqtkBkmgfJk8g9Qqcwy51. cluster.go:357
21:03:47.211 WARNI    cluster: metric alert for freespace: Peer: QmdFBMf9HMDH3eCWrc1U11YCPenC3Uvy9mZQ2BedTyKTDf. cluster.go:357
21:03:47.212 WARNI    cluster: metric alert for freespace: Peer: QmYY1ggjoew5eFrvkenTR3F4uWqtkBkmgfJk8g9Qqcwy51. cluster.go:357
21:04:02.211 WARNI    cluster: metric alert for freespace: Peer: QmdFBMf9HMDH3eCWrc1U11YCPenC3Uvy9mZQ2BedTyKTDf. cluster.go:357
21:04:02.211 WARNI    cluster: metric alert for freespace: Peer: QmYY1ggjoew5eFrvkenTR3F4uWqtkBkmgfJk8g9Qqcwy51. cluster.go:357
21:04:17.211 WARNI    cluster: metric alert for freespace: Peer: QmdFBMf9HMDH3eCWrc1U11YCPenC3Uvy9mZQ2BedTyKTDf. cluster.go:357
21:04:17.211 WARNI    cluster: metric alert for freespace: Peer: QmYY1ggjoew5eFrvkenTR3F4uWqtkBkmgfJk8g9Qqcwy51. cluster.go:357
21:04:32.211 WARNI    cluster: metric alert for freespace: Peer: QmYY1ggjoew5eFrvkenTR3F4uWqtkBkmgfJk8g9Qqcwy51. cluster.go:357
21:04:32.212 WARNI    cluster: metric alert for freespace: Peer: QmSGCzHkz8gC9fNndMtaCZdf9RFtwtbTEEsGo4zkVfcykD. cluster.go:357
21:04:47.211 WARNI    cluster: metric alert for freespace: Peer: QmYY1ggjoew5eFrvkenTR3F4uWqtkBkmgfJk8g9Qqcwy51. cluster.go:357
21:04:47.212 WARNI    cluster: metric alert for freespace: Peer: QmSGCzHkz8gC9fNndMtaCZdf9RFtwtbTEEsGo4zkVfcykD. cluster.go:357
21:05:02.211 WARNI    cluster: metric alert for freespace: Peer: QmSGCzHkz8gC9fNndMtaCZdf9RFtwtbTEEsGo4zkVfcykD. cluster.go:357
21:05:17.211 WARNI    cluster: metric alert for freespace: Peer: QmSGCzHkz8gC9fNndMtaCZdf9RFtwtbTEEsGo4zkVfcykD. cluster.go:357
```

**Comment by hsanjuan** [comment]
This was fixed I think
