### ISSUE TITLE
Master branch build broken

### ISSUE THREAD

**Issue by jin-tron** [ipfs/ipfs-cluster#822]
**Additional information:**
 - OS: [e.g. Linux] Linux
 - IPFS Cluster version: [e.g. 0.10.1, master] master
 - Installation method: [e.g. built from source, dist.ipfs.io, docker]
go install ./cmd/ipfs-cluster-service

**Describe the bug:**
related with this one, https://github.com/dgraph-io/badger/issues/886
When I make a "go clean --modcache", then run "go install ./cmd/ipfs-cluster-service",
I got error,
go: error loading module requirements

Still shows dependency error,
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: go.mod has post-v2 module path "github.com/dgraph-io/badger/v2" at revision v2.0.0-rc.2

**Comment by Kubuxu** [comment]
The resolution is to update to `github.com/ipfs/go-ds-badger@0.0.4`.

**Comment by jin-tron** [comment]
Changed to github.com/ipfs/go-ds-badger v0.0.4 in go.mod but no luck.

**Comment by Kubuxu** [comment]
Try running `go clean -modcache`.

**Comment by hsanjuan** [comment]
Fixed in master #823

**Comment by hsanjuan** [comment]
Thanks for reporting @jin-tron
