### ISSUE TITLE
make install is taking forever

### ISSUE THREAD

**Issue by 0zAND1z** [ipfs/ipfs-cluster#825]
I just cloned the `ipfs-cluster` code on a new metal and it is taking unusual amount of time to fininish `make install` , because downloading gx, gx-go as well as the following packages is taking forever:

![image](https://user-images.githubusercontent.com/11145839/60083036-96863100-9752-11e9-94d0-fd60ebc885d5.png)

Is there a problem with the IPFS network infrastructure?

**Comment by 0zAND1z** [comment]
Just to give you guys more clarity on the speed, I just filed this issue, switched back to my terminal and here is the status:
![image](https://user-images.githubusercontent.com/11145839/60083294-1ad8b400-9753-11e9-836a-79bc342d68bf.png)

**Comment by kishansagathiya** [comment]
@0zAND1z 
Actually, we are not using gx anymore, so it shouldn't really download gx and gx-go. Is this happening on master?

**Comment by kishansagathiya** [comment]
@0zAND1z We have switched to go mod

**Comment by kishansagathiya** [comment]
@0zAND1z Are you running `make install` with `GO111MODULE=on`?

**Comment by 0zAND1z** [comment]
Thanks @kishansagathiya . I did use the master branch & this happened:

![image](https://user-images.githubusercontent.com/11145839/60089871-04385a00-975f-11e9-9d3d-7c37d4f5c875.png)

**Comment by kishansagathiya** [comment]
The errors are unrelated to cluster, this would have something to do with how go is setup on your machine.
I have two envs set on my machine
GOPATH (forgot this the first time) and GO111MODULE. Doing that might help.
There shouldn't be any problems with go version since we are using 1.11.x in travis

**Comment by 0zAND1z** [comment]
Thanks Kishan. I will close this.

**Comment by kishansagathiya** [comment]
> GOPATH (forgot this the first time) and GO111MODULE. Doing that might help.
There shouldn't be any problems with go version since we are using 1.11.x in travis

@0zAND1z Did it work for you?

**Comment by 0zAND1z** [comment]
We updated to the latest version of go (1.12.6) and exported GO111MODULE (which I think was not properly set).

However, the using the same spec in docker is still creating an issue. Not sure why.
