### ISSUE TITLE
PINNING status not go to PINNED on new peer node

### ISSUE THREAD

**Issue by jin-tron** [ipfs/ipfs-cluster#827]
**Additional information:**
 - OS: [e.g. Linux] x86_64 GNU/Linux, AWS EC2 
 - IPFS Cluster version: [e.g. 0.10.1, master] master
 - Installation method: [e.g. built from source, dist.ipfs.io, docker] built from source

**Describe the bug:**

I set up a cluster with 4 nodes, and configured replica min = max = 3.
1. ipfs-cluster-ctl add, ok
2.ipfs-cluster-ctl status, show 3 PINNED
3.chose one node in step2, kill ipfs-cluster-service daemon, ok
4.wait replica PIN to the 4th node
5.ipfs-cluster-ctl status
show the replica PINNING to the 4th node, but status never go to PINNED

I ssh to 4th node, run  "ipfs pin ls",
Error: path 'Qm****' is not pinned 

Is this scenario bring down peer node, replica will PINNED to a new node not support?
Thank you!

**Comment by hsanjuan** [comment]
Hello, PINNING means it's pinning. It's waiting on the IPFS daemon to find and retrieve that file, therefore you need to find out why IPFS is not managing to pin the file. I will close this since it does not seem a cluster-specific issue.
