### ISSUE TITLE
trouble building because of badger

### ISSUE THREAD

**Issue by ec1oud** [ipfs/ipfs-cluster#828]
```
$ cd ~/src/go/src/github.com/ipfs/ipfs-cluster
$ go install ./cmd/ipfs-cluster-service
go: github.com/dgraph-io/badger/v2@v2.0.0-rc2: missing github.com/dgraph-io/badger/go.mod and .../v2/go.mod at revision v2.0.0-rc2
go: error loading module requirements
```
I have tried doing the git clone manually, checking out the v2.0.0-rc2 tagged version... and yes, go.mod is missing in that version.  I tried copying go.mod from master branch; that didn't satisfy it either.

FWIW, in the badger directory, "go build" does something, and doesn't complain.

**Comment by kishansagathiya** [comment]
I can confirm this issue. 
I faced this just yesterday, when my PRs were failing because of this.
I have updated dependencies in https://github.com/ipfs/ipfs-cluster/pull/781
So when that merged this will get resolved.

Thanks for reporting this @ec1oud

**Comment by hsanjuan** [comment]
Please set `export GOPROXY='https://proxy.golang.org'` and should work. Badger broke dependencies twice :(

**Comment by kishansagathiya** [comment]
Fixed by https://github.com/ipfs/ipfs-cluster/pull/830

**Comment by ec1oud** [comment]
confirmed, it builds fine now.  Thanks!
