### ISSUE TITLE
The error "ERROR raft: Failed to make RequestVote RPC to ..." is output and the ipfs-cluster in back ground has stopped.

### ISSUE THREAD

**Issue by satoshi999** [ipfs/ipfs-cluster#829]
The error "ERROR raft: Failed to make RequestVote RPC to ..." is output and the ipfs-cluster in back ground has stopped

I registered ipfs-cluster as a service in Systemctl and run it in the background.
I noticed that service has stopped after 1 day.
In journal log, the following error is output after about 2 hours of startup.
"ERROR raft: Failed to make RequestVote RPC to ..."

Is there anyone who knows what caused?

**Comment by kishansagathiya** [comment]
@satoshi999 Seems like at least one of the peer is down or unreachable.

**Comment by satoshi999** [comment]
@kishansagathiya 
Thank you for comment.
Yes, I contracted ipfs-cluster with 2 node using same sercret key.
ipfs-cluster service in both node has stopped and output same error.
Why both peer's service has stopped?

**Comment by hsanjuan** [comment]
@satoshi999 can you check for other errors? It seems one of the nodes died or they lost connectivity, but after 1 day they should not stop (but rather stay running while logging this error). Would be great if you can share the logs...

**Comment by satoshi999** [comment]
@hsanjuan 
It is difficult to trace back past logs to tell the details, because I don't understand in detail about the following event.
- Configure ipfs-cluster on 2 nodes
Instance configuration is below
: boot node
 OS: Amazon linux
 CPU: t2.micro
 DISC: SSD 8G
: peer node
 OS: Amazon linux
 CPU: t2.micro
 DISC: SSD 8G
 
- Probably, both has stoped after half a day
- The instance of the peer node becomes AWS status error check, it becomed impossible to login with SSH.
- Checked the service log on boot node
- Rebuilded a cluster on boot node
- I don't know why but the peer node passes the status check and become was able to login via SSH
- But, it could not start the service on peer node
- Created other instance and joined the cluster.
:peer node2
 OS: Amazon linux
 CPU: t2.midiuam
 DISC: SSD 8G, HDD 500G
- The boot node has stopped after half a day. peer node2 is running now though it out put an unreachable error
- I confirmed that boot node is giving the following error
"ipfs [3904]: fatal error: runtime: out of memory"

I expect these to be a problem with PC specs.
I think t2.micro was indeed too small as a spec.

How much spec does every one use when build ipfs-cluster-node?

**Comment by hsanjuan** [comment]
likely your machine is running out of memory and things are failing (i.e. things stop listening). ipfs memory usage depends on how you configure it. The cluster process should not be the problem... I recommend reading https://github.com/ipfs/go-ipfs/blob/master/docs/config.md and reducing things like the max number of connections.

**Comment by hsanjuan** [comment]
I'm closing this since there are no updates. Re-open if necessary.
