### ISSUE TITLE
[Daemon] Auto-trust bootstrap peers

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#834]
**Describe the feature you are proposing**

Peers what we bootstrap with (`--bootstrap`) should be 1) trusted in consensus 2) Added to crdt trusted_peers when using crdts and saved in the config, unless a `--no-trust` flag is set.

**Additional context**

It seems the expected flow is that when you bootstrap to a peer, you implicitally trust it.

**Comment by kishansagathiya** [comment]
> saved in the config

I just want to confirm this, since we wanted to avoid cluster modifying `service.json`

**Comment by hsanjuan** [comment]
> > saved in the config
> 
> I just want to confirm this, since we wanted to avoid cluster modifying `service.json`

I have doubts depending on the day. Do without while I think more about it.
