### ISSUE TITLE
[Daemon] Init should take a list of peers

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#835]
**Describe the feature you are proposing**

`ipfs-cluster-service init --peers <multiaddress,multiaddress>`

It should:

1) Add and write the given peers to the peerstore file
2) For raft config section, add the peer IDs to the init_raft_peerset
3) For crdt config section, add the peer IDs to the trusted_peers slice 

**Additional context**

Mostly useful for CRDTs:

`ipfs-cluster-service init --peers /dnsaddr/mycluster.myclyster.io` should allow to run `ipfs-cluster-service daemon --consensus crdt` without needing the bootstrap flag.

**Comment by lanzafame** [comment]
@hsanjuan couldn't the bootstrap flag do the same things as the proposed `--peers` flag?

**Comment by hsanjuan** [comment]
> @hsanjuan couldn't the bootstrap flag do the same things as the proposed `--peers` flag?

`--bootstrap` should probably not touch the `init_raft_peerset`

Regarding adding to peerstore, I think it does (but on a different workflow, only when the peer is shutdown and the peerstore written).

Regarding trusting, yes (but I don't know if permanently)

I don't feel super comfortable with having side effects to the configuration file (re-writing it) when running the daemon.

**Comment by lanzafame** [comment]
> I don't feel super comfortable with having side effects to the configuration file (re-writing it) when running the daemon.

Actually, as long as `trusted_peers` has a env var, I think the use case I had in mind is still already addressed, cloud deployment method is just inconsistent with manual deployment. Which can be solved via documentation for the time being.
