### ISSUE TITLE
[Raft] peers rm doesn't actually remove the peer

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#840]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: 0.11.0-rc4
 - Installation method: docker

**Describe the bug:**

Running `ipfs-cluster-ctl peers rm <peerid>` logs that it removes the peer but then attempts to connect that peer again. Logs:
```
06:33:28.758  INFO  pstoremgr: connecting to QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to pstoremgr.go:315
06:33:33.759 WARNI  pstoremgr: context deadline exceeded pstoremgr.go:318
06:33:45.067  INFO    cluster: re-allocating all CIDs directly associated to QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to cluster.go:810
06:33:45.073  INFO    cluster: Peer removed  QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to cluster.go:818
06:33:58.758  INFO  pstoremgr: connecting to QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to pstoremgr.go:315
06:34:03.760 WARNI  pstoremgr: context deadline exceeded pstoremgr.go:318
```

Note this peer doesn't exist anymore, and no other peer in the cluster thinks it is still around.

Normally, removing the peerstore after shutting the peer down would be a workaround to this, but I don't have access to the volume once the peer has been shutdown.

**Comment by hsanjuan** [comment]
We are going to need to observe removed peers in Raft:

https://godoc.org/github.com/hashicorp/raft#PeerObservation

and when that happens, remove them from the peerstore (`ClearAddrs`).

And hopefully that resolves the issue (next time the peerstore is saved it should not contain that peer).

**Comment by kishansagathiya** [comment]
Can confirm this happening on master as well. 
You won't directly see this happening, since those pstoremanager related info and warning, are now debug (https://github.com/ipfs/ipfs-cluster/commit/10947c837a68cab4946f4a6e26fc01f3d8c83ee6)
