### ISSUE TITLE
IPFS dataset public replication (rsync-like)

### ISSUE THREAD

**Issue by mibofra** [ipfs/ipfs-cluster#844]
Hi all!

I'm Francesco, a Parrot Security OS developer

I've made a copy of the whole Parrot Sec OS repository under IPFS /ipns/QmUhEJjvaYWbxnGUD2Y5UsVrNNZHqpftEsq2QhQaKBgnqZ

I'm really interested in IPFS! It is so nice. Of what I've understood of IPFS, I've made some scripts to make simpler to parrot users to make a copy of the IPFS repository on other nodes:

https://nest.parrotsec.org/parrot-packages/ipfs-mirroring

Don't blame me please if something is incorrect :D , I'm still exploring and learning IPFS and its possibilities.

The idea is to use https://github.com/JaquerEspeis/apt-transport-ipfs as apt transport for the debian packages on the repo (that is working, it needs an update to the newest ipfshttpclient, but it's working)

But ipfs-cluster seems the ideal tool to manage the whole mess really, instead of my scripts.

So, is there the possibility to have a rsync-like function? This means that there is a "master read-only" node, where all the other nodes can publicly connect to, but not managing the pinning sets, just copy them and "sync" from the node as an exact replica, without password.

Sorry if there is already this possibility or an ipfs/ipfs-cluster setup that makes me reach this possibility, but I don't really know it (yet).

Thanks in any reply :)

**Comment by hsanjuan** [comment]
Hello,

the next release (and current master) support cluster made of 1 (or several) "trusted peers" (peers that can modify the pinset) along with followers (peers that cannot modify the peerset nor have any API access to other peers). We call this "collaborative clusters" or "crdt mode", but we are in the process of creating the related documentation before releasing it.

the tl;dr is starting cluster with `ipfs-cluster-service --consensus crdt` and filling the `trusted_peers` array with the list of trusted peers in the `crdt` section in `service.json`. The rest is like before (you will need to `--bootstrap` to an already running peer or put their addresses in the `peerstore` file).

By the way, you may want to get in touch with @andrew and @meiqimichelle from our package managers group as they are working specifically on these usecases.

**Comment by mibofra** [comment]
So you are finally implementing the collaborative user case which is in the roadmap :) https://cluster.ipfs.io/roadmap/ . Nice! I will contact them and surely make feedbacks on this usecase. Thanks in the reply :) . I'm pretty glad that its mostly implemented. I'm looking forward the doc too!

In any case, I'm pretty glad to test it! Let me know if I can do anything when debugging to make progress on this feature.

**Comment by hsanjuan** [comment]
> I'm pretty glad that its mostly implemented

It is implemented, we just haven't released it, pending documentation mostly (we are re-doing all docs)

**Comment by mibofra** [comment]
Oh ok! So it is already all implemented. Thanks for the clarification :)

**Comment by andrew** [comment]
@mibofra great timing, the [package managers](https://github.com/ipfs/package-managers/) team is focused on supporting the mirroring of file system based package manager repositories like yours this quarter.

Would be great to chat about your experience adding your repository to IPFS and what improvements we're working on.

**Comment by mibofra** [comment]
@andrew I'm really willing to... I'm just annoyed that our installation of gitlab at nest. is temporarily down... I've also a copy of an updated version of apt-transport-ipfs to use the latest (and tested, it works), ipfshttpclient instead of ipfsapi. I've pull requested back the modifications: https://github.com/JaquerEspeis/apt-transport-ipfs/pull/3 , and we are planning to make a debian package (for Parrot now, submitting for revision directly to Debian later) for the transport.

So I'll guess I'll strart from the freenode channel :) 

Anyway, basically you will see when nest will be reachable, that simply I made some bash scripts, and a systemd service for the ipfs daemon. One is syncing first from an rsync mirror, and after add all the repo to ipfs datastore, after setting the repo up, and the user for the systemd service. The other, is making the pinning directly from a node already synced on ipfs. 

I've to write the services and  the detection for other systems that are not using systemd as default. Also because the scripts are so simple that should be working also on openwrt with the ash integrated in busybox.

After, to don't eat space, I'm updating the pinnig, using a file to store (but I could use anything else, simply they are bash scripts) the hash of the root dir of the all dataset, and after use an ipfs update oldhash newhash to update the pinning, to make the garbage collector free space. And the "provider nodes" (in this case the trusted peers, syncing first from rsync directly) are updating the ipns name to use the new hashes.

All of this can be rewritten in python3 or go too, the logic is the same.

The whole mess is the realtime sync of the pinsets. I currently sync the pinsets time based with a cronjob. Instead, in this case, I can use, as an example, the cluster proxy as documented in the docs, to update the pinning of all the cluster simultaneously, from the old hash to the new one, and scaling widely without issues :D . That is why I'm so interested in ipfs-cluster.

**Comment by mibofra** [comment]
P.S. nest. is online, so if you are curious, you can view my scripts. Anyway I'm updating them to work with ipfs-cluster :)

**Comment by hsanjuan** [comment]
@mibofra we released 0.11.0 and documentation for it. I'm closing this for the moment but let me know if you need any help!
