### ISSUE TITLE
"ipfs-cluster-ctl add --local" adds to the local peer

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#848]
**Describe the feature you are proposing**

~~A --local flag to "ipfs-cluster-ctl add" should allow to add and pin only on the local peer (with replication-factor=1).~~

**Additional context**

~~Adding may be cumbersome if trying to reach a high replication factor with unavailable peers. This should allow users add to their local node only (they can then re-pin if they want to increase the replication factor).~~

~~This is almost the equivalent of adding with ReplicationFactor=1 + UserAllocations=LocalPeer. However, it might be probably best to carry it as a new, separate add option (to cover the case where there are no local metrics. In that case, the given UserAllocations would be ignored in favour of some other peer).~~

**Comment by hsanjuan** [comment]
Edit:

The `local` flag should specify that the blocks are added locally, regardless of the Allocations they are given. They will be added to the local IPFS peer rather than being sent to remote allocations. Pinning will proceed as normal, with the normal pin allocations, meaning rather than putting content directly at the location, it will have to be copied when pinning.

**Comment by kishansagathiya** [comment]
I am thinking of not using adder for this.

A method for `AddLocal` could be added to cluster and IPFSConnector for this, which would accept a struct (not AddParams) containing file/dir path and some parameters.
And from handler just call rpc methods for `AddLocal` and then `Pin`

**Comment by hsanjuan** [comment]
Use the adder for this. Handle a new `Local` AdderParam in the adders.

What you are thinking does not work. The adding happens through a multipart upload in the API, not by reading a file from disk (ctl does the reading). And that would only be an option if you could stream from the API component to the IPFS component. So use the existing adder, which is way simpler, apart from being the only way I see to do this.
