### ISSUE TITLE
Improve error handling on "add"

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#852]
**Describe the feature you are proposing**

The add process is aborted whenever one of the peers receiving blocks errors. This makes it hard to add things to some clusters if a peer goes away for example. We should:

* Keep adding to peers that never errored
* Remember the peers that errored so that we don't try to put more blocks on them
* as long as the content is added to one place, the peers that errored will be able to fetch it later when pinning.

**Additional context**

This is part of the `adder` submodule and how we handle RPC requests to `IPFSConnector.PutBlock` from there (both local and sharding).

Tests adding to peers which are down and peers which are not should be included.

(Of course all peers fail, adding should stop).

**Comment by kishansagathiya** [comment]
This would require rpc Cluster.BlockAllocate to support blocklists.

Apart from that.
 If peers receiving blocks errors, we block them on coming `add` requests, and not retry the current add request with other peers, right?

**Comment by hsanjuan** [comment]
> If peers receiving blocks errors, we block them on coming add requests, and not retry the current add request with other peers, right?

Right

> This would require rpc Cluster.BlockAllocate to support blocklists.

No. Don't overthink it. This affects `putDAG` and `BlockPut` (util.go) functions in the `adder` which will need memory of blocks peers that failed before (thus probably need to turn into BlockPutHelper, consolidate the common code in both. For sharding. every shard starts with a blank memory.

**Comment by kishansagathiya** [comment]
I don't see any better way for doing this (having a common timecache that could be checked during add) than moving putDAG and PutBlock to cluster methods and accessing them through rpc.

**Comment by hsanjuan** [comment]
It just just about having a map. There is not need for a time cache. Every add process or every shard process checks if a peer is in a map before doing block-puts. That's all. It is simple.

**Comment by kishansagathiya** [comment]
> It just just about having a map. There is not need for a time cache.

So, if a peer errors, we never put any blocks on them again? If we do, a map wouldn't tell when to start putting blocks on them as well.

> Every add process or every shard process checks if a peer is in a map before doing block-puts. That's all. It is simple.

But that map has to be stored somewhere and could be persist for one cluster(`daemon`) run, which could happen by putting it in one of the components. The `adder` is basically a utility, I can't put that information there. I can either put it in `Cluster` or `rest.API`. 

Instead of putting it in `rest.API` and passing it from function to function to function, I think it would be cleaner to put it in Cluster and use cluster methods.

**Comment by hsanjuan** [comment]
OK. Make this in adder/util.go:

```go
type DAGPutHelper struct {
   dests []peer.ID
   rpcClient *rpc.Client
}

func (dph *DAGPutHelper) PutNode(n (n ipld.Node) error {
// 1 put a block in dests. copy-paste existing code.
// 2 for auth errors remove block from dests 
// 3 for client errors nothing
// 4 for server errors remove block from dests
// if len(dests) == 0 return an error. Otherwise, return nil
}

func (dph *DAGPutHelper) PutNodes(ctx, nodes []ipld.Node) error {
   for _, n := range nodes {
      err := dph.PutNode(ctx, n)
      // if not nil return error
  } 
}
```

The sharding dag service uses a new PutHelper per Shard. The local dag service uses a single PutHelper during its lifetime (which corresponds to adding one thing).
