### ISSUE TITLE
Avoid joining a peer that is already part of cluster

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#859]
**Describe the feature you are proposing**

`ipfs-cluster-service daemon --bootstrap <multiaddress>` will try to join bootstrap peers passed through the cmd option and will also try to join peers stored in peerstore. It is likely that we have joined the cluster before, in which case we will be trying to `Join` twice.

**Comment by hsanjuan** [comment]
I don't think that is the case. `Join` is only called for bootstrap peers. You must be referring to calling Connect to those peers, which is fine.

**Comment by kishansagathiya** [comment]
I opened it because I observed it during this PR https://github.com/ipfs/ipfs-cluster/pull/858/commits/bde4cc8cef7a5ebe8a3b1ca2d428e4582f1df50f#diff-5012ac478fddb03fa409c41a16a72b0dR838

Closing it, since I can't reproduce it on master
