### ISSUE TITLE
ipfs-cluster version question

### ISSUE THREAD

**Issue by zhjgit** [ipfs/ipfs-cluster#895]
hello, I would like to ask if ipfs-cluster v0.4.0 is compatible with the latest version of go-ipfs v0.4.22. I don't really want to upgrade cluster service and cli version.

**Comment by hsanjuan** [comment]
Hello, it probably is, but I'm not sure and you should upgrade.

**Comment by zhjgit** [comment]
If not, how can I match the latest version of go-ipfs when I choose the ipfs-cluster version? @hsanjuan

**Comment by hsanjuan** [comment]
Always choose the latest version of cluster. Compatiblity with IPFS depends solely on the ipfs API, and it does not change much. But cluster is adjusted to work well with the latest version of ipfs.
