### ISSUE TITLE
Can I build ipfs-cluster over a global network?

### ISSUE THREAD

**Issue by satoshi999** [ipfs/ipfs-cluster#902]
Can I build ipfs-cluster over a global network?
Currently trying to build a cluster with the following configuration
-Create EC2 instance on AWS and start ipfs and ipfs-cluster daemon
-Create another EC2 instance and start ipfs and ipfs-cluster daemon
At that time, start the first EC2 instance as a boot node. I was able to connect.
This mutil address is "/ip4/{private ip}/tcp/9096/ipfs/Qm....”. In other words, private ip is specified
→ In other words, cluster construction by private ip on AWS succeeded.
・ Two Mac books were prepared and connected to the same wifi access point.
・ I was able to connect the other as the boot node and mutil address = "/ip4/{private ip}/tcp/ 9096/ipfs/Qm ....” with private ip specified.
→ In other words, I was able to connect machines connected to the same wifi on the local machine with private ip.

However, if I try to connect to the AWS boot node from the local machine, an error will occur and you will not be able to connect.
If you specify prviate ip with "/ip4/{private ip}/tcp/9096/ipfs/Qm ....", you will get a "failed: dial backoff" error.
If you specify public ip with "/ip4/{public ip}/tcp/9096/ipfs/Qm ....", a "protocol not supported" error will be displayed.

Is ipfs-cluster construction not supported over the global network?

**Comment by hsanjuan** [comment]
> Is ipfs-cluster construction not supported over the global network?

Yes it's possible, but you need to make sure that:

* You know basic networking and AWS operation (assigning public IPs, opening security groups etc)
* All peers run the same version of cluster
* All peers are configured with the same secret

**Comment by satoshi999** [comment]
@hsanjuan 
The AWS security group is as follows. Are there any missing ports?
I don't think any special operation is required for setting public IP. A screenshot of the public IP is also attached.
also I'm using the default VPC.

I specified "export CLUSTER_SECRET = {boot node secret}" before "ipfs-cluster-service init" command. I also checked service.json.

The ver is not still confirmed, but is it the only reason why it cannot be built over the global network?
<img width="521" alt="スクリーンショット 2019-08-26 18 39 35" src="https://user-images.githubusercontent.com/18362018/63682886-e7d69d80-c833-11e9-99e2-a7314a8b480b.png">
<img width="495" alt="スクリーンショット 2019-08-26 18 40 09" src="https://user-images.githubusercontent.com/18362018/63682892-eb6a2480-c833-11e9-8eba-6d88997438c5.png">

**Comment by hsanjuan** [comment]
ok, double check the version and we'll go on from there, as it is the only thing I can think of to explain your error message.

**Comment by satoshi999** [comment]
@hsanjuan 
I downloaded the latest version of mac and linux from the download page and make the ver of ipfs and ipfs-cluster-servie & ctl the same.
Then, I specified the AWS global IP, I was able to connect well.
Thank you so much! I understood that it was a ver problem.
