### ISSUE TITLE
ERROR   apitypes: error decoding update option parameter:  cid too short

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#908]
**Additional information:**
 - OS: Linux
 - IPFS Cluster version:  master, ef8483e30e4231bc45dd982065f7a4db5cec66fc
 - Installation method: built from source

**Describe the bug:**

Any time you run `ipfs-cluster-ctl pin add`, this error occurs
```
15:55:11.887 ERROR   apitypes: error decoding update option parameter:  cid too short types.go:576
```

So, all pin requests are considered to be pin update requests first and try to decode second argument.

actionables:
- Differentiate between `new pin` and `pin update`, ignore second argument for new pin.

**Comment by hsanjuan** [comment]
Please double check your version. This was fixed in 6743f92e51b8184fb866d4e9c34e1fe37ae545b9
