### ISSUE TITLE
ipfs-cluster-ctl status doesn't output the status for all peers

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#910]
**Additional information:**
 - OS: Ubuntu 19.04 x86_64
 - IPFS Cluster version: 0.11.0-rc8+gitef8483e30e4231bc45dd982065f7a4db5cec66fc
 - Installation method: built from source

**Describe the bug:**

A clear and concise description of what the bug is and how the behaviour was different from expected.

The output of `ipfs-cluster-ctl status` is something like this : 

```
QmYBrUpgc3DRy5eHEDhnanRHbK67ujc6ZCm6uk6QgDjPca :
    > nato-hu              : PIN_QUEUED | 2019-09-03T00:30:37.99061413-04:00
QmUBAPFNJurqs4MTCoxsk1JhJiLeJPR64z4pPth3NXwZRK :
    > nato-hu              : PIN_QUEUED | 2019-09-03T00:25:23.898451099-04:00
```

However, it fails to mention the other peers and their status from the cluster.

```
12D3KooWRHHTLLsiTEtnq8FfC2kMEbVGhkUH98Xj1P96jq7sSXsG | hp-server | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWRHHTLLsiTEtnq8FfC2kMEbVGhkUH98Xj1P96jq7sSXsG
    - /ip4/192.168.1.3/tcp/9096/ipfs/12D3KooWRHHTLLsiTEtnq8FfC2kMEbVGhkUH98Xj1P96jq7sSXsG
  > IPFS: QmdbzQ5mP9GRpqqrTsA43YbDgRJnZjHwFBCPJesKLERFVK
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmdbzQ5mP9GRpqqrTsA43YbDgRJnZjHwFBCPJesKLERFVK
    - /ip4/135.23.195.69/tcp/1925/ipfs/QmdbzQ5mP9GRpqqrTsA43YbDgRJnZjHwFBCPJesKLERFVK
    - /ip4/192.168.1.3/tcp/4001/ipfs/QmdbzQ5mP9GRpqqrTsA43YbDgRJnZjHwFBCPJesKLERFVK
    - /ip6/::1/tcp/4001/ipfs/QmdbzQ5mP9GRpqqrTsA43YbDgRJnZjHwFBCPJesKLERFVK
    - /ip6/fd16:8b3a:8f57:0:6631:50ff:fe5b:b589/tcp/4001/ipfs/QmdbzQ5mP9GRpqqrTsA43YbDgRJnZjHwFBCPJesKLERFVK
    - /ip6/fd16:8b3a:8f57::c7a/tcp/4001/ipfs/QmdbzQ5mP9GRpqqrTsA43YbDgRJnZjHwFBCPJesKLERFVK
12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74 | nato-hu | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.1.2/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.122.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
  > IPFS: QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/135.23.195.69/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.1.2/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.122.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/::1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/fd16:8b3a:8f57:0:c8b5:e028:9803:d4c5/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/fd16:8b3a:8f57::7fc/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY | lineageos-on-ipfs | Sees 2 other peers
  > Addresses:
    - /ip4/10.20.0.5/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
    - /ip4/159.89.116.13/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
  > IPFS: QmUR8d2WLbNcAFRMWn3SMdBRDhJugZUezfwLkDYti3Gc3w
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmUR8d2WLbNcAFRMWn3SMdBRDhJugZUezfwLkDYti3Gc3w
    - /ip4/159.89.116.13/tcp/4001/ipfs/QmUR8d2WLbNcAFRMWn3SMdBRDhJugZUezfwLkDYti3Gc3w
    - /ip6/2604:a880:cad:d0::17:2001/tcp/4001/ipfs/QmUR8d2WLbNcAFRMWn3SMdBRDhJugZUezfwLkDYti3Gc3w
    - /ip6/::1/tcp/4001/ipfs/QmUR8d2WLbNcAFRMWn3SMdBRDhJugZUezfwLkDYti3Gc3w
```

This only happen in `crdt` mode from non-trusted peers.

**Comment by kishansagathiya** [comment]
It is expected. `ipfs-cluster-ctl status` make a broadcast of  rpc call `PinTracker.Status`, which can only be called by trusted peers.

**Comment by kishansagathiya** [comment]
You can get pin status from a peer only if it trusts you.

**Comment by hsanjuan** [comment]
@NatoBoram the question is, are you calling `status` from a peer that is trusted by the others?

**Comment by NatoBoram** [comment]
Nope. I didn't realize a peer needed to be trusted to access `PinTracker.Status`.

Wouldn't it make sense to be able to see it, considering we already see the whole state?

**Comment by obo20** [comment]
@kishansagathiya How does this work in the context of follower nodes?

My understanding was that one of the main benefits of utilizing CRDT consensus is that we can have "master nodes" that trust each other, and then "follower nodes" that copy whatever the master state has, but don't have write access.

**Comment by kishansagathiya** [comment]
@NatoBoram 

> Wouldn't it make sense to be able to see it, considering we already see the whole state?

If an item is part of the shared state, that tells whether it is supposed to be pinned. It doesn't tell if it is actually pinned at the moment or not.
Follower nodes have access to call only those RPC calls that are necessary to perform their follow task. We also have to be concerned about not letting them access any call that could require high resources. This is to stay safe from malicious nodes.

**Comment by kishansagathiya** [comment]
I am going to close this untrusted peers not being able to see status is expected behaviour. Feel free to reopen if you still have questions around it.
