### ISSUE TITLE
Check if all files have been replicated to the new node

### ISSUE THREAD

**Issue by volodyad** [ipfs/ipfs-cluster#916]
There is a scenario

1. Start ipfs and ipfs-cluster on the first vm
2. Upload  files
3. Start ipfs and ipfs-cluster on the second vm
4. Wait all data replicated form the first vm to the second vm
5. Delete ipfs and ipfs-cluster from the first vm

What approach can we use to check step 4? How can we know that all files from the first vm have been replicated to the second vm?

**Comment by hsanjuan** [comment]
` ipfs-cluster-ctl --enc=json status --filter pinned --local | jq '.[].cid | .["/"]' | wc -l` and `ipfs-cluster-ctl pin ls | wc -l` on the second VM should give the same number (`pin ls` should be the total number of pins).

But if you just want to copy the ipfs repository you can also rsync it from one place to the other..

**Comment by volodyad** [comment]
Do you think that rsync approach is better than waiting for new node to replicate all the data?

**Comment by hsanjuan** [comment]
I'll close this for the moment. Please send questions primarily to the discourse forums in the future.
