### ISSUE TITLE
Makefile fails on target deps on OS X

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#92]
Thursday April 13th 

While running Makefile the target deps generates unexpected errors while running $(gx-go_bin) rewrite.  Surprisingly calling the gx-go binary installed by cluster's makefile to perform rewrite, as well as calling gx-go rewrite using the in-path gx-go rewrite does not terminate with errors.  Printing verbosely did not seem to provide any useful extra information.

Here is the full output of make build after a make clean:
"
bash-3.2$ make build
deptools/gx_v0.11.0 install --global
installation of dep go-libp2p-consensus complete!
installation of dep go-semver complete!
installation of dep dns complete!
installation of dep go-text complete!
installation of dep go-net complete!
installation of dep mdns complete!
installation of dep go-randbuf complete!
installation of dep go-msgio complete!
installation of dep go-crypto complete!
installation of dep go-base58 complete!
installation of dep go-multihash complete!
installation of dep go-base58 complete!
installation of dep go-ipfs-util complete!
installation of dep go-keyspace complete!
installation of dep go-multistream complete!
installation of dep go-detect-race complete!
installation of dep goprocess complete!
installation of dep go-logging complete!
installation of dep go-log complete!
installation of dep go-multiaddr complete!
installation of dep go-multiaddr-net complete!
installation of dep go-multihash complete!
installation of dep multiaddr-filter complete!
installation of dep go-base58 complete!
installation of dep go-crypto complete!
installation of dep gogo-protobuf complete!
installation of dep go-multiaddr complete!
installation of dep go-metrics complete!
installation of dep randbo complete!
installation of dep go-notifier complete!
installation of dep go-temp-err-catcher complete!
installation of dep go-stream-muxer complete!
installation of dep go-libp2p-protocol complete!
installation of dep mafmt complete!
installation of dep go-libp2p-transport complete!
installation of dep go-peerstream complete!
installation of dep mafmt complete!
installation of dep gorocheck complete!
installation of dep ed25519 complete!
installation of dep go-libp2p-crypto complete!
installation of dep go-libp2p-peer complete!
installation of dep go.uuid complete!
installation of dep go-libp2p-loggables complete!
installation of dep go-libp2p-secio complete!
installation of dep go-libp2p-peerstore complete!
installation of dep websocket complete!
installation of dep ws-transport complete!
installation of dep go-libp2p-transport complete!
installation of dep go-sockaddr complete!
installation of dep go-net-resolve-addr complete!
installation of dep GoEndian complete!
installation of dep eventfd complete!
installation of dep go-reuseport complete!
installation of dep go-tcp-transport complete!
installation of dep go-maddr-filter complete!
installation of dep go-libp2p-protocol complete!
installation of dep go-addr-util complete!
installation of dep go-datastore complete!
installation of dep go-testutil complete!
installation of dep go-libp2p-interface-conn complete!
installation of dep go-libp2p-interface-pnet complete!
installation of dep go-libp2p-conn complete!
installation of dep go-libp2p-net complete!
installation of dep go-libp2p-metrics complete!
installation of dep go-libp2p-interface-conn complete!
installation of dep go-libp2p-host complete!
installation of dep spdystream complete!
installation of dep go-smux-spdystream complete!
installation of dep go-smux-multistream complete!
installation of dep yamux complete!
installation of dep go-smux-yamux complete!
installation of dep go-libp2p-swarm complete!
installation of dep goupnp complete!
installation of dep gateway complete!
installation of dep go-nat-pmp complete!
installation of dep go-nat complete!
installation of dep go-libp2p-nat complete!
installation of dep go-libp2p-netutil complete!
installation of dep go-libp2p-blankhost complete!
installation of dep go-libp2p complete!
installation of dep go-metrics complete!
installation of dep go-codec complete!
installation of dep raft complete!
installation of dep cbor complete!
installation of dep go-multicodec complete!
installation of dep go-libp2p-raft complete!
installation of dep go-crypto complete!
installation of dep go-multihash complete!
installation of dep go-multibase complete!
installation of dep go-cid complete!
installation of dep cli complete!
installation of dep bolt complete!
installation of dep raft-boltdb complete!
installation of dep context complete!
installation of dep mux complete!
installation of dep go-libp2p-gorpc complete!
installation of dep ipfs-cluster complete!
deptools/gx-go_v1.4.0 rewrite
go build -ldflags "-X ipfscluster.Commit=98039bdd0d5d77f1230bef5e65b7d21069548a95"
vendor/gx/ipfs/QmWRzh5sntXhuZaxmGDEjjBhg1nX7DgaMdhBeik42LZdEv/raft/raft.go:14:2: cannot find package "github.com/armon/go-metrics" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/armon/go-metrics (vendor tree)
	/usr/local/go/src/github.com/armon/go-metrics (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/armon/go-metrics (from $GOPATH)
vendor/gx/ipfs/QmUDCcPkPMPJ149YBpfFLWJtRFeqace5GNdBPD2cW4Z8E6/raft-boltdb/bolt_store.go:6:2: cannot find package "github.com/boltdb/bolt" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/boltdb/bolt (vendor tree)
	/usr/local/go/src/github.com/boltdb/bolt (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/boltdb/bolt (from $GOPATH)
vendor/gx/ipfs/QmUDCcPkPMPJ149YBpfFLWJtRFeqace5GNdBPD2cW4Z8E6/raft-boltdb/bolt_store.go:7:2: cannot find package "github.com/hashicorp/raft" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/hashicorp/raft (vendor tree)
	/usr/local/go/src/github.com/hashicorp/raft (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/hashicorp/raft (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:15:2: cannot find package "github.com/jbenet/go-stream-muxer" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/jbenet/go-stream-muxer (vendor tree)
	/usr/local/go/src/github.com/jbenet/go-stream-muxer (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/jbenet/go-stream-muxer (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/limiter.go:7:2: cannot find package "github.com/libp2p/go-addr-util" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-addr-util (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-addr-util (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-addr-util (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:19:2: cannot find package "github.com/libp2p/go-libp2p-conn" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-conn (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-conn (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-conn (from $GOPATH)
vendor/gx/ipfs/QmW92B7boZiW7qBEUE2aT8vi3WNLWpk6on4mxg1CpEzLpB/go-libp2p-raft/actor.go:7:2: cannot find package "github.com/libp2p/go-libp2p-consensus" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-consensus (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-consensus (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-consensus (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:21:2: cannot find package "github.com/libp2p/go-libp2p-interface-pnet" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-interface-pnet (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-interface-pnet (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-interface-pnet (from $GOPATH)
vendor/gx/ipfs/QmSNJRX4uphb3Eyp69uYbpRVvgqjPxfjnJmjcdMWkDH5Pn/go-libp2p/p2p/host/basic/natmgr.go:10:2: cannot find package "github.com/libp2p/go-libp2p-loggables" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-loggables (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-loggables (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-loggables (from $GOPATH)
vendor/gx/ipfs/QmSNJRX4uphb3Eyp69uYbpRVvgqjPxfjnJmjcdMWkDH5Pn/go-libp2p/p2p/host/basic/basic_host.go:13:2: cannot find package "github.com/libp2p/go-libp2p-metrics" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-metrics (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-metrics (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-metrics (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:23:2: cannot find package "github.com/libp2p/go-libp2p-metrics/conn" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-metrics/conn (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-metrics/conn (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-metrics/conn (from $GOPATH)
vendor/gx/ipfs/QmSNJRX4uphb3Eyp69uYbpRVvgqjPxfjnJmjcdMWkDH5Pn/go-libp2p/p2p/host/basic/basic_host.go:14:2: cannot find package "github.com/libp2p/go-libp2p-metrics/stream" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-metrics/stream (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-metrics/stream (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-metrics/stream (from $GOPATH)
vendor/gx/ipfs/QmSNJRX4uphb3Eyp69uYbpRVvgqjPxfjnJmjcdMWkDH5Pn/go-libp2p/p2p/host/basic/natmgr.go:7:2: cannot find package "github.com/libp2p/go-libp2p-nat" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-nat (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-nat (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-nat (from $GOPATH)
vendor/gx/ipfs/QmW92B7boZiW7qBEUE2aT8vi3WNLWpk6on4mxg1CpEzLpB/go-libp2p-raft/transport.go:17:2: cannot find package "github.com/libp2p/go-libp2p-swarm" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p-swarm (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p-swarm (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p-swarm (from $GOPATH)
vendor/gx/ipfs/QmW92B7boZiW7qBEUE2aT8vi3WNLWpk6on4mxg1CpEzLpB/go-libp2p-raft/transport.go:18:2: cannot find package "github.com/libp2p/go-libp2p/p2p/host/basic" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p/p2p/host/basic (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p/p2p/host/basic (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p/p2p/host/basic (from $GOPATH)
vendor/gx/ipfs/QmSNJRX4uphb3Eyp69uYbpRVvgqjPxfjnJmjcdMWkDH5Pn/go-libp2p/p2p/host/basic/basic_host.go:8:2: cannot find package "github.com/libp2p/go-libp2p/p2p/protocol/identify" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p/p2p/protocol/identify (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p/p2p/protocol/identify (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p/p2p/protocol/identify (from $GOPATH)
vendor/gx/ipfs/QmSNJRX4uphb3Eyp69uYbpRVvgqjPxfjnJmjcdMWkDH5Pn/go-libp2p/p2p/host/basic/basic_host.go:9:2: cannot find package "github.com/libp2p/go-libp2p/p2p/protocol/relay" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-libp2p/p2p/protocol/relay (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-libp2p/p2p/protocol/relay (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-libp2p/p2p/protocol/relay (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:29:2: cannot find package "github.com/libp2p/go-peerstream" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-peerstream (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-peerstream (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-peerstream (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:30:2: cannot find package "github.com/libp2p/go-tcp-transport" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/libp2p/go-tcp-transport (vendor tree)
	/usr/local/go/src/github.com/libp2p/go-tcp-transport (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/libp2p/go-tcp-transport (from $GOPATH)
vendor/gx/ipfs/QmcTcsTvfaeEBRFo1TkFgT8sRmgi1n1LTZpecfVP8fzpGD/go-cid/cid.go:10:2: cannot find package "github.com/multiformats/go-multibase" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/multiformats/go-multibase (vendor tree)
	/usr/local/go/src/github.com/multiformats/go-multibase (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/multiformats/go-multibase (from $GOPATH)
vendor/gx/ipfs/QmYqnvVzUjjVddWPLGMAErUjNBqnyjoeeCgZUZFsAJeGHr/go-libp2p-gorpc/stream_wrap.go:7:2: cannot find package "github.com/multiformats/go-multicodec" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/multiformats/go-multicodec (vendor tree)
	/usr/local/go/src/github.com/multiformats/go-multicodec (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/multiformats/go-multicodec (from $GOPATH)
vendor/gx/ipfs/QmW92B7boZiW7qBEUE2aT8vi3WNLWpk6on4mxg1CpEzLpB/go-libp2p-raft/codec.go:7:2: cannot find package "github.com/multiformats/go-multicodec/msgpack" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/multiformats/go-multicodec/msgpack (vendor tree)
	/usr/local/go/src/github.com/multiformats/go-multicodec/msgpack (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/multiformats/go-multicodec/msgpack (from $GOPATH)
vendor/gx/ipfs/QmUDCcPkPMPJ149YBpfFLWJtRFeqace5GNdBPD2cW4Z8E6/raft-boltdb/util.go:7:2: cannot find package "github.com/ugorji/go/codec" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/ugorji/go/codec (vendor tree)
	/usr/local/go/src/github.com/ugorji/go/codec (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/ugorji/go/codec (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:32:2: cannot find package "github.com/whyrusleeping/go-smux-multistream" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/whyrusleeping/go-smux-multistream (vendor tree)
	/usr/local/go/src/github.com/whyrusleeping/go-smux-multistream (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/whyrusleeping/go-smux-multistream (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:33:2: cannot find package "github.com/whyrusleeping/go-smux-spdystream" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/whyrusleeping/go-smux-spdystream (vendor tree)
	/usr/local/go/src/github.com/whyrusleeping/go-smux-spdystream (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/whyrusleeping/go-smux-spdystream (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:34:2: cannot find package "github.com/whyrusleeping/go-smux-yamux" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/whyrusleeping/go-smux-yamux (vendor tree)
	/usr/local/go/src/github.com/whyrusleeping/go-smux-yamux (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/whyrusleeping/go-smux-yamux (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:35:2: cannot find package "github.com/whyrusleeping/multiaddr-filter" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/whyrusleeping/multiaddr-filter (vendor tree)
	/usr/local/go/src/github.com/whyrusleeping/multiaddr-filter (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/whyrusleeping/multiaddr-filter (from $GOPATH)
vendor/gx/ipfs/QmY8hduizbuACvYmL4aZQbpFeKhEQJ1Nom2jY6kv6rL8Gf/go-libp2p-swarm/swarm.go:36:2: cannot find package "github.com/whyrusleeping/ws-transport" in any of:
	/Users/ZenGround0/go/src/github.com/ipfs/ipfs-cluster/vendor/github.com/whyrusleeping/ws-transport (vendor tree)
	/usr/local/go/src/github.com/whyrusleeping/ws-transport (from $GOROOT)
	/Users/ZenGround0/go/src/github.com/whyrusleeping/ws-transport (from $GOPATH)
make: *** [build] Error 1
"

**Comment by ZenGround0** [comment]
This same issue is occurring on the same machine when trying to build the docker image.

**Comment by Kubuxu** [comment]
Is make on Mac a GNU make?

**Comment by hsanjuan** [comment]
I understand this problem was somehow resolved...

**Comment by ZenGround0** [comment]
Can confirm this now longer shows up when I build.  Wish I had an explanation why

**Comment by hsanjuan** [comment]
@owenauch it would seem you haven't checked out the git repo in the right GOPATH

**Comment by dill0wn** [comment]
I'm having the same issue as @owenauch.  I also have a custom `$GOPATH` `/Users/dill0wn/Work/go/`

Ah, I am a go noobie, and I found my issue. I followed the installation documentation for [Unix](https://cluster.ipfs.io/documentation/download/#unix), which says:

```
git clone https://github.com/ipfs/ipfs-cluster.git $GOPATH/github.com/ipfs/ipfs-cluster
cd $GOPATH/github.com/ipfs/ipfs-cluster
make install
```

I fixed my errors by changing the destination path from
`$GOPATH/github.com/ipfs/ipfs-cluster` to 
`$GOPATH/src/github.com/ipfs/ipfs-cluster`

Does this seem correct?

If so, could someone please update the documentation?

**Comment by dill0wn** [comment]
I got it to work!

I am a go noobie, so this might be obvious to others, but I found my issue. 

I followed the installation documentation for [Unix](https://cluster.ipfs.io/documentation/download/#unix), which says:

```
git clone https://github.com/ipfs/ipfs-cluster.git $GOPATH/github.com/ipfs/ipfs-cluster
cd $GOPATH/github.com/ipfs/ipfs-cluster
make install
```

I fixed my errors by changing the destination path from
`$GOPATH/github.com/ipfs/ipfs-cluster` to 
`$GOPATH/src/github.com/ipfs/ipfs-cluster`

Does this seem correct?

If so, could someone please update the documentation?
