### ISSUE TITLE
Docs Request: Better explanation of pin statuses

### ISSUE THREAD

**Issue by obo20** [ipfs/ipfs-cluster#921]
Currently these are the following statuses that can be returned from ipfs-cluster's "status" API endpoint:

* error
* cluster_error
* pin_error
* pin_queued
* pinned
* pinning
* queued
* remote
* unpin_error
* unpin_queued
* unpinned
* unpinning

I don't see them listed anywhere in the actual documentation (I found them from the help command on the CLI), nor are they actually explained in detail anywhere.

It would be really valuable to have each of these states documented somewhere in the official documentation so developers know what each state means. 

I know the states are sort of self explanatory, but a finer explanation of each state would really be appreciated when architecting out a system to account for edge cases.

A good example of this is how I would have no idea the difference between `queued` and `pin_queued` without directly reaching out to the cluster team and asking. Similarly, `error` and `pin_error`.

**Comment by kishansagathiya** [comment]
+1 on this @obo20 
We need a document on pinning with cluster

**Comment by hsanjuan** [comment]
Is this good enough? cluster.ipfs.io/documentation/guides/pinning/#filtering-results

**Comment by kishansagathiya** [comment]
Feel free to reopen if you think https://cluster.ipfs.io/documentation/guides/pinning/#filtering-results could be improved
