### ISSUE TITLE
ipfs-cluster backup files between multiple nodes

### ISSUE THREAD

**Issue by zhjgit** [ipfs/ipfs-cluster#922]
I have a question about whether ipfs-cluster can be configured. When one of the nodes in the cluster uploads a file, not pin, but other nodes backup all the data of the file synchronously.The reason is that for fear that one node's disk is broken, the other node has backup data, so it is safer.

**Comment by zhjgit** [comment]
I found that the files currently uploaded are stored in the uploaded nodes and can only be activated when other connected nodes have access to the hash. Whether the data of leading and slave nodes can be backed up synchronously in the cluster, just like the ethereum blockChain, each access node has a complete blockChain data

**Comment by kishansagathiya** [comment]
@zhjgit 
IPFS-Cluster does pinset orchestration for IPFS. Say you have 3 IPFS nodes, you will create a cluster with 3 IPFS-Cluster nodes (with an IPFS node linked to each of them). 
Now if you want to ensure that your cat.jpg is available on 2 different nodes, you can try 
```
ipfs-cluster-ctl pin add --replication 2 Qm..CatHash
```
and cluster will make sure that two different IPFS nodes has that cat.jpg

Does that clear your doubts?

**Comment by zhjgit** [comment]
This I know is used in this way, so that the rest of the nodes can synchronize the file data.
`--replication 2` Does it mean copying twice?   I remember to use it directly. `ipfs-cluster-ctl pin add Qm...CatHash`

**Comment by kishansagathiya** [comment]
> --replication 2 Does it mean copying twice?

Yes, it is the number of nodes you want this data on.

> I remember to use it directly. ipfs-cluster-ctl pin add Qm...CatHash

That would choose the default policy (as set in `service.json`). If you haven't edited `service.json`, it should replicate on all nodes.

**Comment by zhjgit** [comment]
Is this configuration item?
`"pin_tracker": {
    "maptracker": {
      "max_pin_queue_size": 4096,
      "concurrent_pins": 10
    }
  }` Modify which parameter changes the number of nodes I need to synchronize

**Comment by zhjgit** [comment]
Specifically, I know how to ensure that all nodes are fully pinset.

**Comment by kishansagathiya** [comment]
```
{
  "cluster": {
    "replication_factor_min": -1,
    "replication_factor_max": -1,
  },
```

**Comment by kishansagathiya** [comment]
Feel to reopen if you still have question around this issue.
