### ISSUE TITLE
ipfs-cluster-service: Enable debug/pprof endpoint

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#936]
**Describe the feature you are proposing**

See https://golang.org/pkg/net/http/pprof/

This is an ipfs-cluster-service feature. Listens by default on localhost. Configurable via flag.

**Comment by hsanjuan** [comment]
Actually, check if we can share the prometheus endpoint and this endpoint on the same listener. In which case this becomes a metrics component feature.

**Comment by kishansagathiya** [comment]
This was open to see if we could reduce code used to set handlers https://github.com/ipfs/ipfs-cluster/blob/2da2dc8c867199be507ac74c3c5aadf62bff73aa/observations/setup.go#L116-L125

I have gone through docs and did not find a short hand for doing this.

One can however do something like this
```
for _, v := []string{"block", "goroutine", "heap", "etc"}{
mux.Handle(fmt.Sprintf("/debug/pprof/%s", v), pprof.Handler(v))
}
```

but I don't see a value of doing that vs loss of readability
