### ISSUE TITLE
Ipfs-cluster-ctl add take too long

### ISSUE THREAD

**Issue by suutaku** [ipfs/ipfs-cluster#941]
when I add a big file with 

```
Ipfs-cluster-ctl add file_name
```

it looks like Ipfs-cluster-ctl never respond.
instead of using 
```
Ipfs add file_name
then
Ipfs-cluster-ctl pin add cid
```
everything is ok.  that's a bug? or I made some mistakes?

```
ipfs-cluster-ctl version 0.11.0
ipfs-cluster-service version 0.11.0
ipfs version 0.4.19-dev
```

**Comment by hsanjuan** [comment]
Hi,

`ipfs-cluster-ctl` is very probably adding, but slowly as it is adding to several peers at once over the network (and more slowly than ipfs does it) (if you run `ipfs-cluster-service --loglevel debug daemon` you should see blocks being put). For big files, you are better off using "ipfs add+pin add", although the time it takes for files to appear as "pinned" in all the destinations will probably be comparable (shorter but comparable) to what "ipfs-cluster-ctl add" took in most cases.

**Comment by hsanjuan** [comment]
@suutaku any feedback here?

**Comment by suutaku** [comment]
@hsanjuan  I'm sorry to replay so late! those day I'm working on other works...
About the pin add problem. I think it's better to use 'ipfs add + pin add'. so I need write an extra module to my code.  at this moment, I have any feedback. so I think you can close this question.
thanks your guys agin.

**Comment by hsanjuan** [comment]
Thanks!
