### ISSUE TITLE
an env set comment on https://cluster.ipfs.io/documentation/deployment/automations/ need update

### ISSUE THREAD

**Issue by godcong** [ipfs/ipfs-cluster#942]
**Additional information:**
 - OS: -
 - IPFS Cluster version: 0.11.0

**Describe the bug:**
on the address of `https://cluster.ipfs.io/documentation/deployment/automations/`
the written in the warning bar is:
```
$IPFS_CLUSTER_IPFSHTTP_NODEMULTIADDRESS 
```
in the source used env is:
```
$CLUSTER_IPFSHTTP_NODEMULTIADDRESS
```

**Comment by hsanjuan** [comment]
Thanks @godcong , would you mind submitting a fix here? https://github.com/ipfs/ipfs-cluster-website/blob/master/content/documentation/deployment/automations.md

**Comment by kishansagathiya** [comment]
I have added one already https://github.com/ipfs/ipfs-cluster-website/pull/105

**Comment by godcong** [comment]
nice
