### ISSUE TITLE
github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch

### ISSUE THREAD

**Issue by jaller94** [ipfs/ipfs-cluster#963]
**Additional information:**
 - OS: Raspbian GNU/Linux 10 (buster)
 - IPFS Cluster version: master a178e5988a64988889f0310e4a197578ded25c97
 - Installation method: built from source

**Describe the bug:**

Following the instructions in cluster.ipfs.io/download/#installing-from-source, I'm trying to install IPFS-Cluster from source. However, it seems like there's an error in one of the dependencies' hash.

```
go: verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
	downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
	go.sum:     h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
```

I already tried running `sudo rm -Rf ~/go/pkg/mod` as suggested in this similar issue: #782

Why does ipfs-cluster need a bitcoin node anyway? 🕵

**Comment by kishansagathiya** [comment]
> Why does ipfs-cluster need a bitcoin node anyway?

It doesn't need a bitcoin node. IPFS-Cluster uses a library which uses github.com/btcsuite/btcd (the library, not the node). In go.mod you will this marked as indirect.

I am going to bump this library to next tag, since I have been getting 410 gone on this consistently

```
go: github.com/btcsuite/btcd@v0.20.0-beta: reading https://proxy.golang.org/github.com/btcsuite/btcd/@v/v0.20.0-beta.mod: 410 Gone
```

**Comment by hsanjuan** [comment]
Thanks for the report, can you try again?

**Comment by kishansagathiya** [comment]
Closed by https://github.com/ipfs/ipfs-cluster/pull/964
Feel free to reopen if you still face the issue.
