### ISSUE TITLE
Permission denied when mounting host directory with Docker

### ISSUE THREAD

**Issue by Schaeff** [ipfs/ipfs-cluster#97]
This might be due to my poor knowledge of Docker but:

`docker run -d --name ipfs-cluster -v ~/.ipfs-cluster:/data/ipfs-cluster ipfs/ipfs-cluster`
yields
```
ERROR  consensus: creating file snapshot store: snapshot path not accessible: mkdir /Users: permission denied raft.go:107
[...]
error starting cluster: snapshot path not accessible: mkdir /home/me: permission denied
```

**Comment by hsanjuan** [comment]
hey! can you check the value in your `service.json` for `consensus_data_folder` ?

I suspect it is set to `/Users/` or something. If you are mounting inside docker it should be `/data/ipfs-cluster/data`.

**Comment by Schaeff** [comment]
Oh, right. It works!
That's because I used `ipfs-cluster` on the host previously, so making that change would fix the Docker one but break the host one. 
Couldn't that field default to `$IPFS_CLUSTER_DIR/data`? In that case it would work in both cases. Otherwise it's not a huge deal.
Thanks :)

**Comment by hsanjuan** [comment]
> Couldn't that field default to $IPFS_CLUSTER_DIR/data?

Yes, I'm going to leave this open until we can leave that option empty and have that default value.
