### ISSUE TITLE
when start ipfs-cluster, can't user ipfs add file through 5001

### ISSUE THREAD

**Issue by beyonderyue** [ipfs/ipfs-cluster#98]
After ipfs-cluster started, I want use  ip:5001/api/v0/add, but always timeout, if I use ip:9095/api/v0/add, it will succed. So what is the problem?

**Comment by hsanjuan** [comment]
are you calling those endpoints from localhost? If not, maybe your ipfs daemon is only listening to localhost, while your cluster proxy endpoint (:9095) is listening on every interface.

**Comment by beyonderyue** [comment]
if  stop ipfs-cluster, I can add file with 5001

**Comment by hsanjuan** [comment]
What error do you get when you can't add with 5001 ?

**Comment by beyonderyue** [comment]
timeout

**Comment by hsanjuan** [comment]
is it while a pin operation is ongoing through cluster? ipfs can't pin 2 things at the same time, one of them will hang until the other is finished.

**Comment by hsanjuan** [comment]
re-open if needed
