### ISSUE TITLE
Disk monitor can easily work on free-space now

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#99]
Since https://github.com/ipfs/go-ipfs/pull/3915, the disk monitor can easily use 'free space' as metric, rather than 'used disk'. This provides better metrics when mixing nodes with different capacities in the same cluster.

**Comment by hsanjuan** [comment]
@dgrisham this is a nice one to pick up: adding a new monitor that uses free space (StorageMax - RepoSize) rather than  just RepoSize.

**Comment by dgrisham** [comment]
Closed by https://github.com/ipfs/ipfs-cluster/pull/142
