### ISSUE TITLE
Can't follow website cluster on 0.12.0

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-cluster#992]
**Additional information:**
 - OS: MacOSX
 - IPFS Cluster version: 0.12.0
 - Installation method: dist

**Describe the bug:**
- On macOSX I need to run **./ipfs-cluster-follow ipfs-websites run --init ipfs-websites.collab.ipfscluster.io** (`ipfs-cluster-follow ipfs-websites run --init ipfs-websites.collab.ipfscluster.io` doesn't work - says `zsh: command not found: ipfs-cluster-follow`)

- I initially ran `./ipfs-cluster-follow ipfs-websites run --init ipfs-websites.collab.ipfscluster.io` without my IPFS deamon running (since that wasn't mentioned in the documentation)

- When I turned on my deamon and ran `./ipfs-cluster-follow ipfs-websites run --init ipfs-websites.collab.ipfscluster.io` again, I got 
`config: loading configuration from http:///ipns/ipfs-websites.collab.ipfscluster.io config.go:359
reading the configurations in /Users/nala/.ipfs-cluster-follow/ipfs-websites: could not fetch configuration from source: http:///ipns/ipfs-websites.collab.ipfscluster.io`
seemingly because ipfs-websites.collab.ipfscluster.io won't load?

LMK if I'm doing something silly - but seems to me there's something wrong here either with the workflow or with the docs for how to do it right.  ;)

**Comment by hsanjuan** [comment]
I screwed up the --init flag :/ . Try `./ipfs-cluster-follow ipfs-websites init ipfs-websites.collab.ipfscluster.io` first, and then the run command.

**Comment by hsanjuan** [comment]
And you'll need to remove `~/.ipfs-cluster-follow/ipfs-websites` folder. :'(

**Comment by hsanjuan** [comment]
I'll make a new release asap.

**Comment by momack2** [comment]
It's working!!! 

Note, the help text also says "ipfs-cluster-follow ipfs-websites run" instead of "./ipfs-cluster-follow ipfs-websites run"

I assume I can kill and restart the follower peer if I don't want to keep it constantly checking for the latest version of the websites, right?

**Comment by hsanjuan** [comment]
> Note, the help text also says "ipfs-cluster-follow ipfs-websites run" instead of "./ipfs-cluster-follow ipfs-websites run"

Yeah, so normally these executables are in one of the folders in your $PATH (`/usr/local/bin`, or `~/go/bin` for example, run `echo $PATH` to see). In that case the `./` is not needed as the shell knows where to find them.

> I assume I can kill and restart the follower peer if I don't want to keep it constantly checking for the latest version of the websites, right?

Correct.
