### ISSUE TITLE
'pin update' with new timeout for new pin

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#996]
It would be nice if we could set the expire time of a new pin which is pushed with `pin update`, while the old pin's expire date is kept unmodified.

Follow-up to:

https://github.com/ipfs/ipfs-cluster/pull/923#issuecomment-577365064

**Comment by hsanjuan** [comment]
Relevant code: https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go#L1496

**Comment by gargdeepak** [comment]
Can I please pick this up if no one else is working on it ?

**Comment by hsanjuan** [comment]
@gargdeepak yes, please do!

**Comment by gargdeepak** [comment]
Are there any testing guidelines to changes made in this repo ? I tried `go test` but it errors out:
`20:08:01.673 ERROR     engine: datastore closed engine.go:291
`

**Comment by hsanjuan** [comment]
Does the test fail or is it just an error message?

**Comment by gargdeepak** [comment]
I don't think the tests started (not sure), the error keeps repeating itself.

**Comment by hsanjuan** [comment]
send the PR and let  travis run the tests. I suppose they are running (progress will show with `go test -v`).

**Comment by gargdeepak** [comment]
needs review

**Comment by gargdeepak** [comment]
needs review

**Comment by RubenKelevra** [comment]
Well, the API has this functionality now, but ipfs-cluster-ctl still don't have this functionality:

```
$ ipfs-cluster-ctl pin update --expire-in 60s <old-CID> <new-CID>
Incorrect Usage: flag provided but not defined: -expire-in
```

Same goes for `--name`:
```
Incorrect Usage: flag provided but not defined: -name
```

**Comment by hsanjuan** [comment]
Added a new issue for this.
