### ISSUE TITLE
showing the 'expire-in' time in pin ls

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-cluster#998]
**Describe the feature you are proposing**

Currently there's no way to see if there's a expire-in time set or on which date/time the pin will be removed from the cluster.

I think it would be nice if the expire-in time can be listed, or just a 'no' (like for metadata) if there's no expire time set.

**Comment by hsanjuan** [comment]
Yes. As workaround, pass `ipfs-cluster-ctl --enc=json` to see the full pin objects.

**Comment by RubenKelevra** [comment]
@hsanjuan thanks! That's helpful!

**Comment by gargdeepak** [comment]
Can I please pick this one up ?

**Comment by hsanjuan** [comment]
Yes, relevant code is in `cmd/ipfs-cluster-ctl/formatters.go`.

**Comment by gargdeepak** [comment]
needs review

**Comment by gargdeepak** [comment]
needs review
